"""
Run this script once to add the Cell Biology question set to the database.
It inserts new questions without deleting existing data or user progress.
Usage: python3 add_questions.py
"""
import database as db

CELL_BIOLOGY_QUESTIONS = [
    # ─────────────────────────────────────────────────────
    # BIOLOGY – Easy  (cell biology recall)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Units', 1,
     'How do you convert micrometres (μm) to nanometres (nm)?',
     'Divide by 1000', 'Multiply by 100', 'Multiply by 1000', 'Divide by 100',
     'C',
     'To convert to a smaller unit you multiply. Dividing would give a larger unit (nm → μm).',
     '1 μm = 1000 nm, so multiply by 1000. To go back (nm → μm), divide by 1000.'),

    ('Biology', 'Units', 1,
     'How do you convert millimetres (mm) to micrometres (μm)?',
     'Multiply by 1000', 'Divide by 1000', 'Multiply by 100', 'Divide by 100',
     'A',
     'To convert to a smaller unit you multiply. 1 mm = 1000 μm.',
     '1 mm = 1000 μm so multiply by 1000. Reversing (μm → mm) means dividing by 1000.'),

    ('Biology', 'Microscopy', 1,
     'What is the definition of magnification?',
     'The ability to distinguish two points clearly from one another',
     'The number of lenses in a microscope',
     'The size of the objective lens',
     'The amount that an image is scaled up when viewed through a microscope',
     'D',
     'The ability to distinguish two points is resolution, not magnification.',
     'Magnification = how much bigger the image appears compared to the real object. Formula: magnification = image size ÷ actual size.'),

    ('Biology', 'Microscopy', 1,
     'What is resolution in microscopy?',
     'How much an image is magnified',
     'The ability to distinguish two separate points clearly from one another',
     'The colour accuracy of the image produced',
     'The size of the eyepiece lens',
     'B',
     'Magnification is how much the image is enlarged. Resolution is about clarity/detail.',
     'Resolution = the ability to distinguish two points. Higher resolution means finer detail can be seen. Electron microscopes have higher resolution than light microscopes.'),

    ('Biology', 'Microscopy', 1,
     'How do you calculate the total magnification of a microscope?',
     'Eyepiece lens magnification × objective lens magnification',
     'Eyepiece lens magnification + objective lens magnification',
     'Image size ÷ actual size',
     'Eyepiece lens magnification ÷ objective lens magnification',
     'A',
     'Magnifications of lenses multiply together, they do not add. Image size ÷ actual size gives the magnification of a specimen, not the microscope.',
     'Total magnification = eyepiece lens magnification × objective lens magnification. E.g. ×10 eyepiece × ×40 objective = ×400 total.'),

    ('Biology', 'Cell biology', 1,
     'What is cell differentiation?',
     'The division of a cell into two identical daughter cells',
     'The process of an unspecialised cell becoming specialised',
     'The death of a programmed cell',
     'The replication of DNA before cell division',
     'B',
     'Cell division is mitosis. Cell death is apoptosis. DNA replication is part of interphase.',
     'Differentiation is when an unspecialised (stem) cell changes to take on a specific structure and function, e.g. becoming a nerve cell or red blood cell.'),

    ('Biology', 'Stem cells', 1,
     'What is a stem cell?',
     'An undifferentiated cell that can differentiate to become any type of cell',
     'A cell found only in plant roots',
     'A specialised red blood cell that carries oxygen',
     'A cell that only divides by meiosis',
     'A',
     'Stem cells are NOT specialised — they are the unspecialised cells that can BECOME specialised. They are not exclusive to plants.',
     'Stem cells are undifferentiated. They can self-renew (copy themselves) and differentiate into specialised cells when needed.'),

    ('Biology', 'Diffusion', 1,
     'What is diffusion?',
     'The net movement of water through a semi-permeable membrane',
     'The movement of molecules against their concentration gradient using energy',
     'The net movement of particles from an area of high concentration to an area of low concentration',
     'The absorption of glucose using carrier proteins',
     'C',
     'Water moving through a semi-permeable membrane is osmosis. Moving against the gradient using energy is active transport.',
     'Diffusion is passive (no energy needed) and moves particles DOWN the concentration gradient — from where there are lots of them to where there are fewer.'),

    ('Biology', 'Osmosis', 1,
     'What is osmosis?',
     'The movement of any particles from high to low concentration',
     'The active movement of water molecules using ATP energy',
     'The net movement of water molecules from high water potential to low water potential through a semi-permeable membrane',
     'The movement of glucose from the gut into the blood',
     'C',
     'Osmosis applies specifically to WATER molecules. It is passive (no energy). Glucose moving from the gut uses active transport.',
     'Osmosis: water moves from where water potential is HIGH (dilute solution) to where it is LOW (concentrated solution), through a partially permeable membrane.'),

    ('Biology', 'Active transport', 1,
     'What is active transport?',
     'The movement of particles from a high concentration to a low concentration',
     'The diffusion of water through a partially permeable membrane',
     'The movement of water from high to low water potential',
     'The movement of molecules from a low concentration to a high concentration, against the gradient, using energy',
     'D',
     'Moving down a gradient is diffusion or osmosis — no energy needed. Active transport works AGAINST the gradient and REQUIRES energy (ATP).',
     'Active transport: moves particles from LOW to HIGH concentration (uphill) — against the gradient — using energy released from respiration.'),

    ('Biology', 'Cell structure', 1,
     'What is the function of the cell wall in a plant cell?',
     'To carry out photosynthesis',
     'To store the cell\'s genetic information',
     'To control what enters and exits the cell',
     'To protect the cell and provide structural support',
     'D',
     'Photosynthesis happens in chloroplasts. Genetic information is in the nucleus. The cell membrane (not wall) controls what enters and exits.',
     'The cell wall is made of cellulose. It is rigid and gives the cell a fixed shape, prevents the cell from bursting, and provides structural support.'),

    ('Biology', 'Cell structure', 1,
     'What is the function of the vacuole in a plant cell?',
     'To store water and keep the cell turgid (rigid)',
     'To carry out aerobic respiration',
     'To produce proteins on ribosomes',
     'To absorb light energy for photosynthesis',
     'A',
     'Respiration happens in mitochondria. Protein synthesis occurs on ribosomes. Light absorption is done by chloroplasts.',
     'The central vacuole stores cell sap (water and dissolved substances). A full vacuole pushes against the cell wall making the cell turgid — important for supporting plant structure.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Medium  (specialised cells & exchange)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Specialised cells', 2,
     'How are sperm cells adapted for their function?',
     'They have a large surface area, thin walls, and sieve plates',
     'They have a tail, lots of mitochondria, an acrosome containing enzymes, and haploid DNA',
     'They contain chloroplasts for energy and a large vacuole',
     'They are hollow with lignin-strengthened walls and no top or bottom walls',
     'B',
     'Sieve plates are in phloem. Chloroplasts are in plant cells. Lignin walls are in xylem.',
     'Sperm adaptations: tail (flagellum) for swimming; mitochondria for energy; acrosome (enzyme store) to penetrate the egg; haploid DNA so the fertilised egg has the correct number of chromosomes.'),

    ('Biology', 'Specialised cells', 2,
     'How are nerve cells (neurones) adapted for their function?',
     'They have lots of mitochondria and contractile protein filaments',
     'They are hollow with no top/bottom walls for efficient flow',
     'They are long and thin with a fatty myelin sheath and branched connections to other cells',
     'They have sieve plates and companion cells with mitochondria',
     'C',
     'Contractile proteins are in muscle cells. Hollow structure with no end walls is xylem. Sieve plates are in phloem.',
     'Nerve cell adaptations: long and thin to carry signals quickly over distance; myelin sheath insulates the axon increasing signal speed; branched endings (dendrites) to connect to many other neurones.'),

    ('Biology', 'Specialised cells', 2,
     'How are muscle cells adapted for their function?',
     'They contain protein filaments that can contract and relax, and many mitochondria to supply energy',
     'They have a large surface area and thin walls for absorption',
     'They are hollow and strengthened with lignin for structural support',
     'They have a tail and acrosome to penetrate another cell',
     'A',
     'Thin walls and large surface area describe villi. Lignin and hollow structure describe xylem. Tail and acrosome describe sperm.',
     'Muscle cells contain actin and myosin protein filaments that slide past each other to contract. Many mitochondria provide the ATP (energy) needed for repeated contraction.'),

    ('Biology', 'Specialised cells', 2,
     'How are root hair cells adapted for absorbing water and minerals?',
     'They have sieve plates for efficient flow of sap and sugars',
     'They contain lots of chloroplasts to absorb light energy',
     'They have a large surface area for more absorption and contain mitochondria for active transport of minerals',
     'They are long and thin with a myelin sheath',
     'C',
     'Sieve plates are in phloem. Chloroplasts are not present in root hair cells (they are underground). Myelin sheaths are on nerve cells.',
     'Root hair cells extend into the soil to increase surface area for water absorption. Mitochondria provide energy for active transport of mineral ions from the soil into the cell.'),

    ('Biology', 'Specialised cells', 2,
     'How are phloem cells adapted for their function?',
     'They are hollow and strengthened with lignin; they have no top or bottom walls',
     'They have sieve plates for sap flow, companion cells with mitochondria, and few subcellular structures to allow sugars to move through efficiently',
     'They have a tail and haploid nucleus',
     'They have lots of microvilli and a thin wall',
     'B',
     'Lignin and hollow structure with no end walls describes xylem. Tail and haploid nucleus describe sperm. Microvilli and thin walls describe villi.',
     'Phloem transports sugars (sucrose) around the plant. Sieve plates allow flow. Companion cells have mitochondria to provide energy for active loading of sugars. Few organelles leave space for the sap to flow.'),

    ('Biology', 'Specialised cells', 2,
     'How are xylem cells adapted for their function?',
     'They are hollow with no top or bottom walls and have lignin-strengthened walls for support',
     'They contain many mitochondria and sieve plates for efficient transport',
     'They have a large surface area and thin walls for diffusion',
     'They contain a large nucleus and many ribosomes to produce transport proteins',
     'A',
     'Mitochondria and sieve plates describe phloem. Large surface area and thin walls describe villi. Xylem cells are dead with no nucleus.',
     'Xylem transports water and minerals from roots to leaves. Cells are hollow (dead), allowing free flow. No end walls means one continuous column. Lignin strengthens and waterproofs the walls.'),

    ('Biology', 'Gas exchange', 2,
     'How are villi in the small intestine adapted for efficient absorption?',
     'They have thick walls, a poor blood supply, and no folds',
     'They have thin walls, a good blood supply to maintain the concentration gradient, and lots of microvilli to increase surface area',
     'They contain chloroplasts and a large central vacuole',
     'They are strengthened with lignin and have sieve plates',
     'B',
     'Thick walls would increase diffusion distance. Poor blood supply would reduce the gradient. Chloroplasts and lignin are plant cell features.',
     'Villi adaptations: thin walls — short diffusion distance; good blood supply — maintains concentration gradient (glucose is constantly removed); microvilli — greatly increase surface area for absorption.'),

    ('Biology', 'Gas exchange', 2,
     'How are gills adapted for gas exchange in fish?',
     'They have thick walls and a small surface area to slow gas loss',
     'They have a large surface area of gill filaments with thin walls and a good capillary blood supply to maintain the concentration gradient',
     'They contain mucus-secreting cells that dissolve oxygen directly',
     'They are hollow with no end walls and strengthened with lignin',
     'B',
     'Thick walls would reduce diffusion. Small surface area would reduce exchange rate. Mucus and lignin are not features of gills.',
     'Gill adaptations: large surface area (many lamellae); thin walls — short diffusion pathway; capillaries — maintain concentration gradient by constantly carrying away absorbed oxygen.'),

    ('Biology', 'Gas exchange', 2,
     'How are the lungs adapted for efficient gas exchange?',
     'They have solid walls and a small surface area to protect the gas exchange tissue',
     'They contain special enzymes that chemically bind oxygen and remove CO₂',
     'They have a large surface area due to many alveoli, thin walls for a short diffusion pathway, and a rich capillary network to maintain the concentration gradient',
     'They use active transport powered by mitochondria to move oxygen into the blood',
     'C',
     'Solid walls would prevent diffusion. No special enzymes are involved. Gas exchange in the lungs is passive diffusion, not active transport.',
     'Lung adaptations: millions of alveoli → huge surface area; walls one cell thick → short diffusion distance; dense capillaries → blood constantly removes O₂ and delivers CO₂, maintaining steep gradients.'),

    ('Biology', 'Microscopy', 2,
     'What are the key differences between electron and light microscopes?',
     'Electron microscopes have lower resolution and can view living organisms in colour',
     'They are identical in resolution but electron microscopes are cheaper to use',
     'Electron microscopes have higher resolution, greater magnification, and can only view dead specimens (producing black and white images)',
     'Light microscopes produce black and white images; electron microscopes produce colour images',
     'C',
     'Electron microscopes have HIGHER resolution, not lower. Electron microscopes produce black and white images, not colour. They are more expensive, not cheaper.',
     'Electron microscopes use electrons (shorter wavelength than light) → higher resolution and magnification. However they can only view dead, preserved specimens and produce black and white images. Light microscopes can view living cells in colour.'),

    ('Biology', 'Cell biology', 2,
     'Where are stem cells found in the human body?',
     'Only in the brain and spinal cord',
     'Embryonic stem cells are found in embryos; adult stem cells are found in bone marrow and other tissues',
     'Only in the liver and kidneys',
     'Only circulating freely in the bloodstream',
     'B',
     'Adult stem cells are primarily in bone marrow, not in the brain, liver, or bloodstream.',
     'Embryonic stem cells: found in early embryos — can differentiate into any cell type. Adult stem cells: mainly in bone marrow — can differentiate into a limited range of cell types (mainly blood cells).'),

    ('Biology', 'Stem cells', 2,
     'Where are stem cells found in plants?',
     'In the leaves where photosynthesis occurs',
     'Scattered randomly throughout all plant tissues',
     'In the meristem regions at the tips of shoots and roots',
     'Only in the flowers during the reproductive season',
     'C',
     'Stem cells in plants are not in leaves or flowers. They are not scattered randomly — they are concentrated in specific growth regions.',
     'Plant stem cells are called meristematic cells and are found in meristems — the growing tips (apices) of roots and shoots. These are the regions where cell division and growth occur.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Hard  (cell cycle, transport, specialisation)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Cell differentiation', 3,
     'Describe how cells become specialised during the development of an organism.',
     'All cells are born fully specialised and remain unchanged throughout life',
     'Cells become specialised randomly with no particular trigger',
     'As the organism develops, unspecialised cells differentiate by switching on specific genes, gaining different subcellular structures to carry out a particular function',
     'Cells only become specialised after the organism reaches adulthood',
     'C',
     'Cells begin as unspecialised (undifferentiated). The process is not random — it is controlled by gene expression. It happens early in development, not in adulthood.',
     'Differentiation: all cells start with the same DNA. During development, different genes are switched on/off in different cells. This causes them to develop different structures (e.g. myelin sheath in nerve cells) for specific functions.'),

    ('Biology', 'Active transport', 3,
     'Explain how active transport moves glucose from the gut into the blood, even when glucose concentration in the gut is lower than in the blood.',
     'Glucose always diffuses from the gut to the blood because the gut produces glucose continuously',
     'Glucose moves by osmosis through the gut wall when concentration in the blood is high',
     'Active transport uses energy from respiration to move glucose against its concentration gradient — from low concentration in the gut to high concentration in the blood',
     'Glucose diffuses into the blood because blood concentration is always lower after digestion',
     'C',
     'Diffusion and osmosis both move substances DOWN the gradient. Here glucose must move AGAINST the gradient, which requires active transport (energy).',
     'When the concentration gradient opposes absorption (more glucose in blood than gut), active transport is essential. Carrier proteins and ATP move glucose against the gradient from the intestine lumen into the blood.'),

    ('Biology', 'Active transport', 3,
     'Explain why root hair cells need active transport to absorb mineral ions from the soil.',
     'Mineral ions are always at higher concentration in the soil so diffuse in naturally',
     'Root hair cells use active transport to move mineral ions from low concentration in the soil to high concentration inside the cell, using energy from mitochondria',
     'Mineral ions enter root hair cells by osmosis through the semi-permeable membrane',
     'Mineral ions are absorbed using light energy captured in chloroplasts',
     'B',
     'If minerals were always more concentrated in soil than in the cell, diffusion would work — but they are not. Osmosis moves water, not minerals. Root hair cells have no chloroplasts.',
     'Mineral ions are often more concentrated INSIDE the root cell than in the soil. Active transport uses ATP (from mitochondria) to move ions against this gradient into the cell.'),

    ('Biology', 'Surface area', 3,
     'Explain the relationship between surface area to volume ratio and the need for a transport system.',
     'As an organism grows larger, its surface area to volume ratio increases, making diffusion more efficient',
     'Surface area to volume ratio stays the same as organisms grow, so diffusion is always sufficient',
     'As an organism grows larger, its surface area to volume ratio decreases — diffusion alone is too slow so dedicated transport systems (e.g. blood) are needed',
     'Larger organisms rely entirely on diffusion because they have a much larger total surface area',
     'C',
     'As organisms grow, volume increases faster than surface area — so the RATIO decreases. Larger surface area in absolute terms is not helpful if the volume is proportionally much larger.',
     'A large organism has a small surface area relative to its volume. Materials (O₂, glucose) cannot reach all cells quickly enough by diffusion alone. Transport systems (blood, xylem, phloem) solve this. Unicellular organisms have a high SA:V ratio so diffusion is sufficient.'),

    ('Biology', 'Cell cycle', 3,
     'What happens during interphase of the cell cycle?',
     'Chromosomes line up along the middle of the cell',
     'The cell grows larger and DNA replicates so each chromosome is copied',
     'One set of chromosomes is pulled to each end of the cell',
     'The cytoplasm divides to produce two new cells',
     'B',
     'Chromosomes lining up is metaphase. Being pulled apart is anaphase. Cytoplasm dividing is cytokinesis.',
     'Interphase is the longest phase. The cell grows, produces more proteins and organelles, and copies all of its DNA so each new cell will receive a complete set of genetic information.'),

    ('Biology', 'Cell cycle', 3,
     'What happens during metaphase of mitosis?',
     'The cytoplasm divides to form two daughter cells',
     'DNA replicates within the nucleus',
     'One set of chromosomes is pulled to each end by spindle fibres',
     'Chromosomes condense and line up along the middle (equator) of the cell',
     'D',
     'Cytoplasm dividing is cytokinesis. DNA replication is in interphase. Chromosomes being pulled apart is anaphase.',
     'In metaphase, condensed chromosomes attach to spindle fibres and align along the cell\'s equator. This ensures each daughter cell receives one copy of every chromosome.'),

    ('Biology', 'Cell cycle', 3,
     'What happens during anaphase of mitosis?',
     'One set of chromosomes is pulled to each end of the cell by spindle fibres',
     'Chromosomes line up in the middle of the cell',
     'DNA is copied within the nucleus',
     'The cell membrane pinches inward to divide the cytoplasm',
     'A',
     'Chromosomes lining up is metaphase. DNA copying is in interphase. Cell membrane pinching is cytokinesis.',
     'In anaphase, spindle fibres shorten and pull the two copies of each chromosome to opposite poles of the cell. This ensures each new cell will have a full set of chromosomes.'),

    ('Biology', 'Mitosis', 3,
     'Why does mitosis occur in organisms?',
     'To produce haploid gametes (sperm and egg cells) for sexual reproduction',
     'To increase genetic variation in the offspring',
     'To repair and replace damaged or old cells, and for growth of the organism',
     'To reduce the chromosome number from diploid to haploid',
     'C',
     'Gametes are produced by meiosis, not mitosis. Mitosis produces genetically IDENTICAL cells — no variation. Chromosome number stays the same in mitosis.',
     'Mitosis produces 2 genetically identical diploid daughter cells. It is used for: growth (increasing cell number), repair (replacing damaged cells), and asexual reproduction.'),

    ('Biology', 'Mitosis vs meiosis', 3,
     'What are the key differences between mitosis and meiosis?',
     'Mitosis produces 4 genetically different haploid cells; meiosis produces 2 genetically identical diploid cells',
     'Mitosis produces 2 genetically identical diploid cells; meiosis produces 4 genetically different haploid cells',
     'Both processes produce 2 identical cells; they differ only in speed',
     'Mitosis only occurs in plants; meiosis only occurs in animals',
     'B',
     'Mitosis and meiosis are the wrong way round in option A. Both occur in animals and plants. They do not produce the same number of cells.',
     'Mitosis: 2 identical diploid cells (for growth/repair). Meiosis: 4 genetically different haploid cells (for gametes/sexual reproduction).'),

    ('Biology', 'Cell cycle', 3,
     'What happens during cytokinesis?',
     'DNA replicates within the nucleus ready for division',
     'Chromosomes condense and line up at the cell equator',
     'Spindle fibres pull chromosomes to opposite ends of the cell',
     'The cytoplasm and cell membrane divide to produce two genetically identical daughter cells',
     'D',
     'DNA replication is interphase. Chromosomes lining up is metaphase. Spindle fibres pulling is anaphase.',
     'Cytokinesis is the final stage of cell division. The cytoplasm divides (often by the cell membrane pinching inward) to produce two separate daughter cells, each with a full set of chromosomes.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Exam Challenge  (extended reasoning)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Stem cells', 4,
     'Explain how a bone marrow transplant can treat certain medical conditions such as anaemia.',
     'Bone marrow cells replace damaged bone tissue directly',
     'Bone marrow stem cells can differentiate into red blood cells and other blood cell types, replacing cells that are deficient or non-functional in the patient',
     'Bone marrow cells carry oxygen directly to organs as a substitute for red blood cells',
     'Bone marrow transplants only treat infections, not conditions involving blood cells',
     'B',
     'Bone marrow transplants treat blood cell conditions, not bone damage. Bone marrow stem cells become blood cells, they do not carry oxygen themselves.',
     'Bone marrow contains haematopoietic stem cells that can differentiate into all blood cell types including red blood cells. In anaemia, these new cells replace the deficient red blood cells, restoring normal oxygen transport.'),

    ('Biology', 'Stem cells', 4,
     'Evaluate the advantages and disadvantages of using embryonic stem cells for medical treatments.',
     'Embryonic stem cells have no disadvantages and should always be used in preference to adult stem cells',
     'Embryonic stem cells can only differentiate into one cell type, making them less useful than adult stem cells',
     'Embryonic stem cells can differentiate into any cell type (pluripotent — useful for many conditions), but raise ethical concerns about harming potential life, and risk contamination or immune rejection',
     'Embryonic stem cells are only useful for treating cancer and have no other medical applications',
     'C',
     'Embryonic stem cells can differentiate into ANY cell type — they are more versatile than adult stem cells. They do have significant disadvantages including ethical concerns.',
     'Advantages: pluripotent (can become any cell type), could treat paralysis, organ failure, diabetes. Disadvantages: ethical issues (embryo is potential life), risk of rejection by patient\'s immune system, stem cells grown in lab may become contaminated.'),

    ('Biology', 'Stem cells', 4,
     'What is therapeutic cloning and why might it reduce the risk of rejection?',
     'Cloning an entire organism to use as an organ donor',
     'Producing stem cells with the same genetic makeup as the patient by replacing an egg cell\'s nucleus with the patient\'s nucleus, so the immune system is less likely to reject the treatment',
     'Creating genetically identical twins to donate organs to each other',
     'Producing cloned animals to study the progression of human disease',
     'B',
     'Therapeutic cloning does not clone a whole organism. It does not involve creating twins. It specifically produces stem cells matched to the patient.',
     'Therapeutic cloning: remove nucleus from egg cell → replace with patient\'s nucleus → stimulate to develop into embryo → harvest stem cells → these cells are genetically identical to the patient, so the body\'s immune system is far less likely to reject them.'),

    ('Biology', 'Genetics', 4,
     'How is genetic information stored in the nucleus of a cell?',
     'As loose nucleotides floating freely in the nucleoplasm',
     'As RNA strands attached to ribosomes on the nuclear envelope',
     'As protein chains wrapped around a lipid core within the nucleus',
     'As DNA molecules coiled into chromosomes, arranged in a double helix structure',
     'D',
     'Nucleotides are the building blocks of DNA but are not stored loose. RNA is found in the cytoplasm (on ribosomes). DNA is not made of protein or lipid.',
     'DNA is a double helix molecule (two strands twisted together). In the nucleus it is wound tightly around proteins called histones, forming chromosomes. Humans have 46 chromosomes (23 pairs) in most body cells.'),

    ('Biology', 'Osmosis', 4,
     'A student places a potato cylinder in a very concentrated salt solution for 24 hours. Predict and explain what will happen to its mass.',
     'The potato gains mass because water enters by osmosis from the salt solution into the cells',
     'The potato stays the same mass because salt and water exchange in equal amounts',
     'The potato loses mass because water leaves the cells by osmosis — the salt solution has a lower water potential than the potato cells',
     'The potato gains mass because salt enters the cells by active transport',
     'C',
     'Water moves from HIGH water potential to LOW. A concentrated salt solution has LOWER water potential than the potato cells, so water leaves the potato — it loses mass.',
     'Osmosis: water moves from the potato cells (higher water potential / more dilute) into the salt solution (lower water potential / more concentrated). Water leaves → the cells become plasmolysed → the potato loses mass and becomes flaccid.'),

    ('Biology', 'Microscopy', 4,
     'A student views a cell through a microscope. The image of the cell measures 4 mm. The actual cell is 0.04 mm wide. What is the magnification?',
     '×10', '×40', '×100', '×400',
     'C',
     'Magnification = image size ÷ actual size = 4 ÷ 0.04 = 100. Dividing 4 by 0.4 gives 10 (wrong). Multiplying gives wrong units.',
     'Magnification = image size ÷ actual size = 4 mm ÷ 0.04 mm = ×100. Always use the same units for both measurements.'),

    ('Biology', 'Stem cells', 4,
     'Evaluate the advantages of using plant meristem (stem) cells compared to embryonic stem cells.',
     'Plant meristem cells raise the same ethical concerns as embryonic stem cells because they come from living organisms',
     'Plant meristem cells can be used to clone plants quickly and economically, preserve rare species, and produce disease-resistant plants — without the ethical issues of using embryonic stem cells',
     'Plant meristem cells can only produce root tissue and have very limited applications',
     'Plant meristem cells are less useful than embryonic stem cells because they cannot differentiate into as many types',
     'B',
     'Plant meristem cells do not raise the same ethical concerns as embryonic stem cells. They can produce whole plants, not just root tissue.',
     'Plant meristem cells: can be used to rapidly clone identical plants (important for agriculture), preserve rare or endangered species, produce disease-free crops. Unlike embryonic stem cells, using plant meristems does not raise ethical issues about harming potential life.'),

    ('Biology', 'Surface area', 4,
     'Using your knowledge of surface area to volume ratio, explain why unicellular organisms do not need a transport system, but large multicellular organisms do.',
     'Unicellular organisms are too small to develop a transport system so use diffusion by necessity',
     'Unicellular organisms have a large surface area to volume ratio, so all cells are close to the surface and sufficient exchange occurs by simple diffusion alone; in large organisms the SA:V ratio is small — diffusion cannot reach internal cells quickly enough',
     'Unicellular organisms have no mitochondria so cannot power active transport',
     'Large organisms use diffusion exclusively because their large surface area compensates for their greater volume',
     'B',
     'Unicellular organisms use diffusion out of biological necessity but it IS efficient for them because of their high SA:V ratio. Large surface area in absolute terms does not compensate for low SA:V ratio.',
     'SA:V ratio decreases as size increases. In unicellular organisms every part of the cell is close to the membrane — diffusion is fast enough. In large organisms, cells deep inside are too far from the exchange surface; dedicated transport systems (blood, xylem) are essential.'),
]


def add():
    db.init_db()
    conn = db.get_db()
    conn.executemany(
        '''INSERT INTO questions
           (subject, topic, difficulty, question_text,
            option_a, option_b, option_c, option_d,
            correct_answer, explanation, correction_tip)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)''',
        CELL_BIOLOGY_QUESTIONS
    )
    conn.commit()
    conn.close()
    print(f'Added {len(CELL_BIOLOGY_QUESTIONS)} new cell biology questions.')


if __name__ == '__main__':
    add()
