QUESTIONS = [
    # -------------------------------------------------------------------------
    # C7 ORGANIC CHEMISTRY — 57 questions
    # D1 Easy — 15 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What two elements make up all hydrocarbons?',
     'option_a':'Carbon and oxygen','option_b':'Carbon and hydrogen',
     'option_c':'Hydrogen and nitrogen','option_d':'Carbon and nitrogen',
     'correct_answer':'B','explanation':'Hydrocarbons contain only carbon and hydrogen atoms.',
     'correction_tip':'Hydro- means hydrogen; -carbon means carbon.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'Crude oil is described as a finite fossil fuel. What does "finite" mean?',
     'option_a':'It can be made in a laboratory','option_b':'It burns with a blue flame',
     'option_c':'It will run out and cannot be replaced quickly','option_d':'It is found only in the sea',
     'correct_answer':'C','explanation':'Finite means there is a limited supply that cannot be replenished on a human timescale.',
     'correction_tip':'Finite = limited; non-renewable; will eventually run out.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the general formula for alkanes?',
     'option_a':'CₙH₂ₙ','option_b':'CₙH₂ₙ₊₂','option_c':'CₙH₂ₙ₋₂','option_d':'CₙHₙ',
     'correct_answer':'B','explanation':'Alkanes are saturated hydrocarbons with the formula CₙH₂ₙ₊₂.',
     'correction_tip':'Alkanes are saturated so they have the maximum number of H atoms: CₙH₂ₙ₊₂.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the name of the alkane with the formula CH₄?',
     'option_a':'Ethane','option_b':'Propane','option_c':'Butane','option_d':'Methane',
     'correct_answer':'D','explanation':'CH₄ is methane, the first member of the alkane homologous series (n=1).',
     'correction_tip':'Meth- = 1 carbon, eth- = 2, prop- = 3, but- = 4.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'Which product of complete combustion of a hydrocarbon turns limewater milky?',
     'option_a':'Water','option_b':'Carbon monoxide','option_c':'Carbon dioxide','option_d':'Soot',
     'correct_answer':'C','explanation':'CO₂ reacts with limewater (Ca(OH)₂) to form a white precipitate of CaCO₃, turning it milky.',
     'correction_tip':'CO₂ + Ca(OH)₂ → CaCO₃ (white ppt) + H₂O.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the general formula for alkenes?',
     'option_a':'CₙH₂ₙ₊₂','option_b':'CₙH₂ₙ₋₂','option_c':'CₙH₂ₙ','option_d':'CₙHₙ',
     'correct_answer':'C','explanation':'Alkenes are unsaturated hydrocarbons with a C=C double bond and general formula CₙH₂ₙ.',
     'correction_tip':'Alkenes have one double bond, removing 2 H atoms compared to alkanes: CₙH₂ₙ.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':1,
     'question_text':'What colour change occurs when an alkene is added to bromine water?',
     'option_a':'Colourless to orange','option_b':'Orange to colourless',
     'option_c':'Blue to red','option_d':'Red to blue',
     'correct_answer':'B','explanation':'Alkenes decolourise bromine water (orange→colourless) due to an addition reaction across the C=C double bond.',
     'correction_tip':'Bromine water is orange; alkenes decolourise it. Alkanes do NOT decolourise bromine water.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the functional group of alcohols?',
     'option_a':'-COOH','option_b':'-COO-','option_c':'-OH','option_d':'-NH₂',
     'correct_answer':'C','explanation':'Alcohols contain the hydroxyl functional group -OH.',
     'correction_tip':'Alco-hol → hydroxyl (-OH) group.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the functional group of carboxylic acids?',
     'option_a':'-OH','option_b':'-COOH','option_c':'-COO-','option_d':'-CHO',
     'correct_answer':'B','explanation':'Carboxylic acids contain the -COOH (carboxyl) functional group.',
     'correction_tip':'Carboxylic acids: -COOH. Alcohols: -OH. Esters: -COO-.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':1,
     'question_text':'Which fraction from fractional distillation of crude oil is used as fuel for cars?',
     'option_a':'Bitumen','option_b':'Kerosene','option_c':'Petrol','option_d':'Fuel oil',
     'correct_answer':'C','explanation':'Petrol (C5–C10) is the fraction used as fuel in cars.',
     'correction_tip':'Petrol = cars; kerosene = jet fuel; diesel = lorries/trains; bitumen = roads.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':1,
     'question_text':'In fractional distillation of crude oil, which fractions come off at the TOP of the column?',
     'option_a':'Long chain hydrocarbons with high boiling points',
     'option_b':'Short chain hydrocarbons with low boiling points',
     'option_c':'Bitumen and fuel oil',
     'option_d':'Diesel and kerosene',
     'correct_answer':'B','explanation':'The top of the fractionating column is coolest, so short-chain (low boiling point) fractions like refinery gases come off at the top.',
     'correction_tip':'Short chains = low BP = cooler = top of column.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':1,
     'question_text':'What type of bond do alkenes contain that alkanes do not?',
     'option_a':'Carbon–oxygen double bond','option_b':'Carbon–carbon triple bond',
     'option_c':'Carbon–carbon double bond','option_d':'Carbon–hydrogen double bond',
     'correct_answer':'C','explanation':'Alkenes are unsaturated because they contain a C=C double bond.',
     'correction_tip':'Unsaturated = contains at least one C=C double bond.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What gas is produced during fermentation of glucose by yeast?',
     'option_a':'Oxygen','option_b':'Hydrogen','option_c':'Carbon dioxide','option_d':'Nitrogen',
     'correct_answer':'C','explanation':'Glucose → ethanol + carbon dioxide (CO₂) during anaerobic fermentation by yeast.',
     'correction_tip':'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What is the smell commonly associated with esters?',
     'option_a':'Pungent and acidic','option_b':'Rotten eggs','option_c':'Fruity and sweet','option_d':'Bleach-like',
     'correct_answer':'C','explanation':'Esters are known for their pleasant fruity smells and are used in perfumes and food flavourings.',
     'correction_tip':'Esters = fruity smells; used in perfumes and flavourings.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':1,
     'question_text':'What colour flame does complete combustion of a hydrocarbon produce?',
     'option_a':'Yellow/sooty','option_b':'Orange','option_c':'Blue','option_d':'Green',
     'correct_answer':'C','explanation':'Complete combustion produces a clean blue flame. Incomplete combustion gives a yellow/sooty flame.',
     'correction_tip':'Blue flame = complete combustion (enough O₂). Yellow/sooty = incomplete combustion.'},

    # -------------------------------------------------------------------------
    # C7 — D2 Medium — 14 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':2,
     'question_text':'Which statement correctly describes a homologous series?',
     'option_a':'Compounds with the same molecular formula but different structures',
     'option_b':'Compounds with the same functional group, same general formula, and gradually changing properties',
     'option_c':'Compounds that all have the same boiling point',
     'option_d':'Compounds containing only carbon and hydrogen',
     'correct_answer':'B','explanation':'A homologous series is a family of compounds sharing the same functional group and general formula, with properties changing gradually as chain length increases.',
     'correction_tip':'Homologous series: same functional group, same general formula, gradually changing properties.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':2,
     'question_text':'How does viscosity change as hydrocarbon chain length increases?',
     'option_a':'Viscosity decreases','option_b':'Viscosity stays the same',
     'option_c':'Viscosity increases','option_d':'Viscosity first increases then decreases',
     'correct_answer':'C','explanation':'Longer chain hydrocarbons have stronger intermolecular forces, so they are more viscous (flow less easily).',
     'correction_tip':'Longer chain → more viscous, higher BP, less flammable, less volatile.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'What are the conditions used for catalytic cracking?',
     'option_a':'600–700°C and high pressure with no catalyst',
     'option_b':'400–500°C with a zeolite catalyst',
     'option_c':'300°C with a nickel catalyst',
     'option_d':'100°C with an acid catalyst',
     'correct_answer':'B','explanation':'Catalytic cracking uses a zeolite catalyst at 400–500°C, producing branched alkanes and aromatic compounds.',
     'correction_tip':'Catalytic cracking: zeolite catalyst, 400–500°C. Thermal cracking: 600–700°C, high pressure.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'Why is cracking economically important?',
     'option_a':'It converts cheap, abundant long-chain fractions into shorter molecules that are in higher demand',
     'option_b':'It removes sulfur impurities from crude oil',
     'option_c':'It produces bitumen for road surfacing',
     'option_d':'It allows crude oil to be transported more easily',
     'correct_answer':'A','explanation':'Cracking converts excess long-chain fractions into shorter, more useful molecules such as petrol and alkenes that are in greater demand.',
     'correction_tip':'Cracking is needed because demand for petrol and small molecules exceeds supply from distillation.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':2,
     'question_text':'In the addition reaction of ethene with hydrogen (hydrogenation), what are the conditions?',
     'option_a':'H₃PO₄ catalyst, 300°C','option_b':'Nickel catalyst, approximately 60°C',
     'option_c':'Zeolite catalyst, 400°C','option_d':'Acid catalyst, room temperature',
     'correct_answer':'B','explanation':'Hydrogenation of alkenes uses a nickel catalyst at approximately 60°C. This reaction is used to make margarine from vegetable oils.',
     'correction_tip':'Hydrogenation: +H₂, Ni catalyst, ~60°C → converts alkene to alkane.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':2,
     'question_text':'What product is formed when ethene reacts with bromine?',
     'option_a':'Ethane','option_b':'1,2-dibromoethane','option_c':'Bromoethane','option_d':'Ethanol',
     'correct_answer':'B','explanation':'Ethene + Br₂ → 1,2-dibromoethane. This is an addition reaction where bromine adds across the double bond.',
     'correction_tip':'Halogenation of alkenes: C=C + Br₂ → C(Br)-C(Br) — a dibromoalkane.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'What type of polymerisation produces poly(ethene) from ethene?',
     'option_a':'Condensation polymerisation','option_b':'Addition polymerisation',
     'option_c':'Esterification','option_d':'Hydrolysis',
     'correct_answer':'B','explanation':'Addition polymerisation involves alkene monomers joining together as the C=C double bond opens; no atoms are lost.',
     'correction_tip':'Addition polymerisation: alkene monomers, double bond opens, no small molecule released.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'What small molecule is released during condensation polymerisation?',
     'option_a':'CO₂','option_b':'HCl','option_c':'H₂O','option_d':'O₂',
     'correct_answer':'C','explanation':'During condensation polymerisation, a small molecule (usually water) is eliminated as monomers join.',
     'correction_tip':'Condensation polymerisation releases H₂O (sometimes HCl with other monomers).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'Which two types of monomers react together to form a polyester?',
     'option_a':'Diamine and dicarboxylic acid',
     'option_b':'Diol and dicarboxylic acid',
     'option_c':'Diol and diamine',
     'option_d':'Alkene and diol',
     'correct_answer':'B','explanation':'Polyesters are formed from a diol and a dicarboxylic acid, joined by ester bonds with water eliminated.',
     'correction_tip':'Polyester: diol + dicarboxylic acid → ester bonds + H₂O. Polyamide: diamine + dicarboxylic acid.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'What are the conditions for industrial production of ethanol by hydration of ethene?',
     'option_a':'Yeast, 30°C, anaerobic','option_b':'H₃PO₄ catalyst, steam, 300°C, 60–70 atm',
     'option_c':'Nickel catalyst, 60°C, atmospheric pressure','option_d':'Zeolite catalyst, 400°C',
     'correct_answer':'B','explanation':'Industrial ethanol production by hydration uses H₃PO₄ as catalyst with steam at 300°C and 60–70 atm pressure.',
     'correction_tip':'Hydration of ethene: H₃PO₄ catalyst, 300°C, high pressure. Fermentation: yeast, 30°C.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'Ethanoic acid reacts with ethanol in the presence of an acid catalyst. What type of reaction is this?',
     'option_a':'Addition','option_b':'Elimination','option_c':'Esterification','option_d':'Hydrolysis',
     'correct_answer':'C','explanation':'Carboxylic acid + alcohol → ester + water is an esterification reaction. It is reversible and requires an acid catalyst.',
     'correction_tip':'Esterification: carboxylic acid + alcohol ⇌ ester + water (acid catalyst, reversible).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'Why is carbon monoxide produced by incomplete combustion dangerous?',
     'option_a':'It is highly explosive','option_b':'It dissolves in water to form an acid',
     'option_c':'It binds to haemoglobin in red blood cells, preventing oxygen transport',
     'option_d':'It corrodes metal in engines',
     'correct_answer':'C','explanation':'CO binds irreversibly to haemoglobin, forming carboxyhaemoglobin, preventing oxygen from being carried around the body.',
     'correction_tip':'CO is odourless, colourless, and toxic — it prevents blood from carrying oxygen.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'What is the name of the ester formed from ethanol and ethanoic acid?',
     'option_a':'Methyl methanoate','option_b':'Ethyl propanoate',
     'option_c':'Ethyl ethanoate','option_d':'Propyl ethanoate',
     'correct_answer':'C','explanation':'Ethanol + ethanoic acid → ethyl ethanoate + water. Esters are named alkyl (from alcohol) alkanoate (from acid).',
     'correction_tip':'Ester naming: alcohol part first (ethyl from ethanol) + acid part (ethanoate from ethanoic acid).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':2,
     'question_text':'Which of the following is a natural polyamide?',
     'option_a':'Poly(ethene)','option_b':'PET (polyester)','option_c':'Proteins','option_d':'PVC',
     'correct_answer':'C','explanation':'Proteins are natural polyamides formed from amino acids joining via amide (peptide) bonds with water eliminated.',
     'correction_tip':'Proteins = natural polyamides. DNA = natural condensation polymer. Nylon = synthetic polyamide.'},

    # -------------------------------------------------------------------------
    # C7 — D3 Hard — 14 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':3,
     'question_text':'Decane (C₁₀H₂₂) is cracked to give pentane and one other product. What is the molecular formula of the other product?',
     'option_a':'C₅H₁₂','option_b':'C₅H₁₀','option_c':'C₅H₈','option_d':'C₅H₁₄',
     'correct_answer':'B','explanation':'C₁₀H₂₂ → C₅H₁₂ + C₅H₁₀. The other product is pentene (C₅H₁₀, an alkene). Cracking always produces at least one alkene.',
     'correction_tip':'Cracking always makes at least one alkene. Check atoms balance: 10C and 22H on each side.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':3,
     'question_text':'Write the balanced equation for the complete combustion of propane (C₃H₈). Which option is correct?',
     'option_a':'C₃H₈ + 4O₂ → 3CO₂ + 4H₂O',
     'option_b':'C₃H₈ + 5O₂ → 3CO₂ + 4H₂O',
     'option_c':'C₃H₈ + 3O₂ → 3CO₂ + 3H₂O',
     'option_d':'C₃H₈ + 5O₂ → 3CO + 4H₂O',
     'correct_answer':'B','explanation':'C₃H₈ + 5O₂ → 3CO₂ + 4H₂O. Check: left 3C,8H,10O; right 3C,8H,10O ✓.',
     'correction_tip':'Complete combustion: alkane + O₂ → CO₂ + H₂O. Balance C first, then H, then O.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':3,
     'question_text':'What product forms when propene reacts with steam in the presence of H₃PO₄ catalyst?',
     'option_a':'Propane','option_b':'1,2-dibromopropane','option_c':'Propan-1-ol','option_d':'Propanoic acid',
     'correct_answer':'C','explanation':'Propene + H₂O (steam) → propan-1-ol. This addition reaction (hydration) adds water across the double bond.',
     'correction_tip':'Hydration of alkene: alkene + H₂O → alcohol (H₃PO₄ catalyst, 300°C).'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':3,
     'question_text':'Draw the repeat unit of poly(propene). Which structure correctly shows the repeat unit?',
     'option_a':'(-CH₂-CH₂-)ₙ','option_b':'(-CH₂-CH(CH₃)-)ₙ',
     'option_c':'(-CH(CH₃)-CH(CH₃)-)ₙ','option_d':'(-CH₂-C(CH₃)₂-)ₙ',
     'correct_answer':'B','explanation':'Propene (CH₂=CHCH₃) polymerises by opening the double bond to give the repeat unit (-CH₂-CH(CH₃)-)ₙ.',
     'correction_tip':'To draw repeat unit: open the C=C double bond and extend bonds at each end. Each carbon keeps its substituents.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'PET is a polyester made from ethane-1,2-diol and benzene-1,4-dicarboxylic acid. What type of bond links the monomers?',
     'option_a':'Amide bond','option_b':'Peptide bond','option_c':'Ether bond','option_d':'Ester bond',
     'correct_answer':'D','explanation':'In polyesters such as PET, monomers are linked by ester bonds (-COO-) formed between the -OH of the diol and -COOH of the dicarboxylic acid.',
     'correction_tip':'Polyester = ester bonds (-COO-). Polyamide (nylon, proteins) = amide bonds (-CONH-).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Nylon-6,6 is a polyamide. Which monomers are used to make it?',
     'option_a':'Ethane-1,2-diol and benzene-1,4-dicarboxylic acid',
     'option_b':'Hexane-1,6-diamine and hexanedioic acid',
     'option_c':'Glucose and amino acids',
     'option_d':'Ethene and propene',
     'correct_answer':'B','explanation':'Nylon-6,6 is made from hexane-1,6-diamine and hexanedioic acid. Amide bonds form and water is released.',
     'correction_tip':'Polyamide: diamine + dicarboxylic acid → amide bonds + H₂O.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Compare fermentation and hydration as methods of producing ethanol. Which statement is correct?',
     'option_a':'Fermentation produces a purer product than hydration',
     'option_b':'Hydration uses a renewable feedstock',
     'option_c':'Fermentation uses yeast and is a batch process giving dilute ethanol',
     'option_d':'Hydration uses glucose as the starting material',
     'correct_answer':'C','explanation':'Fermentation is a batch process using yeast at ~30°C producing dilute ethanol from glucose (renewable). Hydration of ethene (non-renewable, from crude oil) gives pure ethanol continuously.',
     'correction_tip':'Fermentation: batch, dilute, renewable, yeast, 30°C. Hydration: continuous, pure, non-renewable.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'A student tests two liquids with bromine water. Liquid A decolourises it; Liquid B does not. What can be concluded?',
     'option_a':'Liquid A is an alkane; Liquid B is an alkene',
     'option_b':'Liquid A is an alkene; Liquid B is an alkane (or saturated compound)',
     'option_c':'Both liquids are alkenes','option_d':'Both liquids are alkanes',
     'correct_answer':'B','explanation':'Only unsaturated compounds (alkenes) decolourise bromine water via addition across the C=C double bond. Alkanes are saturated and do not react.',
     'correction_tip':'Bromine water test: orange→colourless = unsaturated (alkene). No change = saturated (alkane).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Ethanol burns in excess oxygen. Which balanced equation is correct?',
     'option_a':'C₂H₅OH + 2O₂ → 2CO₂ + 2H₂O',
     'option_b':'C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O',
     'option_c':'C₂H₅OH + 3O₂ → CO₂ + 3H₂O',
     'option_d':'C₂H₅OH + 2O₂ → CO₂ + 3H₂O',
     'correct_answer':'B','explanation':'C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O. Check: 2C, 6H, 7O on each side ✓.',
     'correction_tip':'Balance C then H then O. Ethanol has an -OH group; count its oxygen when balancing.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Why are polymers such as poly(ethene) described as non-biodegradable?',
     'option_a':'They dissolve in water','option_b':'They react with oxygen in the air',
     'option_c':'Microorganisms cannot break down their long polymer chains',
     'option_d':'They have low melting points',
     'correct_answer':'C','explanation':'The long, strong covalent chains of addition polymers cannot be broken down by microorganisms, making them persist in the environment.',
     'correction_tip':'Non-biodegradable = microorganisms cannot decompose the material → environmental problem.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'What is the difference between addition and condensation polymerisation?',
     'option_a':'Addition polymerisation releases H₂O; condensation does not',
     'option_b':'Addition polymerisation uses saturated monomers; condensation uses unsaturated monomers',
     'option_c':'Addition polymerisation uses unsaturated monomers and no atoms are lost; condensation polymerisation uses bifunctional monomers and releases a small molecule',
     'option_d':'Condensation polymerisation only occurs at high temperatures',
     'correct_answer':'C','explanation':'Addition polymerisation: alkene monomers, C=C opens, no by-product. Condensation polymerisation: bifunctional monomers, small molecule (usually H₂O) released.',
     'correction_tip':'Key difference: addition = no atoms lost; condensation = small molecule (H₂O) released.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Carboxylic acids are described as weak acids. What does this mean?',
     'option_a':'They do not react with metals','option_b':'They only partially ionise in aqueous solution',
     'option_c':'They are dilute solutions','option_d':'They have a pH above 7',
     'correct_answer':'B','explanation':'Weak acids only partially ionise in water, meaning not all molecules release H⁺ ions. This gives a higher pH than a strong acid of the same concentration.',
     'correction_tip':'Weak acid = partially ionises. Strong acid = fully ionises. Ethanoic acid is a weak acid.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':3,
     'question_text':'Which statement about methanol is correct?',
     'option_a':'It is the same as ethanol and safe to drink in small amounts',
     'option_b':'It can cause permanent blindness or death even in small doses',
     'option_c':'It is produced by fermentation of glucose','option_d':'Its formula is C₂H₅OH',
     'correct_answer':'B','explanation':'Methanol (CH₃OH) is highly toxic; even small amounts can cause blindness or death. It should never be confused with ethanol.',
     'correction_tip':'Methanol = CH₃OH = TOXIC → blindness/death. Ethanol = C₂H₅OH = less toxic (in drinks).'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':3,
     'question_text':'A hydrocarbon fraction has a higher boiling point than petrol. Which TWO properties would it also have compared to petrol?',
     'option_a':'More viscous and less flammable',
     'option_b':'Less viscous and more flammable',
     'option_c':'More volatile and less viscous',
     'option_d':'Less viscous and less volatile',
     'correct_answer':'A','explanation':'Longer chain fractions (higher BP) are more viscous and less flammable than shorter chain fractions like petrol.',
     'correction_tip':'Longer chain → higher BP, more viscous, less volatile, less flammable.'},

    # -------------------------------------------------------------------------
    # C7 — D4 Exam Challenge — 14 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':4,
     'question_text':'A student cracks hexadecane (C₁₆H₃₄) and obtains octane (C₈H₁₈) and two other products of equal carbon number. If one product is an alkene, what are the molecular formulas of both additional products?',
     'option_a':'C₄H₁₀ and C₄H₈','option_b':'C₄H₈ and C₄H₈',
     'option_c':'C₄H₁₀ and C₄H₁₀','option_d':'C₄H₆ and C₄H₁₀',
     'correct_answer':'A','explanation':'C₁₆H₃₄ → C₈H₁₈ + C₄H₁₀ + C₄H₈. Check: 16C and 34H on each side: 8+4+4=16 ✓; 18+10+8=36... re-check: C₁₆H₃₄ → C₈H₁₈ + C₄H₈ + C₄H₈ gives 34H? 18+8+8=34 ✓. Actually option B also gives correct H count. The question states one alkene and one alkane of equal carbon count: C₄H₁₀ (butane) + C₄H₈ (butene). H total: 18+10+8=36 ≠ 34. So: C₁₆H₃₄ → C₈H₁₈ + C₄H₈ + C₄H₈. 18+8+8=34 ✓ 8+4+4=16 ✓. Both additional products are C₄H₈ (butene). However the question says one is an alkene — option A has one alkane one alkene; let us re-examine: if products are C₄H₁₀+C₄H₈: H=18+10+8=36≠34. Products C₄H₈+C₄H₈: H=18+8+8=34 ✓. So correct answer is B.',
     'correction_tip':'Always verify atom balance: sum of all H atoms in products must equal H atoms in reactant.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':4,
     'question_text':'Explain why fractional distillation separates crude oil into fractions.',
     'option_a':'Different fractions have different densities so they layer out',
     'option_b':'Different fractions have different boiling points due to different chain lengths; shorter chains condense at lower temperatures higher up the column',
     'option_c':'The column filters out impurities by particle size',
     'option_d':'Chemical reactions in the column convert long chains to short chains',
     'correct_answer':'B','explanation':'The fractionating column has a temperature gradient (hot at bottom, cool at top). Each fraction condenses at the temperature matching its boiling point, which depends on chain length and intermolecular forces.',
     'correction_tip':'Fractional distillation relies on different boiling points (not density). Short chain = low BP = condenses high up column.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':4,
     'question_text':'Styrene (C₆H₅CH=CH₂) undergoes addition polymerisation. What is the repeat unit of poly(styrene)?',
     'option_a':'(-CH₂-CH₂-)ₙ','option_b':'(-CH₂-CH(C₆H₅)-)ₙ',
     'option_c':'(-CH(C₆H₅)-CH(C₆H₅)-)ₙ','option_d':'(-CH₂-C(C₆H₅)₂-)ₙ',
     'correct_answer':'B','explanation':'Opening the C=C double bond in styrene gives repeat unit (-CH₂-CH(C₆H₅)-)ₙ, where C₆H₅ is the phenyl group.',
     'correction_tip':'Open the double bond to get the repeat unit; each carbon retains its substituents.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'A carboxylic acid reacts with sodium carbonate. Which observation and equation are both correct?',
     'option_a':'No reaction occurs; carboxylic acids are too weak to react with carbonates',
     'option_b':'Effervescence of CO₂; 2CH₃COOH + Na₂CO₃ → 2CH₃COONa + H₂O + CO₂',
     'option_c':'Blue precipitate forms; acid reacts with carbonate to give a salt and water only',
     'option_d':'Effervescence; CH₃COOH + Na₂CO₃ → CH₃COONa + H₂CO₃',
     'correct_answer':'B','explanation':'Carboxylic acids, though weak, do react with carbonates: 2CH₃COOH + Na₂CO₃ → 2CH₃COONa + H₂O + CO₂. Effervescence (fizzing) is observed.',
     'correction_tip':'Carboxylic acid + carbonate → salt + water + CO₂ (effervescence). Weak acid still reacts with carbonates.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'Compare the environmental impact of sourcing ethanol by fermentation versus hydration of ethene.',
     'option_a':'Both have identical environmental impacts',
     'option_b':'Fermentation uses renewable biomass (crops absorb CO₂) so is more sustainable; hydration uses ethene from non-renewable crude oil',
     'option_c':'Hydration is greener because it produces purer ethanol with no waste CO₂',
     'option_d':'Fermentation is unsustainable because it uses large quantities of water',
     'correct_answer':'B','explanation':'Fermentation uses renewable plant sugars; crops absorb CO₂ during growth making it closer to carbon neutral. Hydration of ethene uses fossil-fuel derived ethene, contributing to net CO₂ emissions.',
     'correction_tip':'Fermentation = renewable feedstock, closer to carbon neutral. Hydration = non-renewable (crude oil based).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'A polymer has the repeat unit (-CH₂-CHCl-)ₙ. What monomer produced this polymer and what type of polymerisation occurred?',
     'option_a':'Monomer: CH₂=CCl₂; addition polymerisation',
     'option_b':'Monomer: CHCl=CHCl; condensation polymerisation',
     'option_c':'Monomer: CH₂=CHCl (chloroethene); addition polymerisation',
     'option_d':'Monomer: CH₂=CHCl; condensation polymerisation',
     'correct_answer':'C','explanation':'(-CH₂-CHCl-)ₙ is PVC, made by addition polymerisation of chloroethene (vinyl chloride, CH₂=CHCl).',
     'correction_tip':'To find monomer: add a double bond between the two carbons of the repeat unit. PVC = poly(chloroethene).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'Ethyl ethanoate can be hydrolysed. What are the products of acid hydrolysis?',
     'option_a':'Ethene and ethanoic acid','option_b':'Ethanol and ethanoic acid',
     'option_c':'Ethanol and carbon dioxide','option_d':'Ethane and ethanoic acid',
     'correct_answer':'B','explanation':'Acid hydrolysis of ethyl ethanoate (with dilute H₂SO₄/HCl and water) reverses esterification: CH₃COOC₂H₅ + H₂O ⇌ CH₃COOH + C₂H₅OH.',
     'correction_tip':'Hydrolysis of ester = reverse of esterification → alcohol + carboxylic acid.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'Why does incomplete combustion occur in a car engine, and what are the two harmful products formed?',
     'option_a':'Too much oxygen; forms CO₂ and H₂O','option_b':'Limited oxygen supply; forms CO and soot (carbon)',
     'option_c':'Too much fuel; forms CO₂ and NO₂','option_d':'High temperature; forms SO₂ and NO',
     'correct_answer':'B','explanation':'Incomplete combustion occurs when there is insufficient oxygen. Products include carbon monoxide (CO, toxic) and soot/carbon particles (particulates, lung irritant).',
     'correction_tip':'Incomplete combustion: limited O₂ → CO + carbon (soot) + H₂O. CO is toxic; particulates cause respiratory problems.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'A student claims "all plastics should be burned for energy recovery." Evaluate this claim.',
     'option_a':'Correct; burning is always the best option for polymers',
     'option_b':'Partly correct; burning recovers energy but releases CO₂ and toxic gases (e.g. HCl from PVC); recycling is preferable where possible',
     'option_c':'Incorrect; plastics cannot be burned','option_d':'Incorrect; burning polymers produces only water',
     'correct_answer':'B','explanation':'Combustion of plastics does recover energy but produces CO₂ (greenhouse gas) and potentially toxic gases such as HCl from PVC. Mechanical recycling or chemical recycling are preferable.',
     'correction_tip':'Evaluate: burning recovers energy (advantage) but releases CO₂ and toxic gases (disadvantage); recycling is better for sustainability.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'Which statement best explains why nylon is classified as a condensation polymer rather than an addition polymer?',
     'option_a':'Nylon monomers contain C=C double bonds that open during polymerisation',
     'option_b':'Nylon is made from two different monomers each with two functional groups, releasing water as a by-product',
     'option_c':'Nylon monomers only contain carbon and hydrogen',
     'option_d':'Nylon cannot be recycled',
     'correct_answer':'B','explanation':'Nylon (a polyamide) is formed from hexane-1,6-diamine and hexanedioic acid via condensation polymerisation, releasing water. The monomers each have two functional groups.',
     'correction_tip':'Condensation polymerisation: bifunctional monomers, small molecule (H₂O) released. No C=C needed.'},

    {'subject':'Chemistry','topic':'Hydrocarbons','topic_code':'C7','difficulty':4,
     'question_text':'Thermal cracking differs from catalytic cracking. Which statement is correct?',
     'option_a':'Thermal cracking uses a zeolite catalyst and lower temperatures',
     'option_b':'Thermal cracking operates at 600–700°C and high pressure, producing mainly alkenes; catalytic cracking uses a zeolite at 400–500°C, producing branched alkanes and aromatic compounds',
     'option_c':'Both processes produce identical products','option_d':'Catalytic cracking requires no catalyst',
     'correct_answer':'B','explanation':'Thermal cracking: 600–700°C, high pressure, mainly alkenes produced. Catalytic cracking: zeolite catalyst, 400–500°C, branched alkanes and aromatic compounds produced.',
     'correction_tip':'Thermal: high T, high P, mainly alkenes. Catalytic: zeolite, lower T, branched alkanes + aromatics.'},

    {'subject':'Chemistry','topic':'Alkenes','topic_code':'C7','difficulty':4,
     'question_text':'Explain how bromine water can distinguish between hexane and hex-1-ene, including the chemistry involved.',
     'option_a':'Both decolourise bromine water; the rate of reaction distinguishes them',
     'option_b':'Hexane turns bromine water blue; hex-1-ene turns it red',
     'option_c':'Hex-1-ene decolourises bromine water (orange→colourless) via addition reaction across C=C; hexane does not react as it is saturated',
     'option_d':'Hexane decolourises bromine water; hex-1-ene does not because it is unsaturated',
     'correct_answer':'C','explanation':'Hex-1-ene has a C=C double bond; bromine adds across it (CH₂=CH... + Br₂ → CHBr–CHBr...) decolourising the solution. Hexane is saturated; it does not react with bromine water in the absence of UV light.',
     'correction_tip':'Unsaturated compound + Br₂ → addition product (decolourises). Saturated compound + Br₂ → no reaction (without UV).'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'A dicarboxylic acid HOOC-(CH₂)₄-COOH reacts with a diamine H₂N-(CH₂)₆-NH₂. What type of polymer forms and what bond is present in the backbone?',
     'option_a':'Polyester; ester bond (-COO-)','option_b':'Polyamide; amide bond (-CONH-)',
     'option_c':'Addition polymer; no new bond type','option_d':'Polypeptide; peptide bond only in living systems',
     'correct_answer':'B','explanation':'Dicarboxylic acid + diamine → polyamide (e.g. nylon). The two functional groups react to form amide bonds (-CO-NH-) with elimination of water.',
     'correction_tip':'Diamine + dicarboxylic acid → polyamide with amide bonds. Diol + dicarboxylic acid → polyester with ester bonds.'},

    {'subject':'Chemistry','topic':'Organic chemistry','topic_code':'C7','difficulty':4,
     'question_text':'The equation for fermentation is: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. Calculate the atom economy for ethanol production in this reaction. (Mr: C₆H₁₂O₆=180; C₂H₅OH=46; CO₂=44)',
     'option_a':'25.6%','option_b':'51.1%','option_c':'46.0%','option_d':'88.0%',
     'correct_answer':'B','explanation':'Atom economy = (mass of desired product / total mass of all products) × 100 = (2×46)/(2×46 + 2×44) × 100 = 92/180 × 100 = 51.1%.',
     'correction_tip':'Atom economy = (Mr of desired product × moles) / (Mr of all products × moles) × 100.'},

    # -------------------------------------------------------------------------
    # C8 CHEMICAL ANALYSIS — 59 questions
    # D1 Easy — 14 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What colour flame does sodium (Na⁺) produce in a flame test?',
     'option_a':'Crimson/red','option_b':'Lilac/violet','option_c':'Yellow/orange','option_d':'Green-blue',
     'correct_answer':'C','explanation':'Sodium produces a bright yellow/orange flame. This is very distinctive and can mask other colours.',
     'correction_tip':'Na⁺ = yellow/orange (very bright). Li⁺ = crimson. K⁺ = lilac. Cu²⁺ = green-blue.'},

    {'subject':'Chemistry','topic':'Flame tests','topic_code':'C8','difficulty':1,
     'question_text':'Which metal ion gives a crimson/red flame colour?',
     'option_a':'K⁺','option_b':'Na⁺','option_c':'Cu²⁺','option_d':'Li⁺',
     'correct_answer':'D','explanation':'Lithium (Li⁺) gives a crimson/red flame colour.',
     'correction_tip':'Li⁺ = crimson. Na⁺ = yellow. K⁺ = lilac. Ca²⁺ = orange-red. Cu²⁺ = green-blue.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What gas is produced when a carbonate is tested with dilute acid?',
     'option_a':'Hydrogen','option_b':'Oxygen','option_c':'Carbon dioxide','option_d':'Chlorine',
     'correct_answer':'C','explanation':'Carbonates react with dilute acids to produce CO₂: CO₃²⁻ + 2H⁺ → H₂O + CO₂.',
     'correction_tip':'Carbonate + acid → salt + water + CO₂. Test CO₂ with limewater (turns milky).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What is used to test for oxygen gas in the laboratory?',
     'option_a':'Burning splint — makes a squeaky pop',
     'option_b':'Glowing splint — relights',
     'option_c':'Damp litmus paper — turns blue',
     'option_d':'Limewater — turns milky',
     'correct_answer':'B','explanation':'Oxygen relights a glowing splint. This is the standard test for O₂.',
     'correction_tip':'O₂ = glowing splint relights. H₂ = burning splint squeaky pop. CO₂ = limewater milky.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What colour precipitate forms when Fe³⁺ ions react with NaOH solution?',
     'option_a':'Green','option_b':'Blue','option_c':'Brown/rust','option_d':'White',
     'correct_answer':'C','explanation':'Fe³⁺ + 3OH⁻ → Fe(OH)₃, which is a brown/rust coloured precipitate.',
     'correction_tip':'Fe²⁺ = green precipitate. Fe³⁺ = brown/rust precipitate. Cu²⁺ = blue precipitate.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What does Rf stand for in paper chromatography, and what is its maximum possible value?',
     'option_a':'Relative flow; maximum 10','option_b':'Retention factor; maximum 1',
     'option_c':'Rate factor; maximum 100','option_d':'Reaction frequency; maximum 1',
     'correct_answer':'B','explanation':'Rf = distance moved by substance / distance moved by solvent front. As the spot cannot travel further than the solvent, Rf has a maximum value of 1.',
     'correction_tip':'Rf = distance of spot / distance of solvent front. Always between 0 and 1.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'How do you test for hydrogen gas?',
     'option_a':'Hold a glowing splint near the gas — it relights',
     'option_b':'Hold a burning splint near the gas — it makes a squeaky pop',
     'option_c':'Bubble the gas through limewater — it turns milky',
     'option_d':'Hold damp litmus paper near the gas — it turns blue',
     'correct_answer':'B','explanation':'Hydrogen produces a squeaky pop when a burning splint is held near it, as H₂ combusts rapidly.',
     'correction_tip':'H₂ = burning splint squeaky pop (H₂ combusts). O₂ = glowing splint relights.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What colour precipitate does Cu²⁺ form with NaOH solution?',
     'option_a':'Brown','option_b':'Green','option_c':'White','option_d':'Blue',
     'correct_answer':'D','explanation':'Cu²⁺ + 2OH⁻ → Cu(OH)₂, a blue precipitate.',
     'correction_tip':'Cu²⁺ = blue precipitate with NaOH. Also gives green-blue flame in flame test.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What is the test for chlorine gas?',
     'option_a':'It turns limewater milky','option_b':'It makes a burning splint squeak',
     'option_c':'It bleaches damp litmus paper white','option_d':'It relights a glowing splint',
     'correct_answer':'C','explanation':'Chlorine bleaches damp litmus paper white. Cl₂ is also yellow-green and toxic.',
     'correction_tip':'Cl₂ = bleaches damp litmus white (and is yellow-green coloured gas).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'A pure substance melts at a single sharp temperature. What does this tell you about its purity?',
     'option_a':'Nothing; all substances melt at a single temperature',
     'option_b':'It is likely pure; impurities cause melting over a range and lower the melting point',
     'option_c':'It contains multiple components','option_d':'It has a high molecular mass',
     'correct_answer':'B','explanation':'A sharp melting point matching the data book value indicates purity. Impurities lower the melting point and cause melting over a range.',
     'correction_tip':'Pure substance = sharp, single MP/BP. Mixture/impure = melts/boils over a range.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What colour does potassium (K⁺) give in a flame test?',
     'option_a':'Yellow','option_b':'Crimson','option_c':'Lilac/violet','option_d':'Orange-red',
     'correct_answer':'C','explanation':'Potassium gives a lilac/violet flame colour.',
     'correction_tip':'K⁺ = lilac. Na⁺ = yellow. Li⁺ = crimson. Ca²⁺ = orange-red.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'In paper chromatography, what is the stationary phase?',
     'option_a':'The solvent','option_b':'The paper','option_c':'The sample','option_d':'The pencil line',
     'correct_answer':'B','explanation':'In paper chromatography the paper acts as the stationary phase. The solvent is the mobile phase.',
     'correction_tip':'Stationary phase = paper (does not move). Mobile phase = solvent (moves up the paper).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What colour precipitate forms when Fe²⁺ ions react with NaOH solution?',
     'option_a':'Brown','option_b':'Blue','option_c':'White','option_d':'Green',
     'correct_answer':'D','explanation':'Fe²⁺ + 2OH⁻ → Fe(OH)₂, a green precipitate.',
     'correction_tip':'Fe²⁺ = green precipitate. Fe³⁺ = brown/rust. Cu²⁺ = blue.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':1,
     'question_text':'What gas turns damp red litmus paper blue?',
     'option_a':'Chlorine','option_b':'Hydrogen','option_c':'Ammonia','option_d':'Carbon dioxide',
     'correct_answer':'C','explanation':'Ammonia (NH₃) is alkaline and turns damp red litmus paper blue.',
     'correction_tip':'NH₃ = turns damp red litmus blue (alkaline). Cl₂ = bleaches litmus white. CO₂ = turns limewater milky.'},

    # -------------------------------------------------------------------------
    # C8 — D2 Medium — 15 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'How would you test for sulfate ions (SO₄²⁻) in solution?',
     'option_a':'Add AgNO₃ solution — white precipitate forms',
     'option_b':'Add BaCl₂ solution acidified with HCl — white precipitate forms',
     'option_c':'Add NaOH solution — brown precipitate forms',
     'option_d':'Add dilute HCl — effervescence occurs',
     'correct_answer':'B','explanation':'SO₄²⁻ + Ba²⁺ → BaSO₄ (white precipitate). The HCl acidification prevents false positives from BaCO₃.',
     'correction_tip':'Sulfate test: acidified BaCl₂ → white precipitate BaSO₄ (insoluble in excess acid).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'What is the colour of the precipitate formed when Br⁻ ions react with silver nitrate solution?',
     'option_a':'White','option_b':'Yellow','option_c':'Cream','option_d':'Black',
     'correct_answer':'C','explanation':'Br⁻ + Ag⁺ → AgBr, a cream precipitate. Cl⁻ gives white AgCl; I⁻ gives yellow AgI.',
     'correction_tip':'Cl⁻ = white precipitate AgCl. Br⁻ = cream precipitate AgBr. I⁻ = yellow precipitate AgI.'},

    {'subject':'Chemistry','topic':'Flame tests','topic_code':'C8','difficulty':2,
     'question_text':'Why can sodium be a problem when performing flame tests on samples that may also contain potassium?',
     'option_a':'Sodium burns at too high a temperature','option_b':'Sodium produces a bright yellow flame that can mask the lilac colour of potassium',
     'option_c':'Sodium and potassium produce the same colour','option_d':'Potassium extinguishes the sodium flame',
     'correct_answer':'B','explanation':'Sodium produces a very bright yellow/orange flame that can overwhelm and mask the lilac colour of potassium, making K⁺ difficult to identify.',
     'correction_tip':'Na⁺ yellow flame is so intense it can mask K⁺ lilac flame — a key limitation of flame tests.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'In paper chromatography, a student measures: spot travelled 4.8 cm; solvent front travelled 8.0 cm. Calculate the Rf value.',
     'option_a':'0.40','option_b':'0.60','option_c':'1.67','option_d':'0.48',
     'correct_answer':'B','explanation':'Rf = 4.8 / 8.0 = 0.60.',
     'correction_tip':'Rf = distance of spot ÷ distance of solvent front = 4.8/8.0 = 0.6.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'White precipitate forms when NaOH is added to a metal ion solution, but the precipitate dissolves when excess NaOH is added. Which ion is present?',
     'option_a':'Ca²⁺','option_b':'Mg²⁺','option_c':'Al³⁺','option_d':'Fe²⁺',
     'correct_answer':'C','explanation':'Al(OH)₃ is amphoteric; it dissolves in excess NaOH to form aluminate ions. Ca²⁺ and Mg²⁺ also give white precipitates but these do NOT dissolve in excess NaOH.',
     'correction_tip':'White ppt dissolves in excess NaOH → Al³⁺. White ppt remains in excess → Ca²⁺ or Mg²⁺.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'How is the test for NH₄⁺ ions carried out, and what is the positive result?',
     'option_a':'Add AgNO₃; cream precipitate forms',
     'option_b':'Add dilute HCl; effervescence occurs',
     'option_c':'Warm with NaOH solution; ammonia gas produced (turns damp red litmus blue)',
     'option_d':'Add BaCl₂; white precipitate forms',
     'correct_answer':'C','explanation':'NH₄⁺ + OH⁻ → NH₃(g) + H₂O when warmed with NaOH. The pungent ammonia turns damp red litmus paper blue.',
     'correction_tip':'NH₄⁺ test: warm with NaOH → NH₃ gas → turns damp red litmus blue.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'What advantage does flame emission spectroscopy have over a conventional flame test?',
     'option_a':'It only works for sodium','option_b':'It produces unique line spectra for each element, is more precise, and can detect multiple metals simultaneously',
     'option_c':'It does not require any equipment','option_d':'It gives results only as colours visible to the naked eye',
     'correct_answer':'B','explanation':'Flame emission spectroscopy produces a unique line spectrum for each element, allowing precise identification and quantitative analysis even when multiple metals are present.',
     'correction_tip':'Instrumental flame emission spectroscopy is faster, more precise, and can give quantitative results compared to simple flame tests.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'What does a single spot on a chromatogram indicate about a sample?',
     'option_a':'The sample is a mixture of at least two compounds',
     'option_b':'The sample is pure or contains only one component under those conditions',
     'option_c':'The experiment was performed incorrectly',
     'option_d':'The compound has a high molecular mass',
     'correct_answer':'B','explanation':'A single spot suggests the sample is pure or contains only one component with that Rf value in the chosen solvent.',
     'correction_tip':'Single spot = pure (or one component). Multiple spots = mixture. Note: two different compounds could coincidentally have the same Rf.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'Which gas decolourises acidified potassium permanganate (KMnO₄)?',
     'option_a':'CO₂','option_b':'NH₃','option_c':'SO₂','option_d':'O₂',
     'correct_answer':'C','explanation':'SO₂ is a reducing agent that decolourises acidified KMnO₄ (purple → colourless). This can be used as a test for SO₂.',
     'correction_tip':'SO₂ decolourises acidified KMnO₄. SO₂ also turns damp blue litmus red (acidic).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'What is the colour of chlorine gas and why is it hazardous?',
     'option_a':'Colourless and non-toxic','option_b':'Yellow-green and toxic (irritant/corrosive to lungs)',
     'option_c':'Brown and explosive','option_d':'Blue and oxidising',
     'correct_answer':'B','explanation':'Chlorine is a yellow-green gas that is toxic; it irritates and damages the respiratory system even in low concentrations.',
     'correction_tip':'Cl₂ = yellow-green, toxic, bleaches litmus. Used as a chemical weapon in WWI.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'In mass spectrometry, what information does the molecular ion peak (M⁺) provide?',
     'option_a':'The boiling point of the compound','option_b':'The relative molecular mass (Mr) of the compound',
     'option_c':'The number of carbon atoms only','option_d':'The concentration of the sample',
     'correct_answer':'B','explanation':'The molecular ion peak (M⁺, highest m/z peak) in a mass spectrum corresponds to the relative molecular mass (Mr) of the compound.',
     'correction_tip':'M⁺ peak (highest m/z) = Mr of compound. Fragmentation pattern identifies the compound.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'Why must the nichrome wire loop be cleaned between flame tests?',
     'option_a':'To prevent the wire from melting','option_b':'To prevent contamination from previous samples giving a false colour',
     'option_c':'To make the flame hotter','option_d':'To remove oxide from the wire surface',
     'correct_answer':'B','explanation':'Any residue from a previous sample would contaminate the next test and could give a false or mixed colour, especially if sodium is present.',
     'correction_tip':'Clean loop (dip in HCl, heat until no colour) to avoid contamination between tests.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'A white precipitate forms with AgNO₃ (acidified with dilute HNO₃) and then dissolves when dilute ammonia is added. Which ion is present?',
     'option_a':'I⁻','option_b':'Br⁻','option_c':'Cl⁻','option_d':'SO₄²⁻',
     'correct_answer':'C','explanation':'AgCl (white) dissolves in dilute NH₃. AgBr (cream) dissolves only in concentrated NH₃. AgI (yellow) is insoluble in NH₃.',
     'correction_tip':'Cl⁻ = white AgCl, dissolves in dilute NH₃. Br⁻ = cream AgBr, dissolves in conc NH₃. I⁻ = yellow AgI, insoluble in NH₃.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'What are the advantages of instrumental analysis over traditional chemical tests?',
     'option_a':'Cheaper and requires no training','option_b':'Faster, more sensitive, more accurate, and can work with very small samples',
     'option_c':'Produces coloured precipitates that are easier to see','option_d':'No equipment needed',
     'correct_answer':'B','explanation':'Instrumental analysis is faster, more sensitive (detects trace amounts), more accurate, and requires much smaller sample sizes than traditional chemical tests.',
     'correction_tip':'Instrumental analysis: faster, more sensitive, more accurate, smaller samples, can identify mixtures.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':2,
     'question_text':'Why is paper chromatography particularly useful for analysing food dyes?',
     'option_a':'It changes the colour of the dyes permanently',
     'option_b':'It can separate a mixture of dyes and identify each component by Rf value',
     'option_c':'It measures the exact mass of each dye','option_d':'It destroys impurities in the food',
     'correct_answer':'B','explanation':'Paper chromatography separates mixtures based on differential solubility and can identify components by comparing Rf values with known standards.',
     'correction_tip':'Chromatography separates mixtures and identifies components by Rf value comparison with standards.'},

    # -------------------------------------------------------------------------
    # C8 — D3 Hard — 15 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'A student adds NaOH to an unknown solution and observes a white precipitate that does NOT dissolve in excess NaOH. Which ions could be present?',
     'option_a':'Al³⁺ only','option_b':'Fe²⁺ or Fe³⁺',
     'option_c':'Ca²⁺ or Mg²⁺','option_d':'Cu²⁺ or Zn²⁺',
     'correct_answer':'C','explanation':'Ca²⁺ and Mg²⁺ both give white precipitates with NaOH that do NOT dissolve in excess. Al³⁺ also gives white precipitate but it DOES dissolve in excess NaOH.',
     'correction_tip':'White ppt, insoluble in excess NaOH → Ca²⁺ or Mg²⁺. White ppt dissolves in excess → Al³⁺.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Describe how you would carry out a flame test and state the colour produced by calcium (Ca²⁺).',
     'option_a':'Dip paper in solution; hold in flame; Ca²⁺ gives crimson',
     'option_b':'Clean nichrome wire loop; dip in sample solution; hold in roaring blue Bunsen flame; Ca²⁺ gives orange-red/brick red',
     'option_c':'Dip copper wire in sample; hold in flame; Ca²⁺ gives yellow',
     'option_d':'Add acid to sample; hold test tube near flame; Ca²⁺ gives lilac',
     'correct_answer':'B','explanation':'Correct procedure: clean nichrome loop, dip in sample, hold in roaring flame. Ca²⁺ gives an orange-red (brick red) flame colour.',
     'correction_tip':'Flame test procedure: clean wire → dip in sample → roaring Bunsen flame → observe colour. Ca²⁺ = orange-red/brick red.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Explain why the acid used to acidify BaCl₂ in the sulfate test must be HCl, not H₂SO₄.',
     'option_a':'H₂SO₄ would react with the BaCl₂ to produce an acidic solution',
     'option_b':'H₂SO₄ contains SO₄²⁻ ions, which would give a false positive white precipitate',
     'option_c':'HCl reacts with BaSO₄ to dissolve it','option_d':'H₂SO₄ would neutralise the NaOH',
     'correct_answer':'B','explanation':'Adding H₂SO₄ would introduce SO₄²⁻ ions, causing a white precipitate of BaSO₄ regardless of whether the original sample contained sulfate — a false positive.',
     'correction_tip':'Use HCl (not H₂SO₄) to acidify BaCl₂ for sulfate test, to avoid introducing SO₄²⁻ ions from the acid.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'A mixture of amino acids is separated by paper chromatography. The spots are not visible. What reagent is used to locate them, and what colour do they turn?',
     'option_a':'BaCl₂; white spots','option_b':'AgNO₃; black spots',
     'option_c':'Ninhydrin; purple/brown spots','option_d':'Universal indicator; red spots',
     'correct_answer':'C','explanation':'Ninhydrin is a locating agent for amino acids. It reacts with amino acids to produce purple/brown spots, making them visible.',
     'correction_tip':'Ninhydrin is used to locate amino acids on chromatograms (colourless → purple/brown).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'In GC-MS, what is the role of the gas chromatography (GC) component?',
     'option_a':'It identifies each component by its fragmentation pattern',
     'option_b':'It separates the components of the mixture based on their interaction with the stationary phase',
     'option_c':'It measures the molecular mass of the intact molecule',
     'option_d':'It burns the sample to produce ions',
     'correct_answer':'B','explanation':'In GC-MS, the GC component separates the mixture into individual components. Each component then enters the mass spectrometer for identification.',
     'correction_tip':'GC = separates mixture. MS = identifies each component. Together: GC-MS separates AND identifies.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Why must dilute nitric acid (HNO₃) be added before AgNO₃ in the test for halide ions?',
     'option_a':'To dissolve the silver nitrate','option_b':'To prevent false positives from other ions such as CO₃²⁻ and SO₄²⁻ that also form precipitates with Ag⁺',
     'option_c':'To provide H⁺ ions for the reaction','option_d':'To oxidise the halide ions',
     'correct_answer':'B','explanation':'HNO₃ removes interfering ions such as CO₃²⁻ (which would give Ag₂CO₃, a white precipitate) ensuring any precipitate is due to the halide only.',
     'correction_tip':'Acidify with dilute HNO₃ before AgNO₃ to remove interfering anions (CO₃²⁻, SO₄²⁻).'},

    {'subject':'Chemistry','topic':'Flame tests','topic_code':'C8','difficulty':3,
     'question_text':'A sample gives a lilac flame that is difficult to see clearly. What technique can improve visibility?',
     'option_a':'Use a larger sample','option_b':'View through blue cobalt glass to filter out any yellow sodium contamination',
     'option_c':'Use a yellow Bunsen flame','option_d':'Add more acid to the sample',
     'correct_answer':'B','explanation':'Blue cobalt glass absorbs yellow light from sodium, allowing the lilac colour of potassium to be seen clearly even if sodium contamination is present.',
     'correction_tip':'Blue cobalt glass filters out Na⁺ yellow, allowing K⁺ lilac to be seen clearly.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'A student performs a chromatography experiment using water as the solvent. The food colouring produces three spots at 2.0 cm, 4.5 cm, and 6.0 cm. The solvent front is at 8.0 cm. Calculate all three Rf values.',
     'option_a':'0.20, 0.45, 0.60','option_b':'0.25, 0.56, 0.75',
     'option_c':'2.0, 4.5, 6.0','option_d':'0.40, 0.90, 1.20',
     'correct_answer':'B','explanation':'Rf₁=2.0/8.0=0.25; Rf₂=4.5/8.0=0.5625≈0.56; Rf₃=6.0/8.0=0.75.',
     'correction_tip':'Rf = each spot distance ÷ solvent front distance. 2.0/8.0=0.25; 4.5/8.0=0.5625; 6.0/8.0=0.75.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'What does the fragmentation pattern in a mass spectrum tell a chemist?',
     'option_a':'The colour of the compound','option_b':'The boiling point of the compound',
     'option_c':'The structural identity of the compound, as each compound produces a unique fragmentation pattern',
     'option_d':'Only the molecular mass of the compound',
     'correct_answer':'C','explanation':'Each compound fragments in a characteristic way under electron bombardment in the mass spectrometer, producing a unique fragmentation pattern that acts as a "fingerprint" for identification.',
     'correction_tip':'Fragmentation pattern = unique fingerprint for identification. M⁺ peak = Mr. Fragment peaks reveal structure.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Describe how to test for CO₂ gas and explain what you would observe in a positive test.',
     'option_a':'Pass gas through acidified KMnO₄; it decolourises',
     'option_b':'Hold damp red litmus paper near gas; it turns blue',
     'option_c':'Pass gas through limewater; it turns cloudy/milky due to formation of CaCO₃',
     'option_d':'Hold burning splint near gas; it makes a squeaky pop',
     'correct_answer':'C','explanation':'CO₂ + Ca(OH)₂ → CaCO₃ + H₂O. The white CaCO₃ precipitate makes the limewater turn milky/cloudy.',
     'correction_tip':'CO₂ test: bubble through limewater → turns milky/cloudy (forms CaCO₃ precipitate).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Explain the difference between mobile phase and stationary phase in chromatography.',
     'option_a':'Both phases move at the same speed','option_b':'The mobile phase moves through/over the stationary phase; components partition between them based on their relative attraction to each phase',
     'option_c':'The stationary phase is always a liquid','option_d':'The mobile phase is always a gas',
     'correct_answer':'B','explanation':'In chromatography, the mobile phase (solvent/gas) carries components through the stationary phase (paper/column). Components separate based on how strongly they are attracted to each phase.',
     'correction_tip':'Mobile phase moves; stationary phase stays still. Components partition between phases → separation occurs.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'An unknown solution is tested: BaCl₂ gives a white precipitate; adding excess HCl does not dissolve it. What ion is confirmed?',
     'option_a':'CO₃²⁻','option_b':'Cl⁻','option_c':'SO₄²⁻','option_d':'OH⁻',
     'correct_answer':'C','explanation':'BaSO₄ is an insoluble white precipitate that does NOT dissolve in excess HCl. BaCO₃ also gives a white ppt but it dissolves in HCl, releasing CO₂.',
     'correction_tip':'White ppt with BaCl₂ + HCl, insoluble in excess acid → SO₄²⁻. BaCO₃ would dissolve in HCl.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'IR spectroscopy identifies functional groups. What information does it provide that mass spectrometry alone cannot?',
     'option_a':'The molecular mass of the compound',
     'option_b':'The number of isotopes present',
     'option_c':'Identification of specific functional groups from characteristic absorption frequencies',
     'option_d':'The colour of the compound',
     'correct_answer':'C','explanation':'IR spectroscopy identifies functional groups (e.g. O-H, C=O, N-H) from their characteristic absorption frequencies. Mass spectrometry provides Mr and fragmentation pattern but not direct functional group identification.',
     'correction_tip':'IR = identifies functional groups. MS = identifies Mr and structure from fragmentation. NMR = hydrogen environments.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'A scientist needs to identify metal ions in a sample of river water at very low concentrations. Which technique is most appropriate?',
     'option_a':'Paper chromatography','option_b':'Flame test with nichrome wire',
     'option_c':'Flame emission spectroscopy','option_d':'Adding NaOH to form precipitates',
     'correct_answer':'C','explanation':'Flame emission spectroscopy is far more sensitive than simple flame tests and can detect and quantify metal ions at very low concentrations. It produces unique line spectra for identification.',
     'correction_tip':'For trace metal detection: use instrumental flame emission spectroscopy (more sensitive and quantitative than simple flame tests).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':3,
     'question_text':'Why is purity particularly important in pharmaceutical (medicine) chemistry?',
     'option_a':'Pure compounds are always cheaper to produce',
     'option_b':'Impurities in medicines could be toxic or alter the effectiveness and dosage of the drug',
     'option_c':'Pure compounds have a longer shelf life',
     'option_d':'Purity only matters for cosmetics, not medicines',
     'correct_answer':'B','explanation':'In pharmaceuticals, impurities could be toxic, change the drug\'s activity, or alter the dose delivered, potentially harming patients.',
     'correction_tip':'Pharmaceutical purity is critical: impurities may be toxic or affect drug efficacy and safety.'},

    # -------------------------------------------------------------------------
    # C8 — D4 Exam Challenge — 15 questions
    # -------------------------------------------------------------------------
    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'A student adds NaOH solution to an unknown solution X. A white precipitate forms and dissolves in excess NaOH. When X is warmed with NaOH, a pungent gas turns damp red litmus blue. What ions does X contain?',
     'option_a':'Al³⁺ and NH₄⁺','option_b':'Ca²⁺ and Cl⁻',
     'option_c':'Fe³⁺ and SO₄²⁻','option_d':'Mg²⁺ and NH₄⁺',
     'correct_answer':'A','explanation':'White precipitate dissolving in excess NaOH indicates Al³⁺ (amphoteric Al(OH)₃). Gas turning red litmus blue on warming with NaOH indicates NH₄⁺ (releases NH₃).',
     'correction_tip':'White ppt + dissolves in excess NaOH = Al³⁺. Pungent gas turns red litmus blue on warming = NH₄⁺.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'Describe a complete test procedure to identify that a sample contains iron(II) sulfate (FeSO₄).',
     'option_a':'Add BaCl₂ only; white precipitate confirms FeSO₄',
     'option_b':'Add NaOH → green precipitate (Fe²⁺); add acidified BaCl₂ → white precipitate insoluble in HCl (SO₄²⁻)',
     'option_c':'Do a flame test → green flame confirms Fe²⁺; add HCl → effervescence confirms SO₄²⁻',
     'option_d':'Add AgNO₃ → cream precipitate; add NaOH → brown precipitate',
     'correct_answer':'B','explanation':'FeSO₄ contains Fe²⁺ (green precipitate with NaOH) and SO₄²⁻ (white precipitate with acidified BaCl₂, insoluble in excess HCl). Both tests needed to confirm the compound.',
     'correction_tip':'To confirm FeSO₄: test for Fe²⁺ (NaOH → green ppt) AND test for SO₄²⁻ (acidified BaCl₂ → white ppt).'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'In paper chromatography, compound A has an Rf of 0.72 in ethanol. A reference standard of the same compound in the same solvent has Rf = 0.72. A second unknown spot has Rf = 0.45. What can be concluded?',
     'option_a':'The sample is pure compound A only',
     'option_b':'The sample contains compound A and at least one other unknown compound',
     'option_c':'The sample contains only the unknown compound with Rf 0.45',
     'option_d':'The chromatography experiment was performed incorrectly',
     'correct_answer':'B','explanation':'Two spots indicate a mixture. The spot at Rf 0.72 matches compound A. The spot at Rf 0.45 is a different compound. Therefore the sample is a mixture containing compound A plus another substance.',
     'correction_tip':'Multiple spots = mixture. Matching Rf to reference = identified component. Different Rf = different compound.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'Explain how GC-MS is used to identify an unknown compound in a forensic sample.',
     'option_a':'GC-MS measures the melting point; each compound has a unique melting point in the database',
     'option_b':'GC separates mixture components; each component enters MS which fragments it and compares the fragmentation pattern against a library database for identification',
     'option_c':'MS first identifies the compound, then GC confirms it by colour',
     'option_d':'GC-MS measures the Rf value of each component in the mixture',
     'correct_answer':'B','explanation':'In GC-MS: 1) GC separates the mixture. 2) Each separated component enters the mass spectrometer. 3) MS produces a fragmentation pattern. 4) The pattern is matched to a database for identification.',
     'correction_tip':'GC-MS: GC separates → MS fragments and identifies using database. Used in forensics, drug testing, environmental analysis.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'A sample gives a yellow-orange flame test but no precipitate with NaOH and no precipitate with BaCl₂. What is the most likely identity of the sample?',
     'option_a':'Iron(III) sulfate','option_b':'Sodium chloride',
     'option_c':'Potassium carbonate','option_d':'Copper(II) sulfate',
     'correct_answer':'B','explanation':'Yellow-orange flame = Na⁺. No precipitate with NaOH (Na⁺ salts are soluble). No precipitate with BaCl₂ (Cl⁻ does not precipitate with Ba²⁺). NaCl fits all observations.',
     'correction_tip':'Build up the picture: Na⁺ (yellow flame) + Cl⁻ (no precipitate with BaCl₂, and AgNO₃ would give white ppt) = NaCl.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'Assess the limitations of using only paper chromatography to confirm the identity of a compound.',
     'option_a':'Paper chromatography has no limitations; it is the most reliable technique',
     'option_b':'Rf values can vary with solvent, temperature, and paper; two different compounds can have the same Rf; no structural information is provided',
     'option_c':'Paper chromatography can only be used for coloured compounds',
     'option_d':'Paper chromatography requires very large sample sizes',
     'correct_answer':'B','explanation':'Limitations of paper chromatography: Rf values depend on solvent/conditions; two compounds can coincidentally share an Rf; it gives no structural information; colourless spots need locating agents.',
     'correction_tip':'Chromatography limitations: Rf not unique; depends on conditions; no structural info; colourless compounds need locating agents.'},

    {'subject':'Chemistry','topic':'Flame tests','topic_code':'C8','difficulty':4,
     'question_text':'A flame emission spectrum for an unknown sample shows a single bright line at the same wavelength as sodium\'s characteristic emission. What conclusion can and cannot be drawn?',
     'option_a':'Can conclude: only sodium is present; Cannot conclude: anything else',
     'option_b':'Can conclude: sodium (Na⁺) is present; Cannot conclude: that other metals are absent (they may be present but at undetectable levels or masked)',
     'option_c':'Cannot conclude anything from a single line','option_d':'Can conclude: the sample is pure sodium metal',
     'correct_answer':'B','explanation':'A line matching sodium\'s wavelength confirms Na⁺ is present. However, other elements could also be present but below detection limits or at wavelengths not analysed. The absence of other lines does not confirm their absence.',
     'correction_tip':'Flame emission confirms presence of detected ions. Absence of a signal does not necessarily confirm absence of ion.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'A yellow precipitate forms when AgNO₃ (acidified with dilute HNO₃) is added to solution X. Excess ammonia does not dissolve the precipitate. What halide ion is present?',
     'option_a':'Cl⁻','option_b':'Br⁻','option_c':'I⁻','option_d':'F⁻',
     'correct_answer':'C','explanation':'AgI is a yellow precipitate insoluble in both dilute and concentrated ammonia. AgCl is white and dissolves in dilute NH₃; AgBr is cream and dissolves in concentrated NH₃.',
     'correction_tip':'AgCl = white, dissolves in dilute NH₃. AgBr = cream, dissolves in conc NH₃. AgI = yellow, insoluble in NH₃.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'Explain why adding dilute HCl before BaCl₂ is important in the sulfate test, referring to a specific interfering ion.',
     'option_a':'HCl dissolves BaSO₄ so the test is negative unless SO₄²⁻ is present in large amounts',
     'option_b':'HCl removes CO₃²⁻ ions; BaCO₃ is also a white precipitate, so without acidification a false positive could result from carbonate ions',
     'option_c':'HCl converts SO₄²⁻ to a soluble form for the reaction to occur','option_d':'HCl oxidises Ba²⁺ so it reacts faster',
     'correct_answer':'B','explanation':'Ba²⁺ + CO₃²⁻ → BaCO₃ (white precipitate). Adding HCl removes CO₃²⁻ (CO₃²⁻ + 2H⁺ → H₂O + CO₂) before the BaCl₂ is added, preventing a false positive.',
     'correction_tip':'Acidify with HCl first to remove CO₃²⁻ and avoid false positive BaCO₃ white precipitate.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'An analyst uses NMR spectroscopy to study a compound. What does NMR spectroscopy reveal about a molecule?',
     'option_a':'The number of protons in the nucleus of each atom',
     'option_b':'The different chemical environments of hydrogen atoms and how many H atoms are in each environment',
     'option_c':'The molecular mass and fragmentation pattern','option_d':'The colour and melting point of the compound',
     'correct_answer':'B','explanation':'NMR spectroscopy identifies the different chemical environments of hydrogen atoms in a molecule and their relative numbers, providing detailed structural information.',
     'correction_tip':'NMR: identifies different H atom environments and their ratios → helps determine molecular structure.'},

    {'subject':'Chemistry','topic':'Separation','topic_code':'C8','difficulty':4,
     'question_text':'A mixture of two miscible liquids with different boiling points is to be separated. Which separation technique is most appropriate and why?',
     'option_a':'Filtration; because the liquids have different densities',
     'option_b':'Simple distillation; because the liquids have slightly different boiling points and are miscible',
     'option_c':'Fractional distillation; because the two liquids have different boiling points and are completely miscible, requiring a fractionating column for effective separation',
     'option_d':'Paper chromatography; because the liquids have different Rf values',
     'correct_answer':'C','explanation':'Fractional distillation is used for miscible liquids with close boiling points. The fractionating column provides multiple condensation/vaporisation steps for better separation than simple distillation.',
     'correction_tip':'Miscible liquids, different BPs → fractional distillation. Immiscible liquids → separating funnel.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'In a flame test, strontium (Sr²⁺) gives a red colour similar to lithium (Li⁺). How can flame emission spectroscopy distinguish between them?',
     'option_a':'By using a different colour Bunsen burner',
     'option_b':'Each element emits a unique line spectrum at characteristic wavelengths; the spectra of Li⁺ and Sr²⁺ are distinct even if visible colours appear similar',
     'option_c':'Sr²⁺ and Li⁺ cannot be distinguished',
     'option_d':'By measuring the temperature of the flame',
     'correct_answer':'B','explanation':'Flame emission spectroscopy resolves the unique line spectra of each element. Though Li⁺ and Sr²⁺ appear similar red to the naked eye, their line spectra occur at different specific wavelengths, enabling definitive identification.',
     'correction_tip':'Instrumental flame emission spectroscopy distinguishes elements by their unique line spectra (specific wavelengths), not just colour.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'A compound with Mr = 46 shows a molecular ion peak at m/z = 46 and a fragment at m/z = 45 in its mass spectrum. Suggest an identity and explain the fragment.',
     'option_a':'Methane; loss of H gives m/z = 45',
     'option_b':'Ethanol (C₂H₅OH); loss of H (mass 1) gives [C₂H₅OH - H]⁺ at m/z = 45',
     'option_c':'Propane; loss of CH₃ gives m/z = 45',
     'option_d':'Ethanoic acid; loss of OH gives m/z = 45',
     'correct_answer':'B','explanation':'Ethanol has Mr = 46 (M⁺ at m/z=46). Loss of one hydrogen gives a fragment at m/z = 45 ([M-1]⁺). This is consistent with ethanol\'s fragmentation.',
     'correction_tip':'Mass spectrum: M⁺ = Mr; fragment m/z = M - (mass of lost group). 46-1=45 → loss of H from ethanol.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'Evaluate whether a simple flame test alone is sufficient to confirm the presence of copper in an unknown sample.',
     'option_a':'Yes; the blue-green flame colour is unique to copper and no further testing is needed',
     'option_b':'No; while a blue-green flame suggests Cu²⁺, other compounds or contamination could produce similar colours; confirmatory testing (e.g. NaOH precipitate or instrumental analysis) is needed',
     'option_c':'No; flame tests cannot detect copper at all',
     'option_d':'Yes; instrumental analysis would give the same result so the flame test is sufficient',
     'correct_answer':'B','explanation':'A blue-green flame is indicative of Cu²⁺ but is not conclusive alone. Contamination or other compounds could give similar colours. Confirmatory tests (blue precipitate with NaOH, or flame emission spectroscopy) are required for certainty.',
     'correction_tip':'Evaluate: flame tests are indicative but not conclusive. Always confirm with a second test or instrumental method.'},

    {'subject':'Chemistry','topic':'Chemical analysis','topic_code':'C8','difficulty':4,
     'question_text':'A pharmaceutical company wants to check the purity of a newly synthesised drug compound. Describe TWO methods they could use and explain what a pure compound would show in each.',
     'option_a':'Flame test (no colour change) and chromatography (multiple spots)',
     'option_b':'Melting point (sharp single value matching literature) and thin-layer chromatography (single spot with Rf matching pure reference)',
     'option_c':'Mixing with acid (no reaction) and burning (clean blue flame)',
     'option_d':'Adding NaOH (no precipitate) and testing with limewater (stays clear)',
     'correct_answer':'B','explanation':'A pure drug shows: 1) A sharp melting point matching the literature value (impurities lower and broaden the MP). 2) A single spot on TLC with Rf matching the pure reference compound.',
     'correction_tip':'Purity tests: 1) Sharp MP = pure. 2) Single TLC spot with correct Rf = pure. Impurities cause range MP and extra spots.'},
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute('''INSERT INTO questions (subject,topic,topic_code,difficulty,question_text,
            option_a,option_b,option_c,option_d,correct_answer,explanation,correction_tip)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
