QUESTIONS = [
    # -------------------------------------------------------------------------
    # D1 EASY (17 questions)
    # -------------------------------------------------------------------------
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What is a pathogen?',
        'option_a': 'A type of white blood cell',
        'option_b': 'A microorganism that causes disease',
        'option_c': 'A protein found on the surface of body cells',
        'option_d': 'A chemical produced by the immune system',
        'correct_answer': 'B',
        'explanation': 'A pathogen is any microorganism (or agent) that causes disease in a host.',
        'correction_tip': 'Remember: pathogens are disease-causing microorganisms — bacteria, viruses, fungi, and protists.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Which of the following is an example of a bacterial disease?',
        'option_a': 'Measles',
        'option_b': 'Malaria',
        'option_c': 'Salmonella food poisoning',
        'option_d': 'Rose black spot',
        'correct_answer': 'C',
        'explanation': 'Salmonella is caused by Salmonella bacteria. Measles is a virus, malaria is caused by a protist, and rose black spot is caused by a fungus.',
        'correction_tip': 'Salmonella = bacteria; measles = virus; malaria = protist; rose black spot = fungus.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Viruses are different from bacteria because viruses:',
        'option_a': 'Are living cells that reproduce independently',
        'option_b': 'Are not cells and can only replicate inside host cells',
        'option_c': 'Produce toxins that damage tissues',
        'option_d': 'Can be killed by antibiotics',
        'correct_answer': 'B',
        'explanation': 'Viruses are not cells. They lack the cellular machinery to reproduce on their own and must invade a host cell to replicate.',
        'correction_tip': 'Viruses ≠ cells. They hijack host cells to reproduce. Bacteria are living cells.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Which disease is caused by a protist?',
        'option_a': 'HIV',
        'option_b': 'Malaria',
        'option_c': 'Gonorrhoea',
        'option_d': 'Influenza',
        'correct_answer': 'B',
        'explanation': 'Malaria is caused by the protist Plasmodium, which is spread by the female Anopheles mosquito acting as a vector.',
        'correction_tip': 'Protist disease = malaria (Plasmodium). HIV/flu = viruses; gonorrhoea = bacterium.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Rose black spot is a plant disease caused by a:',
        'option_a': 'Virus',
        'option_b': 'Bacterium',
        'option_c': 'Fungus',
        'option_d': 'Protist',
        'correct_answer': 'C',
        'explanation': 'Rose black spot is caused by a fungus. It produces black/purple spots on rose leaves, which reduces photosynthesis.',
        'correction_tip': 'Rose black spot = fungal disease. It can be treated with fungicides.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What are the two main symptoms of measles?',
        'option_a': 'Fever and a rash',
        'option_b': 'Sweating and joint pain',
        'option_c': 'Coughing and vomiting',
        'option_d': 'Headache and diarrhoea',
        'correct_answer': 'A',
        'explanation': 'Measles causes fever and a distinctive rash. It is a viral disease spread by droplets in the air.',
        'correction_tip': 'Measles: fever + rash. Prevented by the MMR vaccine.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Which vector spreads malaria?',
        'option_a': 'Housefly',
        'option_b': 'Female Anopheles mosquito',
        'option_c': 'Rat flea',
        'option_d': 'Tsetse fly',
        'correct_answer': 'B',
        'explanation': 'The female Anopheles mosquito is the vector for malaria. When it feeds on blood, it can transfer the Plasmodium protist to a new host.',
        'correction_tip': 'Malaria vector = female Anopheles mosquito. Not all mosquitoes spread malaria.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Tobacco mosaic virus (TMV) affects plants by:',
        'option_a': 'Causing black spots on leaves',
        'option_b': 'Producing a mosaic pattern on leaves, reducing photosynthesis',
        'option_c': 'Blocking water transport in stems',
        'option_d': 'Releasing toxins into the soil',
        'correct_answer': 'B',
        'explanation': 'TMV creates a discoloured mosaic pattern on leaves by destroying chloroplasts, which reduces the plant\'s ability to photosynthesise and stunts growth.',
        'correction_tip': 'TMV = virus; causes mosaic (patchy discolouration) on leaves; reduces photosynthesis.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'HIV is transmitted by which routes? (Select the best answer)',
        'option_a': 'Droplets in the air',
        'option_b': 'Sexual contact and exchange of blood',
        'option_c': 'Contaminated food and water',
        'option_d': 'Insect bites',
        'correct_answer': 'B',
        'explanation': 'HIV is transmitted through unprotected sexual contact and through exchange of bodily fluids containing blood (e.g. sharing needles, blood transfusions).',
        'correction_tip': 'HIV is NOT airborne or spread via food/water. It spreads through blood and sexual contact.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Salmonella bacteria cause illness mainly by:',
        'option_a': 'Destroying red blood cells',
        'option_b': 'Producing toxins inside the digestive system',
        'option_c': 'Blocking the airways',
        'option_d': 'Attacking the nervous system',
        'correct_answer': 'B',
        'explanation': 'Salmonella bacteria produce toxins inside the gut, leading to symptoms of food poisoning such as vomiting and diarrhoea.',
        'correction_tip': 'Bacteria cause illness by reproducing rapidly AND producing toxins. Salmonella mainly acts via gut toxins.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Which of the following is a physical barrier that stops pathogens entering the body?',
        'option_a': 'Antibodies',
        'option_b': 'Phagocytes',
        'option_c': 'Skin',
        'option_d': 'Memory cells',
        'correct_answer': 'C',
        'explanation': 'Skin acts as a waterproof physical barrier preventing most pathogens from entering the body.',
        'correction_tip': 'Physical barriers (skin, mucus, cilia) are the FIRST line of defence. Antibodies/phagocytes come later.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What do phagocytes do to pathogens?',
        'option_a': 'Produce antibodies against them',
        'option_b': 'Engulf and digest them',
        'option_c': 'Produce toxins to destroy them',
        'option_d': 'Form a physical barrier against them',
        'correct_answer': 'B',
        'explanation': 'Phagocytes are white blood cells that perform phagocytosis — they engulf and digest pathogens non-specifically.',
        'correction_tip': 'Phagocytes = engulf and digest (non-specific). Lymphocytes = produce antibodies (specific).',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What is a vaccine?',
        'option_a': 'A drug that kills bacteria inside the body',
        'option_b': 'A preparation containing dead or weakened pathogens (or antigens) that stimulates immunity',
        'option_c': 'A protein produced by phagocytes',
        'option_d': 'A type of antigen found on body cells',
        'correct_answer': 'B',
        'explanation': 'A vaccine contains dead or weakened forms of a pathogen (or its antigens) that stimulate the immune system to produce memory cells without causing disease.',
        'correction_tip': 'Vaccines stimulate memory cell production — NOT immediate antibodies. They prevent future infection.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Antibiotics are effective against which type of pathogen?',
        'option_a': 'Viruses only',
        'option_b': 'Fungi only',
        'option_c': 'Bacteria only',
        'option_d': 'All pathogens equally',
        'correct_answer': 'C',
        'explanation': 'Antibiotics only kill or inhibit bacteria — they have no effect on viruses. This is why antibiotics cannot treat colds or flu.',
        'correction_tip': 'Antibiotics = bacteria killers ONLY. They do NOT work on viruses.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'Gonorrhoea is caused by which type of pathogen?',
        'option_a': 'Virus',
        'option_b': 'Fungus',
        'option_c': 'Protist',
        'option_d': 'Bacterium',
        'correct_answer': 'D',
        'explanation': 'Gonorrhoea is a sexually transmitted infection (STI) caused by the bacterium Neisseria gonorrhoeae. It is traditionally treated with antibiotics, but resistant strains are increasing.',
        'correction_tip': 'Gonorrhoea = bacterial STI. Increasing antibiotic resistance is a major concern.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What is the role of mucus in the respiratory tract?',
        'option_a': 'To produce antibodies',
        'option_b': 'To trap pathogens and particles before they reach the lungs',
        'option_c': 'To digest bacteria using enzymes',
        'option_d': 'To transport oxygen to body cells',
        'correct_answer': 'B',
        'explanation': 'Mucus is a sticky substance that traps pathogens and dust particles in the respiratory tract. Cilia then sweep the mucus away from the lungs.',
        'correction_tip': 'Mucus traps; cilia sweep. Together they form a defence in the airways.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 1,
        'question_text': 'What does the MMR vaccine protect against?',
        'option_a': 'Malaria, Measles, and Rubella',
        'option_b': 'Mumps, Meningitis, and Rubella',
        'option_c': 'Measles, Mumps, and Rubella',
        'option_d': 'Measles, Meningitis, and Rabies',
        'correct_answer': 'C',
        'explanation': 'MMR stands for Measles, Mumps, and Rubella. It is a combined vaccine given to children to protect against all three viral diseases.',
        'correction_tip': 'MMR = Measles, Mumps, Rubella. All three are viral diseases prevented by one combined vaccine.',
    },

    # -------------------------------------------------------------------------
    # D2 MEDIUM (18 questions)
    # -------------------------------------------------------------------------
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'How do bacteria cause disease in the human body?',
        'option_a': 'By inserting their DNA into host cells and taking over cell functions',
        'option_b': 'By reproducing rapidly and producing toxins that damage tissues',
        'option_c': 'By destroying red blood cells directly',
        'option_d': 'By blocking antibody production in lymph nodes',
        'correct_answer': 'B',
        'explanation': 'Bacteria are living cells that reproduce rapidly inside the host. As they multiply, they produce toxins that damage body tissues and cause the symptoms of disease.',
        'correction_tip': 'Bacteria: living cells → reproduce → produce toxins → damage tissues. Viruses insert DNA; bacteria produce toxins.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Why does HIV eventually lead to AIDS?',
        'option_a': 'HIV destroys red blood cells, causing anaemia',
        'option_b': 'HIV attacks and destroys immune cells (helper T cells), leaving the body unable to fight other infections',
        'option_c': 'HIV produces toxins that damage the nervous system',
        'option_d': 'HIV blocks the production of platelets, causing internal bleeding',
        'correct_answer': 'B',
        'explanation': 'HIV specifically targets and destroys helper T cells (a type of immune cell). As the T cell count falls, the immune system becomes too weak to fight off opportunistic infections, leading to AIDS.',
        'correction_tip': 'HIV destroys T cells → immune system collapses → AIDS (collection of opportunistic infections). Antiretrovirals slow this.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'How is rose black spot spread, and how can it be controlled?',
        'option_a': 'Spread by insects; controlled by antibiotics',
        'option_b': 'Spread in water and air; controlled by fungicides and removing infected leaves',
        'option_c': 'Spread by direct animal contact; controlled by quarantine',
        'option_d': 'Spread through the soil; controlled by changing the soil pH',
        'correct_answer': 'B',
        'explanation': 'Rose black spot fungal spores spread via water (rain splash) and air. Control involves applying fungicides and removing/destroying infected leaves to prevent further spread.',
        'correction_tip': 'Rose black spot: fungus spread by water/air. Treatment = fungicides + remove infected leaves.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Why does rose black spot reduce plant growth?',
        'option_a': 'The fungus blocks the plant\'s vascular system, preventing water uptake',
        'option_b': 'Spots damage the leaves, reducing the surface area available for photosynthesis',
        'option_c': 'The fungus produces toxins that poison the roots',
        'option_d': 'The fungus uses up all the nitrates in the soil',
        'correct_answer': 'B',
        'explanation': 'Black spots on the leaves reduce the functional leaf area. Less chlorophyll is available, so photosynthesis rate decreases, reducing the production of glucose needed for growth.',
        'correction_tip': 'Less healthy leaf area → less photosynthesis → less glucose → less growth.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'In the UK, how is the spread of Salmonella in poultry controlled?',
        'option_a': 'Treating poultry with antibiotics continuously',
        'option_b': 'Vaccinating poultry against Salmonella',
        'option_c': 'Keeping all poultry indoors permanently',
        'option_d': 'Irradiating all poultry feed with UV light',
        'correct_answer': 'B',
        'explanation': 'In the UK, chickens are vaccinated against Salmonella to prevent the bacteria from being passed to humans through contaminated eggs or meat.',
        'correction_tip': 'UK poultry vaccination against Salmonella is a key public health measure — not antibiotics.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Which method is most effective at preventing the spread of malaria?',
        'option_a': 'Vaccination against Plasmodium',
        'option_b': 'Using mosquito nets, insecticides, and antimalarial drugs',
        'option_c': 'Drinking only bottled water',
        'option_d': 'Wearing face masks in affected areas',
        'correct_answer': 'B',
        'explanation': 'Because malaria is spread by mosquito bites, preventive measures focus on reducing mosquito contact (nets, insecticides) and using antimalarial drugs as prophylaxis or treatment.',
        'correction_tip': 'No fully effective malaria vaccine yet. Prevention = nets + insecticides + antimalarials.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'What is the role of antigens in triggering an immune response?',
        'option_a': 'Antigens are antibodies released by lymphocytes to destroy pathogens',
        'option_b': 'Antigens are proteins on the pathogen surface that stimulate lymphocytes to produce specific antibodies',
        'option_c': 'Antigens are enzymes that digest the cell walls of bacteria',
        'option_d': 'Antigens are memory cells stored in the lymph nodes',
        'correct_answer': 'B',
        'explanation': 'Antigens are molecules (usually proteins) on the surface of pathogens. Each pathogen has unique antigens. When detected by lymphocytes (B cells), they trigger production of complementary antibodies.',
        'correction_tip': 'Antigens are ON the pathogen surface. Antibodies are PRODUCED BY B lymphocytes in response.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'How do lymphocytes (B cells) provide immunity after vaccination?',
        'option_a': 'They engulf the weakened pathogen by phagocytosis',
        'option_b': 'They produce antibodies and then differentiate into memory cells that respond rapidly to future infection',
        'option_c': 'They release histamine to increase blood flow to infected areas',
        'option_d': 'They form a physical barrier in the lymph nodes',
        'correct_answer': 'B',
        'explanation': 'After encountering vaccine antigens, B lymphocytes clone themselves: some produce antibodies against the pathogen, and others become long-lived memory cells. On future exposure, memory cells allow rapid antibody production.',
        'correction_tip': 'Vaccination → memory cells form → rapid response on real infection = immunity.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'What is herd immunity?',
        'option_a': 'When an entire population has been infected with a disease and recovered',
        'option_b': 'When enough individuals in a population are vaccinated so the disease cannot spread easily to unvaccinated people',
        'option_c': 'When animals are used to produce antibodies that are given to humans',
        'option_d': 'When a pathogen mutates and becomes less harmful to the population',
        'correct_answer': 'B',
        'explanation': 'Herd immunity occurs when a sufficiently large proportion of a population is immune (through vaccination or previous infection), so the pathogen cannot find enough susceptible hosts to spread widely, protecting even unvaccinated individuals.',
        'correction_tip': 'Herd immunity protects the whole population — including those who CAN\'T be vaccinated — by reducing spread.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Why are painkillers not a cure for bacterial infections?',
        'option_a': 'Painkillers destroy the immune system',
        'option_b': 'Painkillers only relieve symptoms; they do not kill the pathogen causing the disease',
        'option_c': 'Painkillers promote bacterial reproduction',
        'option_d': 'Painkillers interfere with antibiotic action',
        'correct_answer': 'B',
        'explanation': 'Painkillers and other symptom-relieving drugs treat the effects of disease (e.g. pain, fever) but do not target or destroy the pathogen itself. Only antibiotics kill bacteria.',
        'correction_tip': 'Treating symptoms ≠ curing the disease. Antibiotics target and kill the bacteria causing illness.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'How does stomach acid act as a defence against pathogens?',
        'option_a': 'It produces antibodies that neutralise pathogens',
        'option_b': 'It kills most pathogens that are swallowed with food or drink',
        'option_c': 'It traps pathogens in a sticky layer',
        'option_d': 'It engulfs pathogens by phagocytosis',
        'correct_answer': 'B',
        'explanation': 'The stomach produces hydrochloric acid (very low pH ~2), which kills the majority of pathogens that are swallowed, preventing them from reaching the intestines.',
        'correction_tip': 'Stomach acid = chemical defence (not physical). It kills swallowed pathogens non-specifically.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'How do cilia in the trachea help defend against disease?',
        'option_a': 'They produce antibodies against inhaled pathogens',
        'option_b': 'They beat rhythmically to sweep mucus (containing trapped pathogens) up and away from the lungs',
        'option_c': 'They secrete enzymes that digest pathogens',
        'option_d': 'They increase the temperature of inhaled air to kill pathogens',
        'correct_answer': 'B',
        'explanation': 'Cilia are tiny hair-like structures lining the trachea. They beat rhythmically to move mucus (which has already trapped pathogens and particles) upward to the throat, where it is swallowed.',
        'correction_tip': 'Mucus traps pathogens; cilia move the mucus away from the lungs — a team effort.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Measles is spread by droplet infection. What does this mean?',
        'option_a': 'The virus is spread when an infected person touches a surface',
        'option_b': 'Tiny fluid droplets containing the virus are released when an infected person coughs or sneezes and inhaled by others',
        'option_c': 'The virus enters through contaminated water',
        'option_d': 'The virus is transmitted via insect bites',
        'correct_answer': 'B',
        'explanation': 'Droplet infection occurs when respiratory droplets (from coughing, sneezing, or talking) containing the measles virus are inhaled by another person, infecting the respiratory tract.',
        'correction_tip': 'Airborne/droplet diseases = spread through the air (measles, flu, COVID). Not the same as contact or vector transmission.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'What is the difference between how bacteria and viruses damage the body?',
        'option_a': 'Bacteria destroy host cell DNA; viruses produce toxins',
        'option_b': 'Bacteria produce toxins that damage tissues; viruses reproduce inside and burst out of host cells, destroying them',
        'option_c': 'Bacteria and viruses both damage cells in exactly the same way',
        'option_d': 'Bacteria attack only plant cells; viruses attack only animal cells',
        'correct_answer': 'B',
        'explanation': 'Bacteria damage the host mainly by secreting toxins. Viruses reproduce inside host cells using the cell\'s own machinery, then new viruses burst out (lysis), destroying the host cell in the process.',
        'correction_tip': 'Bacteria → toxins; viruses → burst out of (lyse) host cells.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Why are some people unable to be vaccinated?',
        'option_a': 'They are too old to develop an immune response',
        'option_b': 'They may have allergies to vaccine components or have a suppressed immune system',
        'option_c': 'Vaccines only work if given before birth',
        'option_d': 'Their bodies already have too many antibodies',
        'correct_answer': 'B',
        'explanation': 'Some individuals cannot be vaccinated because they have severe allergies to ingredients in the vaccine, or because their immune system is suppressed (e.g. by chemotherapy or disease), meaning vaccines could be dangerous or ineffective.',
        'correction_tip': 'Unvaccinated individuals rely on herd immunity for protection. This is why high vaccination rates matter.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Antivirals are different from antibiotics because antivirals:',
        'option_a': 'Kill all types of pathogens including bacteria',
        'option_b': 'Are specifically designed to target viruses, not bacteria',
        'option_c': 'Work by boosting phagocyte activity',
        'option_d': 'Prevent the immune system from overreacting',
        'correct_answer': 'B',
        'explanation': 'Antivirals are drugs specifically developed to combat viruses (e.g. oseltamivir for flu, antiretrovirals for HIV). Unlike antibiotics, they have no effect on bacteria.',
        'correction_tip': 'Antiviral ≠ antibiotic. Antivirals target viruses; antibiotics target bacteria.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'What feature of an antibody makes it specific to one antigen?',
        'option_a': 'Its large size prevents it from binding to the wrong antigen',
        'option_b': 'Its binding site is complementary in shape to one specific antigen',
        'option_c': 'It is made of DNA, which matches the pathogen\'s genetic code',
        'option_d': 'It contains enzymes that digest any antigen it encounters',
        'correct_answer': 'B',
        'explanation': 'Each antibody has a unique binding site with a shape that is complementary to one specific antigen — like a lock and key. This means each antibody only binds to its matching antigen.',
        'correction_tip': 'Antibody–antigen = complementary shapes (lock and key). One antibody type = one antigen type.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 2,
        'question_text': 'Why does the flu vaccine need to be updated every year?',
        'option_a': 'The immune system forgets the old vaccine after 12 months',
        'option_b': 'The influenza virus mutates frequently, changing its surface antigens so old antibodies no longer fit',
        'option_c': 'New flu strains arise because antibiotics are overused',
        'option_d': 'The vaccine becomes toxic after one year',
        'correct_answer': 'B',
        'explanation': 'Influenza viruses mutate rapidly, altering their surface antigens. Each year, scientists identify the most likely circulating strains and update the vaccine so the antibodies it stimulates remain effective.',
        'correction_tip': 'Mutation → new antigens → old antibodies don\'t fit → new vaccine needed. This is why flu shots are annual.',
    },

    # -------------------------------------------------------------------------
    # D3 HARD (17 questions)
    # -------------------------------------------------------------------------
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Explain why a person who has recovered from measles is unlikely to get it again.',
        'option_a': 'Their skin becomes permanently thicker after infection',
        'option_b': 'Memory B cells remain in the body and rapidly produce large amounts of specific antibodies if the measles virus is encountered again',
        'option_c': 'The measles virus is destroyed by stomach acid on re-entry',
        'option_d': 'Phagocytes become faster at engulfing viruses after the first infection',
        'correct_answer': 'B',
        'explanation': 'After recovering from measles, long-lived memory B cells persist in the body. If the measles virus is encountered again, these cells rapidly divide and produce large quantities of specific antibodies, eliminating the virus before symptoms develop — this is immunological memory.',
        'correction_tip': 'Immunity = memory cells (not faster phagocytes). Memory cells respond quickly on re-exposure.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Why do antibiotics work on bacteria but NOT on viruses?',
        'option_a': 'Viruses are too large for antibiotics to reach',
        'option_b': 'Antibiotics target bacterial structures (such as cell walls) that viruses do not possess',
        'option_c': 'Viruses produce enzymes that break down antibiotics',
        'option_d': 'Antibiotics only work in the bloodstream, where viruses do not travel',
        'correct_answer': 'B',
        'explanation': 'Most antibiotics work by disrupting bacterial cell walls or other bacterial-specific structures. Viruses are not cells — they have no cell wall or ribosomes — so antibiotics have nothing to target. Viruses also hide inside host cells, making them harder to reach without harming the host.',
        'correction_tip': 'Antibiotics target cell walls (bacteria have them; viruses don\'t). Viruses = no cell wall = antibiotics useless.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'How does natural selection lead to antibiotic-resistant bacteria?',
        'option_a': 'Bacteria deliberately change their DNA to survive antibiotics',
        'option_b': 'Random mutations produce resistant variants; when antibiotics are used, non-resistant bacteria die and resistant ones survive and reproduce, passing on resistance genes',
        'option_c': 'Antibiotics cause bacteria to fuse together and share resistance genes',
        'option_d': 'Bacteria absorb antibiotic molecules and use them as an energy source',
        'correct_answer': 'B',
        'explanation': 'In any bacterial population, random mutations occasionally produce antibiotic-resistant variants. When antibiotics are used, susceptible bacteria are killed, but resistant ones survive, reproduce, and pass on their resistance genes — natural selection in action.',
        'correction_tip': 'Resistance = natural selection: mutation → selection pressure (antibiotics) → resistant bacteria survive → pass on genes.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Why is MRSA (methicillin-resistant Staphylococcus aureus) a serious concern in hospitals?',
        'option_a': 'MRSA is a virus, so vaccines cannot be made against it',
        'option_b': 'MRSA is resistant to many antibiotics, making infections difficult to treat, especially in already ill or immunocompromised patients',
        'option_c': 'MRSA spreads only through the air, making isolation impossible',
        'option_d': 'MRSA destroys all white blood cells within hours of infection',
        'correct_answer': 'B',
        'explanation': 'MRSA has evolved resistance to multiple antibiotics due to overuse of antibiotics. In hospital settings, patients are often immunocompromised, making MRSA infections life-threatening and extremely difficult to treat.',
        'correction_tip': 'MRSA = resistant bacterium. Threat is high because few antibiotics work against it, especially in vulnerable patients.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Describe how a vaccine triggers the production of memory cells without causing disease.',
        'option_a': 'The vaccine contains active pathogens that infect cells but at too low a dose to cause symptoms',
        'option_b': 'The vaccine introduces dead, weakened, or fragmented pathogens (antigens) that stimulate lymphocytes to clone, produce antibodies, and form memory cells — without replication of disease',
        'option_c': 'The vaccine introduces antibodies directly into the bloodstream, which are stored as memory cells',
        'option_d': 'The vaccine stimulates phagocytes to permanently guard the entry points of the body',
        'correct_answer': 'B',
        'explanation': 'Vaccines contain non-infectious forms of the pathogen (dead/weakened/antigens alone). These are recognised by lymphocytes, which produce antibodies and differentiate into memory cells. Because the pathogen cannot reproduce normally, no disease develops.',
        'correction_tip': 'Key: dead/weakened pathogen → immune response → memory cells → long-term protection. Not real infection.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'What is the role of agglutination in the immune response?',
        'option_a': 'Agglutination is the process by which phagocytes engulf pathogens',
        'option_b': 'Antibodies clump pathogens together (agglutination), making them easier for phagocytes to engulf and destroy',
        'option_c': 'Agglutination describes the thickening of mucus to trap pathogens',
        'option_d': 'Agglutination is when memory cells rapidly divide after re-infection',
        'correct_answer': 'B',
        'explanation': 'When antibodies bind to antigens on multiple pathogens simultaneously, they cross-link the pathogens into clumps — agglutination. This marks them for destruction and makes phagocytosis far more efficient.',
        'correction_tip': 'Agglutination = antibodies clumping pathogens → easier for phagocytes to destroy.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'How are monoclonal antibodies produced?',
        'option_a': 'By extracting antibodies directly from donated human blood',
        'option_b': 'A mouse is immunised; its B lymphocytes are fused with tumour cells to form hybridoma cells that divide indefinitely and produce identical antibodies',
        'option_c': 'By genetically engineering bacteria to produce human antibodies',
        'option_d': 'By stimulating phagocytes in a laboratory to produce specific antibodies',
        'correct_answer': 'B',
        'explanation': 'The process: (1) immunise mouse with target antigen; (2) harvest B lymphocytes producing desired antibody; (3) fuse B cells with myeloma (tumour) cells to create hybridoma cells; (4) hybridoma cells divide indefinitely, producing large quantities of identical (monoclonal) antibodies.',
        'correction_tip': 'Hybridoma = B lymphocyte + tumour cell. Gives unlimited supply of identical (monoclonal) antibodies.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'How is a monoclonal antibody used in a home pregnancy test?',
        'option_a': 'The antibody detects a specific hormone (hCG) produced during pregnancy by binding to it and causing a colour change on the test strip',
        'option_b': 'The antibody detects increased glucose in urine produced during pregnancy',
        'option_c': 'The antibody stimulates hormone production to confirm pregnancy',
        'option_d': 'The antibody blocks hCG from being excreted so it builds up to detectable levels',
        'correct_answer': 'A',
        'explanation': 'Pregnancy tests use monoclonal antibodies specific to hCG (human chorionic gonadotropin), a hormone only present if pregnant. The antibodies bind to hCG in urine, triggering a colour change visible in the test window.',
        'correction_tip': 'Pregnancy test: monoclonal antibody → binds hCG (pregnancy hormone) → colour change = positive result.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'What were the main stages of drug development before thalidomide was approved, and why were these stages insufficient?',
        'option_a': 'Thalidomide was tested only in animals but not on pregnant animals, so its effects on human foetal development were missed',
        'option_b': 'Thalidomide was never tested at all before being given to patients',
        'option_c': 'Thalidomide was tested only for toxicity, and pregnancy testing was considered unnecessary at the time',
        'option_d': 'Both A and C are correct — animal testing was insufficient and teratogenic effects were not studied',
        'correct_answer': 'D',
        'explanation': 'Thalidomide was approved as a sedative and used for morning sickness without adequate testing on pregnant animals. Its teratogenic (birth defect-causing) effects on developing limbs were not detected, leading to thousands of babies born with limb abnormalities. This led to much stricter drug trial protocols.',
        'correction_tip': 'Thalidomide case → stricter drug trials required, including testing on pregnant animals. It is now used for leprosy.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'In a clinical trial, what is the purpose of a placebo group?',
        'option_a': 'To ensure the drug reaches all patients who need it',
        'option_b': 'To act as a control, allowing researchers to determine whether any observed effects are genuinely due to the drug rather than expectation or other factors',
        'option_c': 'To test whether the drug is toxic before giving it to the treatment group',
        'option_d': 'To ensure the drug is distributed evenly among patients of different ages',
        'correct_answer': 'B',
        'explanation': 'A placebo looks identical to the real drug but contains no active ingredient. By comparing outcomes between the drug group and the placebo group, researchers can determine whether the drug has a real effect beyond the placebo effect (psychological benefit from believing you are being treated).',
        'correction_tip': 'Placebo = control group. Without a placebo, you cannot tell if improvement is due to the drug or expectation.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'What does "double-blind" mean in the context of a clinical trial?',
        'option_a': 'Two different drugs are tested simultaneously on the same group of patients',
        'option_b': 'Neither the patients nor the doctors administering the treatment know who has received the drug or placebo until the trial ends',
        'option_c': 'The trial is conducted in two separate hospitals to increase sample size',
        'option_d': 'The drug is tested on patients with two different diseases',
        'correct_answer': 'B',
        'explanation': 'In a double-blind trial, neither the participants nor the researchers know who is receiving the actual drug versus the placebo. This eliminates bias from both patient expectations and researcher interpretation of results.',
        'correction_tip': 'Double-blind: patients AND doctors unaware of treatment allocation → removes bias from both sides.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Why are antiretroviral drugs used to treat HIV rather than antibiotics?',
        'option_a': 'Antiretrovirals are cheaper and easier to produce than antibiotics',
        'option_b': 'HIV is a virus, and antibiotics only kill bacteria; antiretrovirals specifically inhibit viral enzymes needed for HIV to replicate',
        'option_c': 'Antiretrovirals kill HIV-infected T cells to stop the virus from spreading',
        'option_d': 'Antibiotics would destroy all immune cells along with HIV',
        'correct_answer': 'B',
        'explanation': 'HIV is a retrovirus; it uses the enzyme reverse transcriptase to copy its RNA genome into DNA inside host cells. Antiretrovirals target viral-specific enzymes (like reverse transcriptase and protease), slowing replication without killing host cells.',
        'correction_tip': 'HIV = retrovirus. Antiretrovirals target viral enzymes (not bacteria). They don\'t cure HIV but slow progression.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'How can monoclonal antibodies be used to target cancer cells specifically?',
        'option_a': 'They stimulate the immune system to produce more T cells, which attack all abnormal cells',
        'option_b': 'They are attached to a toxic drug or radioactive substance; because they bind only to cancer cell antigens, they deliver the payload directly to the tumour without harming normal cells',
        'option_c': 'They block all cell division in the body, preventing further tumour growth',
        'option_d': 'They carry chemotherapy drugs through the bloodstream to all rapidly dividing cells',
        'correct_answer': 'B',
        'explanation': 'Monoclonal antibodies can be conjugated (joined) to toxic drugs, radioactive isotopes, or enzyme activators. Because the antibody binds specifically to antigens found on cancer cells, it delivers treatment directly to the tumour, reducing damage to healthy tissues compared to conventional chemotherapy.',
        'correction_tip': 'Monoclonal antibody + drug/toxin → guided missile to cancer cells. Specific to cancer antigens = fewer side effects.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'A student suggests that taking antibiotics for a viral cold will help them recover faster. Evaluate this suggestion.',
        'option_a': 'The student is correct — antibiotics kill pathogens of all kinds, speeding recovery from any infection',
        'option_b': 'The student is incorrect — antibiotics have no effect on viruses, will not speed recovery, and unnecessary use contributes to antibiotic resistance',
        'option_c': 'The student is partially correct — antibiotics will not kill the virus but will prevent secondary bacterial infections in all cases',
        'option_d': 'The student is correct — although antibiotics do not kill viruses, they boost the immune system to fight viral infections faster',
        'correct_answer': 'B',
        'explanation': 'Antibiotics target bacterial cell walls and structures not present in viruses. Taking them for a cold has no therapeutic benefit and contributes to selection for antibiotic-resistant bacterial strains, a major public health threat.',
        'correction_tip': 'Antibiotics for viruses = no benefit + contributes to antibiotic resistance. This is a key exam evaluation point.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'What is the role of T lymphocytes in the specific immune response?',
        'option_a': 'T cells produce all the antibodies used to fight infection',
        'option_b': 'Helper T cells activate B cells and coordinate the immune response; cytotoxic T cells directly kill infected cells',
        'option_c': 'T cells form the physical barriers such as skin and mucus',
        'option_d': 'T cells engulf and digest pathogens by phagocytosis',
        'correct_answer': 'B',
        'explanation': 'T lymphocytes have two main roles: helper T cells release cytokines to activate B cells and other immune cells; cytotoxic (killer) T cells recognise and destroy body cells that have been infected by pathogens or have become cancerous.',
        'correction_tip': 'T cells: helper T cells activate immune response; cytotoxic T cells kill infected cells. B cells make antibodies.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Describe the sequence of events in phagocytosis.',
        'option_a': 'Phagocyte produces antibodies → antibodies bind to pathogen → pathogen is absorbed into phagocyte',
        'option_b': 'Phagocyte detects pathogen (via antibody coating or antigens) → extends pseudopodia around it → engulfs it into a vacuole → lysosomes fuse and release enzymes to digest the pathogen',
        'option_c': 'Phagocyte releases toxins → toxins damage pathogen cell wall → fragments are absorbed',
        'option_d': 'Phagocyte releases complement proteins → proteins drill holes in pathogen → phagocyte absorbs debris',
        'correct_answer': 'B',
        'explanation': 'Phagocytosis steps: (1) phagocyte detects and is attracted to pathogen; (2) extends pseudopodia (arms of cytoplasm) to engulf it; (3) pathogen enclosed in a phagosome (vacuole); (4) lysosomes fuse, releasing digestive enzymes that break down the pathogen.',
        'correction_tip': 'Phagocytosis sequence: detect → engulf → vacuole → lysosome fuses → enzymes digest.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 3,
        'question_text': 'Why might an ELISA test use monoclonal antibodies to detect a specific protein in a blood sample?',
        'option_a': 'Because monoclonal antibodies are cheaper to produce than any other detection method',
        'option_b': 'Because monoclonal antibodies bind specifically to the target protein, allowing accurate detection even when the protein is present in very small amounts',
        'option_c': 'Because monoclonal antibodies can kill pathogens in the sample before it is analysed',
        'option_d': 'Because monoclonal antibodies change colour when they enter the blood',
        'correct_answer': 'B',
        'explanation': 'ELISA (Enzyme-Linked Immunosorbent Assay) uses monoclonal antibodies because they have precise, complementary binding sites for the target molecule. A secondary labelled antibody then produces a detectable signal, allowing even very low concentrations of the target protein to be identified accurately.',
        'correction_tip': 'ELISA uses monoclonal antibodies for specificity + sensitivity — key in disease diagnosis and drug testing.',
    },

    # -------------------------------------------------------------------------
    # D4 EXAM CHALLENGE (16 questions)
    # -------------------------------------------------------------------------
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Evaluate the advantages and disadvantages of using monoclonal antibodies in cancer treatment compared to conventional chemotherapy.',
        'option_a': 'Monoclonal antibodies are always superior because they have no side effects whatsoever',
        'option_b': 'Monoclonal antibodies offer targeted delivery to cancer cells (fewer side effects, sparing healthy tissue) but are expensive, may cause immune reactions, and may not work if cancer cell antigens are absent or mutated',
        'option_c': 'Chemotherapy is always more effective because it kills all rapidly dividing cells throughout the body',
        'option_d': 'Monoclonal antibodies are inferior because they cannot reach tumours deep in the body',
        'correct_answer': 'B',
        'explanation': 'Advantages of monoclonal antibody therapy: specific to cancer antigens, fewer side effects on healthy cells, can deliver targeted drugs. Disadvantages: expensive to produce, patients may develop immune reactions to mouse-derived antibodies, effectiveness depends on consistent cancer antigen expression, and they represent a relatively newer treatment with ongoing development.',
        'correction_tip': 'Balanced evaluation: advantages (targeted, fewer side effects) vs disadvantages (cost, immune reactions, antigen variation).',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A new infectious disease is discovered. Scientists want to develop a vaccine. Outline and evaluate the steps required before the vaccine can be used by the public.',
        'option_a': 'Vaccine is designed in the lab → given directly to the public → monitored for effectiveness',
        'option_b': 'Discovery → lab testing (cells/tissues) → animal testing → Phase 1 clinical trial (safety in healthy volunteers) → Phase 2/3 trials (efficacy in patients, double-blind placebo) → regulatory approval → roll-out',
        'option_c': 'Animal testing → Phase 3 clinical trial only → public use',
        'option_d': 'Lab testing → Phase 1 only → public use, with safety monitoring during roll-out',
        'correct_answer': 'B',
        'explanation': 'Drug/vaccine development follows strict stages: (1) laboratory tests on cells and tissues to assess basic safety and mechanism; (2) animal testing to evaluate safety in living organisms; (3) Phase 1 clinical trials — small group of healthy volunteers, safety/dose; (4) Phase 2/3 — larger groups including patients, efficacy and side effects, double-blind placebo-controlled; (5) regulatory review and approval before public use.',
        'correction_tip': 'Remember the order: lab → animals → Phase 1 (safety/healthy) → Phase 2/3 (efficacy/patients) → approval.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Explain, using evolutionary principles, why reducing antibiotic use in medicine and farming could slow the development of antibiotic resistance.',
        'option_a': 'Less antibiotic use means bacteria produce fewer mutations and therefore fewer resistant variants',
        'option_b': 'Reducing antibiotic use decreases the selection pressure that favours resistant bacteria, so resistant strains have no survival advantage and their frequency in the population does not increase',
        'option_c': 'Bacteria share antibiotic resistance genes less frequently when fewer antibiotics are present, so resistance cannot spread',
        'option_d': 'Reducing antibiotic use causes resistant bacteria to revert to non-resistant forms over time',
        'correct_answer': 'B',
        'explanation': 'Natural selection requires a selection pressure. Antibiotics act as the selection pressure that kills non-resistant bacteria and allows resistant ones to survive and reproduce. By reducing antibiotic use, this selection pressure is weakened, so resistant bacteria gain no survival advantage, slowing the increase in their frequency. Note: mutations still occur randomly; it is selection that drives resistant allele frequency up.',
        'correction_tip': 'Less antibiotic → less selection pressure → no competitive advantage for resistant strains → resistance spreads more slowly.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'The thalidomide case study changed how drugs are tested. What specific lesson was learned, and how is this reflected in modern drug trial protocols?',
        'option_a': 'Drugs must now be tested on at least 1000 patients before Phase 1 trials begin',
        'option_b': 'Drugs must now be tested on pregnant animals during pre-clinical stages, and must be assessed for teratogenic (birth defect-causing) effects before approval for use in women of childbearing age',
        'option_c': 'Drugs with sedative effects are now permanently banned from use in pregnant women',
        'option_d': 'All drugs must now be tested in at least 10 countries simultaneously before approval',
        'correct_answer': 'B',
        'explanation': 'Thalidomide caused severe limb abnormalities (phocomelia) in babies born to mothers who took it during pregnancy. The key lesson was that effects on embryonic development must be specifically tested. Modern protocols now require testing on pregnant animals for teratogenicity as part of pre-clinical safety testing.',
        'correction_tip': 'Thalidomide → mandatory teratogenicity testing. It is now approved for treating leprosy under strict safeguards.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A scientist claims that herd immunity can be achieved through natural infection rather than vaccination. Evaluate this claim.',
        'option_a': 'The claim is fully supported — natural infection always produces stronger immunity than vaccination',
        'option_b': 'The claim is valid in theory (natural infection does produce immunity) but is ethically and practically unacceptable because allowing mass infection would cause serious illness and deaths, particularly in vulnerable groups',
        'option_c': 'The claim is incorrect — natural infection does not produce any lasting immunity',
        'option_d': 'The claim is fully correct and has been used as official public health policy in multiple countries',
        'correct_answer': 'B',
        'explanation': 'Natural infection does produce memory cells and immunity, potentially contributing to herd immunity. However, this approach is unethical and dangerous: many individuals (especially elderly, immunocompromised, young babies) would suffer severe disease or death. Vaccination achieves population immunity without the associated morbidity and mortality.',
        'correction_tip': 'Natural infection CAN produce immunity, but the cost (death, serious illness) is unacceptable. Vaccination is safer.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A patient has a bacterial infection that is not responding to three different antibiotics. Suggest and explain a sequence of steps a doctor should take.',
        'option_a': 'Prescribe a higher dose of the same antibiotic until the infection clears',
        'option_b': 'Take a sample of the bacteria and perform sensitivity testing to identify which antibiotics (or combinations) the strain is susceptible to; in the meantime, use strict infection control to prevent spread',
        'option_c': 'Administer antiviral drugs as an alternative treatment',
        'option_d': 'Wait for the patient\'s immune system to clear the infection without any intervention',
        'correct_answer': 'B',
        'explanation': 'If standard antibiotics fail, the bacterium is likely resistant. The correct approach: (1) collect a sample (swab/blood culture); (2) culture bacteria and test susceptibility to various antibiotics (antibiogram); (3) prescribe the effective antibiotic if identified; (4) implement infection control (isolation, hygiene) to prevent spread of the resistant strain.',
        'correction_tip': 'Antibiotic resistance management: culture the bacteria → sensitivity testing → target remaining effective antibiotics → prevent spread.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Describe how you could design a study to test whether a new malaria vaccine is safe and effective, including controls and measures to reduce bias.',
        'option_a': 'Give the vaccine to 20 volunteers in a single location and check how many get malaria',
        'option_b': 'Conduct a large double-blind, randomised, placebo-controlled trial: randomly allocate participants to vaccine or placebo groups, ensure neither participants nor clinicians know group allocation, compare malaria infection rates between groups, and monitor for adverse effects over a defined period',
        'option_c': 'Test the vaccine on animals only, and if safe, approve it for human use',
        'option_d': 'Vaccinate an entire population and compare malaria rates to the previous year\'s data',
        'correct_answer': 'B',
        'explanation': 'A rigorous Phase 3 trial requires: random allocation to vaccine/placebo groups (removes confounding); double-blind design (removes observer and participant bias); large sample (statistical power); long follow-up to assess both efficacy and safety; ethical committee approval and informed consent.',
        'correction_tip': 'Key trial features: random allocation, double-blind, placebo control, large sample. Know why each element matters.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A graph shows that as vaccination coverage for measles drops below 95%, the number of measles cases rises sharply. Explain this pattern using your knowledge of herd immunity.',
        'option_a': 'Below 95%, the MMR vaccine stops working properly in all vaccinated individuals',
        'option_b': 'Below the herd immunity threshold (~95% for measles), there are enough susceptible individuals for the virus to find new hosts and spread through the population, including to unvaccinated people',
        'option_c': 'Below 95% coverage, the measles virus mutates to become more infectious',
        'option_d': 'When vaccination rates drop, antibiotics are used more, allowing measles to become antibiotic-resistant',
        'correct_answer': 'B',
        'explanation': 'Measles has a high transmission rate (R0 ~12-18), so ~95% vaccination coverage is needed for herd immunity. Below this threshold, unvaccinated (or incompletely vaccinated) individuals form clusters, allowing the virus to spread. Cases rise because the pathogen can chain-transmit through susceptible individuals.',
        'correction_tip': 'Herd immunity threshold varies by disease. Measles needs ~95% due to its high infectivity. Below threshold = outbreaks.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Explain why a patient undergoing chemotherapy for cancer may be at greater risk of infection and why vaccination may be less effective for them during treatment.',
        'option_a': 'Chemotherapy increases body temperature, creating conditions where bacteria thrive',
        'option_b': 'Chemotherapy kills rapidly dividing cells including bone marrow cells that produce white blood cells, reducing both phagocyte and lymphocyte counts, impairing all aspects of immunity and the ability to respond to vaccines',
        'option_c': 'Chemotherapy causes skin to become more permeable, allowing pathogens to enter more easily',
        'option_d': 'Chemotherapy destroys all memory cells, removing all previously acquired immunological memory',
        'correct_answer': 'B',
        'explanation': 'Chemotherapy targets all rapidly dividing cells — including cancer cells AND bone marrow stem cells. Bone marrow produces white blood cells (phagocytes and lymphocytes). Reduced white cell counts (immunosuppression) mean fewer phagocytes to engulf pathogens and fewer lymphocytes to produce antibodies, increasing infection risk and reducing vaccine efficacy.',
        'correction_tip': 'Chemotherapy → bone marrow suppression → fewer WBCs → immunocompromised. Vaccines less effective without sufficient lymphocytes.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Explain the ethical considerations surrounding the use of animals in the development of new medicines.',
        'option_a': 'There are no ethical concerns because animals are not sentient beings',
        'option_b': 'Animal testing raises concerns about animal welfare and suffering; however, it is currently required by law before human trials to identify serious toxicity, and alternatives (cell cultures, computer models) are being developed under the 3Rs principle (Replace, Reduce, Refine)',
        'option_c': 'Animal testing is ethically unacceptable under all circumstances and should be replaced immediately',
        'option_d': 'Animal testing is only ethical if conducted on insects and not on mammals',
        'correct_answer': 'B',
        'explanation': 'The ethical debate: animal testing causes suffering and animals cannot give consent; some argue this is unjustifiable. Counter-argument: animal testing has revealed life-saving information and is legally required to protect humans. The 3Rs framework (Replace with alternatives where possible, Reduce numbers used, Refine to minimise suffering) attempts to balance these considerations.',
        'correction_tip': '3Rs: Replace, Reduce, Refine. Show you can present both sides of the animal testing debate.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A new pathogen emerges with antigens that are very similar to a common harmless antigen in the human body. Predict the likely consequence for the immune response and explain your reasoning.',
        'option_a': 'The immune system will immediately and strongly attack the pathogen because it will recognise its antigens',
        'option_b': 'The immune system may fail to mount an effective response (immune tolerance) or, in some cases, produce antibodies that also attack the body\'s own tissues (autoimmunity), because the pathogen antigens mimic self-antigens',
        'option_c': 'The immune system will produce antibodies that destroy both the pathogen and the harmful antigen, providing double protection',
        'option_d': 'The pathogen will be destroyed by phagocytes before the specific immune response is triggered',
        'correct_answer': 'B',
        'explanation': 'This concept is called "molecular mimicry." If a pathogen carries antigens resembling the body\'s own molecules (self-antigens), the immune system may not recognise it as foreign (tolerance) — or worse, antibodies raised against the pathogen may cross-react with the body\'s own tissues, causing an autoimmune condition. This is a serious threat and an active area of research.',
        'correction_tip': 'Molecular mimicry: pathogen antigens look like self-antigens → immune evasion or autoimmunity. High-level concept for top marks.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'A country is experiencing an outbreak of a new disease. Scientists are unsure whether it is caused by a bacterium or a virus. Describe two investigations that could help determine the type of pathogen.',
        'option_a': 'Check the patient\'s temperature and blood pressure; prescribe antibiotics and see if the patient recovers',
        'option_b': 'Treat patients with antibiotics and observe response (recovery suggests bacterium); examine samples with electron microscopy (viruses are smaller than bacteria and have distinctive structures); attempt to culture the pathogen on growth media (bacteria grow; viruses require living host cells)',
        'option_c': 'Sequence the pathogen\'s genome only — this is the sole reliable method',
        'option_d': 'Vaccinate the population and see if the outbreak stops; if it does, the pathogen was a virus',
        'correct_answer': 'B',
        'explanation': 'Several approaches distinguish bacteria from viruses: (1) Antibiotic treatment — if patients recover, a bacterium is likely; (2) Microscopy — bacteria are typically 1-10 µm and can be seen with light microscopy; viruses are ~10-400 nm and require electron microscopy; (3) Culture — bacteria grow on agar plates; viruses cannot grow outside living host cells. Genomic sequencing and PCR are also used in practice.',
        'correction_tip': 'Bacteria vs virus: size (microscopy), culture ability, antibiotic response. Know the differences for experimental design questions.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Explain why passive immunity (e.g. from antibodies given directly) provides faster but shorter-lasting protection than active immunity from vaccination.',
        'option_a': 'Passive immunity involves stronger antibodies that break down faster; active immunity produces weaker but more stable antibodies',
        'option_b': 'In passive immunity, ready-made antibodies are introduced directly, giving immediate protection but no memory cells are produced so protection ends when those antibodies degrade; active immunity involves the body producing its own antibodies and memory cells, which persist long-term',
        'option_c': 'Passive immunity activates phagocytes faster; active immunity activates lymphocytes faster',
        'option_d': 'Passive immunity produces more antibodies than active immunity but they are only effective for one pathogen',
        'correct_answer': 'B',
        'explanation': 'Passive immunity: pre-formed antibodies (from another person/animal, or produced in a lab) are injected. Immediate protection — no lag. But no memory cells are formed, so when the antibodies naturally degrade (weeks to months), protection is lost. Active immunity (vaccination or natural infection): the body makes its own antibodies AND memory cells, which persist for years or decades.',
        'correction_tip': 'Passive = fast but temporary (no memory cells). Active = slower but long-lasting (memory cells formed).',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Scientists publish data showing that countries with higher rates of antibiotic use in farming have higher rates of antibiotic-resistant infections in humans. Evaluate whether this data proves that farming antibiotic use causes resistance in human pathogens.',
        'option_a': 'Yes, the correlation proves causation directly — farming antibiotic use definitely causes human antibiotic resistance',
        'option_b': 'The correlation is suggestive but does not prove causation; other confounding variables (e.g. human antibiotic overuse, healthcare standards) must be controlled, and a plausible mechanism (e.g. resistant bacteria entering the food chain) must be demonstrated',
        'option_c': 'No, there is no relationship because bacteria in animals and bacteria in humans are entirely different species',
        'option_d': 'The data is irrelevant because only hospital antibiotic use contributes to resistance',
        'correct_answer': 'B',
        'explanation': 'Correlation ≠ causation. The data shows an association, which is scientifically interesting and warrants further investigation. However, to demonstrate causation, researchers must control for confounding variables, show a plausible biological mechanism (e.g. resistant bacteria from livestock entering the human food chain via contaminated meat), and conduct controlled experiments. Current evidence does support a link, but the data alone is insufficient proof.',
        'correction_tip': 'Exam skill: correlation ≠ causation. Always mention confounding variables and the need for a plausible mechanism.',
    },
    {
        'subject': 'Biology',
        'topic': 'Immunity',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Some viruses (e.g. flu, HIV) are very difficult to produce long-lasting vaccines for. Explain the biological reasons for this difficulty.',
        'option_a': 'These viruses kill memory cells, making any vaccination useless',
        'option_b': 'These viruses mutate rapidly, changing their surface antigens, so antibodies and memory cells from a previous infection or vaccination no longer recognise the new variant; for HIV, it also integrates into the host genome, making complete elimination very difficult',
        'option_c': 'These viruses produce toxins that destroy vaccines before they can stimulate an immune response',
        'option_d': 'These viruses are too small for the immune system to detect, even after vaccination',
        'correct_answer': 'B',
        'explanation': 'Influenza mutates its haemagglutinin and neuraminidase surface proteins rapidly (antigenic drift/shift) — new antigens mean new vaccines are needed annually. HIV is even more challenging: it has an extremely high mutation rate, can exist as a latent provirus integrated into host DNA (invisible to the immune system), and directly destroys the helper T cells that would normally coordinate the immune response against it.',
        'correction_tip': 'High mutation rates = antigen change = existing antibodies don\'t fit. HIV also hides in host DNA. Both make vaccines very hard.',
    },
    {
        'subject': 'Biology',
        'topic': 'Infection',
        'topic_code': 'B3',
        'difficulty': 4,
        'question_text': 'Oseltamivir (Tamiflu) is an antiviral drug used for influenza. A scientist claims it should be given to everyone who has a cold to prevent complications. Evaluate this claim.',
        'option_a': 'The claim is correct — antivirals should be given widely to prevent all viral complications',
        'option_b': 'The claim is flawed: colds and flu are different viral infections; oseltamivir is specific to influenza neuraminidase and will not treat cold viruses; widespread use increases selection pressure for oseltamivir-resistant influenza strains; and overuse may cause unnecessary side effects and economic cost',
        'option_c': 'The claim is partially correct — oseltamivir cures both colds and flu when given early enough',
        'option_d': 'The claim is flawed only because oseltamivir is too expensive for widespread use',
        'correct_answer': 'B',
        'explanation': 'Multiple problems with the claim: (1) Oseltamivir targets influenza neuraminidase specifically; cold viruses have different mechanisms so it has no effect. (2) Widespread antiviral use creates selection pressure for resistant flu strains (analogous to antibiotic resistance). (3) Like antibiotics, antivirals should be used selectively to preserve efficacy. (4) Side effects (nausea, neuropsychiatric effects) are a concern in mass use.',
        'correction_tip': 'Antivirals, like antibiotics, can select for resistance if overused. Oseltamivir is influenza-specific, not a general antiviral.',
    },
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute(
            '''INSERT INTO questions (subject, topic, topic_code, difficulty, question_text,
               option_a, option_b, option_c, option_d, correct_answer, explanation, correction_tip)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
