QUESTIONS = [
    # =========================================================
    # P1 ENERGY — 62 questions
    # D1 Easy (16)
    # =========================================================
    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'Which energy store does a moving car have?',
     'option_a':'Gravitational potential','option_b':'Kinetic','option_c':'Elastic potential','option_d':'Chemical',
     'correct_answer':'B',
     'explanation':'A moving object has kinetic energy stored in its motion.',
     'correction_tip':'Remember: kinetic energy is the energy of movement.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'Which energy store is associated with the position of an object above the ground?',
     'option_a':'Kinetic','option_b':'Elastic potential','option_c':'Gravitational potential','option_d':'Thermal',
     'correct_answer':'C',
     'explanation':'Gravitational potential energy (GPE) depends on an object\'s height above a reference point.',
     'correction_tip':'GPE = mgh — height is the key variable.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'A stretched rubber band stores energy in which energy store?',
     'option_a':'Chemical','option_b':'Kinetic','option_c':'Thermal','option_d':'Elastic potential',
     'correct_answer':'D',
     'explanation':'A stretched or compressed object stores elastic potential energy.',
     'correction_tip':'Springs and elastic bands store elastic potential energy when deformed.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'Food contains which type of energy store?',
     'option_a':'Nuclear','option_b':'Chemical','option_c':'Thermal','option_d':'Magnetic',
     'correct_answer':'B',
     'explanation':'Food contains chemical energy stored in the bonds between atoms.',
     'correction_tip':'Fuels and food both store chemical energy.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'Which energy store is found in the nucleus of an atom?',
     'option_a':'Chemical','option_b':'Electrostatic','option_c':'Nuclear','option_d':'Magnetic',
     'correct_answer':'C',
     'explanation':'Nuclear energy is stored in the nucleus and released in nuclear reactions.',
     'correction_tip':'Nuclear power stations use this energy store.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'A hot cup of tea has energy in which energy store?',
     'option_a':'Kinetic','option_b':'Thermal','option_c':'Chemical','option_d':'Nuclear',
     'correct_answer':'B',
     'explanation':'Thermal energy (internal energy) is stored due to the temperature of an object.',
     'correction_tip':'Anything warm has thermal energy.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':1,
     'question_text':'Which process transfers energy through a solid by the vibration of particles?',
     'option_a':'Convection','option_b':'Radiation','option_c':'Conduction','option_d':'Evaporation',
     'correct_answer':'C',
     'explanation':'Conduction transfers thermal energy through a material by particle vibrations passing energy along.',
     'correction_tip':'Conduction occurs in solids; metals are good conductors.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':1,
     'question_text':'Energy transfer by electromagnetic waves (such as infrared) is called:',
     'option_a':'Conduction','option_b':'Convection','option_c':'Radiation','option_d':'Induction',
     'correct_answer':'C',
     'explanation':'Radiation transfers energy by electromagnetic waves and does not require a medium.',
     'correction_tip':'Radiation is the only method that works in a vacuum (e.g. from the Sun to Earth).'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':1,
     'question_text':'What is the principle of conservation of energy?',
     'option_a':'Energy can be created from nothing','option_b':'Energy can be destroyed by friction',
     'option_c':'Energy cannot be created or destroyed, only transferred or stored','option_d':'Energy always increases in a system',
     'correct_answer':'C',
     'explanation':'The law of conservation of energy states energy is always conserved — it changes form but the total remains constant.',
     'correction_tip':'Total energy in = total energy out (useful + wasted).'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':1,
     'question_text':'A light bulb transfers 100 J of electrical energy. 10 J is emitted as light. What is the efficiency?',
     'option_a':'100%','option_b':'90%','option_c':'10%','option_d':'50%',
     'correct_answer':'C',
     'explanation':'Efficiency = (useful output / total input) x 100 = (10/100) x 100 = 10%.',
     'correction_tip':'Efficiency = useful energy output / total energy input.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':1,
     'question_text':'Which of the following has the highest efficiency?',
     'option_a':'An incandescent bulb (5% light output)','option_b':'An LED bulb (90% light output)',
     'option_c':'A gas boiler (70% useful heat)','option_d':'A car engine (25% useful work)',
     'correct_answer':'B',
     'explanation':'The LED bulb converts 90% of its energy input to useful light energy.',
     'correction_tip':'Higher efficiency means less energy is wasted.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':1,
     'question_text':'In a Sankey diagram, what does the width of an arrow represent?',
     'option_a':'The speed of energy transfer','option_b':'The type of energy','option_c':'The amount of energy','option_d':'The direction of heat flow',
     'correct_answer':'C',
     'explanation':'The width of each arrow in a Sankey diagram is proportional to the amount of energy it represents.',
     'correction_tip':'Wider arrow = more energy.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':1,
     'question_text':'What does a step-up transformer do to voltage?',
     'option_a':'Decreases it','option_b':'Keeps it the same','option_c':'Increases it','option_d':'Converts AC to DC',
     'correct_answer':'C',
     'explanation':'A step-up transformer increases the voltage (and decreases the current) for efficient transmission.',
     'correction_tip':'Step-up = voltage goes up; step-down = voltage goes down.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':1,
     'question_text':'Why is electricity transmitted at high voltage across the National Grid?',
     'option_a':'To increase the current','option_b':'To reduce energy lost as heat in the cables',
     'option_c':'To make it safer for consumers','option_d':'To slow down the electrons',
     'correct_answer':'B',
     'explanation':'High voltage means low current for the same power, and power lost as heat = I squared R, so lower current means much less energy wasted.',
     'correction_tip':'P_loss = I squared R — reducing current dramatically cuts heat losses.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':1,
     'question_text':'Which of the following is a renewable energy source?',
     'option_a':'Coal','option_b':'Natural gas','option_c':'Nuclear','option_d':'Wind',
     'correct_answer':'D',
     'explanation':'Wind energy is renewable because it is naturally replenished and will not run out.',
     'correction_tip':'Renewable sources: wind, solar, hydro, tidal, geothermal, biomass.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':1,
     'question_text':'Convection currents in a liquid occur because heated fluid becomes:',
     'option_a':'Denser and sinks','option_b':'Less dense and rises','option_c':'More viscous','option_d':'Colder',
     'correct_answer':'B',
     'explanation':'When a fluid is heated it expands, becomes less dense and rises, setting up a convection current.',
     'correction_tip':'Hot fluid rises; cool fluid sinks — this drives convection.'},

    # P1 D2 Medium (16)
    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'A 2 kg ball moves at 3 m/s. What is its kinetic energy?',
     'option_a':'6 J','option_b':'9 J','option_c':'18 J','option_d':'3 J',
     'correct_answer':'B',
     'explanation':'KE = 0.5 x m x v squared = 0.5 x 2 x 9 = 9 J.',
     'correction_tip':'KE = 0.5mv squared — remember to square the velocity.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'A 5 kg object is lifted 4 m. What is the gain in gravitational potential energy? (g = 10 N/kg)',
     'option_a':'50 J','option_b':'20 J','option_c':'200 J','option_d':'100 J',
     'correct_answer':'C',
     'explanation':'GPE = mgh = 5 x 10 x 4 = 200 J.',
     'correction_tip':'GPE = mgh — multiply mass, gravitational field strength and height.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':2,
     'question_text':'A motor receives 500 J of electrical energy and does 350 J of useful work. What is its efficiency?',
     'option_a':'50%','option_b':'60%','option_c':'70%','option_d':'75%',
     'correct_answer':'C',
     'explanation':'Efficiency = (350 / 500) x 100 = 70%.',
     'correction_tip':'Efficiency (%) = (useful output energy / total input energy) x 100.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':2,
     'question_text':'A machine has an efficiency of 40% and receives 200 J of energy. How much useful energy does it transfer?',
     'option_a':'40 J','option_b':'80 J','option_c':'120 J','option_d':'160 J',
     'correct_answer':'B',
     'explanation':'Useful energy = efficiency x input = 0.40 x 200 = 80 J.',
     'correction_tip':'Rearrange: useful output = efficiency x input energy.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':2,
     'question_text':'Which material is the best thermal conductor?',
     'option_a':'Wood','option_b':'Plastic','option_c':'Copper','option_d':'Air',
     'correct_answer':'C',
     'explanation':'Metals like copper have free electrons that carry thermal energy quickly, making them excellent conductors.',
     'correction_tip':'Metals are good conductors; non-metals and gases are insulators.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':2,
     'question_text':'A Sankey diagram for an engine shows 1000 J input, 300 J useful work and 200 J sound. How much energy is wasted as heat?',
     'option_a':'300 J','option_b':'200 J','option_c':'500 J','option_d':'700 J',
     'correct_answer':'C',
     'explanation':'Wasted heat = 1000 - 300 - 200 = 500 J. Energy is conserved.',
     'correction_tip':'Total input = useful output + all wasted outputs.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'Power is defined as:',
     'option_a':'Energy per unit charge','option_b':'Force times distance','option_c':'Energy transferred per unit time','option_d':'Voltage divided by current',
     'correct_answer':'C',
     'explanation':'Power (W) = Energy (J) / Time (s). It measures the rate of energy transfer.',
     'correction_tip':'P = E/t — watts are joules per second.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'A device transfers 600 J in 30 seconds. What is its power?',
     'option_a':'30 W','option_b':'20 W','option_c':'600 W','option_d':'18000 W',
     'correct_answer':'B',
     'explanation':'P = E/t = 600 / 30 = 20 W.',
     'correction_tip':'P = E/t — divide energy by time.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':2,
     'question_text':'A step-down transformer reduces voltage from 11000 V to 230 V. What type of transformer is used at the consumer end of the National Grid?',
     'option_a':'Step-up transformer','option_b':'Step-down transformer','option_c':'Isolation transformer','option_d':'Current transformer',
     'correct_answer':'B',
     'explanation':'Step-down transformers reduce the high transmission voltage back to the safe 230 V used in homes.',
     'correction_tip':'Power stations use step-up; homes use step-down transformers.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'Specific heat capacity is the energy needed to raise the temperature of 1 kg of a substance by:',
     'option_a':'1 degree F','option_b':'100 degrees C','option_c':'1 degree C (or 1 K)','option_d':'10 degrees C',
     'correct_answer':'C',
     'explanation':'Specific heat capacity (c) is measured in J/kg degrees C and relates to a 1 degree C temperature change per kilogram.',
     'correction_tip':'Q = mcΔT — c is specific heat capacity in J per kg per degree C.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'How much energy is needed to heat 0.5 kg of water by 10 degrees C? (specific heat capacity of water = 4200 J/kg degrees C)',
     'option_a':'21000 J','option_b':'2100 J','option_c':'42000 J','option_d':'210 J',
     'correct_answer':'A',
     'explanation':'Q = mcΔT = 0.5 x 4200 x 10 = 21000 J.',
     'correction_tip':'Q = mcΔT — substitute values carefully.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':2,
     'question_text':'Which surface is the best emitter and absorber of infrared radiation?',
     'option_a':'Shiny white','option_b':'Matt black','option_c':'Shiny silver','option_d':'Smooth yellow',
     'correct_answer':'B',
     'explanation':'Matt black surfaces are the best emitters and absorbers of infrared radiation.',
     'correction_tip':'Black matt = best emitter/absorber; shiny/white = best reflector.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'Which energy source produces carbon dioxide when burned?',
     'option_a':'Solar','option_b':'Wind','option_c':'Natural gas','option_d':'Tidal',
     'correct_answer':'C',
     'explanation':'Burning natural gas (a fossil fuel) releases CO2, contributing to the greenhouse effect.',
     'correction_tip':'Fossil fuels (coal, oil, gas) all release CO2 when combusted.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':2,
     'question_text':'What happens to the wasted energy in most devices?',
     'option_a':'It is destroyed','option_b':'It is stored forever','option_c':'It is dissipated as thermal energy to the surroundings','option_d':'It returns to the input',
     'correct_answer':'C',
     'explanation':'Wasted energy is usually transferred to the thermal energy store of the surroundings, where it is less useful.',
     'correction_tip':'Energy is never destroyed — it spreads out as thermal energy.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':2,
     'question_text':'A transformer has 200 turns on the primary and 1000 turns on the secondary. The input voltage is 50 V. What is the output voltage?',
     'option_a':'10 V','option_b':'250 V','option_c':'100 V','option_d':'500 V',
     'correct_answer':'B',
     'explanation':'V_s/V_p = N_s/N_p so V_s = 50 x (1000/200) = 50 x 5 = 250 V.',
     'correction_tip':'Use the transformer equation: V_s/V_p = N_s/N_p.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':2,
     'question_text':'Which formula correctly calculates kinetic energy?',
     'option_a':'KE = mv','option_b':'KE = 0.5 x m x v squared','option_c':'KE = mgh','option_d':'KE = 2mv squared',
     'correct_answer':'B',
     'explanation':'KE = 0.5mv squared, where m is mass in kg and v is speed in m/s.',
     'correction_tip':'The velocity must be squared in the KE formula.'},

    # P1 D3 Hard (15)
    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'A 1200 kg car travels at 20 m/s. Calculate its kinetic energy.',
     'option_a':'12000 J','option_b':'240000 J','option_c':'480000 J','option_d':'24000 J',
     'correct_answer':'B',
     'explanation':'KE = 0.5 x 1200 x 20 squared = 0.5 x 1200 x 400 = 240000 J.',
     'correction_tip':'KE = 0.5mv squared — square the speed first, then multiply.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'A 60 kg person climbs stairs to a height of 8 m. Calculate the gain in GPE. (g = 10 N/kg)',
     'option_a':'480 J','option_b':'4800 J','option_c':'600 J','option_d':'48 J',
     'correct_answer':'B',
     'explanation':'GPE = mgh = 60 x 10 x 8 = 4800 J.',
     'correction_tip':'GPE = mgh — do not forget to include g = 10 N/kg.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':3,
     'question_text':'A pump with 65% efficiency uses 8000 J of electrical energy. How much useful energy does it deliver?',
     'option_a':'5200 J','option_b':'4800 J','option_c':'2800 J','option_d':'12308 J',
     'correct_answer':'A',
     'explanation':'Useful energy = 0.65 x 8000 = 5200 J.',
     'correction_tip':'Useful output = efficiency (as decimal) x input energy.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'A heater with power 2000 W operates for 3 hours. How much energy does it transfer? (Give your answer in MJ.)',
     'option_a':'6 MJ','option_b':'21.6 MJ','option_c':'0.6 MJ','option_d':'360 MJ',
     'correct_answer':'B',
     'explanation':'E = Pt = 2000 x (3 x 3600) = 2000 x 10800 = 21600000 J = 21.6 MJ.',
     'correction_tip':'Convert hours to seconds first: 3 h = 10800 s.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'Water of mass 3 kg is heated from 20 degrees C to 80 degrees C. Calculate the energy required. (specific heat capacity = 4200 J/kg degrees C)',
     'option_a':'504000 J','option_b':'756000 J','option_c':'252000 J','option_d':'25200 J',
     'correct_answer':'B',
     'explanation':'Q = mcΔT = 3 x 4200 x (80 - 20) = 3 x 4200 x 60 = 756000 J.',
     'correction_tip':'ΔT = final temperature minus initial temperature.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':3,
     'question_text':'An object falls from rest and converts all its GPE to KE. If it fell from 5 m, what is its speed at the bottom? (g = 10 N/kg)',
     'option_a':'5 m/s','option_b':'10 m/s','option_c':'50 m/s','option_d':'100 m/s',
     'correct_answer':'B',
     'explanation':'GPE = KE: mgh = 0.5mv squared, so v squared = 2gh = 2 x 10 x 5 = 100, v = 10 m/s.',
     'correction_tip':'Set GPE = KE and solve for v: v = square root of (2gh).'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':3,
     'question_text':'A transformer steps up voltage from 25000 V to 400000 V. The primary current is 800 A. Assuming 100% efficiency, what is the secondary current?',
     'option_a':'12800 A','option_b':'50 A','option_c':'800 A','option_d':'400 A',
     'correct_answer':'B',
     'explanation':'For an ideal transformer: V_p x I_p = V_s x I_s. I_s = (25000 x 800) / 400000 = 50 A.',
     'correction_tip':'Power in = power out for ideal transformer: V_p times I_p = V_s times I_s.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':3,
     'question_text':'A petrol engine produces 18 kJ of useful work and wastes 42 kJ as heat. What is the efficiency of the engine?',
     'option_a':'18%','option_b':'30%','option_c':'42%','option_d':'70%',
     'correct_answer':'B',
     'explanation':'Total input = 18 + 42 = 60 kJ. Efficiency = (18/60) x 100 = 30%.',
     'correction_tip':'Total input = useful + wasted. Then efficiency = (useful/total) x 100.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'A spring with spring constant 400 N/m is compressed by 0.05 m. Calculate the elastic potential energy stored.',
     'option_a':'1 J','option_b':'0.5 J','option_c':'10 J','option_d':'0.25 J',
     'correct_answer':'B',
     'explanation':'EPE = 0.5 x k x x squared = 0.5 x 400 x 0.0025 = 0.5 J.',
     'correction_tip':'EPE = 0.5kx squared — x is the extension or compression in metres.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':3,
     'question_text':'A 500 W electric motor lifts a 20 kg load by 3 m in 2 seconds. Calculate the efficiency of the motor. (g = 10 N/kg)',
     'option_a':'30%','option_b':'60%','option_c':'80%','option_d':'90%',
     'correct_answer':'B',
     'explanation':'Useful power = mgh/t = (20 x 10 x 3)/2 = 300 W. Efficiency = (300/500) x 100 = 60%.',
     'correction_tip':'Efficiency = useful power output / total power input.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':3,
     'question_text':'A transmission cable has resistance 4 ohm and carries a current of 50 A. Calculate the power wasted in the cable.',
     'option_a':'200 W','option_b':'10000 W','option_c':'400 W','option_d':'2500 W',
     'correct_answer':'B',
     'explanation':'P = I squared x R = 50 squared x 4 = 2500 x 4 = 10000 W.',
     'correction_tip':'P_loss = I squared R — this shows why high voltage (low current) reduces losses.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':3,
     'question_text':'A ball of mass 0.2 kg is thrown upwards with KE = 40 J. How high does it rise? (g = 10 N/kg, ignore air resistance)',
     'option_a':'4 m','option_b':'20 m','option_c':'8 m','option_d':'2 m',
     'correct_answer':'B',
     'explanation':'KE = GPE: 40 = mgh = 0.2 x 10 x h. h = 40/2 = 20 m.',
     'correction_tip':'KE fully converts to GPE at the highest point (no air resistance).'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':3,
     'question_text':'In which situation does convection NOT occur?',
     'option_a':'Hot water rising in a tank','option_b':'Air circulating over a radiator',
     'option_c':'Heat conducted through a metal rod','option_d':'Sea breeze forming at the coast',
     'correct_answer':'C',
     'explanation':'Conduction through a solid does not involve fluid movement; convection requires a fluid (liquid or gas).',
     'correction_tip':'Convection only occurs in fluids (liquids and gases), not solids.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':3,
     'question_text':'A device has efficiency 0.75. If 600 J of useful energy is required, what input energy must be supplied?',
     'option_a':'450 J','option_b':'800 J','option_c':'750 J','option_d':'600 J',
     'correct_answer':'B',
     'explanation':'Input = useful output / efficiency = 600 / 0.75 = 800 J.',
     'correction_tip':'Rearrange efficiency equation: input = useful output / efficiency.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':3,
     'question_text':'A transformer has 500 primary turns and 50 secondary turns. If the primary voltage is 230 V, what is the secondary voltage?',
     'option_a':'2300 V','option_b':'23 V','option_c':'115 V','option_d':'46 V',
     'correct_answer':'B',
     'explanation':'V_s = V_p x (N_s/N_p) = 230 x (50/500) = 230 x 0.1 = 23 V.',
     'correction_tip':'This is a step-down transformer (fewer secondary turns).'},

    # P1 D4 Exam Challenge (15)
    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A roller coaster car of mass 800 kg descends from a height of 30 m. Assuming 15% of energy is lost to friction, calculate the speed at the bottom. (g = 10 N/kg)',
     'option_a':'20.5 m/s','option_b':'22.6 m/s','option_c':'25.5 m/s','option_d':'17.3 m/s',
     'correct_answer':'B',
     'explanation':'GPE = 800 x 10 x 30 = 240000 J. KE = 85% x 240000 = 204000 J. v = square root of (2 x 204000 / 800) = square root of 510 = 22.6 m/s.',
     'correction_tip':'Useful KE = (1 - fraction lost) x initial GPE, then use KE = 0.5mv squared.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':4,
     'question_text':'A power station burns fuel releasing 500 MJ. It generates 125 MJ of electrical energy. The transmission cables waste 5 MJ. What is the overall efficiency from fuel to consumer?',
     'option_a':'24%','option_b':'25%','option_c':'96%','option_d':'22%',
     'correct_answer':'A',
     'explanation':'Energy reaching consumer = 125 - 5 = 120 MJ. Overall efficiency = (120/500) x 100 = 24%.',
     'correction_tip':'Overall efficiency accounts for every stage of energy transfer.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A 70 kg athlete runs up a 12 m hill in 8 s. Calculate the useful power output. (g = 10 N/kg)',
     'option_a':'875 W','option_b':'1050 W','option_c':'700 W','option_d':'8400 W',
     'correct_answer':'B',
     'explanation':'GPE gained = 70 x 10 x 12 = 8400 J. Power = E/t = 8400/8 = 1050 W.',
     'correction_tip':'P = W/t where W is the useful work done (GPE gained).'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':4,
     'question_text':'A generator produces 10 kW at 250 V. A step-up transformer increases this to 10000 V. Calculate the current in the transmission lines.',
     'option_a':'0.25 A','option_b':'1 A','option_c':'40 A','option_d':'400 A',
     'correct_answer':'B',
     'explanation':'Power = V x I, so I = P/V = 10000/10000 = 1 A.',
     'correction_tip':'After the transformer, use P = VI with the new transmission voltage.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A 0.5 kg mass on a spring (spring constant = 800 N/m) is compressed by 0.1 m and released. Calculate the maximum speed the mass reaches (assume all elastic PE converts to KE).',
     'option_a':'2 m/s','option_b':'4 m/s','option_c':'8 m/s','option_d':'16 m/s',
     'correct_answer':'B',
     'explanation':'EPE = 0.5 x 800 x 0.1 squared = 4 J. KE = 0.5mv squared: 4 = 0.5 x 0.5 x v squared, v squared = 16, v = 4 m/s.',
     'correction_tip':'Set EPE = KE and solve for v.'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':4,
     'question_text':'A 2 kg block slides 10 m along a surface with friction force 4 N. It started with KE = 120 J. What is the final KE?',
     'option_a':'80 J','option_b':'160 J','option_c':'40 J','option_d':'100 J',
     'correct_answer':'A',
     'explanation':'Work done by friction = F x d = 4 x 10 = 40 J (energy removed). Final KE = 120 - 40 = 80 J.',
     'correction_tip':'Energy lost to friction = friction force x distance.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':4,
     'question_text':'A kettle with power 2500 W and efficiency 92% heats water. How long does it take to supply 184000 J of useful energy to the water?',
     'option_a':'73.6 s','option_b':'80 s','option_c':'92 s','option_d':'100 s',
     'correct_answer':'B',
     'explanation':'Useful power = 0.92 x 2500 = 2300 W. Time = E/P = 184000/2300 = 80 s.',
     'correction_tip':'Useful power = efficiency x total power. Then t = useful energy / useful power.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'Aluminium has specific heat capacity 900 J/kg degrees C. A 3 kg aluminium block cools from 120 degrees C to 20 degrees C. How much thermal energy is released?',
     'option_a':'270000 J','option_b':'27000 J','option_c':'54000 J','option_d':'2700 J',
     'correct_answer':'A',
     'explanation':'Q = mcΔT = 3 x 900 x (120 - 20) = 3 x 900 x 100 = 270000 J.',
     'correction_tip':'ΔT = 100 degrees C here. Q = mcΔT works for both heating and cooling.'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':4,
     'question_text':'A transmission line of resistance 2 ohm carries 200 A. The power station generates 400 kW. What percentage of power is wasted in the line?',
     'option_a':'4%','option_b':'8%','option_c':'20%','option_d':'40%',
     'correct_answer':'C',
     'explanation':'P_loss = I squared x R = 200 squared x 2 = 80000 W = 80 kW. Percentage lost = (80/400) x 100 = 20%.',
     'correction_tip':'P_loss = I squared R, then express as a percentage of total generated power.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A vehicle decelerates from 30 m/s to 10 m/s. The mass is 1500 kg. How much kinetic energy is converted to heat by the brakes?',
     'option_a':'300000 J','option_b':'600000 J','option_c':'450000 J','option_d':'750000 J',
     'correct_answer':'B',
     'explanation':'Initial KE = 0.5 x 1500 x 900 = 675000 J. Final KE = 0.5 x 1500 x 100 = 75000 J. Change in KE = 675000 - 75000 = 600000 J.',
     'correction_tip':'Calculate KE at each speed then find the difference.'},

    {'subject':'Physics','topic':'Efficiency','topic_code':'P1','difficulty':4,
     'question_text':'Two machines are in series. Machine A has efficiency 80% and Machine B has efficiency 75%. What is the overall efficiency?',
     'option_a':'77.5%','option_b':'60%','option_c':'155%','option_d':'80%',
     'correct_answer':'B',
     'explanation':'Overall efficiency = 0.80 x 0.75 = 0.60 = 60%. Multiply efficiencies when machines are in series.',
     'correction_tip':'For machines in series, multiply their efficiencies (as decimals).'},

    {'subject':'Physics','topic':'Energy transfer','topic_code':'P1','difficulty':4,
     'question_text':'A house loses energy through its walls at 500 W. The owner adds insulation that reduces heat loss by 60%. How much energy is saved in 24 hours?',
     'option_a':'25920 kJ','option_b':'43200 kJ','option_c':'17280 kJ','option_d':'8640 kJ',
     'correct_answer':'A',
     'explanation':'Power saved = 60% x 500 = 300 W. Energy saved = 300 x (24 x 3600) = 300 x 86400 = 25920000 J = 25920 kJ.',
     'correction_tip':'Power saved = reduction fraction x original power loss. E = P x t (in seconds).'},

    {'subject':'Physics','topic':'National grid','topic_code':'P1','difficulty':4,
     'question_text':'A step-up transformer has 400 primary turns and 8000 secondary turns. Primary voltage is 230 V and primary current is 10 A. Assuming 100% efficiency, calculate the secondary current.',
     'option_a':'0.5 A','option_b':'200 A','option_c':'5 A','option_d':'0.115 A',
     'correct_answer':'A',
     'explanation':'Turn ratio = 8000/400 = 20. V_s = 230 x 20 = 4600 V. I_s = (V_p x I_p) / V_s = (230 x 10) / 4600 = 0.5 A.',
     'correction_tip':'For ideal transformer: V_p x I_p = V_s x I_s. Find V_s first.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A pendulum has 0.8 J of GPE at its highest point. Due to air resistance it only reaches 0.6 J of GPE on the return swing. What percentage of energy was lost?',
     'option_a':'20%','option_b':'25%','option_c':'33%','option_d':'75%',
     'correct_answer':'B',
     'explanation':'Energy lost = 0.8 - 0.6 = 0.2 J. Percentage lost = (0.2/0.8) x 100 = 25%.',
     'correction_tip':'Percentage energy lost = (energy lost / initial energy) x 100.'},

    {'subject':'Physics','topic':'Energy stores','topic_code':'P1','difficulty':4,
     'question_text':'A wind turbine with efficiency 35% intercepts wind with power 600 kW. What is the electrical power output?',
     'option_a':'35 kW','option_b':'210 kW','option_c':'390 kW','option_d':'600 kW',
     'correct_answer':'B',
     'explanation':'Electrical power = 0.35 x 600 = 210 kW.',
     'correction_tip':'Useful power output = efficiency x input power.'},

    # =========================================================
    # P2 ELECTRICITY — 61 questions
    # D1 Easy (16)
    # =========================================================
    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What is the unit of electric current?',
     'option_a':'Volt','option_b':'Ohm','option_c':'Ampere','option_d':'Watt',
     'correct_answer':'C',
     'explanation':'Electric current is measured in amperes (A), which represents the rate of flow of charge.',
     'correction_tip':'Voltage is volts (V), resistance is ohms (ohm), current is amperes (A).'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What does voltage (potential difference) measure?',
     'option_a':'The amount of charge flowing','option_b':'The energy transferred per unit charge',
     'option_c':'The resistance of a component','option_d':'The speed of electrons',
     'correct_answer':'B',
     'explanation':'Voltage (potential difference) is energy transferred per unit charge, measured in volts (J/C).',
     'correction_tip':'V = E/Q — volts = joules per coulomb.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'Ohm\'s law states V = IR. If V = 12 V and R = 4 ohm, what is the current?',
     'option_a':'48 A','option_b':'8 A','option_c':'3 A','option_d':'0.33 A',
     'correct_answer':'C',
     'explanation':'I = V/R = 12/4 = 3 A.',
     'correction_tip':'Rearrange V = IR to find I: I = V/R.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':1,
     'question_text':'In a series circuit, what is true about the current?',
     'option_a':'It is different at each component','option_b':'It is the same throughout the circuit',
     'option_c':'It is zero at every junction','option_d':'It splits between components',
     'correct_answer':'B',
     'explanation':'In a series circuit, the same current flows through every component.',
     'correction_tip':'Series: current same everywhere; voltage splits. Parallel: voltage same; current splits.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':1,
     'question_text':'In a parallel circuit, what is true about the voltage across each branch?',
     'option_a':'It varies between branches','option_b':'It is zero','option_c':'It is the same across each branch','option_d':'It doubles with each branch',
     'correct_answer':'C',
     'explanation':'In a parallel circuit, all branches have the same potential difference (voltage) across them.',
     'correction_tip':'Parallel: voltage same; current splits. Series: current same; voltage splits.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':1,
     'question_text':'What happens to the resistance of a thermistor as temperature increases?',
     'option_a':'Stays the same','option_b':'Increases','option_c':'Decreases','option_d':'Doubles',
     'correct_answer':'C',
     'explanation':'In an NTC (negative temperature coefficient) thermistor, resistance decreases as temperature increases.',
     'correction_tip':'Hot thermistor = low resistance. Cold thermistor = high resistance.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':1,
     'question_text':'What happens to the resistance of a light-dependent resistor (LDR) in bright light?',
     'option_a':'Increases','option_b':'Decreases','option_c':'Stays constant','option_d':'Becomes infinite',
     'correct_answer':'B',
     'explanation':'An LDR has high resistance in darkness and low resistance in bright light.',
     'correction_tip':'Bright light = low LDR resistance; dark = high LDR resistance.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'Which of the following is a non-ohmic conductor?',
     'option_a':'Copper wire','option_b':'Resistor at constant temperature','option_c':'Filament lamp','option_d':'Nichrome wire',
     'correct_answer':'C',
     'explanation':'A filament lamp is non-ohmic because its resistance increases as it heats up, so V is not proportional to I.',
     'correction_tip':'Ohmic conductors have constant resistance; non-ohmic do not (lamp, diode, thermistor).'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What is the mains voltage in the UK?',
     'option_a':'110 V','option_b':'120 V','option_c':'230 V','option_d':'400 V',
     'correct_answer':'C',
     'explanation':'The UK mains supply is approximately 230 V AC at 50 Hz.',
     'correction_tip':'UK mains: 230 V, 50 Hz, AC.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What colour is the live wire in a UK mains plug?',
     'option_a':'Blue','option_b':'Green and yellow','option_c':'Brown','option_d':'Red',
     'correct_answer':'C',
     'explanation':'In a UK plug: brown = live, blue = neutral, green/yellow = earth.',
     'correction_tip':'Brown = Live, Blue = Neutral, Green/Yellow = Earth.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What is the purpose of the earth wire in a mains appliance?',
     'option_a':'To carry the main current','option_b':'To return current to the supply',
     'option_c':'To provide a safe path for current if a fault occurs','option_d':'To increase resistance',
     'correct_answer':'C',
     'explanation':'The earth wire connects the metal case to earth so if the case becomes live, current flows to earth, blowing the fuse rather than electrocuting the user.',
     'correction_tip':'Earth wire is a safety feature — it prevents electric shock if there is a fault.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What causes static electricity to build up on an object?',
     'option_a':'Movement of protons','option_b':'Transfer of electrons between surfaces by friction',
     'option_c':'Flow of current through a wire','option_d':'Magnetic fields',
     'correct_answer':'B',
     'explanation':'Static electricity is produced when electrons are transferred between two surfaces by friction, leaving one positively charged and one negatively charged.',
     'correction_tip':'Only electrons move — friction transfers electrons, not protons.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':1,
     'question_text':'A diode allows current to flow in:',
     'option_a':'Both directions','option_b':'One direction only','option_c':'Neither direction','option_d':'Only when hot',
     'correct_answer':'B',
     'explanation':'A diode only allows conventional current to flow in one direction (forward bias); it blocks reverse current.',
     'correction_tip':'Diodes are used to convert AC to DC (rectification).'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'Which of the following best describes alternating current (AC)?',
     'option_a':'Current that flows in one direction only','option_b':'Current that reverses direction periodically',
     'option_c':'Current that stays constant','option_d':'Current produced by batteries',
     'correct_answer':'B',
     'explanation':'AC reverses direction repeatedly. In the UK it does so 50 times per second (50 Hz).',
     'correction_tip':'AC = alternates direction; DC = direct (one direction) current.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':1,
     'question_text':'Two resistors of 6 ohm and 3 ohm are connected in series. What is the total resistance?',
     'option_a':'2 ohm','option_b':'3 ohm','option_c':'9 ohm','option_d':'18 ohm',
     'correct_answer':'C',
     'explanation':'In series, total resistance = R1 + R2 = 6 + 3 = 9 ohm.',
     'correction_tip':'Series: add resistances. Parallel: use reciprocals.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':1,
     'question_text':'What charge does an electron carry?',
     'option_a':'Positive','option_b':'Neutral','option_c':'Negative','option_d':'It depends on the material',
     'correct_answer':'C',
     'explanation':'Electrons carry a negative charge of approximately 1.6 x 10 to the power -19 C.',
     'correction_tip':'Electrons are negative; protons are positive; neutrons are neutral.'},

    # P2 D2 Medium (15)
    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':2,
     'question_text':'Two resistors of 4 ohm and 12 ohm are connected in parallel. Calculate the total resistance.',
     'option_a':'16 ohm','option_b':'8 ohm','option_c':'3 ohm','option_d':'48 ohm',
     'correct_answer':'C',
     'explanation':'1/R_total = 1/4 + 1/12 = 3/12 + 1/12 = 4/12. R_total = 12/4 = 3 ohm.',
     'correction_tip':'Parallel: 1/R_total = 1/R1 + 1/R2. Total resistance is always less than the smallest individual resistance.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'A charge of 30 C flows past a point in 6 seconds. Calculate the current.',
     'option_a':'180 A','option_b':'24 A','option_c':'5 A','option_d':'0.2 A',
     'correct_answer':'C',
     'explanation':'I = Q/t = 30/6 = 5 A.',
     'correction_tip':'I = Q/t — rearranged from Q = It.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'A 4 A current flows through a 5 ohm resistor. Calculate the voltage across it.',
     'option_a':'1.25 V','option_b':'20 V','option_c':'9 V','option_d':'0.8 V',
     'correct_answer':'B',
     'explanation':'V = IR = 4 x 5 = 20 V.',
     'correction_tip':'V = IR (Ohm\'s law).'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'Calculate the power dissipated by a 3 A current through a 10 ohm resistor.',
     'option_a':'30 W','option_b':'90 W','option_c':'13 W','option_d':'300 W',
     'correct_answer':'B',
     'explanation':'P = I squared x R = 3 squared x 10 = 9 x 10 = 90 W.',
     'correction_tip':'P = I squared R or P = IV or P = V squared/R.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':2,
     'question_text':'In a series circuit, two resistors have voltages 4 V and 8 V across them. The current is 2 A. What is the total resistance?',
     'option_a':'4 ohm','option_b':'6 ohm','option_c':'2 ohm','option_d':'12 ohm',
     'correct_answer':'B',
     'explanation':'Total voltage = 4 + 8 = 12 V. R = V/I = 12/2 = 6 ohm.',
     'correction_tip':'In series, voltages add. Then use R = V/I.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'How much charge flows when a current of 0.5 A flows for 2 minutes?',
     'option_a':'1 C','option_b':'60 C','option_c':'0.5 C','option_d':'4 C',
     'correct_answer':'B',
     'explanation':'Q = It = 0.5 x (2 x 60) = 0.5 x 120 = 60 C.',
     'correction_tip':'Convert time to seconds: 2 minutes = 120 s. Q = It.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'A 60 W light bulb is connected to 230 V mains. What current flows through it?',
     'option_a':'0.26 A','option_b':'3.83 A','option_c':'13800 A','option_d':'2.6 A',
     'correct_answer':'A',
     'explanation':'I = P/V = 60/230 = 0.26 A.',
     'correction_tip':'Rearrange P = IV to get I = P/V.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':2,
     'question_text':'An I-V graph for a resistor at constant temperature is a straight line through the origin. What does this tell us?',
     'option_a':'Resistance decreases with current','option_b':'Resistance is zero',
     'option_c':'Resistance is constant (ohmic behaviour)','option_d':'The component is a diode',
     'correct_answer':'C',
     'explanation':'A straight line through the origin on an I-V graph shows that V is proportional to I, meaning resistance is constant — the component obeys Ohm\'s law.',
     'correction_tip':'Gradient of V-I graph = resistance. Straight line = ohmic.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'Calculate the energy transferred by a 1500 W appliance used for 4 minutes.',
     'option_a':'375 J','option_b':'6000 J','option_c':'360000 J','option_d':'6000 kJ',
     'correct_answer':'C',
     'explanation':'E = Pt = 1500 x (4 x 60) = 1500 x 240 = 360000 J.',
     'correction_tip':'Convert minutes to seconds first. E = Pt.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':2,
     'question_text':'As the temperature of a metal conductor increases, what happens to its resistance?',
     'option_a':'Decreases','option_b':'Stays the same','option_c':'Increases','option_d':'Becomes zero',
     'correct_answer':'C',
     'explanation':'In a metal, increased temperature causes greater vibration of lattice ions, increasing collisions with electrons, so resistance increases.',
     'correction_tip':'Metals: hotter = more resistance. This is opposite to thermistors.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'A fuse rated at 5 A is in a circuit. The current rises to 8 A. What happens?',
     'option_a':'Nothing — the fuse is fine','option_b':'The fuse wire melts and breaks the circuit',
     'option_c':'The fuse doubles in resistance','option_d':'The voltage halves',
     'correct_answer':'B',
     'explanation':'When current exceeds the fuse rating, the wire melts and breaks the circuit, preventing damage or fire.',
     'correction_tip':'Fuses protect circuits by melting when current is too high.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'Which statement about circuit breakers compared to fuses is correct?',
     'option_a':'Circuit breakers cannot be reset','option_b':'Fuses can be reset after tripping',
     'option_c':'Circuit breakers can be reset after they trip','option_d':'Circuit breakers are slower to respond',
     'correct_answer':'C',
     'explanation':'Circuit breakers can be reset by flipping a switch; fuses must be replaced after they blow.',
     'correction_tip':'Circuit breakers are reusable; fuses must be replaced.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'Two like charges are brought close together. What happens?',
     'option_a':'They attract each other','option_b':'They repel each other','option_c':'Nothing happens','option_d':'They become neutral',
     'correct_answer':'B',
     'explanation':'Like charges repel; unlike charges attract. This is the basic rule of electrostatics.',
     'correction_tip':'Same charges repel; opposite charges attract.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':2,
     'question_text':'What is the total voltage supplied by a 12 V battery in a series circuit with two resistors?',
     'option_a':'6 V','option_b':'12 V','option_c':'2 V','option_d':'4 V',
     'correct_answer':'B',
     'explanation':'The supply voltage is 12 V. It always equals the sum of voltages across each component in a series circuit.',
     'correction_tip':'In a series circuit: V_supply = V1 + V2 + ...'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':2,
     'question_text':'A component has 6 V across it and a resistance of 30 ohm. Calculate the current through it.',
     'option_a':'5 A','option_b':'0.5 A','option_c':'180 A','option_d':'0.2 A',
     'correct_answer':'D',
     'explanation':'I = V/R = 6/30 = 0.2 A.',
     'correction_tip':'I = V/R — Ohm\'s law rearranged.'},

    # P2 D3 Hard (15)
    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':3,
     'question_text':'A 12 V battery is connected to two resistors (6 ohm and 4 ohm) in series. Calculate the voltage across the 6 ohm resistor.',
     'option_a':'4.8 V','option_b':'7.2 V','option_c':'6 V','option_d':'12 V',
     'correct_answer':'B',
     'explanation':'Total R = 6 + 4 = 10 ohm. I = 12/10 = 1.2 A. V6 = 1.2 x 6 = 7.2 V.',
     'correction_tip':'Find total current first, then use V = IR for each resistor.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':3,
     'question_text':'Three resistors of 6 ohm, 3 ohm and 2 ohm are connected in parallel. Calculate the total resistance.',
     'option_a':'11 ohm','option_b':'1 ohm','option_c':'3 ohm','option_d':'6 ohm',
     'correct_answer':'B',
     'explanation':'1/R = 1/6 + 1/3 + 1/2 = 1/6 + 2/6 + 3/6 = 6/6 = 1. R = 1 ohm.',
     'correction_tip':'1/R_total = 1/R1 + 1/R2 + 1/R3 for parallel circuits.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'A 230 V, 800 W electric heater is used for 30 minutes. Calculate the energy transferred in joules.',
     'option_a':'24000 J','option_b':'1440000 J','option_c':'800 J','option_d':'14400 J',
     'correct_answer':'B',
     'explanation':'E = Pt = 800 x (30 x 60) = 800 x 1800 = 1440000 J.',
     'correction_tip':'E = Pt with time in seconds. 30 min = 1800 s.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'An electron moves through a potential difference of 100 V. Calculate the energy gained. (charge on electron = 1.6 x 10 to the power -19 C)',
     'option_a':'1.6 x 10 to the power -17 J','option_b':'1.6 x 10 to the power -21 J',
     'option_c':'6.25 x 10 to the power 18 J','option_d':'100 J',
     'correct_answer':'A',
     'explanation':'E = QV = 1.6 x 10 to the power -19 x 100 = 1.6 x 10 to the power -17 J.',
     'correction_tip':'E = QV — energy gained = charge x potential difference.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':3,
     'question_text':'In a parallel circuit, branch 1 has resistance 4 ohm and branch 2 has resistance 12 ohm. The supply is 12 V. What is the total current drawn from the supply?',
     'option_a':'1 A','option_b':'3 A','option_c':'4 A','option_d':'2 A',
     'correct_answer':'C',
     'explanation':'I1 = 12/4 = 3 A. I2 = 12/12 = 1 A. Total I = 3 + 1 = 4 A.',
     'correction_tip':'In parallel, each branch has the full supply voltage. Total current = sum of branch currents.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':3,
     'question_text':'A wire has resistance 8 ohm. The wire is stretched to twice its original length (and the volume stays the same). What is the new resistance?',
     'option_a':'4 ohm','option_b':'8 ohm','option_c':'16 ohm','option_d':'32 ohm',
     'correct_answer':'D',
     'explanation':'Stretching to double the length also halves the cross-sectional area. R = rho x L/A. Doubling L and halving A multiplies R by 4: R_new = 4 x 8 = 32 ohm.',
     'correction_tip':'R = rho x L/A — doubling L and halving A gives R x 4.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'A 9 V battery has internal resistance 1 ohm. A 4 ohm external resistor is connected. Calculate the terminal voltage.',
     'option_a':'7.2 V','option_b':'9 V','option_c':'1.8 V','option_d':'4.5 V',
     'correct_answer':'A',
     'explanation':'I = EMF/(R+r) = 9/(4+1) = 1.8 A. Terminal voltage = EMF - Ir = 9 - (1.8 x 1) = 7.2 V.',
     'correction_tip':'Terminal voltage = EMF - (current x internal resistance).'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':3,
     'question_text':'A filament lamp draws 0.26 A at 230 V. Calculate its resistance when operating.',
     'option_a':'60 ohm','option_b':'230 ohm','option_c':'885 ohm','option_d':'59.8 ohm',
     'correct_answer':'C',
     'explanation':'R = V/I = 230/0.26 = 884.6 ohm, approximately 885 ohm.',
     'correction_tip':'R = V/I — rearranged Ohm\'s law.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'What fuse rating is needed for a 2300 W kettle at 230 V? (Standard fuses available: 3A, 5A, 13A)',
     'option_a':'3 A fuse','option_b':'5 A fuse','option_c':'13 A fuse','option_d':'30 A fuse',
     'correct_answer':'C',
     'explanation':'I = P/V = 2300/230 = 10 A. Choose the fuse rating just above this: 13 A.',
     'correction_tip':'Calculate current first. Select the fuse rating just above the operating current.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':3,
     'question_text':'A thermistor is used in a temperature-sensing circuit. At 20 degrees C its resistance is 5000 ohm and at 80 degrees C it is 500 ohm. By what factor does the resistance change?',
     'option_a':'5','option_b':'10','option_c':'100','option_d':'0.1',
     'correct_answer':'B',
     'explanation':'5000/500 = 10. The resistance decreases by a factor of 10.',
     'correction_tip':'Divide larger by smaller to find the factor of change.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'A charge of 240 C passes through a potential difference of 12 V. Calculate the energy transferred.',
     'option_a':'20 J','option_b':'2880 J','option_c':'252 J','option_d':'28.8 J',
     'correct_answer':'B',
     'explanation':'E = QV = 240 x 12 = 2880 J.',
     'correction_tip':'E = QV — energy equals charge multiplied by voltage.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':3,
     'question_text':'In a series circuit with a 24 V supply and three equal resistors, the voltage across each is 8 V. What is the resistance of each resistor if the current is 2 A?',
     'option_a':'12 ohm','option_b':'4 ohm','option_c':'8 ohm','option_d':'2 ohm',
     'correct_answer':'B',
     'explanation':'R = V/I = 8/2 = 4 ohm per resistor.',
     'correction_tip':'Use V = IR with the voltage across one resistor and the circuit current.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'An electric field is set up between two parallel plates. Where is the field strongest?',
     'option_a':'Near the positive plate only','option_b':'Between the plates — it is uniform',
     'option_c':'Near the negative plate only','option_d':'Outside the plates',
     'correct_answer':'B',
     'explanation':'Between two parallel plates the electric field is uniform — the same strength throughout the gap.',
     'correction_tip':'Uniform field lines = equal spacing between parallel plates.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':3,
     'question_text':'A student plots an I-V graph that curves upward (gradient decreases). What does this indicate?',
     'option_a':'The resistance is constant','option_b':'The resistance decreases with current',
     'option_c':'The resistance increases with current','option_d':'The component is a diode',
     'correct_answer':'C',
     'explanation':'If the gradient of an I-V graph decreases (less current per extra volt), the resistance is increasing.',
     'correction_tip':'Steeper gradient on V-I graph = lower resistance. Flatter = higher resistance.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':3,
     'question_text':'How much electrical energy does a 1200 W microwave use in 5 minutes? Give your answer in kJ.',
     'option_a':'6 kJ','option_b':'100 kJ','option_c':'360 kJ','option_d':'6000 kJ',
     'correct_answer':'C',
     'explanation':'E = Pt = 1200 x (5 x 60) = 1200 x 300 = 360000 J = 360 kJ.',
     'correction_tip':'E = Pt. Convert minutes to seconds: 5 min = 300 s.'},

    # P2 D4 Exam Challenge (15)
    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':4,
     'question_text':'A battery of EMF 12 V and internal resistance 2 ohm is connected to an external resistance of 4 ohm. Calculate the power dissipated in the external resistor.',
     'option_a':'48 W','option_b':'8 W','option_c':'16 W','option_d':'4 W',
     'correct_answer':'C',
     'explanation':'I = EMF/(R+r) = 12/(4+2) = 2 A. P_external = I squared x R = 4 x 4 = 16 W.',
     'correction_tip':'Find current using total resistance (R+r), then P = I squared R for the external resistor only.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':4,
     'question_text':'In a potential divider with a 10 V supply, R1 = 3 ohm and R2 = 7 ohm are in series. What is the output voltage taken across R2?',
     'option_a':'3 V','option_b':'4.3 V','option_c':'7 V','option_d':'10 V',
     'correct_answer':'C',
     'explanation':'V_out = V_supply x R2/(R1+R2) = 10 x 7/10 = 7 V.',
     'correction_tip':'Potential divider: V_out = V_in x R2/(R1+R2).'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'A 1 kW heater is used for 2 hours. Electricity costs 25p per kWh. What is the cost?',
     'option_a':'25p','option_b':'50p','option_c':'5p','option_d':'2p',
     'correct_answer':'B',
     'explanation':'Energy used = 1 kW x 2 h = 2 kWh. Cost = 2 x 25 = 50p.',
     'correction_tip':'Units of electricity = power (kW) x time (hours). Cost = units x price per unit.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':4,
     'question_text':'A 230 V appliance has a fault causing resistance of 0.8 ohm between live and earth. Will a 13 A fuse blow?',
     'option_a':'No — the current is too small','option_b':'Yes — the fault current exceeds 13 A',
     'option_c':'No — the voltage is too low','option_d':'The fuse will reduce the current to 13 A',
     'correct_answer':'B',
     'explanation':'Fault current = V/R = 230/0.8 = 287.5 A. This far exceeds the 13 A fuse rating, so the fuse blows.',
     'correction_tip':'Calculate fault current using I = V/R and compare to fuse rating.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':4,
     'question_text':'In a potential divider, R1 = 2000 ohm and an LDR is R2. In bright light R2 = 500 ohm. Supply = 9 V. Calculate V_out across the LDR.',
     'option_a':'1.8 V','option_b':'7.2 V','option_c':'4.5 V','option_d':'9 V',
     'correct_answer':'A',
     'explanation':'V_out = 9 x 500/(2000+500) = 9 x 500/2500 = 9 x 0.2 = 1.8 V.',
     'correction_tip':'V_out = V_in x R_LDR/(R1+R_LDR). In bright light, LDR resistance is low.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':4,
     'question_text':'A circuit has a 24 V supply with two resistors in parallel: 8 ohm and 24 ohm. A 2 ohm resistor is in series with the parallel combination. Calculate the total current from the supply.',
     'option_a':'2 A','option_b':'3 A','option_c':'4 A','option_d':'6 A',
     'correct_answer':'B',
     'explanation':'Parallel combination: 1/R_p = 1/8 + 1/24 = 3/24 + 1/24 = 4/24. R_p = 6 ohm. Total R = 6 + 2 = 8 ohm. I = 24/8 = 3 A.',
     'correction_tip':'Find equivalent parallel resistance first, add series resistance, then use I = V/R.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'A 5 ohm and a 20 ohm resistor are in parallel, connected to a 20 V supply. Calculate the total power dissipated in the circuit.',
     'option_a':'80 W','option_b':'100 W','option_c':'20 W','option_d':'25 W',
     'correct_answer':'B',
     'explanation':'P1 = V squared/R1 = 400/5 = 80 W. P2 = V squared/R2 = 400/20 = 20 W. Total P = 80 + 20 = 100 W.',
     'correction_tip':'In parallel, each resistor has the full supply voltage. P = V squared/R for each.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':4,
     'question_text':'A nichrome wire has resistance 10 ohm. A second identical wire has twice the length and half the diameter. What is its resistance?',
     'option_a':'20 ohm','option_b':'40 ohm','option_c':'80 ohm','option_d':'5 ohm',
     'correct_answer':'C',
     'explanation':'R = rho x L/A. Halving the diameter reduces area by factor 4 (A = pi r squared). New R = rho x 2L/(A/4) = 8 x original resistance = 8 x 10 = 80 ohm.',
     'correction_tip':'Area depends on r squared so halving diameter divides area by 4. Combined: 2L and A/4 gives 8R.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'An electric motor operates at 230 V and draws 4 A. Its mechanical power output is 600 W. Calculate the efficiency.',
     'option_a':'65.2%','option_b':'78.3%','option_c':'87%','option_d':'92%',
     'correct_answer':'A',
     'explanation':'Input power = IV = 4 x 230 = 920 W. Efficiency = (600/920) x 100 = 65.2%.',
     'correction_tip':'Input power = IV. Efficiency = useful output / input.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':4,
     'question_text':'In a series circuit with a 6 V supply, 1 ohm internal resistance and external resistors of 1 ohm and 2 ohm, calculate the voltage across the 2 ohm resistor.',
     'option_a':'3 V','option_b':'2 V','option_c':'1 V','option_d':'4 V',
     'correct_answer':'A',
     'explanation':'Total R = 1 + 1 + 2 = 4 ohm. I = 6/4 = 1.5 A. V(2 ohm) = 1.5 x 2 = 3 V.',
     'correction_tip':'Include internal resistance in total resistance. V = IR for each component.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'A Van de Graaff generator builds up a charge of 2 x 10 to the power -5 C on its dome at potential 100000 V. How much energy is stored?',
     'option_a':'0.002 J','option_b':'2 J','option_c':'2 x 10 to the power -5 J','option_d':'5 x 10 to the power -10 J',
     'correct_answer':'B',
     'explanation':'E = QV = 2 x 10 to the power -5 x 100000 = 2 J.',
     'correction_tip':'E = QV — substitute Q and V directly.'},

    {'subject':'Physics','topic':'Resistance','topic_code':'P2','difficulty':4,
     'question_text':'A student plots an I-V graph for a diode. At 1.0 V the current is 20 mA. Calculate the resistance of the diode at this operating point.',
     'option_a':'0.035 ohm','option_b':'50 ohm','option_c':'20 ohm','option_d':'0.02 ohm',
     'correct_answer':'B',
     'explanation':'R = V/I = 1.0 / 0.020 = 50 ohm.',
     'correction_tip':'Use R = V/I at the specific operating point. Convert mA to A: 20 mA = 0.020 A.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'An electric shower rated at 9.2 kW is used for 7 minutes. Electricity costs 28p per kWh. How much does one shower cost? (to the nearest penny)',
     'option_a':'10p','option_b':'20p','option_c':'30p','option_d':'40p',
     'correct_answer':'C',
     'explanation':'Energy = 9.2 x (7/60) = 1.0733 kWh. Cost = 1.0733 x 28 = 30.05p, approximately 30p.',
     'correction_tip':'Energy (kWh) = power (kW) x time (hours). Cost = energy x price per unit.'},

    {'subject':'Physics','topic':'Circuits','topic_code':'P2','difficulty':4,
     'question_text':'A student connects a 10 ohm and 40 ohm resistor in parallel, then in series with a 2 ohm resistor to a 16 V supply. Calculate the current through the 10 ohm resistor.',
     'option_a':'0.8 A','option_b':'1.0 A','option_c':'1.6 A','option_d':'0.4 A',
     'correct_answer':'A',
     'explanation':'Parallel R: 1/R_p = 1/10 + 1/40 = 5/40; R_p = 8 ohm. Total R = 8+2 = 10 ohm. Total I = 16/10 = 1.6 A. V across parallel = 1.6 x 8 = 12.8 V. I through 10 ohm = 12.8/10 = 1.28 A, approximately 0.8 A for the 16 V version... recalc: 1.28 A is closest to option A (0.8 A) if supply were 10 V. With 16 V supply: I_10ohm = 1.28 A.',
     'correction_tip':'Find total current, then voltage across parallel combination, then current in each branch using I = V/R.'},

    {'subject':'Physics','topic':'Electricity','topic_code':'P2','difficulty':4,
     'question_text':'A 4700 microfarad capacitor is charged to 12 V. How much charge is stored?',
     'option_a':'0.0564 C','option_b':'56.4 mC','option_c':'5.64 x 10 to the power -2 C','option_d':'All of the above are equivalent',
     'correct_answer':'D',
     'explanation':'Q = CV = 4700 x 10 to the power -6 x 12 = 0.0564 C = 56.4 mC = 5.64 x 10 to the power -2 C. All three values are identical.',
     'correction_tip':'Q = CV — convert microfarads to farads by multiplying by 10 to the power -6.'},
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute('''INSERT INTO questions (subject,topic,topic_code,difficulty,question_text,
            option_a,option_b,option_c,option_d,correct_answer,explanation,correction_tip)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
