import sqlite3, sys

QUESTIONS = [

    # ------------------------------------------------------------------ #
    # C5 – Energy Changes (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 1,
        'question_text': 'What is an exothermic reaction?',
        'option_a': 'A reaction that absorbs energy from the surroundings',
        'option_b': 'A reaction that releases energy to the surroundings',
        'option_c': 'A reaction that produces a gas',
        'option_d': 'A reaction that only occurs at high temperatures',
        'correct_answer': 'B',
        'explanation': 'Exothermic reactions transfer energy to the surroundings, causing the temperature of the surroundings to rise.',
        'correction_tip': 'Remember: EXothermic = energy EXits to the surroundings.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 1,
        'question_text': 'Which of the following is an endothermic process?',
        'option_a': 'Combustion of methane',
        'option_b': 'Neutralisation of an acid with an alkali',
        'option_c': 'Thermal decomposition of calcium carbonate',
        'option_d': 'Oxidation of iron (rusting)',
        'correct_answer': 'C',
        'explanation': 'Thermal decomposition requires continuous heat input to break down compounds, making it endothermic.',
        'correction_tip': 'Combustion, neutralisation and oxidation all release heat — they are exothermic.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 1,
        'question_text': 'On an energy level diagram for an exothermic reaction, where are the products relative to the reactants?',
        'option_a': 'At a higher energy level',
        'option_b': 'At the same energy level',
        'option_c': 'At a lower energy level',
        'option_d': 'There is no difference — energy level diagrams only apply to endothermic reactions',
        'correct_answer': 'C',
        'explanation': 'In an exothermic reaction the products have less energy than the reactants; the difference is the energy released to the surroundings.',
        'correction_tip': 'Think of it as energy "falling" out of the reaction — products end up lower on the diagram.',
    },

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 2,
        'question_text': 'What is activation energy?',
        'option_a': 'The total energy released by a reaction',
        'option_b': 'The minimum energy required to start a reaction',
        'option_c': 'The energy stored in chemical bonds',
        'option_d': 'The difference in energy between reactants and products',
        'correct_answer': 'B',
        'explanation': 'Activation energy is the minimum energy that reacting particles must have in order for a collision to result in a reaction.',
        'correction_tip': 'Activation energy is the "energy barrier" that must be overcome — it is shown as the hump on an energy level diagram.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 2,
        'question_text': 'In terms of bond breaking and bond making, why is combustion exothermic?',
        'option_a': 'More energy is released making bonds than is taken in breaking bonds',
        'option_b': 'More energy is taken in breaking bonds than is released making bonds',
        'option_c': 'Equal energy is absorbed and released, so the net change is zero',
        'option_d': 'Bond breaking releases energy while bond making absorbs energy',
        'correct_answer': 'A',
        'explanation': 'Bond breaking is endothermic and bond making is exothermic. When more energy is released forming new bonds than is absorbed breaking old ones, the overall reaction is exothermic.',
        'correction_tip': 'Breaking bonds always absorbs energy; making bonds always releases energy. The direction you remember them matters.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 2,
        'question_text': 'A hand warmer uses the reaction between iron powder and oxygen. What type of energy change is this, and why is it suitable for a hand warmer?',
        'option_a': 'Endothermic — it absorbs heat from the hand',
        'option_b': 'Exothermic — it releases heat, warming the surroundings',
        'option_c': 'Endothermic — it lowers the temperature',
        'option_d': 'Exothermic — it absorbs heat and stores it for later',
        'correct_answer': 'B',
        'explanation': 'The slow oxidation of iron is exothermic, releasing heat energy to the surroundings — exactly what is needed to warm a hand.',
        'correction_tip': 'Hand warmers get hot, so they must release energy — that is exothermic.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 3,
        'question_text': 'The bond energies for a reaction are: bonds broken = 2640 kJ/mol; bonds made = 3120 kJ/mol. What is the overall energy change, and is the reaction exothermic or endothermic?',
        'option_a': '−480 kJ/mol; exothermic',
        'option_b': '+480 kJ/mol; endothermic',
        'option_c': '−480 kJ/mol; endothermic',
        'option_d': '+480 kJ/mol; exothermic',
        'correct_answer': 'A',
        'explanation': 'Energy change = energy in − energy out = 2640 − 3120 = −480 kJ/mol. A negative value means energy is released, so the reaction is exothermic.',
        'correction_tip': 'Use: ΔH = energy to break bonds − energy released making bonds. Negative = exothermic.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 3,
        'question_text': 'A student adds ammonium nitrate to water in a beaker. The outside of the beaker feels cold. Which statement correctly explains this observation?',
        'option_a': 'The dissolving process is exothermic, releasing heat to the beaker',
        'option_b': 'The dissolving process is endothermic, absorbing heat from the beaker and surroundings',
        'option_c': 'The reaction produces a gas that cools the solution',
        'option_d': 'Water is always cold, so the beaker will feel cold regardless',
        'correct_answer': 'B',
        'explanation': 'Dissolving ammonium nitrate is endothermic — energy is absorbed from the surroundings (the beaker and its contents), causing the temperature to drop. This is the principle behind instant cold packs.',
        'correction_tip': 'If the beaker feels cold, the reaction is taking heat away from the surroundings — that is endothermic.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 4,
        'question_text': 'The energy level diagram for a reaction shows reactants at 400 kJ and products at 550 kJ. The activation energy is 250 kJ above the reactants. What is the activation energy for the reverse reaction?',
        'option_a': '250 kJ',
        'option_b': '100 kJ',
        'option_c': '400 kJ',
        'option_d': '150 kJ',
        'correct_answer': 'B',
        'explanation': 'The peak is at 400 + 250 = 650 kJ. The products are at 550 kJ. Activation energy for the reverse reaction = 650 − 550 = 100 kJ.',
        'correction_tip': 'The activation energy for the reverse reaction is measured from the products up to the peak, not from the reactants.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Energy changes',
        'difficulty': 4,
        'question_text': 'A catalyst is added to a reaction. Which row correctly describes the effect on the energy level diagram?',
        'option_a': 'Activation energy decreases; overall energy change (ΔH) decreases',
        'option_b': 'Activation energy decreases; overall energy change (ΔH) is unchanged',
        'option_c': 'Activation energy is unchanged; overall energy change (ΔH) decreases',
        'option_d': 'Both activation energy and overall energy change (ΔH) increase',
        'correct_answer': 'B',
        'explanation': 'A catalyst provides an alternative reaction pathway with a lower activation energy, but does not change the energy of the reactants or products, so ΔH remains the same.',
        'correction_tip': 'Catalysts lower the activation energy hump but leave the start and end energy levels — and therefore ΔH — unchanged.',
    },

    # ------------------------------------------------------------------ #
    # C6 – Rate & Extent of Chemical Change (5 extra medium/hard)
    # ------------------------------------------------------------------ #

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Rates',
        'difficulty': 2,
        'question_text': 'A student investigates the effect of surface area on reaction rate using marble chips and hydrochloric acid. Which change would most increase the rate of reaction?',
        'option_a': 'Using larger marble chips',
        'option_b': 'Lowering the temperature of the acid',
        'option_c': 'Powdering the marble chips',
        'option_d': 'Diluting the acid',
        'correct_answer': 'C',
        'explanation': 'Powdering the marble increases the surface area dramatically, allowing more acid particles to collide with the marble at any one time, increasing the rate.',
        'correction_tip': 'Increased surface area → more exposed particles → more frequent collisions → faster reaction.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Equilibrium',
        'difficulty': 2,
        'question_text': 'For a reversible reaction at equilibrium, what happens if the concentration of a reactant is suddenly increased?',
        'option_a': 'The rate of the reverse reaction increases to re-establish equilibrium',
        'option_b': 'The rate of the forward reaction increases, shifting equilibrium to produce more products',
        'option_c': 'The equilibrium constant Kc increases',
        'option_d': 'Nothing changes because the system is at equilibrium',
        'correct_answer': 'B',
        'explanation': 'Adding more reactant increases the forward reaction rate. The system shifts to the right (producing more products) until a new equilibrium is established.',
        'correction_tip': 'Le Chatelier\'s principle: the system opposes the change. More reactant → equilibrium shifts forward.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Haber process',
        'difficulty': 2,
        'question_text': 'In the Haber process (N₂ + 3H₂ ⇌ 2NH₃), why is a temperature of about 450 °C used rather than a much lower temperature?',
        'option_a': 'Lower temperatures would give a higher yield but an unacceptably slow rate',
        'option_b': 'Higher temperatures give a higher yield and a faster rate',
        'option_c': '450 °C is the temperature at which the catalyst stops working',
        'option_d': 'Lower temperatures favour the endothermic direction of the reaction',
        'correct_answer': 'A',
        'explanation': 'The forward reaction is exothermic, so lower temperatures favour a higher yield. However, the rate would be too slow to be economical; 450 °C is a compromise between yield and rate.',
        'correction_tip': 'In the Haber process, temperature is a compromise: high enough for an acceptable rate, low enough for a reasonable yield.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Collision theory',
        'difficulty': 3,
        'question_text': 'Using collision theory, explain why increasing pressure increases the rate of a gas-phase reaction.',
        'option_a': 'Higher pressure increases the energy of each individual particle',
        'option_b': 'Higher pressure forces particles closer together, increasing the frequency of collisions',
        'option_c': 'Higher pressure lowers the activation energy',
        'option_d': 'Higher pressure increases the temperature of the gas',
        'correct_answer': 'B',
        'explanation': 'Increasing pressure compresses the gas, increasing particle concentration. Particles are closer together and collide more frequently, increasing the reaction rate.',
        'correction_tip': 'Pressure affects concentration in gases. More collisions per second → faster reaction rate.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Equilibrium',
        'difficulty': 3,
        'question_text': 'For the reaction: 2SO₂(g) + O₂(g) ⇌ 2SO₃(g)  ΔH = −196 kJ/mol\nWhat conditions of temperature and pressure would give the highest equilibrium yield of SO₃?',
        'option_a': 'High temperature, high pressure',
        'option_b': 'Low temperature, high pressure',
        'option_c': 'High temperature, low pressure',
        'option_d': 'Low temperature, low pressure',
        'correct_answer': 'B',
        'explanation': 'The forward reaction is exothermic, so low temperature shifts equilibrium to the right. There are 3 moles of gas on the left and 2 on the right, so high pressure also shifts equilibrium to the right (fewer moles of gas).',
        'correction_tip': 'For exothermic reactions: low T → higher yield. More moles of gas on left → high pressure favours the right (fewer moles side).',
    },

    # ------------------------------------------------------------------ #
    # C7 – Organic Chemistry (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 1,
        'question_text': 'What is crude oil?',
        'option_a': 'A mixture of different alkanes formed from the remains of ancient marine organisms',
        'option_b': 'Pure methane extracted from underground reservoirs',
        'option_c': 'A synthetic fuel made by combining hydrogen and carbon monoxide',
        'option_d': 'Refined petroleum that has had impurities removed',
        'correct_answer': 'A',
        'explanation': 'Crude oil is a fossil fuel — a mixture of hydrocarbons (mainly alkanes) formed over millions of years from the remains of ancient marine organisms.',
        'correction_tip': 'Crude oil is a MIXTURE of hydrocarbons, not a pure substance. It must be separated by fractional distillation.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Hydrocarbons',
        'difficulty': 1,
        'question_text': 'What is the general formula for alkanes?',
        'option_a': 'CₙH₂ₙ',
        'option_b': 'CₙH₂ₙ₊₂',
        'option_c': 'CₙH₂ₙ₋₂',
        'option_d': 'CₙHₙ',
        'correct_answer': 'B',
        'explanation': 'Alkanes are saturated hydrocarbons with the general formula CₙH₂ₙ₊₂. For example, methane (CH₄) has n=1: 2(1)+2=4 hydrogen atoms.',
        'correction_tip': 'Alkenes have the formula CₙH₂ₙ (one double bond removes two H atoms compared to alkanes).',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 1,
        'question_text': 'What functional group is present in carboxylic acids?',
        'option_a': '–OH',
        'option_b': '–COOH',
        'option_c': '–CHO',
        'option_d': '–COO–',
        'correct_answer': 'B',
        'explanation': 'Carboxylic acids contain the –COOH (carboxyl) functional group. Ethanoic acid (CH₃COOH) is a familiar example.',
        'correction_tip': '–OH alone is the alcohol group. The carboxylic acid group is –COOH (carbonyl + hydroxyl combined).',
    },

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Hydrocarbons',
        'difficulty': 2,
        'question_text': 'Why is cracking of long-chain hydrocarbons carried out in the oil industry?',
        'option_a': 'To increase the boiling point of fractions for use as fuels',
        'option_b': 'To convert saturated hydrocarbons into shorter, more useful fractions including alkenes',
        'option_c': 'To remove sulfur impurities from crude oil',
        'option_d': 'To combine short-chain molecules into longer polymers',
        'correct_answer': 'B',
        'explanation': 'Cracking breaks long, less useful alkanes into shorter alkanes suitable for fuels and alkenes that can be used in making polymers.',
        'correction_tip': 'Cracking = breaking big molecules into smaller, more useful ones. It produces alkenes as well as alkanes.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Alkenes',
        'difficulty': 2,
        'question_text': 'Which reagent is used to test for the presence of a C=C double bond in an alkene?',
        'option_a': 'Limewater',
        'option_b': 'Acidified potassium manganate(VII)',
        'option_c': 'Bromine water',
        'option_d': 'Universal indicator',
        'correct_answer': 'C',
        'explanation': 'Bromine water is decolourised (from orange/brown to colourless) when shaken with an alkene because the bromine adds across the C=C double bond.',
        'correction_tip': 'Bromine water stays orange-brown with alkanes (no double bond) but is decolourised by alkenes.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 2,
        'question_text': 'Ethanol reacts with ethanoic acid in the presence of an acid catalyst. What type of reaction is this, and what is the organic product?',
        'option_a': 'Neutralisation; ethanoate salt',
        'option_b': 'Esterification; ethyl ethanoate',
        'option_c': 'Addition; diethyl ether',
        'option_d': 'Combustion; carbon dioxide and water',
        'correct_answer': 'B',
        'explanation': 'Alcohol + carboxylic acid → ester + water. Ethanol + ethanoic acid → ethyl ethanoate + water. This is esterification.',
        'correction_tip': 'Esters are named: alkyl (from alcohol) + anoate (from acid). Ethanol + ethanoic acid = ethyl ethanoate.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 3,
        'question_text': 'Explain the difference between addition polymerisation and condensation polymerisation.',
        'option_a': 'Addition polymerisation uses monomers with double bonds and produces no by-products; condensation polymerisation joins monomers with two different functional groups and releases a small molecule (e.g. water)',
        'option_b': 'Addition polymerisation always produces nylon; condensation polymerisation always produces poly(ethene)',
        'option_c': 'Both processes are identical — the terms are used interchangeably',
        'option_d': 'Addition polymerisation requires a catalyst; condensation polymerisation does not',
        'correct_answer': 'A',
        'explanation': 'In addition polymerisation, alkene monomers join via their C=C double bonds with no by-products. Condensation polymerisation joins monomers through functional groups (e.g. –OH and –COOH) and releases water.',
        'correction_tip': 'Key clue: condensation polymerisation always releases a small molecule (water or HCl). Addition polymerisation does not.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 3,
        'question_text': 'Compare biofuels with fossil fuels in terms of carbon neutrality and reliability of supply.',
        'option_a': 'Biofuels are carbon neutral and have a completely reliable supply; fossil fuels are not carbon neutral but are unreliable',
        'option_b': 'Biofuels are considered approximately carbon neutral because CO₂ released on combustion was recently absorbed during growth; fossil fuels add CO₂ that was locked away for millions of years and have a finite supply',
        'option_c': 'Fossil fuels are carbon neutral because carbon is recycled; biofuels release more CO₂ than they absorb',
        'option_d': 'There is no difference in carbon output between biofuels and fossil fuels',
        'correct_answer': 'B',
        'explanation': 'Biofuels are approximately carbon neutral — the CO₂ released was recently removed from the atmosphere as the crop grew. Fossil fuels release CO₂ sequestered millions of years ago, increasing atmospheric CO₂.',
        'correction_tip': 'Biofuels are not perfectly carbon neutral (farming machinery uses fossil fuels) but are far better than fossil fuels in terms of net CO₂.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Chemistry',
        'topic': 'Hydrocarbons',
        'difficulty': 4,
        'question_text': 'Propene (C₃H₆) undergoes addition polymerisation. Which structure correctly represents the repeating unit of the polymer formed?',
        'option_a': '–[CH₂–CH₂]ₙ–',
        'option_b': '–[CH₂–CH(CH₃)]ₙ–',
        'option_c': '–[CH(CH₃)–CH(CH₃)]ₙ–',
        'option_d': '–[CH₂–C(CH₃)₂]ₙ–',
        'correct_answer': 'B',
        'explanation': 'When propene (CH₂=CHCH₃) polymerises, the double bond opens. Each repeating unit is –[CH₂–CH(CH₃)]– (polypropene).',
        'correction_tip': 'Draw the monomer, open the double bond, and the two carbons of the former double bond become the backbone of the repeating unit.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Organic chemistry',
        'difficulty': 4,
        'question_text': 'A student says: "Fractional distillation separates crude oil because different fractions have different boiling points, which depend on the size of their molecules." Evaluate this statement.',
        'option_a': 'Incorrect — distillation separates based on colour, not boiling point',
        'option_b': 'Correct — larger molecules have stronger London dispersion forces, raising their boiling point, so they condense at higher temperatures in the column',
        'option_c': 'Partially correct — boiling points differ but they do not depend on molecular size',
        'option_d': 'Incorrect — crude oil fractions all have the same boiling point; they differ only in viscosity',
        'correct_answer': 'B',
        'explanation': 'The student is correct. Larger hydrocarbon molecules have more electrons and stronger London dispersion (intermolecular) forces, requiring more energy to overcome, so they have higher boiling points and condense lower down the column.',
        'correction_tip': 'Boiling point increases with chain length because longer chains have more surface area for London dispersion forces.',
    },

    # ------------------------------------------------------------------ #
    # C8 – Chemical Analysis (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Chemistry',
        'topic': 'Flame tests',
        'difficulty': 1,
        'question_text': 'What colour flame is produced by a sodium compound in a flame test?',
        'option_a': 'Lilac',
        'option_b': 'Green',
        'option_c': 'Yellow/orange',
        'option_d': 'Brick red',
        'correct_answer': 'C',
        'explanation': 'Sodium compounds produce a distinctive yellow/orange flame. This is commonly seen in sodium street lamps.',
        'correction_tip': 'Sodium = yellow/orange; Potassium = lilac; Copper = green; Calcium = brick red/orange-red.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 1,
        'question_text': 'Which test is used to identify the presence of carbon dioxide gas?',
        'option_a': 'Bubble the gas through bromine water — it turns colourless',
        'option_b': 'Bubble the gas through limewater — it turns cloudy/milky',
        'option_c': 'Hold a burning splint to the gas — it extinguishes with a squeaky pop',
        'option_d': 'Hold a glowing splint to the gas — it relights',
        'correct_answer': 'B',
        'explanation': 'CO₂ reacts with calcium hydroxide (limewater) to form calcium carbonate, a white precipitate that turns the solution cloudy.',
        'correction_tip': 'Limewater goes cloudy with CO₂. Squeaky pop = hydrogen; relights glowing splint = oxygen.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 1,
        'question_text': 'How can you tell whether a substance is a pure compound or a mixture based on its melting point?',
        'option_a': 'A pure substance has a sharp, precise melting point; a mixture melts over a range of temperatures',
        'option_b': 'A mixture has a higher melting point than a pure substance',
        'option_c': 'A pure substance melts more slowly than a mixture',
        'option_d': 'You cannot distinguish a pure substance from a mixture using melting point',
        'correct_answer': 'A',
        'explanation': 'A pure substance has a single, sharp melting point. A mixture melts over a range of temperatures because the different components melt at different temperatures.',
        'correction_tip': 'Sharp, single melting point = pure. Melting over a range = mixture (or impure substance).',
    },

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 2,
        'question_text': 'A student runs a paper chromatography experiment. The solvent front travels 9.0 cm and a spot travels 6.3 cm. What is the Rf value of this substance?',
        'option_a': '1.43',
        'option_b': '0.70',
        'option_c': '0.63',
        'option_d': '2.70',
        'correct_answer': 'B',
        'explanation': 'Rf = distance moved by spot ÷ distance moved by solvent front = 6.3 ÷ 9.0 = 0.70.',
        'correction_tip': 'Rf is always between 0 and 1. If your answer is greater than 1, you have divided the wrong way round.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 2,
        'question_text': 'Which reagent is used to test for sulfate ions (SO₄²⁻) in solution, and what is the positive result?',
        'option_a': 'Silver nitrate solution — cream precipitate',
        'option_b': 'Barium chloride solution — white precipitate',
        'option_c': 'Sodium hydroxide solution — blue precipitate',
        'option_d': 'Hydrochloric acid — effervescence',
        'correct_answer': 'B',
        'explanation': 'Adding acidified barium chloride solution to a sulfate produces barium sulfate, a white precipitate that is insoluble in acid.',
        'correction_tip': 'Ba²⁺ + SO₄²⁻ → BaSO₄ (white precipitate). AgNO₃ is for halides, not sulfates.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Flame tests',
        'difficulty': 2,
        'question_text': 'A student performs a flame test on an unknown compound and observes a green flame. Which ion is most likely present?',
        'option_a': 'Na⁺',
        'option_b': 'K⁺',
        'option_c': 'Cu²⁺',
        'option_d': 'Ca²⁺',
        'correct_answer': 'C',
        'explanation': 'Copper compounds produce a distinctive green flame. Sodium gives yellow/orange, potassium gives lilac, and calcium gives brick red/orange-red.',
        'correction_tip': 'Green flame = copper. This is easy to remember — copper salts in fireworks produce green colours.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 3,
        'question_text': 'A solution is tested with dilute HCl (no reaction), then with acidified silver nitrate and a cream precipitate forms. Which halide ion does this indicate, and write the ionic equation for the precipitation.',
        'option_a': 'Cl⁻; Ag⁺(aq) + Cl⁻(aq) → AgCl(s)',
        'option_b': 'Br⁻; Ag⁺(aq) + Br⁻(aq) → AgBr(s)',
        'option_c': 'I⁻; Ag⁺(aq) + I⁻(aq) → AgI(s)',
        'option_d': 'F⁻; Ag⁺(aq) + F⁻(aq) → AgF(s)',
        'correct_answer': 'B',
        'explanation': 'AgCl is white, AgBr is cream, and AgI is pale yellow. A cream precipitate indicates bromide ions. The ionic equation is Ag⁺(aq) + Br⁻(aq) → AgBr(s).',
        'correction_tip': 'Remember: white = chloride, cream = bromide, pale yellow = iodide. Go through the colours in order as you go down Group 7.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 3,
        'question_text': 'In a chromatography experiment, two substances (X and Y) have the same Rf value. What can you conclude?',
        'option_a': 'X and Y are definitely the same substance',
        'option_b': 'X and Y may be the same substance, but further testing would be needed to confirm',
        'option_c': 'X and Y are definitely different substances',
        'option_d': 'The experiment is invalid because two substances should never have the same Rf value',
        'correct_answer': 'B',
        'explanation': 'The same Rf value suggests the substances may be identical, but different substances can coincidentally have the same Rf. Further tests (e.g., different solvent, mass spectrometry) would be needed to confirm.',
        'correction_tip': 'Chromatography gives evidence but not proof of identity. Two spots at the same Rf could be different compounds.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 4,
        'question_text': 'A student tests an unknown white powder. It dissolves in water, gives a yellow/orange flame test, produces a white precipitate with BaCl₂ solution, and no precipitate with AgNO₃ solution. What is the most likely identity of the compound?',
        'option_a': 'Sodium chloride (NaCl)',
        'option_b': 'Sodium sulfate (Na₂SO₄)',
        'option_c': 'Calcium carbonate (CaCO₃)',
        'option_d': 'Potassium bromide (KBr)',
        'correct_answer': 'B',
        'explanation': 'Yellow/orange flame → Na⁺ present. White precipitate with BaCl₂ → SO₄²⁻ present. No precipitate with AgNO₃ → no halide. Together, these indicate sodium sulfate (Na₂SO₄).',
        'correction_tip': 'Build up the identity step by step: flame test gives the cation, precipitation tests give the anion.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Chemical analysis',
        'difficulty': 4,
        'question_text': 'Gas X bleaches damp red litmus paper. Gas Y produces a squeaky pop with a lighted splint. Gas Z relights a glowing splint. Identify gases X, Y, and Z.',
        'option_a': 'X = CO₂, Y = O₂, Z = H₂',
        'option_b': 'X = Cl₂, Y = H₂, Z = O₂',
        'option_c': 'X = SO₂, Y = H₂, Z = O₂',
        'option_d': 'X = Cl₂, Y = O₂, Z = H₂',
        'correct_answer': 'B',
        'explanation': 'Chlorine bleaches damp litmus (X = Cl₂). Hydrogen burns with a squeaky pop (Y = H₂). Oxygen relights a glowing splint (Z = O₂).',
        'correction_tip': 'Learn the four gas tests: H₂ = squeaky pop; O₂ = relights glowing splint; CO₂ = limewater cloudy; Cl₂ = bleaches litmus.',
    },

    # ------------------------------------------------------------------ #
    # C9 – Chemistry of the Atmosphere (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 1,
        'question_text': 'Approximately what percentage of the current atmosphere is nitrogen?',
        'option_a': '21%',
        'option_b': '50%',
        'option_c': '78%',
        'option_d': '0.04%',
        'correct_answer': 'C',
        'explanation': 'The current atmosphere is approximately 78% nitrogen, 21% oxygen, 1% argon, and 0.04% carbon dioxide.',
        'correction_tip': 'A useful mnemonic: 78% N₂, 21% O₂ — the remaining ~1% is mostly argon.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 1,
        'question_text': 'What was the main gas in Earth\'s early atmosphere?',
        'option_a': 'Nitrogen',
        'option_b': 'Oxygen',
        'option_c': 'Carbon dioxide',
        'option_d': 'Methane',
        'correct_answer': 'C',
        'explanation': 'Earth\'s early atmosphere was produced mainly by volcanic activity and was composed primarily of carbon dioxide and water vapour, with little or no oxygen.',
        'correction_tip': 'Early Earth had lots of CO₂ from volcanoes — similar to the atmospheres of Mars and Venus today.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Climate change',
        'difficulty': 1,
        'question_text': 'Which of the following is a greenhouse gas?',
        'option_a': 'Nitrogen',
        'option_b': 'Oxygen',
        'option_c': 'Methane',
        'option_d': 'Argon',
        'correct_answer': 'C',
        'explanation': 'Methane (CH₄), along with carbon dioxide and water vapour, is a greenhouse gas. It absorbs and re-emits infrared radiation, contributing to the greenhouse effect.',
        'correction_tip': 'The main greenhouse gases are CO₂, CH₄ (methane), and H₂O (water vapour). N₂, O₂ and Ar are not greenhouse gases.',
    },

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 2,
        'question_text': 'How did photosynthesis change the composition of Earth\'s early atmosphere?',
        'option_a': 'It increased the amount of CO₂ and decreased the amount of O₂',
        'option_b': 'It decreased CO₂ levels and increased O₂ levels',
        'option_c': 'It removed nitrogen from the atmosphere',
        'option_d': 'It had no effect on atmospheric composition',
        'correct_answer': 'B',
        'explanation': 'Early plants and algae used photosynthesis to absorb CO₂ and release O₂, gradually reducing CO₂ and building up the oxygen levels in the atmosphere over billions of years.',
        'correction_tip': 'Photosynthesis: CO₂ + H₂O → glucose + O₂. So it uses CO₂ and releases O₂ — the opposite of respiration.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Climate change',
        'difficulty': 2,
        'question_text': 'How do greenhouse gases cause global warming?',
        'option_a': 'They reflect incoming solar radiation back into space',
        'option_b': 'They absorb infrared radiation emitted by Earth\'s surface and re-emit it in all directions, reducing heat loss to space',
        'option_c': 'They react with oxygen to produce heat energy',
        'option_d': 'They block ultraviolet radiation from the Sun',
        'correct_answer': 'B',
        'explanation': 'Greenhouse gases absorb infrared (heat) radiation emitted by the Earth and re-radiate it, including back towards Earth\'s surface. This reduces the amount of heat escaping into space, raising the planet\'s temperature.',
        'correction_tip': 'Greenhouse gases trap outgoing infrared radiation, not incoming visible light. Think of them as a thermal blanket around Earth.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 2,
        'question_text': 'Carbon monoxide (CO) is a pollutant produced by incomplete combustion. Why is it harmful?',
        'option_a': 'It reacts with water in the lungs to form carbonic acid',
        'option_b': 'It is toxic because it binds to haemoglobin, preventing it from carrying oxygen',
        'option_c': 'It causes acid rain by dissolving in rainwater',
        'option_d': 'It depletes the ozone layer',
        'correct_answer': 'B',
        'explanation': 'CO binds irreversibly to haemoglobin (forming carboxyhaemoglobin), preventing red blood cells from transporting oxygen, which can be fatal at high concentrations.',
        'correction_tip': 'CO is dangerous because it is colourless and odourless, and prevents oxygen transport in blood. SO₂ causes acid rain, not CO.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 3,
        'question_text': 'Explain how the formation of oceans helped reduce CO₂ in Earth\'s early atmosphere.',
        'option_a': 'Oceans reflected sunlight, cooling the atmosphere and causing CO₂ to solidify',
        'option_b': 'CO₂ dissolved in the oceans and reacted to form carbonate compounds and carbonate rocks, locking carbon away',
        'option_c': 'Water vapour in the oceans reacted directly with CO₂ to form methane',
        'option_d': 'Oceans absorbed nitrogen, creating space for CO₂ to expand into and diluting its concentration',
        'correct_answer': 'B',
        'explanation': 'As Earth cooled, water vapour condensed to form oceans. CO₂ dissolved in the oceans and reacted with dissolved minerals to form carbonate rocks (e.g. limestone), removing CO₂ from the atmosphere.',
        'correction_tip': 'Two routes removed CO₂: (1) dissolving in oceans → carbonate rocks, and (2) photosynthesis by early plants.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Climate change',
        'difficulty': 3,
        'question_text': 'Describe two environmental consequences of increased levels of greenhouse gases.',
        'option_a': 'Increased rainfall worldwide and thicker polar ice caps',
        'option_b': 'Global temperature rise leading to melting polar ice/rising sea levels, and more extreme weather events (e.g. storms, droughts)',
        'option_c': 'Depletion of the ozone layer and increased ultraviolet radiation',
        'option_d': 'Decreased biodiversity due to higher oxygen levels',
        'correct_answer': 'B',
        'explanation': 'Enhanced greenhouse effect raises global temperatures, causing polar ice to melt (raising sea levels, threatening coastal areas) and increasing the frequency and severity of extreme weather events.',
        'correction_tip': 'Keep ozone depletion separate — that is caused by CFCs, not by CO₂/CH₄. Focus on temperature rise and its knock-on effects.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Chemistry',
        'topic': 'Climate change',
        'difficulty': 4,
        'question_text': 'A scientist argues that although carbon capture and storage (CCS) can reduce CO₂ emissions, it does not address the root cause of climate change. Evaluate this argument.',
        'option_a': 'The argument is wrong — CCS permanently removes CO₂ so it completely solves climate change',
        'option_b': 'The argument is valid — CCS captures CO₂ after combustion but does not reduce dependence on fossil fuels; a more sustainable solution would be switching to renewable energy sources',
        'option_c': 'The argument is wrong — CCS is not a real technology and cannot capture any CO₂',
        'option_d': 'The argument is valid — CCS only works for methane, not CO₂',
        'correct_answer': 'B',
        'explanation': 'CCS is a mitigation strategy that captures CO₂ produced by burning fossil fuels. However, it still requires burning fossil fuels and depends on permanent, safe storage. Reducing fossil fuel use is more fundamental.',
        'correction_tip': 'Evaluate questions expect you to give a balanced view: CCS is helpful but does not solve the fundamental problem of burning fossil fuels.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Atmosphere',
        'difficulty': 4,
        'question_text': 'Nitrogen oxides (NOₓ) are produced in car engines. Explain the conditions that cause their formation and describe two harmful effects.',
        'option_a': 'Formed when nitrogen reacts with fuel at low temperatures; they cause corrosion of engine parts and depletion of the ozone layer',
        'option_b': 'Formed when N₂ and O₂ react at the very high temperatures inside engines; they contribute to acid rain and photochemical smog',
        'option_c': 'Formed only from incomplete combustion of petrol; they are the main cause of global warming',
        'option_d': 'Formed when nitrogen reacts with water in the fuel; they only affect health, not the environment',
        'correct_answer': 'B',
        'explanation': 'At the very high temperatures inside car engines, atmospheric N₂ and O₂ react to form NOₓ. These gases dissolve in rain to form acid rain (damaging ecosystems and buildings) and react in sunlight to form photochemical smog (harming respiratory health).',
        'correction_tip': 'NOₓ is different from CO. NOₓ → acid rain + smog; CO → binds to haemoglobin; SO₂ → acid rain from sulfur in fuels.',
    },

    # ------------------------------------------------------------------ #
    # C10 – Using Resources (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Chemistry',
        'topic': 'Using resources',
        'difficulty': 1,
        'question_text': 'What conditions are required for iron to rust?',
        'option_a': 'Water only',
        'option_b': 'Oxygen only',
        'option_c': 'Both water AND oxygen',
        'option_d': 'Carbon dioxide and water',
        'correct_answer': 'C',
        'explanation': 'Rusting is the corrosion of iron. It requires both water and oxygen to be present — neither alone is sufficient to cause rusting.',
        'correction_tip': 'Classic experiment: iron in dry air does not rust; iron in water with no air does not rust; iron in water and air rusts.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Water treatment',
        'difficulty': 1,
        'question_text': 'Which two processes are used to make drinking water (potable water) from fresh water sources?',
        'option_a': 'Electrolysis and distillation',
        'option_b': 'Filtration and chlorination',
        'option_c': 'Precipitation and crystallisation',
        'option_d': 'Reverse osmosis and evaporation',
        'correct_answer': 'B',
        'explanation': 'Fresh water is filtered to remove solids and then chlorinated (treated with chlorine) to kill pathogens, making it safe to drink.',
        'correction_tip': 'Filtration removes particles; chlorination kills microorganisms. Both steps are needed for potable water from rivers/lakes.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Using resources',
        'difficulty': 1,
        'question_text': 'What is the main advantage of recycling metals such as aluminium?',
        'option_a': 'Recycled metals are stronger than newly extracted metals',
        'option_b': 'Recycling uses much less energy than extracting metal from its ore, and conserves finite resources',
        'option_c': 'Recycled metals are purer than metals extracted from ores',
        'option_d': 'Recycling produces useful by-products such as oxygen',
        'correct_answer': 'B',
        'explanation': 'Extracting aluminium from bauxite by electrolysis requires enormous amounts of energy. Recycling aluminium uses about 95% less energy and reduces the need to mine finite ore deposits.',
        'correction_tip': 'Two key benefits of recycling: saves energy AND conserves finite (non-renewable) resources.',
    },

    # Medium (3)
    {
        'subject': 'Chemistry',
        'topic': 'Corrosion',
        'difficulty': 2,
        'question_text': 'Steel girders are often galvanised to prevent rusting. What does galvanising involve and how does it protect the steel?',
        'option_a': 'Coating the steel with aluminium, which is less reactive and acts as a barrier',
        'option_b': 'Coating the steel with zinc, which acts as a barrier and also provides sacrificial protection',
        'option_c': 'Painting the steel with iron oxide to create a protective layer',
        'option_d': 'Treating the steel with an electrical current to harden the surface',
        'correct_answer': 'B',
        'explanation': 'Galvanising coats steel with zinc. Zinc is more reactive than iron, so it oxidises preferentially (sacrificial protection) even if the coating is scratched, preventing the iron beneath from rusting.',
        'correction_tip': 'Zinc protects steel in two ways: (1) physical barrier and (2) sacrificial anode. Even scratched galvanised steel stays rust-free.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Life cycle assessment',
        'difficulty': 2,
        'question_text': 'What is a life cycle assessment (LCA)?',
        'option_a': 'A calculation of how long a product will last before breaking',
        'option_b': 'An assessment of the environmental impact of a product at every stage — from raw material extraction through to disposal',
        'option_c': 'A financial analysis of the cost of producing a product',
        'option_d': 'A test to determine how toxic a material is',
        'correct_answer': 'B',
        'explanation': 'An LCA evaluates the environmental impact of a product across its whole life: extraction of raw materials, manufacturing, use, and final disposal/recycling.',
        'correction_tip': 'LCA = "cradle to grave". It covers extraction → manufacturing → use → disposal.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Using resources',
        'difficulty': 2,
        'question_text': 'Why are alloys generally harder and stronger than pure metals?',
        'option_a': 'Alloys contain more electrons, increasing their conductivity and strength',
        'option_b': 'Atoms of different sizes in an alloy disrupt the regular layers, making it harder for layers to slide over each other',
        'option_c': 'Alloying removes impurities from the metal, making it purer and therefore stronger',
        'option_d': 'Alloys are heated during production, which changes their crystal structure permanently',
        'correct_answer': 'B',
        'explanation': 'In a pure metal, atoms are the same size and layers can slide easily. Mixing in atoms of a different size distorts the lattice, preventing layers from sliding and making the alloy harder.',
        'correction_tip': 'Alloys are harder because different-sized atoms disrupt regular layers. This is why pure gold (24 carat) is too soft for jewellery.',
    },

    # Hard (2)
    {
        'subject': 'Chemistry',
        'topic': 'Water treatment',
        'difficulty': 3,
        'question_text': 'Explain why desalination by distillation is not widely used in countries with large freshwater reserves.',
        'option_a': 'Distillation of seawater produces toxic by-products',
        'option_b': 'Distillation requires very large amounts of energy, making it expensive and impractical when cheaper freshwater sources are available',
        'option_c': 'Distillation cannot remove salt from seawater',
        'option_d': 'Distilled water lacks essential minerals and is unsafe to drink',
        'correct_answer': 'B',
        'explanation': 'Distillation of seawater requires heating vast quantities of water, consuming huge amounts of energy. It is only cost-effective in regions where freshwater is extremely scarce and energy is cheap.',
        'correction_tip': 'Desalination works but is energy-intensive and expensive. It is mainly used in arid regions (e.g., Middle East) or on ships.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Life cycle assessment',
        'difficulty': 3,
        'question_text': 'A manufacturer compares two carrier bags: a plastic bag and a cotton bag. The LCA shows the cotton bag has a higher carbon footprint in production. What additional factors should be considered before concluding which is more sustainable?',
        'option_a': 'Only production energy matters in an LCA',
        'option_b': 'The number of times each bag is reused and how it is disposed of must also be considered — a cotton bag reused many times may have a lower overall impact',
        'option_c': 'The colour of the bag affects its environmental impact',
        'option_d': 'LCA data is always objective and no other factors need to be considered',
        'correct_answer': 'B',
        'explanation': 'LCA must consider the entire lifespan. A cotton bag has high production impact but can be reused hundreds of times, spreading that impact. End-of-life (biodegradable vs landfill) is also important.',
        'correction_tip': 'LCA can be selective — some data may be chosen to favour one product. Always check all stages and consider reusability.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Chemistry',
        'topic': 'Using resources',
        'difficulty': 4,
        'question_text': 'Phytomining is used to extract copper from low-grade ores. Describe the process and explain one advantage and one disadvantage compared with traditional mining.',
        'option_a': 'Plants are grown in copper-rich soil; the plants are harvested and burned to produce an ash rich in copper compounds. Advantage: less energy than smelting. Disadvantage: slow process.',
        'option_b': 'Bacteria dissolve copper from ores producing a leachate; copper is extracted by electrolysis. Advantage: no large waste heaps. Disadvantage: produces toxic leachate.',
        'option_c': 'Copper is extracted directly from seawater using ion exchange resins. Advantage: infinite supply. Disadvantage: too dilute to be commercial.',
        'option_d': 'Copper is synthesised chemically from carbon and sulfur. Advantage: no mining needed. Disadvantage: requires rare catalysts.',
        'correct_answer': 'A',
        'explanation': 'Phytomining uses plants (hyperaccumulators) that absorb copper through their roots. The plants are harvested, dried, and burned; the resulting ash (bio-ore) is processed to extract copper. It works on low-grade ores unsuitable for traditional mining, but is slow and produces lower yields.',
        'correction_tip': 'Phytomining = plants extract metal. Bioleaching = bacteria extract metal. Both are for low-grade ores where traditional mining is uneconomical.',
    },
    {
        'subject': 'Chemistry',
        'topic': 'Using resources',
        'difficulty': 4,
        'question_text': 'A student states: "All finite resources will eventually run out, so scientists should focus entirely on finding replacements rather than recycling." Evaluate this argument.',
        'option_a': 'The argument is fully correct — recycling is a waste of resources that should be spent on finding alternatives',
        'option_b': 'The argument is partially valid but incomplete: recycling extends the lifetime of finite resources, reduces energy use, and reduces environmental damage, buying time for sustainable alternatives to be developed',
        'option_c': 'The argument is wrong because finite resources never actually run out',
        'option_d': 'The argument is wrong because replacements for metals cannot be found',
        'correct_answer': 'B',
        'explanation': 'Recycling and developing replacements are complementary, not competing, strategies. Recycling conserves finite resources and reduces environmental impact, extending the period over which alternatives can be developed and implemented.',
        'correction_tip': 'Evaluate questions: present both sides. Recycling is a short-to-medium term solution; new materials/renewable alternatives are long-term solutions.',
    },

    # ------------------------------------------------------------------ #
    # P3 – Particle Model of Matter (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 1,
        'question_text': 'In which state of matter do particles have a fixed volume but no fixed shape?',
        'option_a': 'Solid',
        'option_b': 'Liquid',
        'option_c': 'Gas',
        'option_d': 'Plasma',
        'correct_answer': 'B',
        'explanation': 'In a liquid, particles are close together (fixed volume) but can flow past each other (no fixed shape), allowing the liquid to take the shape of its container.',
        'correction_tip': 'Solid = fixed shape AND volume; liquid = fixed volume only; gas = neither fixed.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 1,
        'question_text': 'What is the formula for density?',
        'option_a': 'density = volume ÷ mass',
        'option_b': 'density = mass × volume',
        'option_c': 'density = mass ÷ volume',
        'option_d': 'density = weight ÷ area',
        'correct_answer': 'C',
        'explanation': 'Density = mass ÷ volume (ρ = m/V). The SI unit is kg/m³, though g/cm³ is also commonly used.',
        'correction_tip': 'Think of density as "how much mass is packed into a given volume." More mass per unit volume = higher density.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 1,
        'question_text': 'What is the specific latent heat of fusion?',
        'option_a': 'The energy needed to raise 1 kg of a substance by 1 °C',
        'option_b': 'The energy needed to change 1 kg of a solid into a liquid without changing temperature',
        'option_c': 'The energy released when a gas condenses to a liquid',
        'option_d': 'The temperature at which a substance melts',
        'correct_answer': 'B',
        'explanation': 'Specific latent heat of fusion is the energy required to change 1 kg of a solid to a liquid at constant temperature (at the melting point), without changing the temperature.',
        'correction_tip': 'Latent heat of FUSION = melting/freezing. Latent heat of VAPORISATION = boiling/condensing.',
    },

    # Medium (3)
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 2,
        'question_text': 'A block of copper has a mass of 890 g and a volume of 100 cm³. What is its density in g/cm³?',
        'option_a': '89 000 g/cm³',
        'option_b': '0.11 g/cm³',
        'option_c': '8.9 g/cm³',
        'option_d': '890 g/cm³',
        'correct_answer': 'C',
        'explanation': 'Density = mass ÷ volume = 890 ÷ 100 = 8.9 g/cm³. This is close to the accepted density of copper (8.96 g/cm³).',
        'correction_tip': 'Make sure mass and volume use consistent units before dividing. 890 g ÷ 100 cm³ = 8.9 g/cm³.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 2,
        'question_text': 'Why does the temperature of a substance remain constant during a change of state, even though it is being heated?',
        'option_a': 'The energy is lost to the surroundings as infrared radiation',
        'option_b': 'The energy is used to overcome the forces between particles rather than to increase their kinetic energy',
        'option_c': 'The thermometer is not accurate enough to detect the small temperature increase',
        'option_d': 'Heating stops automatically at the melting or boiling point',
        'correct_answer': 'B',
        'explanation': 'During a change of state, the energy supplied (latent heat) is used to break or weaken the forces between particles, not to increase the average kinetic energy (temperature) of the particles.',
        'correction_tip': 'Temperature = average kinetic energy of particles. During a change of state, energy changes potential energy (separating particles), not kinetic energy.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 2,
        'question_text': 'What causes pressure in a gas, according to the particle model?',
        'option_a': 'The weight of the gas particles pressing downwards',
        'option_b': 'Collisions of gas particles with the walls of the container',
        'option_c': 'The attraction between gas particles',
        'option_d': 'The vibration of the container walls',
        'correct_answer': 'B',
        'explanation': 'Gas particles move rapidly in all directions. When they collide with the container walls, they exert a force. The total force per unit area from all these collisions is the gas pressure.',
        'correction_tip': 'Gas pressure = force from particle–wall collisions per unit area. More/faster particles = more collisions = higher pressure.',
    },

    # Hard (2)
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 3,
        'question_text': 'A fixed amount of gas is heated at constant volume. How does this affect the pressure of the gas, and why?',
        'option_a': 'Pressure decreases because the particles slow down',
        'option_b': 'Pressure stays the same because the volume has not changed',
        'option_c': 'Pressure increases because particles move faster and collide with the walls more frequently and with greater force',
        'option_d': 'Pressure increases because the gas expands when heated',
        'correct_answer': 'C',
        'explanation': 'Heating increases the average kinetic energy of particles (they move faster). At constant volume, they collide with the walls more often and with greater force, so pressure increases.',
        'correction_tip': 'At constant volume: T↑ → particles faster → more frequent, harder collisions → pressure ↑. This is Gay-Lussac\'s law.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 3,
        'question_text': 'What is Brownian motion, and what does it provide evidence for?',
        'option_a': 'The regular vibration of atoms in a crystal lattice; evidence for the ordered structure of solids',
        'option_b': 'The random, erratic movement of small particles (e.g. pollen) suspended in a fluid; evidence that fluids are made of many tiny, randomly moving particles',
        'option_c': 'The movement of electrons through a conductor; evidence for electrical charge',
        'option_d': 'The circular motion of planets; evidence for gravitational fields',
        'correct_answer': 'B',
        'explanation': 'Brownian motion is the random movement of small visible particles (like smoke or pollen) caused by uneven bombardment from invisible, fast-moving fluid molecules. It provides evidence for the particle model of matter.',
        'correction_tip': 'Key word: "random" and "erratic". Brownian motion is evidence for the existence of small, invisible, randomly-moving particles.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 4,
        'question_text': 'A 2 kg block of ice at 0 °C is melted completely and heated to 100 °C. The specific latent heat of fusion of water is 334 000 J/kg, and the specific heat capacity of water is 4200 J/kg °C. Calculate the total energy required.',
        'option_a': '1 508 000 J',
        'option_b': '840 000 J',
        'option_c': '668 000 J',
        'option_d': '1 248 000 J',
        'correct_answer': 'A',
        'explanation': 'Energy to melt: Q₁ = mL = 2 × 334 000 = 668 000 J. Energy to heat water: Q₂ = mcΔT = 2 × 4200 × 100 = 840 000 J. Total = 668 000 + 840 000 = 1 508 000 J.',
        'correction_tip': 'Two separate calculations: (1) melting uses Q = mL; (2) heating uses Q = mcΔT. Add them together at the end.',
    },
    {
        'subject': 'Physics',
        'topic': 'Particle model',
        'difficulty': 4,
        'question_text': 'A gas in a sealed container at 27 °C has a pressure of 200 kPa. The gas is heated to 127 °C at constant volume. What is the new pressure? (Use the pressure law: P₁/T₁ = P₂/T₂, temperatures in kelvin.)',
        'option_a': '400 kPa',
        'option_b': '267 kPa',
        'option_c': '150 kPa',
        'option_d': '320 kPa',
        'correct_answer': 'B',
        'explanation': 'Convert temperatures: T₁ = 27 + 273 = 300 K; T₂ = 127 + 273 = 400 K. P₂ = P₁ × T₂/T₁ = 200 × 400/300 = 266.7 kPa ≈ 267 kPa.',
        'correction_tip': 'Always convert Celsius to Kelvin (add 273) before using gas law equations. Using °C will give a wrong answer.',
    },

    # ------------------------------------------------------------------ #
    # P4 – Atomic Structure / Nuclear Physics (8 questions to add to 4)
    # ------------------------------------------------------------------ #

    # Easy (2)
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 1,
        'question_text': 'What is emitted during alpha (α) decay?',
        'option_a': 'A high-energy electron',
        'option_b': 'A helium nucleus (2 protons and 2 neutrons)',
        'option_c': 'A high-energy electromagnetic wave',
        'option_d': 'A neutron',
        'correct_answer': 'B',
        'explanation': 'An alpha particle is a helium nucleus, consisting of 2 protons and 2 neutrons. When a nucleus emits an alpha particle, its atomic number decreases by 2 and its mass number decreases by 4.',
        'correction_tip': 'Alpha = helium nucleus (⁴₂He). Its emission reduces atomic number by 2 and mass number by 4.',
    },
    {
        'subject': 'Physics',
        'topic': 'Atomic structure physics',
        'difficulty': 1,
        'question_text': 'What is the half-life of a radioactive isotope?',
        'option_a': 'The time it takes for all atoms in a sample to decay',
        'option_b': 'The time it takes for half the radioactive atoms in a sample to decay',
        'option_c': 'The time it takes for the activity of a sample to double',
        'option_d': 'The time it takes for the sample to become completely non-radioactive',
        'correct_answer': 'B',
        'explanation': 'Half-life is the time for the number of radioactive nuclei (or the activity) of a sample to decrease to half its original value.',
        'correction_tip': 'After 1 half-life: 50% remains. After 2: 25%. After 3: 12.5%. It never reaches exactly zero.',
    },

    # Medium (2)
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 2,
        'question_text': 'Carbon-14 has a half-life of 5700 years. A sample originally contains 4800 radioactive carbon-14 atoms. How many remain after 17 100 years?',
        'option_a': '2400',
        'option_b': '600',
        'option_c': '1200',
        'option_d': '300',
        'correct_answer': 'B',
        'explanation': '17 100 years ÷ 5700 years = 3 half-lives. 4800 → 2400 → 1200 → 600. After 3 half-lives, 600 atoms remain.',
        'correction_tip': 'Count the number of half-lives first (total time ÷ half-life), then halve the starting amount that many times.',
    },
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 2,
        'question_text': 'What happens to the atomic number and mass number of a nucleus during beta-minus (β⁻) decay?',
        'option_a': 'Atomic number decreases by 1; mass number is unchanged',
        'option_b': 'Atomic number increases by 1; mass number is unchanged',
        'option_c': 'Atomic number decreases by 2; mass number decreases by 4',
        'option_d': 'Neither atomic number nor mass number changes',
        'correct_answer': 'B',
        'explanation': 'In beta-minus decay, a neutron converts to a proton and an electron (beta particle). The proton stays in the nucleus, so atomic number increases by 1 while mass number stays the same.',
        'correction_tip': 'β⁻ decay: neutron → proton + electron. Atomic number +1, mass number unchanged. Compare with α decay: atomic number −2, mass number −4.',
    },

    # Hard (2)
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 3,
        'question_text': 'Describe how Rutherford\'s gold foil experiment changed the model of the atom.',
        'option_a': 'It confirmed the plum-pudding model by showing electrons were evenly distributed',
        'option_b': 'It showed that most of the atom is empty space, with a tiny, dense, positively charged nucleus at the centre, replacing the plum-pudding model',
        'option_c': 'It proved that atoms are indivisible and cannot be broken down',
        'option_d': 'It showed that electrons orbit the nucleus in fixed energy levels',
        'correct_answer': 'B',
        'explanation': 'Most alpha particles passed straight through the foil (empty space), some deflected slightly (positive nucleus repelling positive alpha particles), and a very few bounced back (extremely dense, small nucleus). This replaced Thomson\'s plum-pudding model.',
        'correction_tip': 'Key results: most pass through (empty space), some deflect (repulsion), a few bounce back (dense nucleus). Each result provides a piece of evidence.',
    },
    {
        'subject': 'Physics',
        'topic': 'Atomic structure physics',
        'difficulty': 3,
        'question_text': 'Two isotopes of uranium are ²³⁵U and ²³⁸U. How do they differ, and why can ²³⁵U undergo nuclear fission more readily?',
        'option_a': 'They differ in the number of protons; ²³⁵U is fissile because it has more protons',
        'option_b': 'They differ in the number of neutrons (²³⁵U has 143, ²³⁸U has 146); ²³⁵U has an unstable nucleus more easily split by slow neutrons',
        'option_c': 'They are identical in structure; the difference is only in their electron configurations',
        'option_d': 'They differ in atomic number; ²³⁸U has a higher atomic number making it more stable',
        'correct_answer': 'B',
        'explanation': 'Isotopes have the same number of protons but different numbers of neutrons. ²³⁵U (92 protons, 143 neutrons) is fissile — its nucleus absorbs a slow neutron and splits readily. ²³⁸U (92 protons, 146 neutrons) requires fast neutrons and is far less fissile.',
        'correction_tip': 'Isotopes = same protons, different neutrons. ²³⁵U is the fissile isotope used in nuclear reactors and weapons.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 4,
        'question_text': 'A hospital uses a radioactive tracer with a half-life of 6 hours for a diagnostic scan. Explain why a very short half-life (e.g. 6 minutes) or a very long half-life (e.g. 60 years) would both be unsuitable for this purpose.',
        'option_a': '6 minutes is too radioactive; 60 years is not radioactive enough',
        'option_b': '6 minutes would decay before the scan is complete (too little activity remains); 60 years would expose the patient to radiation for an unacceptably long time',
        'option_c': '6 minutes is too long; 60 years produces the wrong type of radiation',
        'option_d': 'Both are unsuitable because medical tracers must always be gamma emitters',
        'correct_answer': 'B',
        'explanation': 'A tracer needs to remain active long enough for the scan to be performed. 6 minutes is too short — it would decay before imaging. 60 years is too long — the patient would receive an unnecessary radiation dose for decades.',
        'correction_tip': 'Medical tracers need a half-life matched to the procedure: long enough to complete the scan, short enough to minimise patient radiation exposure.',
    },
    {
        'subject': 'Physics',
        'topic': 'Nuclear physics',
        'difficulty': 4,
        'question_text': 'In a nuclear fission chain reaction, what is the role of a moderator in a nuclear reactor, and what material is commonly used?',
        'option_a': 'The moderator absorbs excess neutrons to prevent the chain reaction going too fast; boron control rods are used',
        'option_b': 'The moderator slows down fast neutrons so they are more likely to cause fission in ²³⁵U; water or graphite is commonly used',
        'option_c': 'The moderator generates the initial neutrons needed to start the chain reaction; uranium is used',
        'option_d': 'The moderator cools the reactor core; liquid sodium is used',
        'correct_answer': 'B',
        'explanation': 'Fast neutrons produced by fission are less effective at causing further fission. A moderator (water or graphite) slows them to thermal speeds, greatly increasing the probability of initiating another fission event and sustaining the chain reaction.',
        'correction_tip': 'Moderator = slows neutrons (water/graphite). Control rods = absorb neutrons to control rate (boron/cadmium). Don\'t mix them up.',
    },

    # ------------------------------------------------------------------ #
    # P7 – Magnetism & Electromagnetism (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Physics',
        'topic': 'Magnetism',
        'difficulty': 1,
        'question_text': 'Which of the following materials is magnetic?',
        'option_a': 'Copper',
        'option_b': 'Aluminium',
        'option_c': 'Iron',
        'option_d': 'Gold',
        'correct_answer': 'C',
        'explanation': 'Iron is a magnetic material — it is attracted to magnets and can be magnetised. Copper, aluminium, and gold are non-magnetic.',
        'correction_tip': 'Magnetic materials: iron, steel, nickel, cobalt. Remember "FENICOCO" or just learn the four: Fe, Ni, Co, steel.',
    },
    {
        'subject': 'Physics',
        'topic': 'Magnetism',
        'difficulty': 1,
        'question_text': 'In which direction do magnetic field lines run outside a bar magnet?',
        'option_a': 'From south pole to north pole',
        'option_b': 'From north pole to south pole',
        'option_c': 'Parallel to the magnet with no defined direction',
        'option_d': 'Randomly in all directions',
        'correct_answer': 'B',
        'explanation': 'By convention, magnetic field lines run from the north pole to the south pole outside the magnet. They form closed loops, running from south to north inside the magnet.',
        'correction_tip': 'Field lines go: N → S (outside). Arrows on field lines always point away from N and towards S.',
    },
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 1,
        'question_text': 'What is an electromagnet?',
        'option_a': 'A permanent magnet made from an electrical conductor',
        'option_b': 'A coil of wire that produces a magnetic field when a current flows through it',
        'option_c': 'A device that converts electrical energy directly into mechanical energy',
        'option_d': 'A type of permanent magnet used only in motors',
        'correct_answer': 'B',
        'explanation': 'An electromagnet is a coil of wire (solenoid) that behaves as a magnet when current flows through it. Its strength can be varied and it can be switched off.',
        'correction_tip': 'Electromagnet = current → magnetic field. Advantages over permanent magnets: switchable, adjustable strength.',
    },

    # Medium (3)
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 2,
        'question_text': 'Fleming\'s left-hand rule is used to determine the direction of force on a current-carrying conductor in a magnetic field. What do the thumb, first finger, and second finger represent respectively?',
        'option_a': 'Force, Current, Field',
        'option_b': 'Field, Force, Current',
        'option_c': 'Force, Field, Current',
        'option_d': 'Current, Field, Force',
        'correct_answer': 'C',
        'explanation': 'In Fleming\'s left-hand rule: thuMb = Motion (force), First finger = Field, seCond finger = Current. The three are mutually perpendicular.',
        'correction_tip': 'Memory aid: "FBI" — First = Field, thuMb = Motion, seCond = Current. Or: "Father, Mother, Child" (Field, Motion, Current).',
    },
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 2,
        'question_text': 'A transformer has 200 turns on the primary coil and 50 turns on the secondary coil. If the primary voltage is 240 V, what is the secondary voltage?',
        'option_a': '960 V',
        'option_b': '60 V',
        'option_c': '120 V',
        'option_d': '48 V',
        'correct_answer': 'B',
        'explanation': 'Using Vs/Vp = Ns/Np: Vs = Vp × (Ns/Np) = 240 × (50/200) = 240 × 0.25 = 60 V. Fewer secondary turns → lower voltage → step-down transformer.',
        'correction_tip': 'Vs/Vp = Ns/Np. More secondary turns → step UP; fewer secondary turns → step DOWN.',
    },
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 2,
        'question_text': 'Why does the National Grid transmit electricity at very high voltages?',
        'option_a': 'Higher voltage increases the speed at which electricity travels',
        'option_b': 'Higher voltage means a lower current is needed for the same power, reducing energy wasted as heat in the cables (P = I²R)',
        'option_c': 'Higher voltage increases the resistance of the cables, preventing overheating',
        'option_d': 'Higher voltage is needed to overcome the magnetic field of the Earth',
        'correct_answer': 'B',
        'explanation': 'Power loss in cables is given by P = I²R. Transmitting at high voltage means low current (P = IV), so I²R losses are greatly reduced, making long-distance transmission efficient.',
        'correction_tip': 'National Grid: step UP voltage (step DOWN current) at power station → transmit → step DOWN voltage (step UP current) for homes. Less current = less heat wasted.',
    },

    # Hard (2)
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 3,
        'question_text': 'Explain how a loudspeaker uses the motor effect to produce sound.',
        'option_a': 'The loudspeaker uses a permanent magnet to attract a metal cone, pushing air to create sound',
        'option_b': 'An alternating current in the voice coil interacts with the magnetic field of a permanent magnet, causing the coil and attached cone to vibrate, creating pressure waves (sound)',
        'option_c': 'The cone vibrates due to electrostatic forces between the coil and the magnet',
        'option_d': 'A DC current produces a constant force pushing the cone outward',
        'correct_answer': 'B',
        'explanation': 'An alternating current through the voice coil creates a varying force (motor effect: F = BIL). As current direction alternates, the force on the coil reverses, causing the cone to vibrate at the same frequency as the current, producing sound waves.',
        'correction_tip': 'AC is essential — it reverses direction, so the force reverses, so the cone vibrates. DC would just push it out and hold it there.',
    },
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 3,
        'question_text': 'A generator produces a larger EMF when the coil rotates faster. Explain why, in terms of electromagnetic induction.',
        'option_a': 'Faster rotation increases the resistance of the coil, producing more voltage',
        'option_b': 'Faster rotation means the magnetic flux through the coil changes more rapidly, and induced EMF is proportional to the rate of change of flux',
        'option_c': 'Faster rotation heats the coil, increasing its ability to conduct electricity',
        'option_d': 'Faster rotation brings the coil closer to the magnets, increasing the field strength',
        'correct_answer': 'B',
        'explanation': 'Faraday\'s law states that induced EMF is proportional to the rate of change of magnetic flux. Faster rotation means flux changes more rapidly per unit time, inducing a larger EMF.',
        'correction_tip': 'Larger EMF: rotate faster, stronger magnet, more turns on coil, or larger coil area — all increase the rate of flux change.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Physics',
        'topic': 'Electromagnetism',
        'difficulty': 4,
        'question_text': 'A step-up transformer in the National Grid increases voltage from 25 000 V to 400 000 V. If the primary coil carries a current of 800 A (assume 100% efficiency), what is the current in the secondary coil?',
        'option_a': '12 800 A',
        'option_b': '50 A',
        'option_c': '800 A',
        'option_d': '32 000 000 A',
        'correct_answer': 'B',
        'explanation': 'For an ideal transformer, power is conserved: Vp × Ip = Vs × Is. Is = (Vp × Ip)/Vs = (25 000 × 800)/400 000 = 20 000 000/400 000 = 50 A.',
        'correction_tip': 'Step-up voltage → step-down current (for same power). Use VpIp = VsIs for efficiency = 100%.',
    },
    {
        'subject': 'Physics',
        'topic': 'Magnetism',
        'difficulty': 4,
        'question_text': 'Explain the difference between a hard and a soft magnetic material, giving one example of each, and one application that requires each type.',
        'option_a': 'Hard = easily magnetised and demagnetised (e.g. iron), used in electromagnets; soft = stays magnetised (e.g. steel), used in permanent magnets',
        'option_b': 'Hard = retains magnetism (e.g. steel), used in permanent magnets; soft = easily magnetised and demagnetised (e.g. iron), used in electromagnet cores',
        'option_c': 'Hard = higher density (e.g. steel), used in motors; soft = lower density (e.g. iron), used in generators',
        'option_d': 'Hard and soft magnetic materials behave identically; the terms only refer to their physical hardness',
        'correct_answer': 'B',
        'explanation': 'Hard magnetic materials (e.g. steel, alnico, neodymium) are difficult to demagnetise and are used for permanent magnets. Soft magnetic materials (e.g. iron) are easily magnetised and demagnetised, making them ideal for the cores of electromagnets and transformers.',
        'correction_tip': 'Hard = permanent magnets (stays magnetised). Soft = temporary magnets/transformer cores (easily switched). The "hardness" refers to magnetic properties, not physical hardness.',
    },

    # ------------------------------------------------------------------ #
    # P8 – Space Physics (10 questions)
    # ------------------------------------------------------------------ #

    # Easy (3)
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 1,
        'question_text': 'What is a light year?',
        'option_a': 'The time it takes light to travel from the Sun to Earth',
        'option_b': 'The distance light travels in one year (approximately 9.5 × 10¹⁵ m)',
        'option_c': 'The speed of light (3 × 10⁸ m/s)',
        'option_d': 'The time it takes for Earth to orbit the Sun',
        'correct_answer': 'B',
        'explanation': 'A light year is a unit of distance — the distance that light (at 3 × 10⁸ m/s) travels in one year, approximately 9.5 × 10¹⁵ metres.',
        'correction_tip': 'A light year is a distance, not a time. Don\'t be misled by the word "year" in the name.',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 1,
        'question_text': 'What is the correct sequence for the life cycle of a star similar in mass to our Sun?',
        'option_a': 'Nebula → protostar → main sequence → red giant → white dwarf',
        'option_b': 'Nebula → main sequence → protostar → supernova → neutron star',
        'option_c': 'Protostar → nebula → red supergiant → black hole',
        'option_d': 'Nebula → protostar → main sequence → supernova → black dwarf',
        'correct_answer': 'A',
        'explanation': 'A Sun-like star forms in a nebula, contracts to a protostar, enters the main sequence (hydrogen fusion), expands to a red giant, and finally collapses to a white dwarf.',
        'correction_tip': 'Sun-like stars end as WHITE DWARFS. Massive stars end as neutron stars or black holes (after a supernova).',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 1,
        'question_text': 'What provides the centripetal force that keeps planets in orbit around the Sun?',
        'option_a': 'The magnetic force from the Sun',
        'option_b': 'Gravitational attraction between the planet and the Sun',
        'option_c': 'The nuclear force from the Sun\'s core',
        'option_d': 'Solar wind pressure',
        'correct_answer': 'B',
        'explanation': 'Gravity between the planet and the Sun acts as the centripetal force, continuously pulling the planet towards the Sun and keeping it in its orbital path.',
        'correction_tip': 'In any orbit (planets, moons, satellites), gravity is the centripetal force. It acts inward (towards the centre of the orbit).',
    },

    # Medium (3)
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 2,
        'question_text': 'What is red-shift, and what does it tell us about the universe?',
        'option_a': 'Light from distant galaxies is shifted to shorter (bluer) wavelengths, indicating the universe is contracting',
        'option_b': 'Light from distant galaxies is shifted to longer (redder) wavelengths, indicating those galaxies are moving away from us and the universe is expanding',
        'option_c': 'The Sun\'s light turns red at sunset due to scattering; this has nothing to do with cosmology',
        'option_d': 'Red-shift only affects sound waves; it has no relevance to light from galaxies',
        'correct_answer': 'B',
        'explanation': 'Red-shift is the increase in wavelength of light from distant galaxies. It occurs because those galaxies are moving away from us. The further the galaxy, the greater the red-shift, indicating the universe is expanding in all directions.',
        'correction_tip': 'Red-shift → longer wavelength → moving away. Blue-shift would mean moving towards us. All distant galaxies show red-shift.',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 2,
        'question_text': 'What is cosmic microwave background (CMB) radiation, and why is it important evidence for the Big Bang?',
        'option_a': 'Radiation emitted by stars in distant galaxies; evidence that stars have always existed',
        'option_b': 'Uniform microwave radiation detected from all directions in space; it is the afterglow of the hot, dense early universe predicted by the Big Bang theory',
        'option_c': 'Radiation produced by black holes at the centre of galaxies',
        'option_d': 'Radiation from the Sun that has been stretched to microwave wavelengths',
        'correct_answer': 'B',
        'explanation': 'CMB radiation is electromagnetic radiation left over from the very early universe, now stretched to microwave wavelengths as the universe has expanded. It is detected uniformly from all directions, consistent with Big Bang predictions.',
        'correction_tip': 'CMB = leftover heat from the Big Bang, now cooled to microwaves. Along with red-shift, it is the main evidence for the Big Bang.',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 2,
        'question_text': 'How does a massive star\'s lifecycle differ from a Sun-like star after the red giant / red supergiant stage?',
        'option_a': 'Massive stars shrink directly to a white dwarf; Sun-like stars explode as supernovae',
        'option_b': 'Massive stars explode as supernovae and leave a neutron star or black hole; Sun-like stars shed outer layers to leave a white dwarf',
        'option_c': 'Both types of star follow the same lifecycle and end as black holes',
        'option_d': 'Massive stars become pulsars immediately after the main sequence; Sun-like stars become red dwarfs',
        'correct_answer': 'B',
        'explanation': 'Massive stars become red supergiants, then explode as supernovae, producing heavy elements. The remnant is a neutron star or (for the most massive stars) a black hole. Sun-like stars become red giants and shed their outer layers to leave a white dwarf.',
        'correction_tip': 'The key difference: MASSIVE → supernova → neutron star/black hole. SUN-LIKE → red giant → white dwarf. Mass determines the endpoint.',
    },

    # Hard (2)
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 3,
        'question_text': 'Why does the Big Bang theory predict that the universe should be cooling over time, and what observation supports this?',
        'option_a': 'The universe is cooling because stars are running out of fuel; we observe fewer hot young stars today',
        'option_b': 'As the universe expands, the same energy is spread over an ever-larger volume, so the average temperature decreases; the CMB temperature (~2.7 K) is far cooler than the billions of kelvin of the early universe',
        'option_c': 'The universe cools because dark matter absorbs energy from radiation',
        'option_d': 'The universe is not cooling — its temperature has remained constant since the Big Bang',
        'correct_answer': 'B',
        'explanation': 'In an expanding universe, the same amount of radiation energy is diluted over an ever-growing volume, reducing energy density and temperature. The CMB, once extremely hot plasma, is now just ~2.7 K — consistent with ~13.8 billion years of expansion.',
        'correction_tip': 'Expansion → cooling. The CMB temperature of 2.7 K confirms the universe has been expanding and cooling since the Big Bang.',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 3,
        'question_text': 'The Milky Way galaxy is approximately 100 000 light years across. If a signal travelling at the speed of light were sent from one side to the other, how long would it take?',
        'option_a': '100 000 years',
        'option_b': '100 000 seconds',
        'option_c': '100 000 × 3 × 10⁸ years',
        'option_d': '1 year',
        'correct_answer': 'A',
        'explanation': 'A light year is defined as the distance light travels in one year. If the galaxy is 100 000 light years across, light takes exactly 100 000 years to cross it.',
        'correction_tip': 'The definition makes this straightforward: light year = distance light travels in one year. So n light years → n years for light to cross it.',
    },

    # Exam Challenge (2)
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 4,
        'question_text': 'A galaxy 500 million light years away has a measured red-shift that indicates it is receding at 11 000 km/s. A galaxy 1000 million light years away is measured to recede at 22 000 km/s. What does this relationship suggest, and what theory does it support?',
        'option_a': 'The recession speed is independent of distance, supporting the steady-state model',
        'option_b': 'Recession speed is proportional to distance (Hubble\'s law: v = H₀d), supporting the Big Bang model of an expanding universe',
        'option_c': 'The relationship shows the universe is rotating, not expanding',
        'option_d': 'The relationship is a coincidence with no theoretical significance',
        'correct_answer': 'B',
        'explanation': 'Doubling the distance doubles the recession speed — recession velocity is proportional to distance. This is Hubble\'s law (v = H₀d) and provides strong evidence that the universe is expanding uniformly, consistent with the Big Bang theory.',
        'correction_tip': 'Hubble\'s law: more distant galaxies recede faster. This makes sense if the universe is expanding — like dots on a balloon being inflated.',
    },
    {
        'subject': 'Physics',
        'topic': 'Space physics',
        'difficulty': 4,
        'question_text': 'During a star\'s main sequence phase, it is in hydrostatic equilibrium. Explain what this means and what eventually causes the star to leave the main sequence.',
        'option_a': 'Hydrostatic equilibrium means the star is not rotating; it leaves the main sequence when it starts rotating',
        'option_b': 'Hydrostatic equilibrium is the balance between the inward force of gravity and the outward pressure from nuclear fusion; the star leaves the main sequence when hydrogen in the core is depleted and fusion slows, so gravity wins and the core contracts',
        'option_c': 'Hydrostatic equilibrium means the star\'s temperature is constant; it leaves the main sequence when the temperature rises too high',
        'option_d': 'Hydrostatic equilibrium means the star emits equal energy in all directions; it ends when a nearby star disturbs this symmetry',
        'correct_answer': 'B',
        'explanation': 'In the main sequence, gravity (inward) is balanced by radiation pressure from hydrogen fusion (outward). When the core\'s hydrogen is used up, fusion decreases, gravity takes over and the core contracts, heating the outer layers which expand — forming a red giant.',
        'correction_tip': 'Main sequence = gravity balanced by fusion pressure. No more H in core → gravity wins → contraction/expansion → red giant.',
    },

]


def insert():
    conn = sqlite3.connect('quiz.db')
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute(
            '''INSERT INTO questions
               (subject, topic, difficulty, question_text,
                option_a, option_b, option_c, option_d,
                correct_answer, explanation, correction_tip)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'], q['topic'], q['difficulty'],
             q['question_text'],
             q['option_a'], q['option_b'], q['option_c'], q['option_d'],
             q['correct_answer'], q['explanation'], q['correction_tip'])
        )
        added += 1
    conn.commit()
    conn.close()
    print(f'Added {added} new questions.')


if __name__ == '__main__':
    insert()
