QUESTIONS = [
    # =========================================================================
    # P3 PARTICLE MODEL OF MATTER — 59 questions
    # D1: 15, D2: 15, D3: 15, D4: 14
    # =========================================================================

    # --- P3 Easy (D1) — 15 questions ---

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'In which state of matter are particles arranged in a fixed, regular lattice?',
     'option_a':'Gas','option_b':'Liquid','option_c':'Solid','option_d':'Plasma',
     'correct_answer':'C',
     'explanation':'In a solid, particles are in a fixed, regular arrangement and only vibrate about fixed positions.',
     'correction_tip':'Solid = fixed, regular arrangement; liquid = close but random; gas = spread out.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'What happens to the particles in a substance when it melts?',
     'option_a':'They start to move faster and spread very far apart',
     'option_b':'They break free from fixed positions and can flow past each other',
     'option_c':'They stop vibrating completely',
     'option_d':'They gain a fixed shape',
     'correct_answer':'B',
     'explanation':'During melting the regular lattice breaks down and particles can flow past each other, forming a liquid.',
     'correction_tip':'Melting = solid to liquid; particles gain enough energy to overcome the fixed lattice forces.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'Which change of state is called evaporation?',
     'option_a':'Liquid to solid','option_b':'Gas to liquid','option_c':'Solid to gas','option_d':'Liquid to gas',
     'correct_answer':'D',
     'explanation':'Evaporation (and boiling) are both liquid-to-gas changes of state.',
     'correction_tip':'Evaporation = liquid to gas; condensation = gas to liquid.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'Which of the following correctly describes particles in a gas?',
     'option_a':'Close together, fixed positions, strong forces',
     'option_b':'Close together, random arrangement, weak forces',
     'option_c':'Far apart, random arrangement, negligible forces',
     'option_d':'Far apart, regular arrangement, strong forces',
     'correct_answer':'C',
     'explanation':'Gas particles are widely spaced, move randomly and rapidly, and have negligible intermolecular forces.',
     'correction_tip':'Gas = far apart, random, fast, negligible forces.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'The internal energy of a substance is the sum of which two types of energy of its particles?',
     'option_a':'Gravitational potential energy and elastic potential energy',
     'option_b':'Kinetic energy and potential energy',
     'option_c':'Nuclear energy and chemical energy',
     'option_d':'Thermal energy and electrical energy',
     'correct_answer':'B',
     'explanation':'Internal energy = total kinetic energy + total potential energy of all the particles in the substance.',
     'correction_tip':'Internal energy = KE + PE of particles.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'What does the specific heat capacity of a material tell you?',
     'option_a':'The energy needed to change 1 kg of the material from solid to liquid',
     'option_b':'The energy needed to raise the temperature of 1 kg of the material by 1 degree C',
     'option_c':'The maximum temperature the material can reach',
     'option_d':'The rate at which the material conducts heat',
     'correct_answer':'B',
     'explanation':'Specific heat capacity (c) is defined as the energy required to raise the temperature of 1 kg of a substance by 1 degree C (or 1 K).',
     'correction_tip':'SHC: energy per kg per degree. Units: J/(kg degrees C).'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':1,
     'question_text':'What is the formula for density?',
     'option_a':'density = mass x volume','option_b':'density = volume / mass',
     'option_c':'density = mass / volume','option_d':'density = mass + volume',
     'correct_answer':'C',
     'explanation':'Density (rho) = mass / volume. Units are kg/m^3 or g/cm^3.',
     'correction_tip':'Rho = m/V. Higher density means more mass packed into the same volume.'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':1,
     'question_text':'A block has a mass of 200 g and a volume of 40 cm^3. What is its density?',
     'option_a':'8000 g/cm^3','option_b':'5 g/cm^3','option_c':'0.2 g/cm^3','option_d':'240 g/cm^3',
     'correct_answer':'B',
     'explanation':'Density = mass / volume = 200 / 40 = 5 g/cm^3.',
     'correction_tip':'Use density = m/V with matching units.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'Which change of state describes water vapour turning into liquid water?',
     'option_a':'Evaporation','option_b':'Melting','option_c':'Condensation','option_d':'Sublimation',
     'correct_answer':'C',
     'explanation':'Condensation is the change from gas to liquid. It releases energy to the surroundings.',
     'correction_tip':'Condensation = gas to liquid (the reverse of evaporation).'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'Which process describes a solid changing directly into a gas without passing through the liquid state?',
     'option_a':'Condensation','option_b':'Evaporation','option_c':'Freezing','option_d':'Sublimation',
     'correct_answer':'D',
     'explanation':'Sublimation is the direct change from solid to gas. Dry ice (solid CO2) is a common example.',
     'correction_tip':'Sublimation: solid directly to gas (skips liquid stage).'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':1,
     'question_text':'What does Boyle\'s Law state about a fixed mass of gas at constant temperature?',
     'option_a':'Pressure is proportional to temperature',
     'option_b':'Volume is proportional to temperature',
     'option_c':'Pressure is inversely proportional to volume',
     'option_d':'Pressure is directly proportional to volume',
     'correct_answer':'C',
     'explanation':'Boyle\'s Law: P x V = constant (at constant temperature). If volume decreases, pressure increases.',
     'correction_tip':'Boyle\'s Law: P x V = constant at fixed temperature.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':1,
     'question_text':'What happens to the pressure of a gas if its temperature increases and volume stays constant?',
     'option_a':'Pressure decreases','option_b':'Pressure stays the same',
     'option_c':'Pressure increases','option_d':'Pressure becomes zero',
     'correct_answer':'C',
     'explanation':'At constant volume, increasing temperature increases the kinetic energy of particles, causing more frequent and harder collisions with the container walls, increasing pressure.',
     'correction_tip':'Higher temperature = faster particles = more pressure (constant volume).'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'During a change of state (e.g. melting at constant temperature), what happens to the internal energy of the substance?',
     'option_a':'It decreases','option_b':'It stays the same',
     'option_c':'It increases','option_d':'It first increases then decreases',
     'correct_answer':'C',
     'explanation':'Energy is still being supplied during a change of state; it increases the potential energy of the particles (separating them) even though temperature stays constant.',
     'correction_tip':'During change of state: temperature flat, but internal energy (potential energy) still rises.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'What is Brownian motion?',
     'option_a':'The regular vibration of particles in a solid',
     'option_b':'The random, jerky motion of small particles suspended in a fluid',
     'option_c':'The flow of liquid particles from hot to cold regions',
     'option_d':'The circular motion of gas particles in a container',
     'correct_answer':'B',
     'explanation':'Brownian motion is the random, unpredictable movement of small particles (e.g. pollen in water) caused by collisions with invisible fast-moving fluid molecules.',
     'correction_tip':'Brownian motion = random jerky movement; evidence for the particle model of matter.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':1,
     'question_text':'The specific latent heat of fusion refers to the energy needed per kg for which change of state?',
     'option_a':'Liquid to gas','option_b':'Gas to solid',
     'option_c':'Solid to liquid (melting)','option_d':'Gas to liquid',
     'correct_answer':'C',
     'explanation':'Specific latent heat of fusion is the energy per unit mass required to change a substance from solid to liquid (melting) at constant temperature.',
     'correction_tip':'Fusion = melting (solid to liquid); vaporisation = liquid to gas.'},

    # --- P3 Medium (D2) — 15 questions ---

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'When a liquid evaporates, the remaining liquid cools. What is the best explanation for this?',
     'option_a':'Energy is released into the liquid as particles leave',
     'option_b':'The fastest-moving particles escape the liquid, lowering the average kinetic energy',
     'option_c':'All particles slow down equally when one leaves',
     'option_d':'The liquid absorbs energy from surrounding particles to fill the gap',
     'correct_answer':'B',
     'explanation':'The most energetic (fastest) particles escape the liquid surface. This lowers the average kinetic energy of the remaining particles, so temperature drops.',
     'correction_tip':'Evaporation cools because the highest-energy particles leave, reducing the average KE.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'A substance is heated and its temperature does not change for a period of time. What is most likely happening?',
     'option_a':'No energy is being supplied','option_b':'The substance is losing energy faster than it gains it',
     'option_c':'The substance is undergoing a change of state','option_d':'The specific heat capacity has become zero',
     'correct_answer':'C',
     'explanation':'A flat section on a heating curve indicates a change of state. Energy is being used to increase potential energy (break bonds) rather than increase temperature.',
     'correction_tip':'Flat region on a temperature-time graph = change of state occurring.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'Which formula correctly represents the energy transferred during a temperature change?',
     'option_a':'Q = mL','option_b':'Q = mcT','option_c':'Q = mcDeltaT','option_d':'Q = Lm^2',
     'correct_answer':'C',
     'explanation':'Q = mcDeltaT, where m = mass (kg), c = specific heat capacity (J/kg degrees C), DeltaT = temperature change (degrees C).',
     'correction_tip':'Q = mcDeltaT for temperature changes; Q = mL for changes of state.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'How much energy is needed to heat 2 kg of water by 10 degrees C? (specific heat capacity of water = 4200 J/kg degrees C)',
     'option_a':'42 000 J','option_b':'84 000 J','option_c':'8 400 J','option_d':'420 J',
     'correct_answer':'B',
     'explanation':'Q = mcDeltaT = 2 x 4200 x 10 = 84 000 J.',
     'correction_tip':'Q = mcDeltaT: multiply mass, SHC, and temperature change together.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'The specific latent heat of vaporisation of water is 2 260 000 J/kg. How much energy is needed to evaporate 0.5 kg of water at 100 degrees C?',
     'option_a':'1 130 000 J','option_b':'4 520 000 J','option_c':'2 260 000 J','option_d':'565 000 J',
     'correct_answer':'A',
     'explanation':'Q = mL = 0.5 x 2 260 000 = 1 130 000 J.',
     'correction_tip':'Q = mL: multiply mass by specific latent heat. No temperature change is involved.'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':2,
     'question_text':'A liquid has a density of 900 kg/m^3. What volume does 1800 kg of this liquid occupy?',
     'option_a':'0.5 m^3','option_b':'2 m^3','option_c':'1620 000 m^3','option_d':'900 m^3',
     'correct_answer':'B',
     'explanation':'V = m/rho = 1800 / 900 = 2 m^3.',
     'correction_tip':'Rearrange density = m/V to get V = m/density.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':2,
     'question_text':'A gas has a volume of 3 m^3 at a pressure of 100 000 Pa. The gas is compressed at constant temperature to a volume of 1 m^3. What is the new pressure?',
     'option_a':'33 333 Pa','option_b':'300 000 Pa','option_c':'100 000 Pa','option_d':'200 000 Pa',
     'correct_answer':'B',
     'explanation':'Boyle\'s Law: P1V1 = P2V2. So P2 = P1V1/V2 = (100 000 x 3) / 1 = 300 000 Pa.',
     'correction_tip':'Apply P1V1 = P2V2 and rearrange for the unknown.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':2,
     'question_text':'Explain why increasing the temperature of a gas in a sealed rigid container increases its pressure.',
     'option_a':'The gas molecules get larger so they take up more space',
     'option_b':'The molecules move faster, collide with the walls more frequently and with greater force',
     'option_c':'The container walls expand outwards',
     'option_d':'The number of gas molecules increases',
     'correct_answer':'B',
     'explanation':'Higher temperature = higher average kinetic energy = faster molecules. These hit the container walls more frequently and with greater momentum, increasing pressure.',
     'correction_tip':'Pressure from a gas = caused by particle collisions with walls. Faster = more force and frequency.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'What is the significance of Brownian motion as evidence for the particle model?',
     'option_a':'It shows that large particles are always stationary',
     'option_b':'It shows that fluids are made of tiny, randomly moving particles that bombard larger particles',
     'option_c':'It shows that heat always flows from cold to hot',
     'option_d':'It shows that gas pressure depends on temperature',
     'correct_answer':'B',
     'explanation':'The random, jerky motion of pollen grains in water (Brownian motion) is caused by unequal collisions from the invisible water molecules, providing evidence for the particle model.',
     'correction_tip':'Brownian motion proves fluids are made of tiny moving particles.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'Why does a substance have a lower density as a gas than as a liquid?',
     'option_a':'Gas particles are heavier than liquid particles',
     'option_b':'Gas particles have larger mass',
     'option_c':'Gas particles are much further apart, so the same mass occupies a much larger volume',
     'option_d':'Gas particles move slower so they spread out more',
     'correct_answer':'C',
     'explanation':'Density = m/V. In a gas, the particles are much more widely spaced than in a liquid, so the volume is much larger for the same mass, giving a lower density.',
     'correction_tip':'Greater spacing in gas = larger volume for same mass = lower density.'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':2,
     'question_text':'What is the pressure at the bottom of a column of water of depth 5 m? (density of water = 1000 kg/m^3, g = 10 N/kg)',
     'option_a':'50 Pa','option_b':'5000 Pa','option_c':'500 Pa','option_d':'50 000 Pa',
     'correct_answer':'D',
     'explanation':'P = rho x g x h = 1000 x 10 x 5 = 50 000 Pa.',
     'correction_tip':'Pressure in a fluid: P = rho x g x h (density x gravitational field strength x depth).'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':2,
     'question_text':'A diver descends deeper in the ocean. What happens to the pressure on the diver?',
     'option_a':'Pressure decreases because less water is above','option_b':'Pressure stays constant',
     'option_c':'Pressure increases because more water is above','option_d':'Pressure first increases then decreases',
     'correct_answer':'C',
     'explanation':'Pressure in a fluid increases with depth. More fluid above means greater weight of fluid acting on the diver.',
     'correction_tip':'P = rho x g x h: deeper = greater h = greater pressure.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':2,
     'question_text':'Which statement correctly describes the difference between specific latent heat of fusion and specific latent heat of vaporisation for the same substance?',
     'option_a':'Latent heat of fusion is always larger','option_b':'They are always equal',
     'option_c':'Latent heat of vaporisation is always larger because particles must be separated much further',
     'option_d':'Latent heat of vaporisation is always smaller',
     'correct_answer':'C',
     'explanation':'Vaporisation requires breaking all intermolecular forces completely (particles very far apart), so it requires far more energy per kg than fusion (where forces are only partially broken).',
     'correction_tip':'Vaporisation > fusion energy because gas particles are much more widely separated than liquid particles.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':2,
     'question_text':'The pressure of a gas at constant volume is 200 kPa at 300 K. What is the pressure at 600 K?',
     'option_a':'100 kPa','option_b':'400 kPa','option_c':'200 kPa','option_d':'600 kPa',
     'correct_answer':'B',
     'explanation':'P/T = constant (constant volume). P2 = P1 x T2/T1 = 200 x 600/300 = 400 kPa.',
     'correction_tip':'Use P1/T1 = P2/T2. Always use temperature in Kelvin (K = degrees C + 273).'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':2,
     'question_text':'Two objects are made of the same material. Object A has twice the mass of object B. How do their densities compare?',
     'option_a':'Object A has twice the density of object B',
     'option_b':'Object A has half the density of object B',
     'option_c':'They have the same density',
     'option_d':'Density depends on shape so cannot be compared',
     'correct_answer':'C',
     'explanation':'Density is an intrinsic property of a material. If mass doubles, volume also doubles (same material), so density = m/V remains unchanged.',
     'correction_tip':'Density is a property of the material, not of the object size.'},

    # --- P3 Hard (D3) — 15 questions ---

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'A 3 kg block of aluminium (specific heat capacity = 900 J/kg degrees C) is heated from 20 degrees C to 80 degrees C. How much energy is transferred to it?',
     'option_a':'162 000 J','option_b':'216 000 J','option_c':'54 000 J','option_d':'2700 J',
     'correct_answer':'A',
     'explanation':'Q = mcDeltaT = 3 x 900 x (80 - 20) = 3 x 900 x 60 = 162 000 J.',
     'correction_tip':'DeltaT = final temperature - initial temperature = 60 degrees C here.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'Ice at 0 degrees C is melted and the resulting water is heated to 100 degrees C. The specific latent heat of fusion of ice is 334 000 J/kg and the specific heat capacity of water is 4200 J/kg degrees C. For 0.5 kg of ice, what is the total energy required?',
     'option_a':'167 000 J','option_b':'210 000 J','option_c':'377 000 J','option_d':'544 000 J',
     'correct_answer':'C',
     'explanation':'Energy to melt: Q1 = mL = 0.5 x 334 000 = 167 000 J. Energy to heat water: Q2 = mcDeltaT = 0.5 x 4200 x 100 = 210 000 J. Total = 167 000 + 210 000 = 377 000 J.',
     'correction_tip':'Two-step calculation: add energy for change of state (Q = mL) to energy for temperature rise (Q = mcDeltaT).'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':3,
     'question_text':'A gas occupies 400 cm^3 at a pressure of 150 kPa. What volume does it occupy at 50 kPa (constant temperature)?',
     'option_a':'133 cm^3','option_b':'1200 cm^3','option_c':'600 cm^3','option_d':'300 cm^3',
     'correct_answer':'B',
     'explanation':'Boyle\'s Law: P1V1 = P2V2. V2 = P1V1/P2 = (150 x 400) / 50 = 60 000 / 50 = 1200 cm^3.',
     'correction_tip':'Lower pressure = larger volume. P1V1 = P2V2.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':3,
     'question_text':'A sealed container of gas has a pressure of 1.2 x 10^5 Pa at 27 degrees C. What is the pressure at 127 degrees C? (Volume is constant.)',
     'option_a':'1.6 x 10^5 Pa','option_b':'0.9 x 10^5 Pa','option_c':'5.6 x 10^5 Pa','option_d':'2.4 x 10^5 Pa',
     'correct_answer':'A',
     'explanation':'T1 = 27 + 273 = 300 K. T2 = 127 + 273 = 400 K. P2 = P1 x T2/T1 = 1.2 x 10^5 x 400/300 = 1.6 x 10^5 Pa.',
     'correction_tip':'Convert Celsius to Kelvin first. Then use P1/T1 = P2/T2.'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':3,
     'question_text':'A hydraulic system has a small piston of area 0.002 m^2 and a large piston of area 0.02 m^2. A force of 50 N is applied to the small piston. What force is exerted by the large piston?',
     'option_a':'5 N','option_b':'50 N','option_c':'500 N','option_d':'5000 N',
     'correct_answer':'C',
     'explanation':'Pressure is transmitted equally: P = F1/A1 = 50/0.002 = 25 000 Pa. F2 = P x A2 = 25 000 x 0.02 = 500 N.',
     'correction_tip':'In hydraulics, pressure is the same throughout the fluid. F2/A2 = F1/A1, so F2 = F1 x (A2/A1).'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':3,
     'question_text':'An irregular stone is placed in a measuring cylinder containing 40 cm^3 of water. The water level rises to 65 cm^3. The mass of the stone is 74.75 g. What is the density of the stone?',
     'option_a':'2.99 g/cm^3','option_b':'1.15 g/cm^3','option_c':'1.87 g/cm^3','option_d':'4.0 g/cm^3',
     'correct_answer':'A',
     'explanation':'Volume of stone = 65 - 40 = 25 cm^3. Density = mass/volume = 74.75/25 = 2.99 g/cm^3.',
     'correction_tip':'Volume by displacement = final reading - initial reading. Then density = m/V.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'A student heats 0.2 kg of a solid. It takes 3600 J to raise its temperature by 30 degrees C. What is the specific heat capacity of the solid?',
     'option_a':'600 J/kg degrees C','option_b':'540 J/kg degrees C','option_c':'18 J/kg degrees C','option_d':'21 600 J/kg degrees C',
     'correct_answer':'A',
     'explanation':'c = Q/(mDeltaT) = 3600 / (0.2 x 30) = 3600 / 6 = 600 J/kg degrees C.',
     'correction_tip':'Rearrange Q = mcDeltaT to c = Q / (m x DeltaT).'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'The specific latent heat of vaporisation of a liquid is 850 000 J/kg. A heater supplies 2550 J per second (2550 W). How long does it take to evaporate 0.6 kg of the liquid?',
     'option_a':'200 s','option_b':'3 s','option_c':'510 000 s','option_d':'2000 s',
     'correct_answer':'A',
     'explanation':'Energy needed: Q = mL = 0.6 x 850 000 = 510 000 J. Time = Q / Power = 510 000 / 2550 = 200 s.',
     'correction_tip':'Q = mL gives total energy. Then time = energy / power.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':3,
     'question_text':'A bicycle tyre contains gas at 3.0 x 10^5 Pa and 17 degrees C. The tyre is left in sunlight and warms to 57 degrees C (volume unchanged). What is the new pressure?',
     'option_a':'3.0 x 10^5 Pa','option_b':'3.41 x 10^5 Pa','option_c':'10.4 x 10^5 Pa','option_d':'2.64 x 10^5 Pa',
     'correct_answer':'B',
     'explanation':'T1 = 290 K, T2 = 330 K. P2 = P1 x T2/T1 = 3.0 x 10^5 x 330/290 = 3.41 x 10^5 Pa.',
     'correction_tip':'Remember to convert degrees C to Kelvin (add 273) before using the pressure-temperature law.'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':3,
     'question_text':'Sea water has a density of 1025 kg/m^3. What is the pressure due to the water at a depth of 200 m? (g = 10 N/kg)',
     'option_a':'205 000 Pa','option_b':'2 050 000 Pa','option_c':'20 500 Pa','option_d':'5125 Pa',
     'correct_answer':'B',
     'explanation':'P = rho x g x h = 1025 x 10 x 200 = 2 050 000 Pa (2.05 MPa).',
     'correction_tip':'P = rho g h. Make sure h is in metres.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'Why does the temperature of water remain at 100 degrees C while it boils, even though a heater is continuously supplying energy?',
     'option_a':'The heater output drops to zero at 100 degrees C',
     'option_b':'Energy is used to increase the potential energy of the particles (break bonds), not kinetic energy',
     'option_c':'Heat is being conducted away at the same rate as it is supplied',
     'option_d':'The kinetic energy of particles is at its maximum',
     'correct_answer':'B',
     'explanation':'At the boiling point, supplied energy goes into increasing the potential energy of particles (overcoming intermolecular forces) rather than increasing kinetic energy, so temperature stays constant.',
     'correction_tip':'During change of state: energy goes into PE (separating particles), not KE, so temperature is constant.'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':3,
     'question_text':'A cube of metal has sides of length 0.05 m and a mass of 1.05 kg. What is its density?',
     'option_a':'420 kg/m^3','option_b':'8400 kg/m^3','option_c':'1680 kg/m^3','option_d':'21 000 kg/m^3',
     'correct_answer':'B',
     'explanation':'Volume = 0.05^3 = 0.000125 m^3. Density = m/V = 1.05 / 0.000125 = 8400 kg/m^3.',
     'correction_tip':'Volume of cube = side^3. Be careful with unit conversion when side is in cm or mm.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':3,
     'question_text':'A gas in a piston has a volume of 0.8 m^3 at 2 x 10^5 Pa. The gas is then allowed to expand isothermally to 1.6 m^3. What is the final pressure?',
     'option_a':'4 x 10^5 Pa','option_b':'1 x 10^5 Pa','option_c':'2 x 10^5 Pa','option_d':'0.5 x 10^5 Pa',
     'correct_answer':'B',
     'explanation':'P2 = P1V1/V2 = (2 x 10^5 x 0.8) / 1.6 = 1.6 x 10^5 / 1.6 = 1 x 10^5 Pa.',
     'correction_tip':'Isothermal = constant temperature. Use P1V1 = P2V2.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':3,
     'question_text':'A copper calorimeter of mass 150 g (c = 380 J/kg degrees C) contains 200 g of water (c = 4200 J/kg degrees C). Both are at 20 degrees C. How much energy is required to raise both to 60 degrees C?',
     'option_a':'2280 J','option_b':'33 600 J','option_c':'35 880 J','option_d':'38 160 J',
     'correct_answer':'C',
     'explanation':'Q(copper) = 0.15 x 380 x 40 = 2280 J. Q(water) = 0.2 x 4200 x 40 = 33 600 J. Total = 2280 + 33 600 = 35 880 J.',
     'correction_tip':'Calculate energy for each component separately using Q = mcDeltaT, then add them.'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':3,
     'question_text':'The atmospheric pressure at sea level is approximately 101 325 Pa. A submarine is at a depth of 300 m in sea water (density 1025 kg/m^3, g = 10 N/kg). What is the total pressure on the submarine hull?',
     'option_a':'3 075 000 Pa','option_b':'3 176 325 Pa','option_c':'3 075 325 Pa','option_d':'101 325 Pa',
     'correct_answer':'B',
     'explanation':'Water pressure: P = 1025 x 10 x 300 = 3 075 000 Pa. Total = 3 075 000 + 101 325 = 3 176 325 Pa.',
     'correction_tip':'Total pressure = atmospheric pressure + pressure due to fluid column above.'},

    # --- P3 Exam Challenge (D4) — 14 questions ---

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':4,
     'question_text':'A 500 g sample of liquid (c = 2400 J/kg degrees C) is heated from 25 degrees C to its boiling point of 85 degrees C, then completely vaporised. The specific latent heat of vaporisation is 1 200 000 J/kg. What is the total energy supplied?',
     'option_a':'72 000 J','option_b':'600 000 J','option_c':'672 000 J','option_d':'528 000 J',
     'correct_answer':'C',
     'explanation':'Q1 (heating) = 0.5 x 2400 x 60 = 72 000 J. Q2 (vaporising) = 0.5 x 1 200 000 = 600 000 J. Total = 72 000 + 600 000 = 672 000 J.',
     'correction_tip':'Add Q = mcDeltaT (temperature rise) and Q = mL (change of state) together.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':4,
     'question_text':'A gas has a volume of 2.0 L at a pressure of 250 kPa and a temperature of 300 K. It is heated to 450 K and the pressure changes to 375 kPa. What is the new volume?',
     'option_a':'2.0 L','option_b':'3.0 L','option_c':'1.33 L','option_d':'4.5 L',
     'correct_answer':'A',
     'explanation':'Combined gas law: P1V1/T1 = P2V2/T2. V2 = P1V1T2 / (T1P2) = (250 x 2.0 x 450) / (300 x 375) = 225 000 / 112 500 = 2.0 L.',
     'correction_tip':'Use combined gas law: P1V1/T1 = P2V2/T2. Rearrange for V2.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':4,
     'question_text':'In an experiment, a student measures the energy supplied to melt an ice cube of mass 60 g and finds Q = 18 900 J. What value of specific latent heat of fusion does this give, and how does it compare to the accepted value of 334 000 J/kg?',
     'option_a':'315 000 J/kg; 5.7% below accepted value',
     'option_b':'315 000 J/kg; 5.7% above accepted value',
     'option_c':'31 500 J/kg; very different from accepted value',
     'option_d':'350 000 J/kg; 4.8% above accepted value',
     'correct_answer':'A',
     'explanation':'L = Q/m = 18 900 / 0.060 = 315 000 J/kg. % difference = (334 000 - 315 000)/334 000 x 100 = 5.7% below.',
     'correction_tip':'L = Q/m. Then percentage difference = |calculated - accepted| / accepted x 100.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':4,
     'question_text':'A student compresses a gas in a sealed syringe from 80 cm^3 at 1.0 x 10^5 Pa to 20 cm^3. Assuming constant temperature, what is the final pressure and what does it suggest about the relationship between pressure and volume?',
     'option_a':'4.0 x 10^5 Pa; pressure is directly proportional to volume',
     'option_b':'4.0 x 10^5 Pa; pressure is inversely proportional to volume',
     'option_c':'0.25 x 10^5 Pa; pressure is inversely proportional to volume',
     'option_d':'0.25 x 10^5 Pa; pressure is directly proportional to volume',
     'correct_answer':'B',
     'explanation':'P2 = P1V1/V2 = (1.0 x 10^5 x 80) / 20 = 4.0 x 10^5 Pa. Volume decreased by factor 4, pressure increased by factor 4: confirms Boyle\'s Law (inverse proportionality).',
     'correction_tip':'When V halves, P doubles (at constant T). This is inverse proportionality: P x V = constant.'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':4,
     'question_text':'A hollow metal sphere has an outer radius of 5 cm and an inner radius of 4 cm. The metal has a density of 8000 kg/m^3. What is the mass of the sphere? (Volume of sphere = (4/3)pi r^3)',
     'option_a':'0.0615 kg','option_b':'4.19 kg','option_c':'2.04 kg','option_d':'0.492 kg',
     'correct_answer':'C',
     'explanation':'Convert: r_outer = 0.05 m, r_inner = 0.04 m. V_outer = (4/3) x pi x (0.05)^3 = 5.236 x 10^-4 m^3. V_inner = (4/3) x pi x (0.04)^3 = 2.681 x 10^-4 m^3. V_metal = 5.236e-4 - 2.681e-4 = 2.555 x 10^-4 m^3. Mass = 8000 x 2.555 x 10^-4 = 2.04 kg.',
     'correction_tip':'Volume of hollow sphere = V_outer - V_inner. Then mass = density x volume. Convert radii to metres first.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':4,
     'question_text':'A thermometer is used to track the temperature of a substance being cooled. The graph shows temperature falling, then remaining constant for a period, then falling again. What can be deduced about the substance and the flat region?',
     'option_a':'The substance is being heated; the flat region is an anomaly',
     'option_b':'The substance is freezing; the flat region represents the latent heat of fusion being released',
     'option_c':'The substance is evaporating; the flat region shows the boiling point',
     'option_d':'The substance is losing kinetic energy throughout with no change of state',
     'correct_answer':'B',
     'explanation':'A flat region on a cooling curve indicates a change of state. During freezing, particles lose potential energy (bonds form) at constant temperature, releasing latent heat.',
     'correction_tip':'Flat region on a cooling curve = freezing (solid forming). Latent heat is released to surroundings.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':4,
     'question_text':'A gas at 27 degrees C and 1 x 10^5 Pa has a volume of 3 L. It is heated to 327 degrees C at constant pressure. What is the new volume?',
     'option_a':'6 L','option_b':'3 L','option_c':'1.5 L','option_d':'9 L',
     'correct_answer':'A',
     'explanation':'At constant pressure, V/T = constant (Charles\'s Law). T1 = 300 K, T2 = 600 K. V2 = V1 x T2/T1 = 3 x 600/300 = 6 L.',
     'correction_tip':'Charles\'s Law: V1/T1 = V2/T2 (constant pressure). Always use Kelvin.'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':4,
     'question_text':'In a hydraulic press, the effort piston has an area of 5 cm^2 and the load piston has an area of 200 cm^2. If a load of 8000 N must be lifted, what effort force is needed? What is the mechanical advantage?',
     'option_a':'Effort = 200 N; MA = 40','option_b':'Effort = 8000 N; MA = 1',
     'option_c':'Effort = 320 000 N; MA = 0.025','option_d':'Effort = 400 N; MA = 20',
     'correct_answer':'A',
     'explanation':'Pressure is equal throughout: F1/A1 = F2/A2. F1 = F2 x A1/A2 = 8000 x 5/200 = 200 N. MA = load/effort = 8000/200 = 40.',
     'correction_tip':'F1/A1 = F2/A2 (pressure equal). MA = load/effort = A_load/A_effort.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':4,
     'question_text':'A fixed amount of gas at pressure 2.5 x 10^5 Pa, volume 4 m^3, and temperature 500 K is compressed to 1 m^3 and cooled to 250 K. What is the new pressure?',
     'option_a':'5 x 10^5 Pa','option_b':'2.5 x 10^5 Pa','option_c':'10 x 10^5 Pa','option_d':'1.25 x 10^5 Pa',
     'correct_answer':'A',
     'explanation':'P1V1/T1 = P2V2/T2. P2 = P1V1T2 / (V2T1) = (2.5 x 10^5 x 4 x 250) / (1 x 500) = 2.5 x 10^8 / 500 = 5 x 10^5 Pa.',
     'correction_tip':'Use combined gas law: P1V1/T1 = P2V2/T2. Rearrange for P2.'},

    {'subject':'Physics','topic':'Density','topic_code':'P3','difficulty':4,
     'question_text':'A piece of wood of mass 240 g floats in water with 60% of its volume submerged. The density of water is 1000 kg/m^3. What is the density of the wood?',
     'option_a':'600 kg/m^3','option_b':'400 kg/m^3','option_c':'1667 kg/m^3','option_d':'1000 kg/m^3',
     'correct_answer':'A',
     'explanation':'For floating, weight = upthrust. Mass of displaced water = 240 g. Volume displaced = 0.240/1000 = 2.4 x 10^-4 m^3 = 60% of total volume. Total volume = 2.4 x 10^-4 / 0.6 = 4 x 10^-4 m^3. Density of wood = 0.240 / (4 x 10^-4) = 600 kg/m^3.',
     'correction_tip':'An object floats when density < fluid density. Use the fraction submerged = density of object / density of fluid.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':4,
     'question_text':'When a liquid cools and freezes, the temperature-time graph shows a flat region. During this flat region, which of the following is correct about the internal energy and particle arrangement?',
     'option_a':'Internal energy increases; particles become more disordered',
     'option_b':'Internal energy decreases; potential energy falls as bonds form and particles become ordered',
     'option_c':'Internal energy stays constant; particles do not change arrangement',
     'option_d':'Kinetic energy increases; potential energy decreases by the same amount',
     'correct_answer':'B',
     'explanation':'During freezing, the substance loses energy to the surroundings (latent heat of fusion released). Potential energy decreases as intermolecular bonds form and the regular lattice is established, while kinetic energy (and temperature) remain constant.',
     'correction_tip':'Freezing = PE decreases (bonds form), KE constant, temperature constant, internal energy overall decreases.'},

    {'subject':'Physics','topic':'Gas laws','topic_code':'P3','difficulty':4,
     'question_text':'A weather balloon has a volume of 1.5 m^3 at sea level where pressure is 100 kPa and temperature is 17 degrees C. At high altitude the pressure is 30 kPa and temperature is -43 degrees C. What is the new volume of the balloon?',
     'option_a':'4.0 m^3','option_b':'5.0 m^3','option_c':'3.0 m^3','option_d':'7.5 m^3',
     'correct_answer':'A',
     'explanation':'T1 = 17 + 273 = 290 K. T2 = -43 + 273 = 230 K. V2 = P1V1T2/(P2T1) = (100 x 1.5 x 230) / (30 x 290) = 34 500 / 8700 = 3.97 m^3, approximately 4.0 m^3.',
     'correction_tip':'Combined gas law: V2 = P1V1T2 / (P2T1). Convert all temperatures to Kelvin (add 273).'},

    {'subject':'Physics','topic':'Pressure','topic_code':'P3','difficulty':4,
     'question_text':'A gas molecule of mass 3 x 10^-26 kg in a container moves at 500 m/s and bounces elastically off a wall. If there are 6 x 10^20 such collisions per second on a wall of area 0.01 m^2, estimate the pressure on the wall.',
     'option_a':'1.8 x 10^3 Pa','option_b':'1.8 x 10^5 Pa','option_c':'9 x 10^3 Pa','option_d':'9 x 10^5 Pa',
     'correct_answer':'A',
     'explanation':'Change in momentum per collision = 2mv = 2 x 3x10^-26 x 500 = 3 x 10^-23 kg m/s. Total force = 3 x 10^-23 x 6 x 10^20 = 18 N. Pressure = F/A = 18 / 0.01 = 1800 Pa = 1.8 x 10^3 Pa.',
     'correction_tip':'Force = rate of change of momentum. For N collisions per second: F = N x 2mv. Then P = F/A.'},

    {'subject':'Physics','topic':'States of matter','topic_code':'P3','difficulty':4,
     'question_text':'A student heats 200 g of a substance in an insulated container using a 50 W heater. The temperature rises by 25 degrees C in 120 s. Calculate the specific heat capacity and identify a likely source of error.',
     'option_a':'c = 1200 J/kg degrees C; heater power varied',
     'option_b':'c = 480 J/kg degrees C; no errors possible in insulated container',
     'option_c':'c = 1200 J/kg degrees C; energy lost to surroundings despite insulation',
     'option_d':'c = 600 J/kg degrees C; the heater only worked at 50% efficiency',
     'correct_answer':'C',
     'explanation':'Energy supplied: Q = P x t = 50 x 120 = 6000 J. c = Q/(mDeltaT) = 6000 / (0.2 x 25) = 6000/5 = 1200 J/kg degrees C. Energy is always lost to surroundings even with insulation, so the true SHC would be slightly higher.',
     'correction_tip':'Q = Pt for electrical heater. Then c = Q/(mDeltaT). Energy losses mean calculated c is slightly too low.'},

    # =========================================================================
    # P4 ATOMIC STRUCTURE — 57 questions
    # D1: 15, D2: 14, D3: 14, D4: 14
    # =========================================================================

    # --- P4 Easy (D1) — 15 questions ---

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'What are the three subatomic particles that make up an atom?',
     'option_a':'Protons, neutrons, and photons',
     'option_b':'Protons, electrons, and neutrons',
     'option_c':'Quarks, electrons, and bosons',
     'option_d':'Protons, neutrinos, and electrons',
     'correct_answer':'B',
     'explanation':'An atom consists of protons and neutrons in the nucleus, surrounded by electrons in shells.',
     'correction_tip':'Protons (+), neutrons (0) in nucleus; electrons (-) in shells outside.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'What is the atomic number of an element?',
     'option_a':'The number of neutrons in the nucleus',
     'option_b':'The total number of protons and neutrons',
     'option_c':'The number of protons in the nucleus',
     'option_d':'The number of electrons in the outer shell',
     'correct_answer':'C',
     'explanation':'The atomic number (Z) is the number of protons in the nucleus. It defines which element the atom is.',
     'correction_tip':'Atomic number = number of protons. Mass number = protons + neutrons.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'What is the mass number of an atom?',
     'option_a':'The number of protons only','option_b':'The number of electrons',
     'option_c':'The number of protons plus the number of neutrons','option_d':'The number of neutrons only',
     'correct_answer':'C',
     'explanation':'Mass number (A) = number of protons + number of neutrons in the nucleus.',
     'correction_tip':'Mass number = protons + neutrons. Atomic number = protons only.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'What are isotopes?',
     'option_a':'Atoms of different elements with the same number of protons',
     'option_b':'Atoms of the same element with different numbers of neutrons',
     'option_c':'Atoms of the same element with different numbers of electrons',
     'option_d':'Ions with different charges',
     'correct_answer':'B',
     'explanation':'Isotopes are atoms of the same element (same number of protons) but with different numbers of neutrons, so they have different mass numbers.',
     'correction_tip':'Isotopes: same proton number (same element), different neutron number (different mass number).'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':1,
     'question_text':'What is emitted during alpha decay?',
     'option_a':'A high-energy electron','option_b':'A helium-4 nucleus (2 protons, 2 neutrons)',
     'option_c':'A photon of electromagnetic radiation','option_d':'A neutron',
     'correct_answer':'B',
     'explanation':'An alpha particle is a helium-4 nucleus, consisting of 2 protons and 2 neutrons. It is emitted from the nucleus during alpha decay.',
     'correction_tip':'Alpha = helium-4 nucleus (2p + 2n). Very ionising but stopped by paper.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':1,
     'question_text':'Which type of nuclear radiation has the greatest penetrating power?',
     'option_a':'Alpha','option_b':'Beta','option_c':'Gamma','option_d':'All have equal penetrating power',
     'correct_answer':'C',
     'explanation':'Gamma radiation is electromagnetic waves with very high frequency. It can penetrate several centimetres of lead or metres of concrete.',
     'correction_tip':'Penetrating power: gamma > beta > alpha. Gamma needs thick lead to absorb it.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':1,
     'question_text':'Which type of radiation is stopped by a sheet of paper?',
     'option_a':'Gamma','option_b':'Beta','option_c':'Alpha','option_d':'X-rays',
     'correct_answer':'C',
     'explanation':'Alpha particles are large (2p+2n) and highly ionising but have very low penetrating power. A sheet of paper or a few centimetres of air will stop them.',
     'correction_tip':'Alpha stopped by paper; beta stopped by few mm of aluminium; gamma needs thick lead/concrete.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':1,
     'question_text':'What is background radiation?',
     'option_a':'Radiation emitted only from nuclear power stations',
     'option_b':'Low-level radiation always present in the environment from natural and artificial sources',
     'option_c':'Radiation from the Sun only',
     'option_d':'Radiation that cannot be detected by Geiger counters',
     'correct_answer':'B',
     'explanation':'Background radiation is the low-level ionising radiation always present in the environment. Sources include radon gas, cosmic rays, rocks, food, and medical sources.',
     'correction_tip':'Background radiation is always present; sources include radon, cosmic rays, rocks/soil, and medical/industrial sources.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':1,
     'question_text':'What is meant by the half-life of a radioactive isotope?',
     'option_a':'The time for all the atoms in a sample to decay',
     'option_b':'The time for half the radioactive atoms in a sample to decay',
     'option_c':'The time for the activity to double',
     'option_d':'Half the time it takes for the sample to become safe',
     'correct_answer':'B',
     'explanation':'The half-life is the time taken for half of the radioactive nuclei in a sample to decay. After one half-life, activity is halved.',
     'correction_tip':'Half-life: time for HALF of the nuclei (or activity) to decrease by half. It is constant for a given isotope.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'In the Rutherford scattering experiment, what was fired at a thin gold foil?',
     'option_a':'Electrons','option_b':'Gamma rays',
     'option_c':'Alpha particles','option_d':'Neutrons',
     'correct_answer':'C',
     'explanation':'In the Geiger-Marsden experiment (directed by Rutherford), alpha particles were fired at a thin gold foil to investigate atomic structure.',
     'correction_tip':'Rutherford scattering: alpha particles fired at gold foil; some deflected back, revealing the nucleus.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':1,
     'question_text':'What model of the atom did Rutherford propose after his scattering experiment?',
     'option_a':'The plum pudding model (electrons embedded in positive sphere)',
     'option_b':'The nuclear model (tiny, dense, positive nucleus with electrons orbiting at a distance)',
     'option_c':'The shell model with electrons in fixed energy levels',
     'option_d':'The solid sphere model',
     'correct_answer':'B',
     'explanation':'Rutherford concluded that the atom is mostly empty space with a tiny, dense, positively charged nucleus at the centre, and electrons orbiting at relatively large distances.',
     'correction_tip':'Rutherford: most alpha particles passed straight through (atom is mostly empty), some deflected back (dense positive nucleus).'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':1,
     'question_text':'Which particle is emitted during beta-minus decay?',
     'option_a':'Proton','option_b':'Alpha particle',
     'option_c':'High-energy electron (from the nucleus)','option_d':'Neutron',
     'correct_answer':'C',
     'explanation':'In beta-minus decay, a neutron in the nucleus decays into a proton and a high-energy electron (beta particle), which is emitted.',
     'correction_tip':'Beta-minus: neutron to proton + electron. The electron is emitted as the beta particle.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':1,
     'question_text':'Which type of radiation has no mass and no charge?',
     'option_a':'Alpha','option_b':'Beta',
     'option_c':'Gamma','option_d':'Neutron radiation',
     'correct_answer':'C',
     'explanation':'Gamma radiation consists of high-frequency electromagnetic waves. It has no mass and no charge.',
     'correction_tip':'Gamma = electromagnetic wave; mass = 0, charge = 0. Alpha = charge +2; beta = charge -1.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':1,
     'question_text':'A radioactive sample has an activity of 800 Bq. After two half-lives, what is its activity?',
     'option_a':'400 Bq','option_b':'200 Bq','option_c':'100 Bq','option_d':'600 Bq',
     'correct_answer':'B',
     'explanation':'After 1 half-life: 800 / 2 = 400 Bq. After 2 half-lives: 400 / 2 = 200 Bq.',
     'correction_tip':'Each half-life halves the activity. After n half-lives, activity = initial / 2^n.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':1,
     'question_text':'What is nuclear fission?',
     'option_a':'Two small nuclei combining to form a larger nucleus',
     'option_b':'A large nucleus splitting into two smaller nuclei, releasing energy',
     'option_c':'An electron being emitted from the nucleus',
     'option_d':'A nucleus emitting a gamma ray photon',
     'correct_answer':'B',
     'explanation':'Nuclear fission is the splitting of a large, unstable nucleus (e.g. uranium-235) into two smaller nuclei, releasing a large amount of energy and neutrons.',
     'correction_tip':'Fission = splitting (large nucleus breaks into smaller ones). Fusion = joining (small nuclei combine).'},

    # --- P4 Medium (D2) — 14 questions ---

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':2,
     'question_text':'An atom of carbon has the symbol 12C with atomic number 6. How many neutrons does it have?',
     'option_a':'12','option_b':'6','option_c':'18','option_d':'3',
     'correct_answer':'B',
     'explanation':'Neutrons = mass number - atomic number = 12 - 6 = 6.',
     'correction_tip':'Neutrons = mass number - atomic number. Protons = atomic number.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':2,
     'question_text':'Carbon-12 and carbon-14 are isotopes. How do they differ?',
     'option_a':'They have different numbers of protons','option_b':'They have different numbers of electrons',
     'option_c':'Carbon-14 has 2 more neutrons than carbon-12','option_d':'They are different elements',
     'correct_answer':'C',
     'explanation':'Both have 6 protons (both are carbon). Carbon-12 has 6 neutrons; carbon-14 has 8 neutrons. They differ by 2 neutrons.',
     'correction_tip':'Isotopes: same protons, different neutrons. Mass number difference = neutron number difference.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'What are the changes to atomic number and mass number when an alpha particle is emitted?',
     'option_a':'Atomic number decreases by 2; mass number decreases by 4',
     'option_b':'Atomic number decreases by 4; mass number decreases by 2',
     'option_c':'Atomic number increases by 2; mass number increases by 4',
     'option_d':'Atomic number decreases by 1; mass number unchanged',
     'correct_answer':'A',
     'explanation':'An alpha particle has 2 protons and 2 neutrons. Emitting it reduces the atomic number by 2 and the mass number by 4.',
     'correction_tip':'Alpha emission: Z decreases by 2, A decreases by 4.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'What are the changes to atomic number and mass number when a beta-minus particle is emitted?',
     'option_a':'Atomic number increases by 1; mass number unchanged',
     'option_b':'Atomic number decreases by 1; mass number unchanged',
     'option_c':'Atomic number unchanged; mass number decreases by 1',
     'option_d':'Atomic number increases by 2; mass number decreases by 2',
     'correct_answer':'A',
     'explanation':'In beta-minus decay, a neutron becomes a proton (Z increases by 1) and an electron is emitted. Mass number does not change (proton count goes up, neutron count goes down).',
     'correction_tip':'Beta-minus decay: Z increases by 1, A unchanged (neutron becomes proton).'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':2,
     'question_text':'Which type of nuclear radiation is the most ionising?',
     'option_a':'Gamma','option_b':'Beta','option_c':'Alpha','option_d':'X-rays',
     'correct_answer':'C',
     'explanation':'Alpha particles are the most ionising because they are large, slow, and carry a +2 charge, causing many ionisations over a short distance.',
     'correction_tip':'Ionising power: alpha > beta > gamma. Penetrating power: gamma > beta > alpha. (They are inversely related.)'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':2,
     'question_text':'A radioactive isotope has a half-life of 8 days. Starting with 6400 Bq, what is the activity after 32 days?',
     'option_a':'800 Bq','option_b':'400 Bq','option_c':'200 Bq','option_d':'1600 Bq',
     'correct_answer':'B',
     'explanation':'Number of half-lives = 32/8 = 4. Activity = 6400 / 2^4 = 6400 / 16 = 400 Bq.',
     'correction_tip':'Count how many half-lives fit into the total time. Activity = A0 / 2^n.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'What observation from the Rutherford scattering experiment led to the conclusion that most of the atom is empty space?',
     'option_a':'Most alpha particles were deflected through large angles',
     'option_b':'Most alpha particles passed straight through the foil with little or no deflection',
     'option_c':'All alpha particles bounced straight back',
     'option_d':'The gold foil was destroyed by the radiation',
     'correct_answer':'B',
     'explanation':'Most alpha particles passed through the foil with little deflection, indicating the atom is mostly empty space. Only a tiny fraction were deflected back, suggesting a tiny dense nucleus.',
     'correction_tip':'Most particles through = mostly empty space. Few deflected back = tiny dense positive nucleus.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'Which of the following is a use of radioactive tracers in medicine?',
     'option_a':'Irradiating food to kill bacteria','option_b':'Detecting the presence of cancer using PET scans',
     'option_c':'Powering pacemakers','option_d':'Dating ancient rocks',
     'correct_answer':'B',
     'explanation':'Radioactive tracers (e.g. fluorine-18) are used in PET scans to detect cancer. The tracer emits positrons (gamma) that are detected outside the body.',
     'correction_tip':'Tracer = radioactive substance taken into body; detected externally to track biological processes.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':2,
     'question_text':'Why is gamma radiation used in cancer treatment (radiotherapy) rather than alpha radiation?',
     'option_a':'Gamma is more ionising and causes more damage','option_b':'Alpha is cheaper to produce',
     'option_c':'Gamma can penetrate tissues to reach deep tumours; alpha cannot penetrate deeply enough',
     'option_d':'Alpha has no charge so it cannot target cells',
     'correct_answer':'C',
     'explanation':'Gamma radiation can penetrate deeply into the body to reach tumours. Alpha radiation is stopped by skin and cannot penetrate to internal organs.',
     'correction_tip':'Gamma = high penetrating power = can reach internal tumours. Alpha stopped by skin.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':2,
     'question_text':'The plum pudding model described the atom as a positive sphere with electrons embedded in it. What evidence from Rutherford scattering disproved this model?',
     'option_a':'Some alpha particles were deflected through large angles or bounced back, showing the positive charge is concentrated in a tiny nucleus',
     'option_b':'Alpha particles were slowed down by the sphere of positive charge',
     'option_c':'None of the alpha particles were deflected',
     'option_d':'Electrons were knocked out of the gold atoms',
     'correct_answer':'A',
     'explanation':'If the positive charge were spread throughout the atom (plum pudding), no large deflections would occur. The fact that some alpha particles bounced back showed the positive charge is concentrated in a tiny dense nucleus.',
     'correction_tip':'Large deflections and back-scattering disproved plum pudding; proved dense positive nucleus exists.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'What is meant by the activity of a radioactive source?',
     'option_a':'The total number of radioactive atoms in the source',
     'option_b':'The number of nuclear decays per second, measured in becquerel (Bq)',
     'option_c':'The energy released per decay',
     'option_d':'The penetrating power of the radiation emitted',
     'correct_answer':'B',
     'explanation':'Activity is the number of radioactive decays per second. The unit is the becquerel (Bq), where 1 Bq = 1 decay per second.',
     'correction_tip':'Activity = decays per second, unit = Bq (becquerel).'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':2,
     'question_text':'Why is carbon-14 useful for dating organic remains, but not for dating rocks that are millions of years old?',
     'option_a':'Carbon-14 is found only in organic materials and decays too quickly over millions of years',
     'option_b':'Carbon-14 is radioactive and dangerous to use on old rocks',
     'option_c':'Carbon-14 has too long a half-life to be useful for organic remains',
     'option_d':'Carbon-14 is only found in rocks, not in organic materials',
     'correct_answer':'A',
     'explanation':'Carbon-14 has a half-life of ~5700 years. After millions of years, virtually no C-14 would remain in rocks, making it undetectable. Longer half-life isotopes (e.g. uranium-238) are used for old rocks.',
     'correction_tip':'Use an isotope whose half-life is comparable to the age being measured. C-14 (5700 years) = organic remains; U-238 (4.5 billion years) = rocks.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':2,
     'question_text':'What is nuclear fusion?',
     'option_a':'A large nucleus splitting into two smaller nuclei',
     'option_b':'Two light nuclei joining together to form a heavier nucleus, releasing energy',
     'option_c':'An atom losing electrons to form a positive ion',
     'option_d':'A neutron splitting into a proton and an electron',
     'correct_answer':'B',
     'explanation':'Nuclear fusion is the joining of two light nuclei (e.g. hydrogen isotopes) to form a heavier nucleus, releasing a large amount of energy. This powers the Sun.',
     'correction_tip':'Fusion = combining nuclei (like in the Sun). Fission = splitting nuclei (like in nuclear reactors).'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':2,
     'question_text':'Which statement about ionising radiation and health is correct?',
     'option_a':'Ionising radiation always causes immediate death',
     'option_b':'Ionising radiation can damage or kill cells, and may cause cancer or mutations in DNA',
     'option_c':'Low doses of ionising radiation are always beneficial',
     'option_d':'Only alpha radiation causes health risks',
     'correct_answer':'B',
     'explanation':'Ionising radiation can damage DNA in cells. This may cause cancer (if cells multiply uncontrollably) or cell death. Higher doses cause more damage.',
     'correction_tip':'Ionising radiation = can damage DNA, cause cancer or cell death. Higher dose = greater risk.'},

    # --- P4 Hard (D3) — 14 questions ---

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':3,
     'question_text':'Complete the nuclear equation for the alpha decay of radium-226 (atomic number 88): Ra-226 to X + alpha. What is the element X and its mass/atomic numbers?',
     'option_a':'Radon-222, atomic number 86','option_b':'Polonium-222, atomic number 84',
     'option_c':'Thorium-230, atomic number 90','option_d':'Francium-222, atomic number 87',
     'correct_answer':'A',
     'explanation':'Alpha decay: mass number decreases by 4 (226 - 4 = 222), atomic number decreases by 2 (88 - 2 = 86). Element with Z=86 is Radon. Product: Rn-222.',
     'correction_tip':'Alpha decay: A - 4, Z - 2. Use a periodic table to find the new element from its atomic number.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':3,
     'question_text':'Carbon-14 undergoes beta-minus decay. Write the correct nuclear equation products. (Carbon has atomic number 6.)',
     'option_a':'14C becomes 14N (Z=7) + beta particle',
     'option_b':'14C becomes 13B (Z=5) + beta particle',
     'option_c':'14C becomes 14B (Z=5) + beta particle',
     'option_d':'14C becomes 10Be (Z=4) + alpha particle',
     'correct_answer':'A',
     'explanation':'Beta-minus decay: a neutron becomes a proton. Z increases by 1 (6 to 7 = Nitrogen). Mass number unchanged (14). So: C-14 decays to N-14 + beta particle.',
     'correction_tip':'Beta-minus: Z + 1, A unchanged. Carbon (Z=6) becomes Nitrogen (Z=7).'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':3,
     'question_text':'A sample of a radioactive isotope has an initial activity of 3200 Bq. After 60 hours the activity is 100 Bq. What is the half-life of the isotope?',
     'option_a':'10 hours','option_b':'12 hours','option_c':'15 hours','option_d':'20 hours',
     'correct_answer':'B',
     'explanation':'3200 to 100 is a reduction by factor 32 = 2^5. So 5 half-lives have passed. Half-life = 60/5 = 12 hours.',
     'correction_tip':'Find how many times the activity has halved: 3200 / 100 = 32 = 2^5, so 5 half-lives. Then half-life = total time / number of half-lives.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':3,
     'question_text':'A radioactive sample has a half-life of 20 minutes. After how many minutes will the activity fall to 6.25% of its original value?',
     'option_a':'40 min','option_b':'60 min','option_c':'80 min','option_d':'100 min',
     'correct_answer':'C',
     'explanation':'6.25% = 1/16 = 1/2^4. So 4 half-lives are needed. Time = 4 x 20 = 80 minutes.',
     'correction_tip':'Express the fraction as a power of 1/2: 6.25% = 6.25/100 = 1/16 = (1/2)^4. Then multiply by half-life.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':3,
     'question_text':'A Geiger counter measures the count rate near a source as 520 counts/min. The background count rate is 20 counts/min. What is the corrected count rate from the source?',
     'option_a':'540 counts/min','option_b':'520 counts/min',
     'option_c':'500 counts/min','option_d':'26 counts/min',
     'correct_answer':'C',
     'explanation':'Corrected count rate = measured count rate - background count rate = 520 - 20 = 500 counts/min.',
     'correction_tip':'Always subtract background radiation from measurements: corrected = measured - background.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':3,
     'question_text':'Uranium-235 undergoes fission when struck by a neutron. A possible reaction is: U-235 + n → Ba-141 + Kr-92 + x neutrons. How many neutrons (x) are released?',
     'option_a':'1','option_b':'2','option_c':'3','option_d':'4',
     'correct_answer':'C',
     'explanation':'Mass numbers must balance: 235 + 1 = 141 + 92 + x. So x = 236 - 233 = 3 neutrons.',
     'correction_tip':'Balance mass numbers: total before = total after. 235 + 1 = 141 + 92 + x. Solve for x.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':3,
     'question_text':'In a nuclear reactor, what is the role of control rods?',
     'option_a':'To slow down the neutrons to thermal speeds',
     'option_b':'To absorb excess neutrons and control the rate of fission',
     'option_c':'To provide fuel for the chain reaction',
     'option_d':'To convert heat into electricity',
     'correct_answer':'B',
     'explanation':'Control rods (e.g. boron) absorb neutrons. Inserting them deeper slows the chain reaction; withdrawing them speeds it up, controlling the power output of the reactor.',
     'correction_tip':'Control rods absorb neutrons; more in = slower reaction. Moderator slows neutrons; coolant transfers heat.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':3,
     'question_text':'An experiment measures the count rate with different materials between a source and a Geiger tube. The count rate drops significantly with a few mm of aluminium but is barely reduced by paper. What type of radiation is the source most likely emitting?',
     'option_a':'Gamma only','option_b':'Alpha only',
     'option_c':'Beta only','option_d':'A mixture of alpha and gamma',
     'correct_answer':'C',
     'explanation':'Beta is stopped by a few mm of aluminium but passes through paper. Alpha is stopped by paper. Gamma is barely stopped by aluminium. The evidence points to beta radiation.',
     'correction_tip':'Use absorption to identify radiation: paper stops alpha; mm of Al stops beta; thick lead stops gamma.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':3,
     'question_text':'A radioactive isotope has a half-life of 5 years. A sample currently contains 6 x 10^20 atoms. How many radioactive atoms will remain after 20 years?',
     'option_a':'3 x 10^20','option_b':'1.5 x 10^20',
     'option_c':'3.75 x 10^19','option_d':'7.5 x 10^19',
     'correct_answer':'C',
     'explanation':'Number of half-lives = 20/5 = 4. Remaining atoms = 6 x 10^20 / 2^4 = 6 x 10^20 / 16 = 3.75 x 10^19.',
     'correction_tip':'After n half-lives, N = N0 / 2^n. Count how many half-lives fit into the time given.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':3,
     'question_text':'Why must scientists working with radioactive materials take precautions such as using tongs, lead-lined containers, and standing behind shields?',
     'option_a':'To prevent the radioactive material from contaminating equipment',
     'option_b':'To reduce the dose of ionising radiation received, minimising the risk of cell damage and cancer',
     'option_c':'Radioactive materials are chemically corrosive',
     'option_d':'Lead is attracted to radioactive materials',
     'correct_answer':'B',
     'explanation':'Ionising radiation can damage DNA and cells, leading to cancer or radiation sickness. Lead absorbs gamma; distance reduces intensity; tongs avoid contamination. All reduce radiation dose.',
     'correction_tip':'Dose reduction: maximise distance, minimise time, use shielding. Reduces risk of DNA damage and cancer.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':3,
     'question_text':'Bohr modified Rutherford\'s model by proposing that electrons orbit the nucleus in fixed energy levels (shells). What experimental evidence supports this?',
     'option_a':'The existence of isotopes','option_b':'The line emission spectra of excited atoms',
     'option_c':'The deflection of alpha particles','option_d':'The existence of beta radiation',
     'correct_answer':'B',
     'explanation':'When atoms are excited, electrons jump to higher energy levels and then fall back, emitting light of specific frequencies (line spectra). This is only possible if energy levels are discrete (fixed), supporting the Bohr model.',
     'correction_tip':'Line spectra = evidence for discrete energy levels. Electrons only emit specific frequencies when falling between fixed shells.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':3,
     'question_text':'Technetium-99m is used as a medical tracer. It decays by emitting only gamma radiation with a half-life of about 6 hours. Why are these properties ideal for medical imaging?',
     'option_a':'Long half-life means it stays in the body for a long time; alpha is safe internally',
     'option_b':'Gamma can be detected outside the body; short half-life means radiation dose is low; gamma is less ionising internally',
     'option_c':'Short half-life means high initial activity is useful for long scans',
     'option_d':'Gamma cannot penetrate body tissue and stays localised',
     'correct_answer':'B',
     'explanation':'Gamma rays are detected outside the body. The 6-hour half-life means activity drops quickly (low total dose to patient). Gamma is less ionising than alpha/beta inside the body, reducing cell damage.',
     'correction_tip':'Ideal medical tracer: gamma (detected externally, less ionising internally), short half-life (low dose), targets specific tissue.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':3,
     'question_text':'An alpha source inside the body is considered more dangerous than one outside the body, even though alpha has low penetrating power. Why?',
     'option_a':'Alpha can pass through internal organs more easily','option_b':'Alpha becomes beta inside the body',
     'option_c':'Inside the body, alpha particles cause intense ionisation of nearby cells because they cannot escape and deposit all their energy locally',
     'option_d':'The magnetic field inside the body deflects alpha towards organs',
     'correct_answer':'C',
     'explanation':'When an alpha source is outside the body, alpha particles are stopped by skin and cause no internal damage. Inside the body, the high ionising power of alpha causes severe, concentrated damage to nearby cells and DNA.',
     'correction_tip':'Alpha is most dangerous inside the body (intense ionisation in local tissue). Outside the body, skin blocks alpha completely.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':3,
     'question_text':'A graph of activity versus time for a radioactive source shows the activity halving every 4 minutes. If the initial activity was 1600 Bq, write an expression for activity A after time t (in minutes).',
     'option_a':'A = 1600 x 2^(t/4)','option_b':'A = 1600 x (0.5)^(t/4)',
     'option_c':'A = 1600 - 400t','option_d':'A = 1600 / t',
     'correct_answer':'B',
     'explanation':'The activity halves every 4 minutes (the half-life). A = A0 x (0.5)^(t/T_half) = 1600 x (0.5)^(t/4).',
     'correction_tip':'General formula: A = A0 x (1/2)^(t / T_half). This gives exponential decay.'},

    # --- P4 Exam Challenge (D4) — 14 questions ---

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':4,
     'question_text':'A sample of radioactive iodine-131 (half-life = 8 days) has an initial activity of 25 600 Bq. A patient requires the activity to be 200 Bq before disposal. How many days must the hospital store the sample before disposal?',
     'option_a':'64 days','option_b':'56 days','option_c':'48 days','option_d':'72 days',
     'correct_answer':'B',
     'explanation':'25 600 to 200: factor = 128 = 2^7. So 7 half-lives needed. Time = 7 x 8 = 56 days.',
     'correction_tip':'25600 / 200 = 128 = 2^7, so 7 half-lives. Multiply by the half-life duration.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':4,
     'question_text':'Thorium-234 (Z=90) undergoes beta-minus decay twice and then alpha decay once. What is the final nucleus produced?',
     'option_a':'Atomic number 90, mass number 226','option_b':'Atomic number 90, mass number 230',
     'option_c':'Atomic number 88, mass number 230','option_d':'Atomic number 86, mass number 228',
     'correct_answer':'B',
     'explanation':'Start: A=234, Z=90. Beta-minus decay 1: Z=91, A=234. Beta-minus decay 2: Z=92, A=234. Alpha decay: Z=90, A=230. Final: Z=90 (Thorium), A=230.',
     'correction_tip':'Apply each decay step by step: beta x2 raises Z by 2 (mass unchanged); alpha lowers Z by 2, A by 4. Net result: same Z as start, A reduced by 4.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':4,
     'question_text':'In a chain reaction using U-235, each fission releases 3 neutrons. If there is no moderation or control, and each neutron causes one more fission, how many fissions occur in the 5th generation (starting from 1 fission in generation 1)?',
     'option_a':'15','option_b':'81','option_c':'243','option_d':'3',
     'correct_answer':'B',
     'explanation':'Each fission produces 3 neutrons, each causing one new fission. Generation 1 = 1 = 3^0; Gen 2 = 3; Gen 3 = 9; Gen 4 = 27; Gen 5 = 81 = 3^4. General formula: Gen n = 3^(n-1).',
     'correction_tip':'In a chain reaction with 3 neutrons per fission: Gen n = 3^(n-1). Gen 5 = 3^4 = 81.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':4,
     'question_text':'A radiation detector records 860 counts per minute near a source. The background count is 20 counts per minute. After placing 5 mm of aluminium between the source and detector, the reading falls to 140 counts per minute. After adding a thick lead sheet, it falls to 22 counts per minute. What types of radiation does the source emit?',
     'option_a':'Alpha only',
     'option_b':'Beta and gamma',
     'option_c':'Alpha and beta',
     'option_d':'Alpha, beta and gamma',
     'correct_answer':'B',
     'explanation':'Corrected readings: no shield = 840, after Al = 120, after Pb = ~2. Paper (not mentioned) would check for alpha. Al stops beta (840 - 120 = 720 from beta). Remaining 120 corrected to ~2 after Pb = gamma. No paper check here, but if alpha were present it would have been stopped by the detector casing. The data shows beta (stopped by Al) and gamma (reduced by Pb). No evidence of alpha.',
     'correction_tip':'Identify radiation by what absorbs it: paper = alpha; aluminium = beta; thick lead = gamma. Always subtract background first.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':4,
     'question_text':'The count rate from a radioactive source at t=0 is 6400 counts/min. At t=24 hours it is 800 counts/min (background already subtracted). What is the half-life in hours?',
     'option_a':'6 hours','option_b':'8 hours','option_c':'12 hours','option_d':'4 hours',
     'correct_answer':'B',
     'explanation':'6400 / 800 = 8 = 2^3. So 3 half-lives in 24 hours. Half-life = 24 / 3 = 8 hours.',
     'correction_tip':'Divide initial by final count rate to find the factor. Express as 2^n, then half-life = total time / n.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':4,
     'question_text':'Explain, using nuclear equations, what happens during the alpha decay of americium-241 (Z=95, A=241) and state the daughter product.',
     'option_a':'Am-241 decays to Np-237 (Z=93) + He-4',
     'option_b':'Am-241 decays to Pu-237 (Z=94) + He-4',
     'option_c':'Am-241 decays to Np-241 (Z=93) + He-4',
     'option_d':'Am-241 decays to Cm-245 (Z=96) + He-4',
     'correct_answer':'A',
     'explanation':'Alpha decay: A decreases by 4 (241-4=237), Z decreases by 2 (95-2=93). Z=93 is Neptunium (Np). Daughter product: Np-237.',
     'correction_tip':'Alpha decay: A - 4, Z - 2. Find the element from the new atomic number.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':4,
     'question_text':'Scientists first proposed the plum pudding model, then the nuclear model, then added electron shells (Bohr model). What drives these changes in scientific models?',
     'option_a':'Scientists change models to make them more complicated',
     'option_b':'New experimental evidence that cannot be explained by the current model causes scientists to modify or replace it',
     'option_c':'Models change when scientists disagree with each other',
     'option_d':'Older models are discarded without needing evidence',
     'correct_answer':'B',
     'explanation':'Scientific models evolve when new experimental evidence cannot be explained by the existing model. Rutherford\'s scattering results contradicted the plum pudding model, leading to the nuclear model. Line spectra required the addition of quantised energy levels.',
     'correction_tip':'Science progresses by testing models against evidence. If evidence contradicts a model, the model must be revised or replaced.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':4,
     'question_text':'A nuclear power station produces 1200 MW of electrical power with an efficiency of 40%. What is the total thermal power produced by the reactor, and what happens to the remaining energy?',
     'option_a':'Total = 3000 MW; remaining 1800 MW is wasted as heat to the environment',
     'option_b':'Total = 480 MW; remaining 720 MW is used to power the plant',
     'option_c':'Total = 1200 MW; all energy is converted to electricity',
     'option_d':'Total = 3000 MW; remaining 1800 MW is stored in batteries',
     'correct_answer':'A',
     'explanation':'Efficiency = useful output / total input. Total thermal power = 1200 / 0.40 = 3000 MW. Wasted power = 3000 - 1200 = 1800 MW, dissipated as heat (to cooling towers / river / sea).',
     'correction_tip':'Efficiency = useful power / total power. Rearrange: total power = useful / efficiency. Wasted = total - useful.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':4,
     'question_text':'Radon-222 (Z=86) undergoes alpha decay to form polonium. Polonium then undergoes beta-minus decay. What is the atomic number and mass number of the final product after both decays?',
     'option_a':'Z=85, A=218','option_b':'Z=84, A=218',
     'option_c':'Z=85, A=214','option_d':'Z=83, A=218',
     'correct_answer':'A',
     'explanation':'Alpha decay of Rn-222: Z=86-2=84 (Polonium), A=222-4=218. Beta-minus decay of Po-218: Z=84+1=85 (Astatine), A=218. Final: Z=85, A=218.',
     'correction_tip':'Step by step: alpha (Z-2, A-4), then beta-minus (Z+1, A unchanged). Track Z and A through each step.'},

    {'subject':'Physics','topic':'Half-life','topic_code':'P4','difficulty':4,
     'question_text':'Strontium-90 (half-life 29 years) is a radioactive isotope found in nuclear fallout. If an area is contaminated with strontium-90 at a level 400 times the safe limit, how many years must pass before it reaches the safe limit?',
     'option_a':'116 years','option_b':'145 years','option_c':'232 years','option_d':'261 years',
     'correct_answer':'D',
     'explanation':'2^8 = 256 (less than 400, so 8 half-lives are not enough). 2^9 = 512 (greater than 400, so 9 half-lives are sufficient to reduce the level to below the safe limit). Time = 9 x 29 = 261 years.',
     'correction_tip':'Check powers of 2: 2^8 = 256 (not enough for 400x reduction), 2^9 = 512 (sufficient). Minimum whole half-lives needed = 9. Time = 9 x 29 = 261 years.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':4,
     'question_text':'In a nuclear reactor, the moderator slows neutrons down. Why is this necessary for uranium-235 fission?',
     'option_a':'Fast neutrons cause the reactor to explode',
     'option_b':'U-235 fission is most likely to occur when neutrons are slow (thermal neutrons); fast neutrons are more likely to escape without causing fission',
     'option_c':'The moderator absorbs excess neutrons to control the reaction',
     'option_d':'Slow neutrons have greater mass and therefore more energy',
     'correct_answer':'B',
     'explanation':'U-235 has a much larger fission cross-section for slow (thermal) neutrons than for fast neutrons. The moderator (e.g. graphite or water) slows neutrons to thermal energies, greatly increasing the probability of inducing fission.',
     'correction_tip':'Moderator slows neutrons to thermal speeds, increasing probability of U-235 fission. Control rods absorb neutrons to regulate rate.'},

    {'subject':'Physics','topic':'Radioactivity','topic_code':'P4','difficulty':4,
     'question_text':'A student measures the count rate from a beta source at various distances. At 10 cm, the corrected count rate is 800 counts/min. At 20 cm, it is approximately 200 counts/min. What law does this illustrate and what would the count rate be at 40 cm?',
     'option_a':'Inverse square law; about 50 counts/min',
     'option_b':'Inverse law; about 100 counts/min',
     'option_c':'Inverse square law; about 100 counts/min',
     'option_d':'Exponential decay; about 25 counts/min',
     'correct_answer':'A',
     'explanation':'When distance doubles (10 to 20 cm), count rate decreases by factor 4 (800 to 200). This is the inverse square law: intensity is proportional to 1/d^2. At 40 cm (x4 the original distance): 800 / 16 = 50 counts/min.',
     'correction_tip':'Inverse square law: double distance = quarter the intensity. I proportional to 1/d^2.'},

    {'subject':'Physics','topic':'Nuclear radiation','topic_code':'P4','difficulty':4,
     'question_text':'Compare the risks and benefits of using radioactive tracers in medicine. Which statement best represents a balanced scientific view?',
     'option_a':'Radioactive tracers should never be used as they always cause cancer',
     'option_b':'The benefits of diagnosis (finding cancer, monitoring organ function) can outweigh the small radiation dose risk, but careful selection of tracer, dose, and half-life minimises risk',
     'option_c':'There are no risks associated with using medical tracers',
     'option_d':'Tracers are only safe if the patient is under 18',
     'correct_answer':'B',
     'explanation':'The risk of a small radiation dose must be weighed against the benefit of accurate diagnosis. Short half-life, gamma-emitting tracers minimise dose while enabling imaging. The decision should be based on individual patient risk-benefit analysis.',
     'correction_tip':'Risk-benefit analysis: consider type of radiation, half-life, dose, and diagnostic benefit. Balanced judgement required in exam questions.'},

    {'subject':'Physics','topic':'Atomic structure','topic_code':'P4','difficulty':4,
     'question_text':'Uranium-235 and uranium-238 are both found naturally but only U-235 can sustain a chain reaction in a thermal reactor. Natural uranium contains only 0.7% U-235. Why must uranium be enriched for use in most reactors, and what does enrichment involve?',
     'option_a':'Enrichment adds neutrons to U-238 to convert it to U-235',
     'option_b':'Enrichment removes all the U-238, leaving pure U-235',
     'option_c':'Enrichment increases the proportion of U-235 to about 3-5% so that the chain reaction can be sustained',
     'option_d':'Enrichment is not required; natural uranium works in all reactors',
     'correct_answer':'C',
     'explanation':'Natural uranium (0.7% U-235) has too low a concentration of fissile material to sustain a chain reaction in most reactor designs. Enrichment separates isotopes to increase U-235 concentration to about 3-5%, making a sustainable chain reaction possible.',
     'correction_tip':'Enrichment increases the proportion of fissile U-235. Separates isotopes physically (e.g. gas centrifuge) since they have slightly different masses.'},
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute('''INSERT INTO questions (subject,topic,topic_code,difficulty,question_text,
            option_a,option_b,option_c,option_d,correct_answer,explanation,correction_tip)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
