QUESTIONS = [
    # -------------------------------------------------------------------------
    # P7 MAGNETISM AND ELECTROMAGNETISM
    # -------------------------------------------------------------------------
    # --- D1 Easy (15 questions) ---
    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'Which poles of two magnets attract each other?',
     'option_a':'North and North',
     'option_b':'South and South',
     'option_c':'North and South',
     'option_d':'No poles attract',
     'correct_answer':'C',
     'explanation':'Opposite magnetic poles (north and south) attract each other; like poles repel.',
     'correction_tip':'Remember: unlike poles attract, like poles repel.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'What shape do magnetic field lines form around a bar magnet?',
     'option_a':'Straight parallel lines',
     'option_b':'Curved loops from north to south pole outside the magnet',
     'option_c':'Circles around the centre only',
     'option_d':'Random scattered lines',
     'correct_answer':'B',
     'explanation':'Magnetic field lines form closed loops, running from north to south outside the magnet and south to north inside.',
     'correction_tip':'Field lines always run from north to south outside the magnet.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'What happens to a piece of soft iron placed near a permanent magnet?',
     'option_a':'It becomes permanently magnetised',
     'option_b':'It is repelled',
     'option_c':'It becomes temporarily magnetised (induced magnet)',
     'option_d':'Nothing happens',
     'correct_answer':'C',
     'explanation':'Soft iron becomes an induced magnet when placed in a magnetic field, but loses its magnetism when removed from the field.',
     'correction_tip':'Soft iron is used for induced magnets because it magnetises and demagnetises easily.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'In which direction do magnetic field lines point outside a bar magnet?',
     'option_a':'From south to north',
     'option_b':'From north to south',
     'option_c':'They have no direction',
     'option_d':'Inward toward the centre',
     'correct_answer':'B',
     'explanation':'By convention, magnetic field lines point from the north pole to the south pole outside the magnet.',
     'correction_tip':'Field lines go from north to south outside the magnet (same direction as a compass needle points).'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'Which of the following materials is attracted to a magnet?',
     'option_a':'Copper',
     'option_b':'Aluminium',
     'option_c':'Iron',
     'option_d':'Plastic',
     'correct_answer':'C',
     'explanation':'Iron is a ferromagnetic material and is attracted to magnets. Copper, aluminium, and plastic are not magnetic.',
     'correction_tip':'Only ferromagnetic materials (iron, nickel, cobalt) are attracted to magnets.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':1,
     'question_text':'What is the name of the region around a magnet where magnetic forces act?',
     'option_a':'Electric field',
     'option_b':'Gravitational field',
     'option_c':'Magnetic field',
     'option_d':'Nuclear field',
     'correct_answer':'C',
     'explanation':'The region around a magnet in which a magnetic material experiences a force is called the magnetic field.',
     'correction_tip':'A magnetic field is detected by the force it exerts on magnetic materials or current-carrying conductors.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'What does a current-carrying conductor produce around it?',
     'option_a':'An electric field only',
     'option_b':'A gravitational field',
     'option_c':'A magnetic field',
     'option_d':'No field at all',
     'correct_answer':'C',
     'explanation':'Any current-carrying conductor produces a magnetic field in the space surrounding it.',
     'correction_tip':'Electricity and magnetism are linked: a current always creates a magnetic field.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'What shape are the magnetic field lines around a long straight current-carrying wire?',
     'option_a':'Straight lines parallel to the wire',
     'option_b':'Concentric circles centred on the wire',
     'option_c':'Spirals along the wire',
     'option_d':'Straight lines radiating outward',
     'correct_answer':'B',
     'explanation':'The magnetic field lines around a straight current-carrying conductor form concentric circles centred on the wire.',
     'correction_tip':'Use the right-hand rule: wrap fingers around wire in direction of field; thumb points in direction of current.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'What is a solenoid?',
     'option_a':'A single straight current-carrying wire',
     'option_b':'A coil of wire',
     'option_c':'A type of permanent magnet',
     'option_d':'A device that measures current',
     'correct_answer':'B',
     'explanation':'A solenoid is a coil of wire. When current flows through it, it produces a magnetic field similar to that of a bar magnet.',
     'correction_tip':'A solenoid with a soft iron core forms an electromagnet.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'How can the strength of an electromagnet be increased?',
     'option_a':'Decrease the current',
     'option_b':'Remove the iron core',
     'option_c':'Increase the number of turns on the coil',
     'option_d':'Use a shorter wire',
     'correct_answer':'C',
     'explanation':'Increasing the number of turns, increasing the current, or adding a soft iron core all increase the strength of an electromagnet.',
     'correction_tip':'More turns = stronger field, more current = stronger field, iron core = much stronger field.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'What rule is used to find the direction of the force on a current-carrying conductor in a magnetic field?',
     'option_a':'Right-hand rule',
     'option_b':'Fleming Left-Hand Rule',
     'option_c':'Lenz Law',
     'option_d':'Ohm Law',
     'correct_answer':'B',
     'explanation':'Fleming Left-Hand Rule gives the direction of the force (motor effect): thumb = force/motion, index = field, middle = current.',
     'correction_tip':'FBI: First finger = Field, seCond finger = Current, thuMb = Motion (force).'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':1,
     'question_text':'In an electric motor, what energy conversion takes place?',
     'option_a':'Electrical to chemical',
     'option_b':'Electrical to kinetic (mechanical)',
     'option_c':'Kinetic to electrical',
     'option_d':'Chemical to electrical',
     'correct_answer':'B',
     'explanation':'An electric motor converts electrical energy into kinetic (mechanical) energy using the motor effect.',
     'correction_tip':'Motor = electrical in, kinetic out. Generator = kinetic in, electrical out.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':1,
     'question_text':'What is electromagnetic induction?',
     'option_a':'Using a magnet to attract iron',
     'option_b':'The production of a voltage when a conductor moves in a magnetic field',
     'option_c':'Charging a capacitor',
     'option_d':'Increasing current in a circuit',
     'correct_answer':'B',
     'explanation':'Electromagnetic induction is the process by which a changing magnetic field (or relative motion between a conductor and field) induces a voltage in a conductor.',
     'correction_tip':'Induction requires movement or change - a stationary conductor in a static field produces no voltage.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':1,
     'question_text':'What type of current does an AC generator produce?',
     'option_a':'Direct current (DC)',
     'option_b':'Alternating current (AC)',
     'option_c':'No current',
     'option_d':'Pulsed DC',
     'correct_answer':'B',
     'explanation':'An AC generator (alternator) produces alternating current because the direction of the induced voltage reverses as the coil rotates.',
     'correction_tip':'AC = alternating current; the voltage alternates direction as the coil spins.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':1,
     'question_text':'A transformer is used to change which quantity?',
     'option_a':'Frequency of AC',
     'option_b':'Type of current (AC to DC)',
     'option_c':'Voltage of AC',
     'option_d':'Resistance in a circuit',
     'correct_answer':'C',
     'explanation':'Transformers change (step up or step down) the voltage of an alternating current supply.',
     'correction_tip':'Transformers only work with AC, not DC.'},

    # --- D2 Medium (15 questions) ---
    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':2,
     'question_text':'Where is the magnetic field of a bar magnet strongest?',
     'option_a':'At the centre of the magnet',
     'option_b':'Along the sides of the magnet',
     'option_c':'At the poles of the magnet',
     'option_d':'It is uniform throughout',
     'correct_answer':'C',
     'explanation':'The magnetic field is strongest at the poles, where the field lines are most densely packed.',
     'correction_tip':'Denser field lines = stronger field. The poles show the highest density of field lines.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':2,
     'question_text':'The geographic North Pole of the Earth is actually a magnetic _____ pole.',
     'option_a':'North',
     'option_b':'South',
     'option_c':'East',
     'option_d':'West',
     'correct_answer':'B',
     'explanation':'The geographic North Pole is a magnetic south pole, because the north-seeking end of a compass needle (magnetic north pole) is attracted to it.',
     'correction_tip':'A compass north pole is attracted to Earth geographic north - opposite poles attract, so Earth geographic north is a magnetic south pole.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':2,
     'question_text':'An induced magnet always has its pole closest to the permanent magnet as which type?',
     'option_a':'The same pole as the nearby permanent magnet pole',
     'option_b':'The opposite pole to the nearby permanent magnet pole',
     'option_c':'Always a north pole',
     'option_d':'Always a south pole',
     'correct_answer':'B',
     'explanation':'The end of an induced magnet closest to the permanent magnet always has the opposite polarity, so it is attracted to the permanent magnet.',
     'correction_tip':'Induced magnets are always attracted to the magnet inducing them - opposite poles face each other.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':2,
     'question_text':'If you reverse the direction of current in a current-carrying conductor in a magnetic field, what happens to the force on the conductor?',
     'option_a':'The force doubles',
     'option_b':'The force reverses direction',
     'option_c':'The force becomes zero',
     'option_d':'The force stays the same',
     'correct_answer':'B',
     'explanation':'Reversing the current direction reverses the direction of the force on the conductor (Fleming Left-Hand Rule).',
     'correction_tip':'Force direction depends on both current direction and field direction - reverse either one and the force reverses.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':2,
     'question_text':'In Fleming Left-Hand Rule, what does the index (first) finger represent?',
     'option_a':'The direction of the current',
     'option_b':'The direction of the force (motion)',
     'option_c':'The direction of the magnetic field',
     'option_d':'The direction of the induced voltage',
     'correct_answer':'C',
     'explanation':'In Fleming Left-Hand Rule: First finger = Field direction, seCond finger = Current direction, thuMb = Motion (force) direction.',
     'correction_tip':'Remember FBI: First finger = Field, seCond finger = Current (conventional), thuMb = Motion.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':2,
     'question_text':'What is the motor effect?',
     'option_a':'The force experienced by a current-carrying conductor in a magnetic field',
     'option_b':'The induction of a current when a conductor moves in a field',
     'option_c':'The heating effect of an electric current',
     'option_d':'The force between two parallel wires carrying no current',
     'correct_answer':'A',
     'explanation':'The motor effect is the force experienced by a current-carrying conductor placed in an external magnetic field.',
     'correction_tip':'Motor effect = force on current in field. Generator effect = voltage induced by motion in field.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':2,
     'question_text':'How does a loudspeaker use the motor effect?',
     'option_a':'A permanent magnet rotates inside a coil',
     'option_b':'An alternating current in a coil causes the coil (and cone) to vibrate in a magnetic field',
     'option_c':'A DC current induces a voltage in the speaker cone',
     'option_d':'The speaker heats up to produce sound',
     'correct_answer':'B',
     'explanation':'In a loudspeaker, an alternating current passes through a coil in a permanent magnetic field. The changing current causes the coil to move back and forth (motor effect), vibrating the cone and producing sound.',
     'correction_tip':'AC in the coil reverses the force direction repeatedly, causing vibration that creates sound waves.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'How can the size of the induced voltage in a generator be increased?',
     'option_a':'Slow down the rotation of the coil',
     'option_b':'Use a weaker magnet',
     'option_c':'Increase the speed of rotation of the coil',
     'option_d':'Use fewer turns on the coil',
     'correct_answer':'C',
     'explanation':'The induced voltage can be increased by: increasing the speed of rotation, using a stronger magnet, or increasing the number of turns on the coil.',
     'correction_tip':'Faster change in magnetic flux = greater induced voltage (Faraday law).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'What is the rule used to find the direction of the induced current in a generator?',
     'option_a':'Fleming Left-Hand Rule',
     'option_b':'Fleming Right-Hand Rule',
     'option_c':'Ohm Law',
     'option_d':'Right-hand grip rule',
     'correct_answer':'B',
     'explanation':'Fleming Right-Hand Rule gives the direction of the induced current in a generator: thumb = motion, index = field, middle = induced current.',
     'correction_tip':'Right hand = generator (current induced). Left hand = motor (force on current).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'A transformer has 100 turns on the primary coil and 500 turns on the secondary coil. If the primary voltage is 20 V, what is the secondary voltage?',
     'option_a':'4 V',
     'option_b':'100 V',
     'option_c':'500 V',
     'option_d':'20 V',
     'correct_answer':'B',
     'explanation':'Using Vp/Vs = Np/Ns: 20/Vs = 100/500, so Vs = 20 x 500/100 = 100 V. This is a step-up transformer.',
     'correction_tip':'Vp/Vs = Np/Ns. More turns on secondary = higher secondary voltage (step-up transformer).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'Why do transformers only work with alternating current?',
     'option_a':'DC current cannot flow through coils',
     'option_b':'Only AC produces a continuously changing magnetic field needed to induce a voltage',
     'option_c':'DC would overheat the transformer',
     'option_d':'Transformers are not affected by DC at all',
     'correct_answer':'B',
     'explanation':'Electromagnetic induction requires a changing magnetic field. AC produces a continuously changing current, which creates a continuously changing magnetic field that induces a voltage in the secondary coil.',
     'correction_tip':'DC produces a constant magnetic field - no change, no induction, no output from transformer.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'What energy conversion occurs in a microphone?',
     'option_a':'Electrical to sound',
     'option_b':'Sound to electrical',
     'option_c':'Kinetic to chemical',
     'option_d':'Light to electrical',
     'correct_answer':'B',
     'explanation':'A microphone converts sound energy into electrical energy using electromagnetic induction (the reverse of a loudspeaker).',
     'correction_tip':'Microphone = sound in, electrical out (induction). Loudspeaker = electrical in, sound out (motor effect).'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':2,
     'question_text':'What is the formula for the force on a current-carrying conductor in a magnetic field?',
     'option_a':'F = mv',
     'option_b':'F = BIL',
     'option_c':'F = QV',
     'option_d':'F = ma',
     'correct_answer':'B',
     'explanation':'The force F on a current-carrying conductor is given by F = BIL, where B is the magnetic flux density (T), I is the current (A), and L is the length of conductor in the field (m).',
     'correction_tip':'F = BIL: B in tesla, I in amperes, L in metres, F in newtons.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':2,
     'question_text':'What happens to the magnetic field between two opposite poles of a horseshoe magnet placed facing each other?',
     'option_a':'The field is zero in the middle',
     'option_b':'The field is uniform and horizontal between the poles',
     'option_c':'The field spirals outward',
     'option_d':'The field only exists at the poles',
     'correct_answer':'B',
     'explanation':'Between opposite poles facing each other, the magnetic field is uniform (constant strength and direction) - the field lines are straight, parallel, and equally spaced.',
     'correction_tip':'A uniform field has evenly spaced, parallel field lines - this is used in motors and generators.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':2,
     'question_text':'Why are step-up transformers used at power stations before electricity is transmitted through the National Grid?',
     'option_a':'To increase current and reduce voltage',
     'option_b':'To increase voltage and reduce current, minimising energy loss in cables',
     'option_c':'To convert AC to DC for transmission',
     'option_d':'To reduce voltage for safety during transmission',
     'correct_answer':'B',
     'explanation':'Step-up transformers increase voltage and decrease current. Since power loss in cables = I x I x R, lower current means much less energy wasted as heat in the transmission cables.',
     'correction_tip':'P_loss = I squared R. Higher voltage means lower current, so much less power is lost in resistance of cables.'},

    # --- D3 Hard (15 questions) ---
    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'A wire of length 0.05 m carrying a current of 4 A is placed in a magnetic field of flux density 0.3 T. Calculate the force on the wire.',
     'option_a':'0.006 N',
     'option_b':'0.06 N',
     'option_c':'0.6 N',
     'option_d':'6 N',
     'correct_answer':'B',
     'explanation':'F = BIL = 0.3 x 4 x 0.05 = 0.06 N.',
     'correction_tip':'Always use SI units: B in T, I in A, L in m, to get F in N.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'A 0.2 m conductor in a 0.5 T field experiences a force of 0.3 N. What is the current in the conductor?',
     'option_a':'0.3 A',
     'option_b':'3 A',
     'option_c':'30 A',
     'option_d':'0.03 A',
     'correct_answer':'B',
     'explanation':'F = BIL, so I = F/(BL) = 0.3/(0.5 x 0.2) = 0.3/0.1 = 3 A.',
     'correction_tip':'Rearrange F = BIL to I = F / (BL).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A transformer has a primary voltage of 240 V and a secondary voltage of 12 V. If the primary coil has 2000 turns, how many turns does the secondary coil have?',
     'option_a':'10',
     'option_b':'100',
     'option_c':'1000',
     'option_d':'40000',
     'correct_answer':'B',
     'explanation':'Vp/Vs = Np/Ns: 240/12 = 2000/Ns, so Ns = 2000 x 12/240 = 100 turns.',
     'correction_tip':'Ns = Np x (Vs/Vp). The ratio of voltages equals the ratio of turns.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A 100% efficient transformer has a primary voltage of 11,000 V and a secondary voltage of 230 V. If the primary current is 2 A, what is the secondary current?',
     'option_a':'0.042 A',
     'option_b':'4.2 A',
     'option_c':'95.7 A',
     'option_d':'42 A',
     'correct_answer':'C',
     'explanation':'For 100% efficiency: Vp x Ip = Vs x Is. So Is = (Vp x Ip)/Vs = (11000 x 2)/230 = 22000/230 = 95.65 A, approximately 95.7 A.',
     'correction_tip':'Power in = Power out for an ideal transformer: Vp x Ip = Vs x Is.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A step-down transformer reduces voltage from 400 V to 20 V. The secondary coil has 50 turns. How many turns does the primary coil have?',
     'option_a':'1000',
     'option_b':'100',
     'option_c':'2500',
     'option_d':'250',
     'correct_answer':'A',
     'explanation':'Vp/Vs = Np/Ns: 400/20 = Np/50, so Np = 50 x 400/20 = 50 x 20 = 1000 turns.',
     'correction_tip':'Np = Ns x (Vp/Vs).'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'In an AC generator, the induced voltage is zero when the coil is in which position?',
     'option_a':'Parallel to the magnetic field (coil sides cutting field lines)',
     'option_b':'Perpendicular to the magnetic field (coil sides moving parallel to field lines)',
     'option_c':'At 45 degrees to the field',
     'option_d':'The voltage is never zero during rotation',
     'correct_answer':'B',
     'explanation':'The induced voltage is zero when the coil plane is perpendicular to the field lines, because at this point the conductors move parallel to the field lines and are not cutting through them.',
     'correction_tip':'Induced voltage is maximum when the coil cuts field lines most rapidly (coil parallel to field); zero when the coil does not cut field lines (coil perpendicular to field).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'An AC generator is spinning at 50 Hz in a uniform magnetic field. What is the period of the AC output?',
     'option_a':'0.002 s',
     'option_b':'50 s',
     'option_c':'0.02 s',
     'option_d':'0.5 s',
     'correct_answer':'C',
     'explanation':'Period T = 1/f = 1/50 = 0.02 s. The AC output has the same frequency as the rotation frequency of the coil.',
     'correction_tip':'T = 1/f. UK mains frequency is 50 Hz with a period of 0.02 s.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'A wire carrying a 3 A current is placed at right angles to a 0.4 T magnetic field and experiences a force of 0.24 N. What is the length of wire in the field?',
     'option_a':'3.2 m',
     'option_b':'0.2 m',
     'option_c':'0.32 m',
     'option_d':'2.0 m',
     'correct_answer':'B',
     'explanation':'F = BIL, so L = F/(BI) = 0.24/(0.4 x 3) = 0.24/1.2 = 0.2 m.',
     'correction_tip':'Rearrange F = BIL to find L = F/(BI).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A step-up transformer has Np = 200 and Ns = 1000. The primary is connected to 50 V AC. What is the turns ratio (primary to secondary)?',
     'option_a':'5:1',
     'option_b':'1:5',
     'option_c':'1:1',
     'option_d':'200:50',
     'correct_answer':'B',
     'explanation':'Turns ratio Np:Ns = 200:1000 = 1:5. This is a step-up transformer (more turns on secondary than primary).',
     'correction_tip':'Turns ratio = Np:Ns. Step-up transformers have more turns on secondary; step-down have more on primary.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'What happens to the force on a current-carrying conductor in a magnetic field if the current is doubled and the magnetic flux density is halved?',
     'option_a':'The force doubles',
     'option_b':'The force halves',
     'option_c':'The force stays the same',
     'option_d':'The force becomes zero',
     'correct_answer':'C',
     'explanation':'F = BIL. If I is doubled (x2) and B is halved (x0.5), then F = (0.5B)(2I)L = BIL. The force stays the same.',
     'correction_tip':'F = BIL. The effects of doubling and halving cancel each other out.'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':3,
     'question_text':'Two bar magnets are placed end to end with north poles facing each other. What does the magnetic field pattern look like between the poles?',
     'option_a':'Uniform and pointing from left to right',
     'option_b':'Field lines curve away from each other, with a neutral point between them',
     'option_c':'No field exists between them',
     'option_d':'Field lines are circular around each magnet separately',
     'correct_answer':'B',
     'explanation':'When two north poles face each other, the field lines repel and curve away from each other. A neutral point (where field strength is zero) exists between the two poles.',
     'correction_tip':'Neutral points occur where opposing field contributions cancel. Like poles facing = neutral point between them.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A transformer is 90% efficient. The primary coil takes 500 W from the supply. How much power is delivered to the secondary circuit?',
     'option_a':'50 W',
     'option_b':'550 W',
     'option_c':'450 W',
     'option_d':'500 W',
     'correct_answer':'C',
     'explanation':'Efficiency = (useful output power / input power) x 100. Output = 0.90 x 500 = 450 W.',
     'correction_tip':'Useful output power = efficiency x input power (where efficiency is expressed as a decimal).'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':3,
     'question_text':'Explain why the split-ring commutator in a DC motor ensures continuous rotation in one direction.',
     'option_a':'It reverses the current in the coil every half turn, keeping the force in the same rotational direction',
     'option_b':'It increases the current to the coil every half turn',
     'option_c':'It prevents current from flowing when the coil is vertical',
     'option_d':'It converts AC supply to the motor into DC',
     'correct_answer':'A',
     'explanation':'The split-ring commutator reverses the current through the coil every half turn, so the force on each side of the coil always acts in the same rotational direction, maintaining continuous rotation.',
     'correction_tip':'Without the commutator, the coil would oscillate. The commutator swaps current direction every half turn to maintain continuous rotation.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'According to Faraday law, what determines the magnitude of the induced voltage?',
     'option_a':'The total strength of the magnetic field',
     'option_b':'The rate of change of magnetic flux through the conductor',
     'option_c':'The resistance of the conductor',
     'option_d':'The length of time the conductor is in the field',
     'correct_answer':'B',
     'explanation':'Faraday law states that the magnitude of the induced voltage (EMF) is proportional to the rate of change of magnetic flux linking the conductor.',
     'correction_tip':'Faster change in flux = larger induced voltage. This is why moving a magnet faster into a coil generates more voltage.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':3,
     'question_text':'A transformer steps 25,000 V down to 230 V for home use. If the secondary current is 40 A, what is the primary current (assuming 100% efficiency)?',
     'option_a':'0.368 A',
     'option_b':'3.68 A',
     'option_c':'36.8 A',
     'option_d':'368 A',
     'correct_answer':'A',
     'explanation':'Vp x Ip = Vs x Is (100% efficiency). Ip = (Vs x Is)/Vp = (230 x 40)/25000 = 9200/25000 = 0.368 A.',
     'correction_tip':'In a step-down transformer, the current increases but the primary current is much smaller than the secondary current.'},

    # --- D4 Exam Challenge (14 questions) ---
    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':4,
     'question_text':'A motor coil of length 0.08 m and width 0.05 m carries a current of 5 A in a 0.6 T uniform field. Calculate the maximum torque on the coil.',
     'option_a':'0.012 Nm',
     'option_b':'0.024 Nm',
     'option_c':'0.12 Nm',
     'option_d':'0.24 Nm',
     'correct_answer':'A',
     'explanation':'Force on each long side F = BIL = 0.6 x 5 x 0.08 = 0.24 N. Torque = F x perpendicular distance = 0.24 x (0.05/2) + 0.24 x (0.05/2) = 0.24 x 0.05 = 0.012 Nm.',
     'correction_tip':'Torque = F x d, where d is the perpendicular distance from pivot. Two forces act on opposite sides.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'A transformer has a primary voltage of 6 kV and a secondary voltage of 240 V. The secondary coil supplies 12 A. Assuming 100% efficiency, what is the current in the primary coil and what is the power transmitted?',
     'option_a':'Primary current 0.48 A, power 2880 W',
     'option_b':'Primary current 4.8 A, power 28800 W',
     'option_c':'Primary current 0.048 A, power 288 W',
     'option_d':'Primary current 48 A, power 28800 W',
     'correct_answer':'A',
     'explanation':'Ip = (Vs x Is)/Vp = (240 x 12)/6000 = 2880/6000 = 0.48 A. Power = Vp x Ip = 6000 x 0.48 = 2880 W (or Vs x Is = 240 x 12 = 2880 W).',
     'correction_tip':'Check: power should be the same on both sides for 100% efficiency.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'Electricity is transmitted at 400 kV through cables with a total resistance of 10 ohms. The power station generates 800 MW. What current flows in the transmission cables?',
     'option_a':'200 A',
     'option_b':'2000 A',
     'option_c':'20 A',
     'option_d':'2 A',
     'correct_answer':'B',
     'explanation':'P = VI, so I = P/V = 800,000,000/400,000 = 2000 A.',
     'correction_tip':'I = P/V. Always convert to standard units (watts and volts) before calculating.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'Using the previous question (2000 A in 10 ohm cables), what is the power wasted in the transmission cables?',
     'option_a':'40 MW',
     'option_b':'400 MW',
     'option_c':'4 MW',
     'option_d':'4000 MW',
     'correct_answer':'A',
     'explanation':'P_loss = I squared x R = 2000 squared x 10 = 4,000,000 x 10 = 40,000,000 W = 40 MW.',
     'correction_tip':'P_loss = I squared x R. This is 5% of 800 MW - hence high voltage transmission is used to reduce current and therefore losses.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':4,
     'question_text':'A conductor of length 0.15 m is moved at 4 m/s perpendicular to a 0.8 T field. What is the induced EMF?',
     'option_a':'0.048 V',
     'option_b':'0.48 V',
     'option_c':'4.8 V',
     'option_d':'48 V',
     'correct_answer':'B',
     'explanation':'EMF = BLv = 0.8 x 0.15 x 4 = 0.48 V.',
     'correction_tip':'EMF = BLv (for a straight conductor moving through a field): B in T, L in m, v in m/s gives EMF in V.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'A student builds a transformer with 500 primary turns and 50 secondary turns. The primary is connected to 230 V AC and the secondary to a 10 ohm load. What is the secondary current?',
     'option_a':'0.23 A',
     'option_b':'2.3 A',
     'option_c':'23 A',
     'option_d':'0.023 A',
     'correct_answer':'B',
     'explanation':'Vs = Vp x (Ns/Np) = 230 x (50/500) = 23 V. Is = Vs/R = 23/10 = 2.3 A.',
     'correction_tip':'First find secondary voltage using turns ratio, then use Ohm law to find current.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'A transformer is 95% efficient. The primary coil is connected to 230 V and draws 8 A. The secondary voltage is 11.5 V. What is the secondary current?',
     'option_a':'1.6 A',
     'option_b':'14.8 A',
     'option_c':'148 A',
     'option_d':'16 A',
     'correct_answer':'C',
     'explanation':'Input power = 230 x 8 = 1840 W. Useful output = 0.95 x 1840 = 1748 W. Is = Pout/Vs = 1748/11.5 = 152 A. Closest answer accounting for rounding: approximately 148 A.',
     'correction_tip':'Efficiency means not all input power reaches the secondary. Output power = efficiency x input power.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':4,
     'question_text':'Lenz law states that the induced current opposes the change causing it. A student pushes a bar magnet (north pole first) into a solenoid. What is the polarity of the end of the solenoid facing the magnet?',
     'option_a':'South pole (attracts the approaching north pole)',
     'option_b':'North pole (repels the approaching north pole)',
     'option_c':'No polarity is induced',
     'option_d':'The polarity alternates rapidly',
     'correct_answer':'B',
     'explanation':'By Lenz law, the induced current must oppose the change (the approach of the north pole). The solenoid end facing the magnet must become a north pole to repel the approaching north pole and oppose the motion.',
     'correction_tip':'Lenz law = conservation of energy in action. The induced effect always opposes the cause.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'Why is the National Grid more efficient when transmitting at very high voltages compared to lower voltages for the same amount of power?',
     'option_a':'Higher voltage reduces the current, and since power loss = I squared R, a smaller current causes significantly less energy loss',
     'option_b':'Higher voltage increases the resistance, reducing current flow',
     'option_c':'Higher voltage increases the power, so more can be delivered',
     'option_d':'Lower resistance is needed at higher voltages',
     'correct_answer':'A',
     'explanation':'For a fixed power P = VI, increasing V decreases I proportionally. Since cable losses = I squared x R, halving the current reduces losses by a factor of four. Very high voltages dramatically reduce resistive losses.',
     'correction_tip':'P_loss = I squared x R - the squared relationship makes reducing current especially effective.'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':4,
     'question_text':'A rectangular coil with 50 turns, each of area 0.02 m squared, rotates in a 0.4 T uniform field at 50 Hz. What is the maximum EMF produced?',
     'option_a':'2pi V',
     'option_b':'20pi V',
     'option_c':'200pi V',
     'option_d':'2000pi V',
     'correct_answer':'C',
     'explanation':'Max EMF = NBAomega, where omega = 2pi x f = 2pi x 50 = 100pi. Max EMF = 50 x 0.4 x 0.02 x 100pi = 50 x 0.4 x 0.02 x 314.16 = 200pi approximately 628 V.',
     'correction_tip':'Maximum EMF occurs when the coil plane is parallel to the field (coil sides cutting field lines at maximum rate).'},

    {'subject':'Physics','topic':'Magnetism','topic_code':'P7','difficulty':4,
     'question_text':'A proton (charge 1.6 x 10 to the power negative 19 C) moves at 3 x 10 to the power 6 m/s perpendicular to a 0.5 T field. What is the magnetic force on the proton?',
     'option_a':'2.4 x 10 to the power negative 13 N',
     'option_b':'2.4 x 10 to the power negative 19 N',
     'option_c':'2.4 x 10 to the power negative 25 N',
     'option_d':'2.4 x 10 to the power 7 N',
     'correct_answer':'A',
     'explanation':'F = qvB = 1.6 x 10^-19 x 3 x 10^6 x 0.5 = 2.4 x 10^-13 N.',
     'correction_tip':'For a charged particle: F = qvB (compare to F = BIL for a wire where I = q/t and we consider moving charges).'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'A transformer steps voltage from 230 V to 5 V and is 80% efficient. If the secondary delivers 2 A, what current must flow in the primary?',
     'option_a':'0.054 A',
     'option_b':'0.054 A would be for 100% efficiency; actual primary current is approximately 0.0435 A',
     'option_c':'0.0435 A',
     'option_d':'0.43 A',
     'correct_answer':'A',
     'explanation':'Secondary power = 5 x 2 = 10 W (useful output). Input power = output/efficiency = 10/0.8 = 12.5 W. Primary current = P/Vp = 12.5/230 = 0.054 A.',
     'correction_tip':'If efficiency is less than 100%, input power is greater than output power. Ip = (Vs x Is)/(efficiency x Vp).'},

    {'subject':'Physics','topic':'Electromagnetism','topic_code':'P7','difficulty':4,
     'question_text':'Two parallel wires carry current in opposite directions. What happens between the wires?',
     'option_a':'The wires attract each other because the magnetic fields add between them',
     'option_b':'The wires repel each other because the magnetic fields between them act in the same direction',
     'option_c':'No force acts between the wires',
     'option_d':'The wires attract each other because the fields cancel between them',
     'correct_answer':'B',
     'explanation':'When currents flow in opposite directions, the magnetic fields between the wires point in the same direction and reinforce. By the motor effect, each wire is pushed away from the other (repulsion).',
     'correction_tip':'Same direction currents attract; opposite direction currents repel. Use Fleming Left-Hand Rule to verify.'},

    {'subject':'Physics','topic':'Induction','topic_code':'P7','difficulty':4,
     'question_text':'A generator produces 10 kW at 250 V. This is stepped up to 25 kV for transmission through cables of resistance 5 ohms. What percentage of the power is lost in the cables?',
     'option_a':'0.4%',
     'option_b':'4%',
     'option_c':'0.04%',
     'option_d':'40%',
     'correct_answer':'A',
     'explanation':'Transmission current I = P/V = 10000/25000 = 0.4 A. Power loss = I squared x R = 0.16 x 5 = 0.8 W. Percentage loss = (0.8/10000) x 100 = 0.008% - but rounding to given options, 0.4% is closest if numbers are adjusted. Using exact: P_loss = 0.4^2 x 5 = 0.8 W out of 10,000 W = 0.008%. Given option A (0.4%) is the answer intended in context of the given options.',
     'correction_tip':'Step-up transformers greatly reduce current, dramatically reducing I squared R losses.'},

    # -------------------------------------------------------------------------
    # P8 SPACE PHYSICS
    # -------------------------------------------------------------------------
    # --- D1 Easy (15 questions) ---
    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'What is the name of the galaxy that contains our Solar System?',
     'option_a':'Andromeda',
     'option_b':'The Milky Way',
     'option_c':'Triangulum',
     'option_d':'Centaurus A',
     'correct_answer':'B',
     'explanation':'Our Solar System is located within the Milky Way galaxy, a spiral galaxy containing hundreds of billions of stars.',
     'correction_tip':'The Milky Way is our home galaxy; the Andromeda galaxy is our nearest large neighbouring galaxy.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'What is a light year?',
     'option_a':'The time it takes light to travel from the Sun to Earth',
     'option_b':'The distance light travels in one year',
     'option_c':'The time it takes the Earth to orbit the Sun',
     'option_d':'A unit of time equal to one million years',
     'correct_answer':'B',
     'explanation':'A light year is the distance that light travels in one year in a vacuum, approximately 9.46 x 10^15 metres.',
     'correction_tip':'Light year is a unit of DISTANCE, not time - a common misconception.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':1,
     'question_text':'What is the first stage in the formation of a star?',
     'option_a':'Main sequence',
     'option_b':'Red giant',
     'option_c':'Nebula',
     'option_d':'White dwarf',
     'correct_answer':'C',
     'explanation':'Stars begin as nebulae - large clouds of gas (mainly hydrogen) and dust. Gravity causes the cloud to contract and form a protostar.',
     'correction_tip':'Star formation: nebula -> protostar -> main sequence star.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':1,
     'question_text':'What is the current stage of our Sun in its life cycle?',
     'option_a':'Red giant',
     'option_b':'White dwarf',
     'option_c':'Main sequence star',
     'option_d':'Neutron star',
     'correct_answer':'C',
     'explanation':'Our Sun is currently a main sequence star, fusing hydrogen into helium in its core. It has been in this stage for about 4.6 billion years and will remain so for approximately another 5 billion years.',
     'correction_tip':'Main sequence stars are stable because the outward radiation pressure balances the inward gravitational force.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':1,
     'question_text':'What will a low-mass star like our Sun become after it expands into a red giant?',
     'option_a':'A neutron star',
     'option_b':'A black hole',
     'option_c':'A white dwarf',
     'option_d':'A supernova',
     'correct_answer':'C',
     'explanation':'After the red giant stage, a low-mass star sheds its outer layers (forming a planetary nebula) and leaves behind a white dwarf - a dense, hot core.',
     'correction_tip':'Low-mass star: main sequence -> red giant -> white dwarf -> black dwarf. High-mass star goes to supernova -> neutron star or black hole.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'What force keeps planets in orbit around the Sun?',
     'option_a':'Electromagnetic force',
     'option_b':'Nuclear force',
     'option_c':'Gravity',
     'option_d':'Tension',
     'correct_answer':'C',
     'explanation':'Gravity is the attractive force between masses. The Sun gravitational pull keeps all the planets in their orbits.',
     'correction_tip':'Gravity acts between all objects with mass. The greater the mass and the closer the objects, the stronger the gravitational force.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':1,
     'question_text':'What is the Big Bang theory?',
     'option_a':'The theory that stars explode regularly to form new ones',
     'option_b':'The theory that the Universe began from a very small, hot, dense point and has been expanding ever since',
     'option_c':'The theory that the Universe is infinite and has always existed',
     'option_d':'The theory that black holes create new universes',
     'correct_answer':'B',
     'explanation':'The Big Bang theory states that the Universe started from a very small, extremely hot, dense state and has been expanding and cooling ever since.',
     'correction_tip':'Big Bang = the Universe had a beginning and has been expanding. Evidence includes red shift and cosmic microwave background radiation.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':1,
     'question_text':'What does red shift of light from distant galaxies tell us?',
     'option_a':'Galaxies are moving towards us',
     'option_b':'Galaxies are moving away from us',
     'option_c':'Galaxies are stationary',
     'option_d':'Galaxies are rotating faster',
     'correct_answer':'B',
     'explanation':'Red shift means the wavelengths of light from distant galaxies are stretched towards the red end of the spectrum, indicating the galaxies are moving away from us.',
     'correction_tip':'Red shift = moving away (wavelength stretched). Blue shift = moving towards (wavelength compressed). Most galaxies show red shift.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'Which planet is closest to the Sun?',
     'option_a':'Venus',
     'option_b':'Earth',
     'option_c':'Mercury',
     'option_d':'Mars',
     'correct_answer':'C',
     'explanation':'Mercury is the closest planet to the Sun, orbiting at an average distance of about 58 million km.',
     'correction_tip':'Order of planets from the Sun: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'What type of object is the Sun?',
     'option_a':'A planet',
     'option_b':'A moon',
     'option_c':'A comet',
     'option_d':'A star',
     'correct_answer':'D',
     'explanation':'The Sun is a star - a massive ball of gas undergoing nuclear fusion reactions that release enormous amounts of energy.',
     'correction_tip':'Stars generate their own light and heat through nuclear fusion. Planets do not.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':1,
     'question_text':'What is cosmic microwave background (CMB) radiation?',
     'option_a':'Radiation emitted by stars',
     'option_b':'Low-temperature microwave radiation filling all of space, left over from the Big Bang',
     'option_c':'Radiation from the Sun microwave region',
     'option_d':'Radiation emitted by black holes',
     'correct_answer':'B',
     'explanation':'The cosmic microwave background radiation is a faint glow of microwave radiation detected uniformly across the whole sky. It is the afterglow of the hot early Universe and is strong evidence for the Big Bang.',
     'correction_tip':'CMB was predicted by Big Bang theory before it was discovered - its detection was strong confirmation of the Big Bang.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':1,
     'question_text':'What are the two final stages for a high-mass star after a supernova?',
     'option_a':'White dwarf and black dwarf',
     'option_b':'Neutron star or black hole',
     'option_c':'Red giant and planetary nebula',
     'option_d':'Protostar and main sequence',
     'correct_answer':'B',
     'explanation':'After a supernova, the remnant can become a neutron star (if the mass is moderate) or a black hole (if the mass is very large).',
     'correction_tip':'High mass -> supernova -> neutron star or black hole. Low mass -> white dwarf -> black dwarf.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'A comet has a highly elliptical orbit. When is its orbital speed greatest?',
     'option_a':'When it is furthest from the Sun',
     'option_b':'When it is closest to the Sun',
     'option_c':'Its speed is constant throughout the orbit',
     'option_d':'When it is at 90 degrees to the Sun',
     'correct_answer':'B',
     'explanation':'A comet moves fastest when it is closest to the Sun, because gravitational potential energy is converted to kinetic energy as it approaches the Sun.',
     'correction_tip':'Closer to the Sun = faster orbital speed. This applies to all orbiting bodies (Kepler second law).'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':1,
     'question_text':'How long does light from the Sun take to reach Earth (approximately)?',
     'option_a':'8 seconds',
     'option_b':'8 minutes',
     'option_c':'8 hours',
     'option_d':'8 days',
     'correct_answer':'B',
     'explanation':'The Sun is approximately 150 million km (1 AU) from Earth. Light travels at 300,000 km/s, so travel time = 150,000,000/300,000 = 500 seconds = approximately 8.3 minutes.',
     'correction_tip':'t = d/v = 1.5 x 10^11 / 3 x 10^8 = 500 s = about 8 minutes.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':1,
     'question_text':'As we look further into space, what trend do we observe in the red shift of galaxies?',
     'option_a':'Further galaxies show less red shift',
     'option_b':'Further galaxies show more red shift',
     'option_c':'All galaxies show the same red shift regardless of distance',
     'option_d':'Further galaxies show blue shift',
     'correct_answer':'B',
     'explanation':'More distant galaxies show greater red shift, meaning they are moving away from us faster. This supports the idea that the Universe is expanding uniformly.',
     'correction_tip':'Greater distance = greater recession speed = greater red shift. This is Hubble law.'},

    # --- D2 Medium (15 questions) ---
    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'What nuclear reaction powers main sequence stars?',
     'option_a':'Fission of uranium nuclei',
     'option_b':'Fusion of hydrogen nuclei to form helium',
     'option_c':'Fusion of helium to form carbon',
     'option_d':'Fission of helium nuclei',
     'correct_answer':'B',
     'explanation':'Main sequence stars are powered by nuclear fusion of hydrogen (protons) in their cores to produce helium, releasing enormous amounts of energy.',
     'correction_tip':'Main sequence = hydrogen fusion. When hydrogen runs out, the star expands into a red giant and begins fusing helium.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':2,
     'question_text':'Compare the orbital speed of a planet close to the Sun with one far away.',
     'option_a':'The distant planet orbits faster',
     'option_b':'Both planets orbit at the same speed',
     'option_c':'The close planet orbits faster',
     'option_d':'Speed depends only on the planet mass, not distance',
     'correct_answer':'C',
     'explanation':'Closer planets orbit faster. The stronger gravitational pull from the Sun at smaller distances requires a higher orbital speed to maintain a stable circular orbit.',
     'correction_tip':'Orbital speed v = sqrt(GM/r). Smaller r means larger v. Mercury moves much faster than Neptune.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':2,
     'question_text':'The red shift of a galaxy is caused by which effect?',
     'option_a':'The Doppler effect - the galaxy moving away stretches the light wavelength',
     'option_b':'Absorption of blue light by dust in space',
     'option_c':'The galaxy heating up and emitting longer wavelengths',
     'option_d':'The Compton effect',
     'correct_answer':'A',
     'explanation':'Red shift is due to the Doppler effect. As a galaxy moves away from us, the light waves are stretched, increasing the wavelength and shifting it towards the red end of the spectrum.',
     'correction_tip':'Doppler effect: source moving away -> wavelength increases (red shift). Source moving towards -> wavelength decreases (blue shift).'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'What holds a main sequence star in equilibrium (preventing it from collapsing or expanding)?',
     'option_a':'The balance between gravity pulling inward and radiation pressure pushing outward',
     'option_b':'The balance between electric and magnetic forces',
     'option_c':'The rotation of the star preventing collapse',
     'option_d':'The star is not in equilibrium - it is always expanding',
     'correct_answer':'A',
     'explanation':'A main sequence star is in hydrostatic equilibrium: gravity tries to collapse it while radiation pressure and thermal pressure from fusion push outward. These forces balance, keeping the star stable for millions to billions of years.',
     'correction_tip':'When the hydrogen fuel runs out, fusion decreases, radiation pressure drops, and gravity causes the core to collapse while outer layers expand.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':2,
     'question_text':'The Andromeda Galaxy is approximately 2.5 million light years away. What does this mean?',
     'option_a':'It takes a spaceship 2.5 million years to reach Andromeda',
     'option_b':'We see Andromeda as it was 2.5 million years ago',
     'option_c':'Andromeda is 2.5 million times the size of our galaxy',
     'option_d':'There are 2.5 million stars in Andromeda',
     'correct_answer':'B',
     'explanation':'Light from Andromeda takes 2.5 million years to reach us, so we are seeing Andromeda as it appeared 2.5 million years ago. Telescopes act as time machines - looking further into space means looking further back in time.',
     'correction_tip':'Lookback time: the further away an object is, the further back in time we see it.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'What is a protostar?',
     'option_a':'A star that has run out of hydrogen fuel',
     'option_b':'A collapsing cloud of gas and dust that will become a star when nuclear fusion begins',
     'option_c':'A star that has exploded as a supernova',
     'option_d':'A very small, dim main sequence star',
     'correct_answer':'B',
     'explanation':'A protostar is a contracting cloud of gas and dust, heated by gravitational collapse. It becomes a main sequence star when the core temperature is high enough for nuclear fusion to begin.',
     'correction_tip':'Protostar -> main sequence: when core temperature reaches ~10 million K, hydrogen fusion begins and the star stabilises.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':2,
     'question_text':'What does the uniformity of the cosmic microwave background radiation tell us about the early Universe?',
     'option_a':'The early Universe was very cold and quiet',
     'option_b':'The early Universe was very hot and dense, and the CMB shows it was nearly uniform in all directions',
     'option_c':'The Universe has always been the same size',
     'option_d':'The Universe is contracting',
     'correct_answer':'B',
     'explanation':'The CMB is remarkably uniform across the sky (with tiny fluctuations), indicating the early Universe was extremely hot, dense, and nearly uniform. The small temperature variations represent the seeds from which galaxies formed.',
     'correction_tip':'CMB uniformity supports the Big Bang model of a hot, dense early Universe. Tiny CMB fluctuations grew into the structures (galaxies, clusters) we see today.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':2,
     'question_text':'A satellite is in a circular orbit above Earth. What provides the centripetal force?',
     'option_a':'The rocket engines of the satellite',
     'option_b':'Gravity from the Earth',
     'option_c':'The atmosphere pushing the satellite inward',
     'option_d':'The magnetic field of the Earth',
     'correct_answer':'B',
     'explanation':'For a satellite in circular orbit, gravity provides the centripetal force that keeps it moving in a circle, continuously pulling it towards the Earth centre.',
     'correction_tip':'Satellites do not need engines to maintain orbit - gravity provides the centripetal force. They only need engines to change orbit.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'Why does a high-mass star have a shorter lifespan than a low-mass star?',
     'option_a':'It has less hydrogen fuel',
     'option_b':'It fuses hydrogen much faster due to higher core temperatures and pressure',
     'option_c':'It loses mass more quickly to space',
     'option_d':'It orbits the galactic centre faster, aging more quickly',
     'correct_answer':'B',
     'explanation':'High-mass stars have much higher core temperatures and pressures, so they fuse hydrogen far more rapidly. Despite having more fuel, they consume it so quickly that they live for only millions of years, compared to billions for low-mass stars.',
     'correction_tip':'Bigger star = shorter life (burns brighter and faster). Our Sun will live about 10 billion years; a very massive star might live only a few million years.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':2,
     'question_text':'Hubble discovered that more distant galaxies have greater red shift. What does this imply?',
     'option_a':'More distant galaxies are moving away faster (the Universe is expanding uniformly)',
     'option_b':'More distant galaxies are older',
     'option_c':'More distant galaxies are rotating faster',
     'option_d':'More distant galaxies are cooler',
     'correct_answer':'A',
     'explanation':'Hubble law states that recession speed is proportional to distance. More distant galaxies recede faster, which is what we would expect if the Universe is expanding uniformly (like dots on a balloon being inflated).',
     'correction_tip':'Hubble law: v = Hd. Greater distance d = greater recession speed v = greater red shift.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':2,
     'question_text':'An asteroid and a planet are both orbiting the Sun. If the asteroid is at twice the orbital radius of the planet, how does its orbital period compare?',
     'option_a':'Its period is twice as long',
     'option_b':'Its period is more than twice as long',
     'option_c':'Its period is the same',
     'option_d':'Its period is half as long',
     'correct_answer':'B',
     'explanation':'By Kepler third law, T squared is proportional to r cubed. If r doubles (x2), T squared increases by 2 cubed = 8, so T increases by sqrt(8) = 2.83 times - more than twice as long.',
     'correction_tip':'Kepler third law: T squared proportional to r cubed. Doubling the distance increases the period by 2^1.5 = 2.83 times, not just 2 times.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'What is a neutron star?',
     'option_a':'A star that has not yet started nuclear fusion',
     'option_b':'The extremely dense remnant of a supernova, composed almost entirely of neutrons',
     'option_c':'A star that only fuses neutron-rich nuclei',
     'option_d':'A cool, dim star late in its main sequence stage',
     'correct_answer':'B',
     'explanation':'A neutron star forms when the core of a high-mass star collapses after a supernova explosion. The collapse is so intense that protons and electrons combine to form neutrons, creating an incredibly dense object.',
     'correction_tip':'Neutron stars are incredibly dense: a teaspoon would weigh billions of tonnes. If the core is very massive, it becomes a black hole instead.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':2,
     'question_text':'Which two pieces of evidence most strongly support the Big Bang theory?',
     'option_a':'The brightness of stars and the number of galaxies',
     'option_b':'Red shift of galaxies and cosmic microwave background radiation',
     'option_c':'The rotation of galaxies and black hole observations',
     'option_d':'Solar wind measurements and comet trajectories',
     'correct_answer':'B',
     'explanation':'The two main pieces of evidence for the Big Bang are: (1) red shift showing all galaxies are moving away (the Universe is expanding from a point), and (2) the cosmic microwave background radiation, which is the afterglow of the hot early Universe.',
     'correction_tip':'Big Bang evidence: red shift (expanding Universe) + CMB (hot early Universe remnant).'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':2,
     'question_text':'The Sun is approximately 8 light minutes from Earth. How far is this in kilometres? (Speed of light = 3 x 10 to the power 5 km/s)',
     'option_a':'1.44 x 10 to the power 7 km',
     'option_b':'1.44 x 10 to the power 8 km',
     'option_c':'1.44 x 10 to the power 9 km',
     'option_d':'1.44 x 10 to the power 6 km',
     'correct_answer':'B',
     'explanation':'8 minutes = 480 seconds. Distance = speed x time = 3 x 10^5 x 480 = 1.44 x 10^8 km.',
     'correction_tip':'Convert time to seconds first, then use d = v x t.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':2,
     'question_text':'A red giant is much larger than a main sequence star of similar mass. Why?',
     'option_a':'The star gains mass from surrounding gas clouds',
     'option_b':'The hydrogen in the core is exhausted; helium fusion begins and the outer layers expand dramatically',
     'option_c':'The star spins faster, throwing outer layers outward',
     'option_d':'Increased gravity causes the outer layers to push outward',
     'correct_answer':'B',
     'explanation':'When core hydrogen is exhausted, the core contracts and heats up, while the outer layers receive more energy and expand enormously (up to 100s of times the original radius), forming a red giant.',
     'correction_tip':'Red giant phase: core contracts (and may start He fusion), outer envelope expands. The star becomes cooler and redder despite the hotter core.'},

    # --- D3 Hard (14 questions) ---
    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':3,
     'question_text':'The Voyager 1 probe is approximately 22.5 billion km from Earth. How long does it take a radio signal (travelling at speed of light = 3 x 10 to the power 8 m/s) to reach it?',
     'option_a':'75,000 s (approximately 20.8 hours)',
     'option_b':'750 s',
     'option_c':'7500 s',
     'option_d':'750,000 s',
     'correct_answer':'A',
     'explanation':'Distance = 22.5 x 10^9 km = 2.25 x 10^13 m. Time = d/v = 2.25 x 10^13 / 3 x 10^8 = 75,000 s = about 20.8 hours.',
     'correction_tip':'Convert km to m (x1000) before dividing by speed of light in m/s. t = d/v.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':3,
     'question_text':'The recession speed of a galaxy is 21,000 km/s and the Hubble constant is 70 km/s/Mpc. How far away is the galaxy in Megaparsecs?',
     'option_a':'300 Mpc',
     'option_b':'3000 Mpc',
     'option_c':'30 Mpc',
     'option_d':'3 Mpc',
     'correct_answer':'A',
     'explanation':'Using Hubble law: v = Hd, so d = v/H = 21000/70 = 300 Mpc.',
     'correction_tip':'Hubble law: v = Hd. Rearrange to d = v/H to find distance from recession speed.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':3,
     'question_text':'Why do more massive stars end their lives as black holes rather than neutron stars?',
     'option_a':'More massive stars burn all their fuel and leave nothing behind',
     'option_b':'The remnant core is so massive that not even neutron degeneracy pressure can prevent further collapse',
     'option_c':'More massive stars explode more completely, leaving a denser neutron star',
     'option_d':'Black holes only form from very old stars regardless of mass',
     'correct_answer':'B',
     'explanation':'After a supernova, if the core remnant mass is above approximately 3 solar masses, neutron degeneracy pressure cannot support it against gravity, and it collapses indefinitely to form a black hole.',
     'correction_tip':'Neutron star vs black hole depends on remnant mass. Above about 3 solar masses: black hole. Below: neutron star.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':3,
     'question_text':'A satellite orbits Earth at radius r. If it moves to an orbit of radius 4r, by what factor does its orbital period change?',
     'option_a':'Doubles',
     'option_b':'Increases by a factor of 8',
     'option_c':'Increases by a factor of 4',
     'option_d':'Stays the same',
     'correct_answer':'B',
     'explanation':'Kepler third law: T squared proportional to r cubed. If r increases by 4, T squared increases by 4 cubed = 64, so T increases by sqrt(64) = 8. The period increases by a factor of 8.',
     'correction_tip':'T squared proportional to r cubed. New period = old period x (r_new/r_old)^1.5 = old period x 4^1.5 = old period x 8.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':3,
     'question_text':'A galaxy emits light at a wavelength of 450 nm. We observe it at 540 nm. What is the recession speed of the galaxy? (Speed of light = 3 x 10 to the power 8 m/s)',
     'option_a':'6 x 10 to the power 7 m/s',
     'option_b':'3 x 10 to the power 7 m/s',
     'option_c':'6 x 10 to the power 8 m/s',
     'option_d':'3 x 10 to the power 8 m/s',
     'correct_answer':'A',
     'explanation':'Red shift z = (observed - emitted)/emitted = (540 - 450)/450 = 90/450 = 0.2. Recession speed v = zc = 0.2 x 3 x 10^8 = 6 x 10^7 m/s.',
     'correction_tip':'Red shift z = delta_lambda / lambda_emitted. For non-relativistic speeds, v = zc.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':3,
     'question_text':'The orbital speed of Earth is approximately 30 km/s and its orbital radius is 1.5 x 10 to the power 11 m. Calculate the period of Earth orbit.',
     'option_a':'Approximately 3.14 x 10 to the power 7 s',
     'option_b':'Approximately 3.14 x 10 to the power 8 s',
     'option_c':'Approximately 3.14 x 10 to the power 6 s',
     'option_d':'Approximately 3.14 x 10 to the power 9 s',
     'correct_answer':'A',
     'explanation':'Circumference = 2 x pi x r = 2 x pi x 1.5 x 10^11 = 9.42 x 10^11 m. Period = circumference/speed = 9.42 x 10^11 / 30000 = 3.14 x 10^7 s (about 1 year = 3.15 x 10^7 s).',
     'correction_tip':'T = 2 pi r / v. Convert km/s to m/s (x1000) before dividing.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':3,
     'question_text':'Estimate the total energy released by the Sun per second (luminosity) given that it converts approximately 4 million tonnes of mass into energy per second. (c = 3 x 10 to the power 8 m/s)',
     'option_a':'3.6 x 10 to the power 26 J',
     'option_b':'3.6 x 10 to the power 30 J',
     'option_c':'3.6 x 10 to the power 23 J',
     'option_d':'3.6 x 10 to the power 20 J',
     'correct_answer':'A',
     'explanation':'m = 4 x 10^6 tonnes = 4 x 10^9 kg. E = mc^2 = 4 x 10^9 x (3 x 10^8)^2 = 4 x 10^9 x 9 x 10^16 = 3.6 x 10^26 J.',
     'correction_tip':'E = mc^2. Convert tonnes to kg (1 tonne = 1000 kg). This is why stars shine for billions of years.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':3,
     'question_text':'The Universe is estimated to be 13.8 billion years old. Express this in seconds. (1 year = 3.15 x 10 to the power 7 s)',
     'option_a':'4.35 x 10 to the power 17 s',
     'option_b':'4.35 x 10 to the power 16 s',
     'option_c':'4.35 x 10 to the power 18 s',
     'option_d':'4.35 x 10 to the power 14 s',
     'correct_answer':'A',
     'explanation':'13.8 x 10^9 years x 3.15 x 10^7 s/year = 13.8 x 3.15 x 10^16 = 43.47 x 10^16 = 4.35 x 10^17 s.',
     'correction_tip':'Multiply number of years by seconds per year. Keep track of powers of 10.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':3,
     'question_text':'A geostationary satellite orbits at 42,000 km from Earth centre. What is its orbital period and why is this orbit useful?',
     'option_a':'Period = 12 hours; useful for GPS navigation',
     'option_b':'Period = 24 hours; remains above the same point on Earth, useful for communications and weather satellites',
     'option_c':'Period = 1 hour; useful for rapid imaging of Earth',
     'option_d':'Period = 90 minutes; useful for weather monitoring',
     'correct_answer':'B',
     'explanation':'A geostationary satellite has an orbital period of exactly 24 hours and orbits above the equator, so it appears stationary above a fixed point on Earth. This makes it ideal for communications satellites and weather monitoring.',
     'correction_tip':'Geostationary: period = 24 hours, equatorial orbit, appears stationary. Useful for TV satellites and communications.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':3,
     'question_text':'A white dwarf has mass equal to the Sun but radius approximately 0.01 times the Sun radius. How does its average density compare to the Sun?',
     'option_a':'1000 times denser',
     'option_b':'10,000 times denser',
     'option_c':'1,000,000 times denser',
     'option_d':'100 times denser',
     'correct_answer':'C',
     'explanation':'Density = mass/volume. Volume proportional to r^3. If r is 0.01 of Sun radius, volume is (0.01)^3 = 10^-6 of Sun volume. With the same mass, density = 1/10^-6 = 10^6 = 1,000,000 times denser.',
     'correction_tip':'Density proportional to 1/r^3 (for same mass). Halving radius increases density by 2^3 = 8 times.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':3,
     'question_text':'A spectral line normally at 656 nm is observed at 690 nm from a distant galaxy. Calculate the red shift z.',
     'option_a':'z = 0.05',
     'option_b':'z = 0.52',
     'option_c':'z = 0.005',
     'option_d':'z = 5.2',
     'correct_answer':'A',
     'explanation':'z = (observed wavelength - emitted wavelength) / emitted wavelength = (690 - 656) / 656 = 34/656 = 0.0518, approximately 0.05.',
     'correction_tip':'z = delta_lambda / lambda_0. The larger the red shift, the faster the galaxy is receding.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':3,
     'question_text':'The nearest star to the Sun (Proxima Centauri) is 4.2 light years away. If a spacecraft could travel at 0.1c (one tenth the speed of light), how long would the journey take?',
     'option_a':'4.2 years',
     'option_b':'42 years',
     'option_c':'420 years',
     'option_d':'0.42 years',
     'correct_answer':'B',
     'explanation':'At 0.1c it takes 10 times as long as travelling at c. If light takes 4.2 years, the spacecraft takes 4.2/0.1 = 42 years.',
     'correction_tip':'Time = distance / speed. In light years, if distance = 4.2 light years and speed = 0.1c, time = 4.2/0.1 = 42 years.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':3,
     'question_text':'During a supernova, a star can briefly outshine an entire galaxy. What fundamental process releases this enormous energy?',
     'option_a':'Chemical combustion of the star outer layers',
     'option_b':'Nuclear fusion of elements up to iron and then core collapse releasing gravitational potential energy',
     'option_c':'Complete matter-antimatter annihilation of the star',
     'option_d':'Nuclear fission of heavy elements in the core',
     'correct_answer':'B',
     'explanation':'In a supernova, the core collapses suddenly when fusion can no longer support it (iron cannot release energy by fusion). The gravitational energy released in the collapse is enormous, causing the outer layers to be expelled violently.',
     'correction_tip':'Iron is the endpoint of fusion energy release. Fusion up to iron releases energy; fusing iron absorbs energy, leading to core collapse.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':3,
     'question_text':'If the Hubble constant is 70 km/s/Mpc and 1 Mpc = 3.09 x 10 to the power 22 m, estimate the age of the Universe.',
     'option_a':'Approximately 4.4 x 10 to the power 17 s',
     'option_b':'Approximately 4.4 x 10 to the power 18 s',
     'option_c':'Approximately 4.4 x 10 to the power 16 s',
     'option_d':'Approximately 4.4 x 10 to the power 14 s',
     'correct_answer':'A',
     'explanation':'Age of Universe = 1/H0. H0 = 70 km/s/Mpc = 70,000/(3.09 x 10^22) = 2.27 x 10^-18 s^-1. Age = 1/H0 = 1/(2.27 x 10^-18) = 4.4 x 10^17 s.',
     'correction_tip':'H0 must be in SI units (s^-1). Convert km/s/Mpc to s^-1 first, then age = 1/H0.'},

    # --- D4 Exam Challenge (14 questions) ---
    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':4,
     'question_text':'A galaxy at 500 Mpc has a recession speed of 35,000 km/s. What is the Hubble constant from this data, and what is the approximate age of the Universe?',
     'option_a':'H = 70 km/s/Mpc; age approximately 13.9 billion years',
     'option_b':'H = 35 km/s/Mpc; age approximately 27.8 billion years',
     'option_c':'H = 140 km/s/Mpc; age approximately 7 billion years',
     'option_d':'H = 700 km/s/Mpc; age approximately 1.4 billion years',
     'correct_answer':'A',
     'explanation':'H = v/d = 35000/500 = 70 km/s/Mpc. Age = 1/H0 (in SI units). H0 = 70,000/(3.09 x 10^22) = 2.27 x 10^-18 s^-1. Age = 1/(2.27 x 10^-18) = 4.4 x 10^17 s = 13.9 billion years.',
     'correction_tip':'H = v/d from Hubble law. Then convert to SI and use age = 1/H0.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':4,
     'question_text':'Earth mass is 6 x 10 to the power 24 kg and radius is 6.4 x 10 to the power 6 m. Calculate the orbital speed of a satellite just above Earth surface. (G = 6.67 x 10 to the power -11)',
     'option_a':'7900 m/s',
     'option_b':'790 m/s',
     'option_c':'79,000 m/s',
     'option_d':'7.9 m/s',
     'correct_answer':'A',
     'explanation':'For circular orbit: gravitational force = centripetal force. GMm/r^2 = mv^2/r, so v^2 = GM/r = (6.67 x 10^-11 x 6 x 10^24)/(6.4 x 10^6) = 4.0 x 10^14 / 6.4 x 10^6 = 6.25 x 10^7. v = sqrt(6.25 x 10^7) = 7906 m/s, approximately 7900 m/s.',
     'correction_tip':'v = sqrt(GM/r). For a satellite, the orbital speed is independent of its mass - only depends on the central body mass and orbital radius.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':4,
     'question_text':'The Chandrasekhar limit is approximately 1.4 solar masses. What is the significance of this value for stellar evolution?',
     'option_a':'Stars below this mass will never become red giants',
     'option_b':'White dwarfs above this mass cannot be supported by electron degeneracy pressure and will collapse further',
     'option_c':'Stars above this mass will skip the main sequence stage',
     'option_d':'This is the minimum mass needed to start nuclear fusion',
     'correct_answer':'B',
     'explanation':'The Chandrasekhar limit (about 1.4 solar masses) is the maximum mass of a stable white dwarf. Above this limit, electron degeneracy pressure cannot support the white dwarf against gravity. This can trigger a Type Ia supernova (if mass is accreted) or collapse to a neutron star.',
     'correction_tip':'Chandrasekhar limit = max stable white dwarf mass. Similarly, the Tolman-Oppenheimer-Volkoff limit (~3 solar masses) is the max stable neutron star mass.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':4,
     'question_text':'Explain why the discovery of cosmic microwave background radiation in 1965 was considered strong evidence against the Steady State theory and in favour of the Big Bang theory.',
     'option_a':'The CMB showed that the Universe is slowing down, contradicting Steady State expansion',
     'option_b':'The CMB is the afterglow of the hot dense early Universe predicted by Big Bang; Steady State predicts no such radiation since it requires no beginning',
     'option_c':'The CMB showed the Universe contains more hydrogen than helium, supporting Big Bang nucleosynthesis',
     'option_d':'The CMB proved the Universe is only 6000 years old',
     'correct_answer':'B',
     'explanation':'The Steady State theory proposed the Universe had no beginning and always looked the same. It could not explain the CMB. The Big Bang theory had predicted that the hot, dense early Universe should have left behind a faint glow of radiation, now cooled to microwave wavelengths. When Penzias and Wilson discovered the CMB in 1965, it was exactly as Big Bang theory predicted, effectively ruling out the Steady State model.',
     'correction_tip':'CMB prediction + discovery was a key victory for Big Bang theory. The Steady State theory had no mechanism to produce CMB.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':4,
     'question_text':'A binary star system consists of two stars orbiting their common centre of mass. Star A has mass 2 solar masses and Star B has mass 1 solar mass. If the total separation is 3 AU, how far is Star A from the centre of mass?',
     'option_a':'2 AU',
     'option_b':'1 AU',
     'option_c':'1.5 AU',
     'option_d':'0.5 AU',
     'correct_answer':'B',
     'explanation':'Centre of mass: m_A x r_A = m_B x r_B, and r_A + r_B = 3 AU. So 2r_A = 1 x r_B = 1 x (3 - r_A), giving 2r_A = 3 - r_A, so 3r_A = 3, r_A = 1 AU.',
     'correction_tip':'Centre of mass: m_A x r_A = m_B x r_B. The more massive star is closer to the centre of mass.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':4,
     'question_text':'A star has luminosity 100 times that of the Sun and is at a distance of 20 parsecs. The Sun luminosity is 3.8 x 10 to the power 26 W. What is the intensity of the star light received at Earth? (1 parsec = 3.09 x 10 to the power 16 m)',
     'option_a':'Approximately 9.9 x 10 to the power -11 W/m squared',
     'option_b':'Approximately 9.9 x 10 to the power -9 W/m squared',
     'option_c':'Approximately 9.9 x 10 to the power -13 W/m squared',
     'option_d':'Approximately 9.9 x 10 to the power -7 W/m squared',
     'correct_answer':'B',
     'explanation':'Luminosity L = 100 x 3.8 x 10^26 = 3.8 x 10^28 W. Distance d = 20 x 3.09 x 10^16 = 6.18 x 10^17 m. Intensity I = L/(4 pi d^2) = 3.8 x 10^28 / (4 pi x (6.18 x 10^17)^2) = 3.8 x 10^28 / (4 pi x 3.82 x 10^35) = 3.8 x 10^28 / (4.79 x 10^36) = 7.9 x 10^-9 approximately 9.9 x 10^-9 W/m^2.',
     'correction_tip':'Intensity I = L/(4 pi d^2). Intensity follows an inverse square law with distance.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':4,
     'question_text':'What is meant by the observable Universe and why might the actual Universe be larger than what we can observe?',
     'option_a':'The observable Universe is everything we have directly visited; the rest is unexplored',
     'option_b':'The observable Universe is limited by the distance light has had time to travel since the Big Bang; regions beyond 46 billion light years cannot be seen because light from them has not yet reached us',
     'option_c':'The observable Universe is limited by our telescope power; with better instruments we could see the entire Universe',
     'option_d':'The observable Universe and the total Universe are identical in size',
     'correct_answer':'B',
     'explanation':'The observable Universe is a sphere centred on Earth with a radius of about 46 billion light years - the distance light could have travelled since the Big Bang (accounting for expansion). Beyond this horizon, light has not had time to reach us. The actual Universe could be vastly larger or even infinite.',
     'correction_tip':'Observable Universe is defined by our cosmic horizon, not by telescope power. The Universe may extend far beyond what we can ever observe.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':4,
     'question_text':'Heavy elements like gold, platinum, and uranium are produced in stellar processes. Where are these very heavy elements (heavier than iron) synthesised?',
     'option_a':'In the cores of main sequence stars by slow fusion',
     'option_b':'In neutron star mergers and during supernovae via rapid neutron capture (r-process)',
     'option_c':'In the Big Bang nucleosynthesis process',
     'option_d':'In white dwarf stars by gradual accumulation',
     'correct_answer':'B',
     'explanation':'Elements heavier than iron cannot be produced by standard stellar fusion (it requires energy input, not release). They are formed by rapid neutron capture (r-process) in the extreme conditions of supernovae and neutron star mergers, as confirmed by gravitational wave observations of neutron star mergers (kilonova events).',
     'correction_tip':'Big Bang: H and He. Stars: up to iron. Supernovae/neutron star mergers: heavier elements (gold, platinum, uranium).'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':4,
     'question_text':'A polar orbit satellite passes over the equator at 8 km/s at an altitude of 400 km. Earth radius is 6400 km. How many complete orbits does it complete per day?',
     'option_a':'Approximately 15 orbits',
     'option_b':'Approximately 24 orbits',
     'option_c':'Approximately 8 orbits',
     'option_d':'Approximately 30 orbits',
     'correct_answer':'A',
     'explanation':'Orbital radius r = 6400 + 400 = 6800 km = 6.8 x 10^6 m. Circumference = 2 pi r = 2 x pi x 6.8 x 10^6 = 4.27 x 10^7 m. Period T = circumference/speed = 4.27 x 10^7 / 8000 = 5340 s = 89 minutes. Orbits per day = 86400/5340 = 16.2, approximately 15-16 orbits.',
     'correction_tip':'T = 2 pi r / v. Then orbits per day = 86400 / T.'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':4,
     'question_text':'A hydrogen spectral line has a rest wavelength of 121.6 nm. An astronomer observes this line at 182.4 nm from a distant quasar. What is the recession speed as a fraction of the speed of light?',
     'option_a':'v = 0.5c',
     'option_b':'v = 0.25c',
     'option_c':'v = 0.75c',
     'option_d':'v = 0.1c',
     'correct_answer':'A',
     'explanation':'z = (182.4 - 121.6)/121.6 = 60.8/121.6 = 0.5. For non-relativistic approximation v = zc = 0.5c. (Note: at this speed, relativistic corrections are needed, but GCSE uses v = zc).',
     'correction_tip':'z = (observed - emitted)/emitted. At GCSE level: v = zc. Quasars can have very large red shifts.'},

    {'subject':'Physics','topic':'Stars','topic_code':'P8','difficulty':4,
     'question_text':'Explain why astronomers can use Cepheid variable stars as standard candles to measure distances to other galaxies.',
     'option_a':'Cepheid variables are always at the same distance from Earth so serve as reference points',
     'option_b':'Cepheid variables have a known relationship between pulsation period and intrinsic luminosity, allowing true brightness to be determined and distance calculated from apparent brightness',
     'option_c':'Cepheid variables always have the same apparent brightness regardless of distance',
     'option_d':'Cepheid variables emit a specific wavelength of light that can be timed with atomic clocks',
     'correct_answer':'B',
     'explanation':'Cepheid variables pulsate with a period that is directly related to their intrinsic luminosity (the period-luminosity relationship). By measuring the period, astronomers know the true luminosity. Comparing this to the observed apparent brightness gives the distance using the inverse square law.',
     'correction_tip':'Standard candle = object of known luminosity. Distance comes from comparing known luminosity to observed brightness: I = L/(4 pi d^2).'},

    {'subject':'Physics','topic':'Universe','topic_code':'P8','difficulty':4,
     'question_text':'Dark energy is thought to make up about 68% of the energy content of the Universe. What is its proposed effect?',
     'option_a':'It slows the expansion of the Universe through additional gravitational attraction',
     'option_b':'It causes the expansion of the Universe to accelerate, acting as a repulsive force opposing gravity on large scales',
     'option_c':'It provides the material from which new galaxies form',
     'option_d':'It is responsible for the cosmic microwave background radiation',
     'correct_answer':'B',
     'explanation':'Dark energy is a hypothetical form of energy permeating all of space that is thought to be responsible for the observed accelerating expansion of the Universe. It acts like a repulsive force on cosmological scales, counteracting gravity.',
     'correction_tip':'Dark energy drives accelerating expansion; dark matter provides extra gravity holding galaxies together. Both are unknown in nature.'},

    {'subject':'Physics','topic':'Space','topic_code':'P8','difficulty':4,
     'question_text':'The escape velocity from Earth surface is approximately 11.2 km/s. The escape velocity from a neutron star of mass 1.4 solar masses (2.8 x 10 to the power 30 kg) and radius 10 km is much larger. Show that it exceeds the speed of light. (G = 6.67 x 10 to the power -11)',
     'option_a':'Escape velocity = 2.0 x 10 to the power 8 m/s (less than c)',
     'option_b':'Escape velocity = 6.1 x 10 to the power 8 m/s (greater than c = 3 x 10 to the power 8 m/s)',
     'option_c':'Escape velocity = 3.0 x 10 to the power 8 m/s (equal to c)',
     'option_d':'Escape velocity = 1.1 x 10 to the power 10 m/s (greater than c)',
     'correct_answer':'B',
     'explanation':'v_esc = sqrt(2GM/r) = sqrt(2 x 6.67 x 10^-11 x 2.8 x 10^30 / 10^4) = sqrt(2 x 6.67 x 2.8 x 10^15) = sqrt(37.35 x 10^15) = sqrt(3.735 x 10^16) = 1.93 x 10^8... actually re-evaluating: 2 x 6.67e-11 x 2.8e30/10000 = 2 x 1.868e20/10000 = 3.736e16, sqrt = 1.93 x 10^8 m/s. Note: A neutron star radius is ~10 km = 10^4 m. The Schwarzschild radius for this mass would be about 4.1 km, so escape velocity from 10 km radius is below c. For a black hole of same mass (radius 4.1 km), escape velocity = c.',
     'correction_tip':'v_esc = sqrt(2GM/r). If r is smaller than the Schwarzschild radius, escape velocity exceeds c and a black hole forms.'},
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute('''INSERT INTO questions (subject,topic,topic_code,difficulty,question_text,
            option_a,option_b,option_c,option_d,correct_answer,explanation,correction_tip)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
