QUESTIONS = [
    # =========================================================
    # P5 FORCES - D1 EASY (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'Which of the following is a contact force?',
     'option_a':'Gravity','option_b':'Magnetism','option_c':'Friction','option_d':'Electrostatic force',
     'correct_answer':'C',
     'explanation':'Friction is a contact force because it only acts when two surfaces are touching. Gravity, magnetism and electrostatic forces are non-contact forces.',
     'correction_tip':'Contact forces require physical contact between objects; non-contact forces act at a distance.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What is the unit of force?',
     'option_a':'Joule','option_b':'Watt','option_c':'Newton','option_d':'Pascal',
     'correct_answer':'C',
     'explanation':'Force is measured in Newtons (N), named after Isaac Newton.',
     'correction_tip':'Remember: Newton = kg m/s^2. Do not confuse with Joule (energy) or Watt (power).'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'An object has a mass of 5 kg. What is its weight on Earth where g = 10 N/kg?',
     'option_a':'2 N','option_b':'15 N','option_c':'50 N','option_d':'500 N',
     'correct_answer':'C',
     'explanation':'W = mg = 5 x 10 = 50 N.',
     'correction_tip':'Use W = mg. Mass is in kg, g = 10 N/kg on Earth, weight is in Newtons.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What does a resultant force of zero mean for a stationary object?',
     'option_a':'It accelerates','option_b':'It remains stationary','option_c':'It moves in a circle','option_d':'It decelerates',
     'correct_answer':'B',
     'explanation':'If the resultant force is zero and the object is stationary, it remains stationary (Newton\'s 1st Law).',
     'correction_tip':'Zero resultant force means no change in motion - stationary objects stay still, moving objects continue at constant velocity.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What is the formula for calculating speed?',
     'option_a':'speed = distance x time','option_b':'speed = distance / time','option_c':'speed = time / distance','option_d':'speed = force / mass',
     'correct_answer':'B',
     'explanation':'Speed = distance / time (v = s/t). It is measured in metres per second (m/s).',
     'correction_tip':'Remember the formula triangle: distance = speed x time. Cover what you want to find.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'Which of the following best describes a scalar quantity?',
     'option_a':'Has magnitude and direction','option_b':'Has magnitude only','option_c':'Has direction only','option_d':'Has no measurable value',
     'correct_answer':'B',
     'explanation':'Scalar quantities have magnitude (size) only. Examples include speed, mass, and temperature.',
     'correction_tip':'Scalars have size only; vectors have both size and direction. Speed is scalar, velocity is vector.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'A car travels 120 m in 10 seconds. What is its average speed?',
     'option_a':'1200 m/s','option_b':'12 m/s','option_c':'0.08 m/s','option_d':'110 m/s',
     'correct_answer':'B',
     'explanation':'Speed = distance / time = 120 / 10 = 12 m/s.',
     'correction_tip':'Divide distance by time to get speed. Check units carefully.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What does a horizontal line on a distance-time graph represent?',
     'option_a':'Constant speed','option_b':'Acceleration','option_c':'The object is stationary','option_d':'Deceleration',
     'correct_answer':'C',
     'explanation':'A horizontal line on a distance-time graph means the distance is not changing, so the object is stationary.',
     'correction_tip':'Slope on a distance-time graph = speed. No slope = no movement.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'Which law states that for every action there is an equal and opposite reaction?',
     'option_a':'Newton\'s 1st Law','option_b':'Newton\'s 2nd Law','option_c':'Newton\'s 3rd Law','option_d':'Hooke\'s Law',
     'correct_answer':'C',
     'explanation':'Newton\'s 3rd Law states that forces come in equal and opposite pairs acting on different objects.',
     'correction_tip':'3rd Law pairs act on DIFFERENT objects. The forces are equal in size but opposite in direction.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What is the difference between mass and weight?',
     'option_a':'Mass is measured in Newtons; weight in kg','option_b':'Mass is the amount of matter; weight is the gravitational force on that mass','option_c':'They are the same thing','option_d':'Mass changes with gravity; weight does not',
     'correct_answer':'B',
     'explanation':'Mass is the amount of matter in an object (kg). Weight is the gravitational force acting on that mass (N).',
     'correction_tip':'Mass is constant everywhere. Weight changes depending on gravitational field strength.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'An object at rest on a table has two forces acting on it: weight downward and normal reaction upward. What can you conclude?',
     'option_a':'The object is accelerating upward','option_b':'The forces are unbalanced','option_c':'The resultant force is zero','option_d':'Weight is greater than normal reaction',
     'correct_answer':'C',
     'explanation':'Since the object is at rest, the forces must be balanced and the resultant force is zero.',
     'correction_tip':'Balanced forces (resultant = 0) mean no change in motion.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What does a steeper gradient on a distance-time graph indicate?',
     'option_a':'Slower speed','option_b':'Greater speed','option_c':'Negative acceleration','option_d':'Constant acceleration',
     'correct_answer':'B',
     'explanation':'A steeper gradient on a distance-time graph means the object covers more distance per unit time, so it is moving faster.',
     'correction_tip':'Gradient = speed on a d-t graph. Steeper = faster.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'Which of these is a non-contact force?',
     'option_a':'Air resistance','option_b':'Tension','option_c':'Normal reaction','option_d':'Gravity',
     'correct_answer':'D',
     'explanation':'Gravity acts at a distance without objects needing to touch. The others require contact.',
     'correction_tip':'Non-contact forces: gravity, magnetism, electrostatic. Contact forces: friction, tension, normal reaction, air resistance.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'What is the unit of acceleration?',
     'option_a':'m/s','option_b':'m/s^2','option_c':'N/kg','option_d':'kg m/s',
     'correct_answer':'B',
     'explanation':'Acceleration is the rate of change of velocity, measured in metres per second squared (m/s^2).',
     'correction_tip':'Acceleration = change in velocity / time. Units = m/s divided by s = m/s^2.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'A free body diagram shows the forces acting on an object. If an object has 30 N to the right and 10 N to the left, what is the resultant force?',
     'option_a':'40 N to the right','option_b':'20 N to the left','option_c':'20 N to the right','option_d':'30 N to the right',
     'correct_answer':'C',
     'explanation':'Resultant = 30 - 10 = 20 N in the direction of the larger force (to the right).',
     'correction_tip':'For forces along the same line, subtract smaller from larger and use the direction of the larger force.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':1,
     'question_text':'Stopping distance is made up of which two distances?',
     'option_a':'Reaction distance and impact distance','option_b':'Thinking distance and braking distance','option_c':'Speed distance and time distance','option_d':'Initial distance and final distance',
     'correct_answer':'B',
     'explanation':'Stopping distance = thinking distance (distance travelled during reaction time) + braking distance (distance during braking).',
     'correction_tip':'Thinking distance depends on reaction time; braking distance depends on speed, road conditions and brakes.'},

    # =========================================================
    # P5 FORCES - D2 MEDIUM (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':2,
     'question_text':'A resultant force of 20 N acts on a 4 kg object. What is the acceleration of the object?',
     'option_a':'80 m/s^2','option_b':'0.2 m/s^2','option_c':'5 m/s^2','option_d':'16 m/s^2',
     'correct_answer':'C',
     'explanation':'F = ma, so a = F/m = 20/4 = 5 m/s^2.',
     'correction_tip':'Rearrange F = ma to a = F/m. Ensure units are consistent (N, kg, m/s^2).'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':2,
     'question_text':'A spring with spring constant 200 N/m is extended by 0.05 m. What is the force applied?',
     'option_a':'4000 N','option_b':'10 N','option_c':'0.25 N','option_d':'4 N',
     'correct_answer':'B',
     'explanation':'F = ke = 200 x 0.05 = 10 N (Hooke\'s Law).',
     'correction_tip':'Hooke\'s Law: F = ke where k is spring constant (N/m) and e is extension (m).'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'How much work is done when a 500 N force moves an object 3 m in the direction of the force?',
     'option_a':'167 J','option_b':'503 J','option_c':'1500 J','option_d':'150 J',
     'correct_answer':'C',
     'explanation':'Work done = Force x distance = 500 x 3 = 1500 J.',
     'correction_tip':'W = Fs. Work done is in Joules. Distance must be in the direction of the force.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'A velocity-time graph shows a straight line with positive gradient. What does this represent?',
     'option_a':'Constant velocity','option_b':'Uniform deceleration','option_c':'Uniform acceleration','option_d':'Zero velocity',
     'correct_answer':'C',
     'explanation':'A straight line with positive gradient on a v-t graph means velocity increases uniformly, which is uniform acceleration.',
     'correction_tip':'Gradient of v-t graph = acceleration. Positive gradient = acceleration; negative = deceleration.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'What is the pressure exerted by a force of 100 N over an area of 0.5 m^2?',
     'option_a':'50 Pa','option_b':'200 Pa','option_c':'0.005 Pa','option_d':'50 N',
     'correct_answer':'B',
     'explanation':'Pressure = Force / Area = 100 / 0.5 = 200 Pa.',
     'correction_tip':'p = F/A. Pressure is in Pascals (Pa = N/m^2). Smaller area = greater pressure for same force.'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':2,
     'question_text':'A car accelerates from 10 m/s to 30 m/s in 5 seconds. What is its acceleration?',
     'option_a':'6 m/s^2','option_b':'4 m/s^2','option_c':'8 m/s^2','option_d':'2 m/s^2',
     'correct_answer':'B',
     'explanation':'a = (v - u) / t = (30 - 10) / 5 = 20 / 5 = 4 m/s^2.',
     'correction_tip':'Use a = (v - u) / t. v is final velocity, u is initial velocity.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':2,
     'question_text':'What is the momentum of a 3 kg object moving at 8 m/s?',
     'option_a':'24 kg m/s','option_b':'2.67 kg m/s','option_c':'11 kg m/s','option_d':'0.375 kg m/s',
     'correct_answer':'A',
     'explanation':'Momentum p = mv = 3 x 8 = 24 kg m/s.',
     'correction_tip':'p = mv. Units are kg m/s. Momentum is a vector quantity.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'Which factor does NOT affect thinking distance when stopping a vehicle?',
     'option_a':'Speed of the vehicle','option_b':'Condition of the tyres','option_c':'Reaction time of the driver','option_d':'Tiredness of the driver',
     'correct_answer':'B',
     'explanation':'Tyre condition affects braking distance, not thinking distance. Thinking distance depends on reaction time, which is affected by speed, tiredness, alcohol, and distractions.',
     'correction_tip':'Thinking distance = speed x reaction time. Anything affecting reaction time affects thinking distance.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'An object moves in a circle at constant speed. Which statement is correct?',
     'option_a':'No force is needed because speed is constant','option_b':'A centripetal force acts toward the centre of the circle','option_c':'The force acts outward from the centre','option_d':'The velocity is constant',
     'correct_answer':'B',
     'explanation':'Circular motion requires a centripetal force directed toward the centre of the circle. Although speed is constant, the direction changes so velocity changes.',
     'correction_tip':'Centripetal force causes direction change, not speed change. It acts inward (toward centre).'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':2,
     'question_text':'According to Newton\'s 1st Law, what happens to a moving object when there is no resultant force?',
     'option_a':'It slows down gradually','option_b':'It continues at constant velocity','option_c':'It accelerates','option_d':'It stops immediately',
     'correct_answer':'B',
     'explanation':'Newton\'s 1st Law (inertia): an object continues at constant velocity (or remains stationary) unless acted upon by a resultant force.',
     'correction_tip':'No resultant force = no change in motion. This is inertia.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'The area under a velocity-time graph represents which quantity?',
     'option_a':'Acceleration','option_b':'Speed','option_c':'Distance travelled','option_d':'Force',
     'correct_answer':'C',
     'explanation':'The area under a v-t graph equals the distance (or displacement) travelled by the object.',
     'correction_tip':'Area under v-t graph = displacement. Count squares or use geometry for irregular shapes.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'What happens to pressure in a fluid as depth increases?',
     'option_a':'Pressure decreases','option_b':'Pressure remains constant','option_c':'Pressure increases','option_d':'Pressure becomes zero',
     'correct_answer':'C',
     'explanation':'Fluid pressure increases with depth because of the increasing weight of fluid above. p = rho x g x h.',
     'correction_tip':'More fluid above = more weight = more pressure. Pressure acts in all directions in a fluid.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'A machine does 600 J of work in 30 seconds. What is its power output?',
     'option_a':'18000 W','option_b':'570 W','option_c':'20 W','option_d':'630 W',
     'correct_answer':'C',
     'explanation':'Power = Work done / time = 600 / 30 = 20 W.',
     'correction_tip':'P = W/t. Power is in Watts (W). 1 W = 1 J/s.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':2,
     'question_text':'A spring obeys Hooke\'s Law up to its elastic limit. What happens if it is stretched beyond its elastic limit?',
     'option_a':'It returns to its original length when force is removed','option_b':'It becomes permanently deformed','option_c':'It exerts twice the force','option_d':'It shatters',
     'correct_answer':'B',
     'explanation':'Beyond the elastic limit, the spring is permanently deformed and will not return to its original length even when the force is removed.',
     'correction_tip':'Elastic limit = point of permanent deformation. Below it: elastic behaviour. Above it: plastic behaviour.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':2,
     'question_text':'A 2000 kg car experiences a braking force of 8000 N. What is the deceleration of the car?',
     'option_a':'16 m/s^2','option_b':'4 m/s^2','option_c':'0.25 m/s^2','option_d':'10 m/s^2',
     'correct_answer':'B',
     'explanation':'a = F/m = 8000 / 2000 = 4 m/s^2. This is a deceleration.',
     'correction_tip':'Use F = ma rearranged to a = F/m. For deceleration, the force opposes motion.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':2,
     'question_text':'Two ice skaters push each other apart. Skater A (mass 60 kg) moves at 2 m/s to the right. Skater B has mass 40 kg. What is skater B\'s velocity?',
     'option_a':'2 m/s to the left','option_b':'3 m/s to the left','option_c':'1.33 m/s to the left','option_d':'4 m/s to the left',
     'correct_answer':'B',
     'explanation':'Conservation of momentum: total momentum before = 0 (both stationary). So 60x2 + 40xv = 0, giving v = -3 m/s (3 m/s to the left).',
     'correction_tip':'Total momentum before = total momentum after. If system starts from rest, total momentum remains zero.'},

    # =========================================================
    # P5 FORCES - D3 HARD (15 questions)
    # =========================================================
    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':3,
     'question_text':'A ball is thrown horizontally from rest vertically. It accelerates from 0 m/s and reaches 25 m/s. Using v^2 = u^2 + 2as with u = 0, v = 25 m/s, a = 10 m/s^2, what distance has it fallen?',
     'option_a':'62.5 m','option_b':'31.25 m','option_c':'125 m','option_d':'2.5 m',
     'correct_answer':'B',
     'explanation':'v^2 = u^2 + 2as => 625 = 0 + 2(10)s => s = 625/20 = 31.25 m.',
     'correction_tip':'v^2 = u^2 + 2as. Rearrange to s = (v^2 - u^2) / (2a). Substitute carefully.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':3,
     'question_text':'A 0.5 kg ball hits a wall at 6 m/s and bounces back at 4 m/s. If contact lasts 0.02 s, what is the average force exerted on the ball?',
     'option_a':'250 N','option_b':'100 N','option_c':'500 N','option_d':'50 N',
     'correct_answer':'A',
     'explanation':'Change in momentum = m(v - u) = 0.5 x ((-4) - 6) = 0.5 x (-10) = -5 kg m/s. Force = change in momentum / time = 5 / 0.02 = 250 N.',
     'correction_tip':'F = delta p / delta t. Take care with signs: bouncing back means velocity reverses direction.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':3,
     'question_text':'A cyclist of total mass 80 kg travels at constant velocity on a flat road. The driving force is 40 N. What is the total resistive force?',
     'option_a':'800 N','option_b':'0 N','option_c':'40 N','option_d':'2 N',
     'correct_answer':'C',
     'explanation':'At constant velocity, the resultant force is zero. Therefore the resistive force equals the driving force = 40 N.',
     'correction_tip':'Constant velocity means balanced forces. Driving force = resistive force (resultant = 0).'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':3,
     'question_text':'A rocket of mass 500 kg (including fuel) has a thrust of 7500 N. Taking g = 10 N/kg, what is the initial upward acceleration of the rocket?',
     'option_a':'5 m/s^2','option_b':'25 m/s^2','option_c':'15 m/s^2','option_d':'0 m/s^2',
     'correct_answer':'A',
     'explanation':'Weight = mg = 500 x 10 = 5000 N. Net upward force = 7500 - 5000 = 2500 N. a = F/m = 2500/500 = 5 m/s^2.',
     'correction_tip':'Find net force first: thrust minus weight. Then use a = F/m. Do not forget to subtract weight.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':3,
     'question_text':'A spring with spring constant 400 N/m stores 50 J of elastic potential energy. What is the extension?',
     'option_a':'0.5 m','option_b':'0.25 m','option_c':'0.125 m','option_d':'0.354 m',
     'correct_answer':'A',
     'explanation':'Elastic PE = 0.5 x k x e^2. 50 = 0.5 x 400 x e^2 => e^2 = 0.25 => e = 0.5 m.',
     'correction_tip':'Elastic PE = (1/2)ke^2. Rearrange to e = sqrt(2 x PE / k).'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':3,
     'question_text':'A vehicle travelling at 20 m/s brakes with a deceleration of 4 m/s^2. How far does it travel before stopping?',
     'option_a':'80 m','option_b':'100 m','option_c':'50 m','option_d':'40 m',
     'correct_answer':'C',
     'explanation':'v^2 = u^2 + 2as => 0 = 400 - 8s => s = 400/8 = 50 m.',
     'correction_tip':'Use v^2 = u^2 + 2as with v = 0 (stopped). Deceleration means a is negative.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':3,
     'question_text':'An object of mass 10 kg is on a slope inclined at 30 degrees. The component of weight parallel to the slope is W sin(30) = 50 N. The friction force is 20 N opposing motion. What is the net force along the slope?',
     'option_a':'30 N up the slope','option_b':'30 N down the slope','option_c':'70 N down the slope','option_d':'50 N down the slope',
     'correct_answer':'B',
     'explanation':'Net force = 50 N (down slope) - 20 N (friction up slope) = 30 N down the slope.',
     'correction_tip':'Resolve forces along the slope. Weight component down the slope minus friction up the slope gives net force.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':3,
     'question_text':'A 1200 kg car moving at 15 m/s collides with a stationary 800 kg car and they stick together. What is their combined velocity after the collision?',
     'option_a':'9 m/s','option_b':'12 m/s','option_c':'6 m/s','option_d':'18 m/s',
     'correct_answer':'A',
     'explanation':'Conservation of momentum: p_before = 1200 x 15 = 18000 kg m/s. p_after = (1200 + 800) x v = 2000v. v = 18000/2000 = 9 m/s.',
     'correction_tip':'For perfectly inelastic collisions, objects stick together. Use m1u1 + m2u2 = (m1+m2)v.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':3,
     'question_text':'A hydraulic system has a small piston of area 0.002 m^2 and a large piston of area 0.02 m^2. A force of 50 N is applied to the small piston. What force acts on the large piston?',
     'option_a':'500 N','option_b':'5 N','option_c':'1000 N','option_d':'250 N',
     'correct_answer':'A',
     'explanation':'Pressure is transmitted equally: P = F1/A1 = 50/0.002 = 25000 Pa. F2 = P x A2 = 25000 x 0.02 = 500 N.',
     'correction_tip':'In a hydraulic system, pressure is equal throughout. F2/A2 = F1/A1, so F2 = F1 x (A2/A1).'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':3,
     'question_text':'A stone is dropped from rest and falls for 3 seconds (g = 10 m/s^2). What is its velocity at the end of the 3 seconds?',
     'option_a':'10 m/s','option_b':'30 m/s','option_c':'45 m/s','option_d':'90 m/s',
     'correct_answer':'B',
     'explanation':'v = u + at = 0 + (10)(3) = 30 m/s.',
     'correction_tip':'Use v = u + at. For free fall, a = g = 10 m/s^2 and u = 0 if dropped from rest.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':3,
     'question_text':'A force of 60 N acts on a 3 kg object for 5 seconds from rest. What is the final velocity?',
     'option_a':'100 m/s','option_b':'36 m/s','option_c':'9 m/s','option_d':'20 m/s',
     'correct_answer':'A',
     'explanation':'Impulse = F x t = 60 x 5 = 300 N s. Impulse = change in momentum = mv - 0 = 3v. v = 300/3 = 100 m/s.',
     'correction_tip':'Impulse = Ft = delta(mv). Rearrange to find v.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':3,
     'question_text':'A person weighs 800 N and stands on a surface of area 0.04 m^2 (both feet). What pressure do they exert on the floor?',
     'option_a':'20000 Pa','option_b':'32 Pa','option_c':'32000 Pa','option_d':'2000 Pa',
     'correct_answer':'A',
     'explanation':'p = F/A = 800 / 0.04 = 20000 Pa.',
     'correction_tip':'p = F/A. Check area is in m^2 and force in N to get Pa.'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':3,
     'question_text':'On a velocity-time graph, a car travels at 20 m/s for 5 s, then decelerates uniformly to rest in 4 s. What is the total distance travelled?',
     'option_a':'140 m','option_b':'100 m','option_c':'180 m','option_d':'40 m',
     'correct_answer':'A',
     'explanation':'Area = (20 x 5) + (0.5 x 20 x 4) = 100 + 40 = 140 m.',
     'correction_tip':'Distance = area under v-t graph. For uniform deceleration, use area of triangle = 0.5 x base x height.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':3,
     'question_text':'A person of mass 70 kg stands in a lift accelerating upward at 2 m/s^2. What is the normal force from the floor on the person? (g = 10 N/kg)',
     'option_a':'700 N','option_b':'840 N','option_c':'560 N','option_d':'140 N',
     'correct_answer':'B',
     'explanation':'Net upward force = ma = 70 x 2 = 140 N. N - W = 140. N = W + 140 = 700 + 140 = 840 N.',
     'correction_tip':'Apply Newton\'s 2nd Law: resultant force = ma. The normal force must exceed weight to cause upward acceleration.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':3,
     'question_text':'An elastic band stores 0.18 J of elastic potential energy when extended by 6 cm (0.06 m). What is the spring constant of the elastic band?',
     'option_a':'100 N/m','option_b':'50 N/m','option_c':'100 N/m','option_d':'3 N/m',
     'correct_answer':'A',
     'explanation':'PE = 0.5 x k x e^2. 0.18 = 0.5 x k x (0.06)^2 = 0.5 x k x 0.0036. k = 0.18 / 0.0018 = 100 N/m.',
     'correction_tip':'Rearrange PE = (1/2)ke^2 to k = 2 x PE / e^2.'},

    # =========================================================
    # P5 FORCES - D4 EXAM CHALLENGE (15 questions)
    # =========================================================
    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':4,
     'question_text':'A 0.2 kg ball travelling at 5 m/s east collides with a 0.3 kg ball at rest. The 0.2 kg ball bounces back at 1 m/s west. What is the velocity of the 0.3 kg ball after the collision?',
     'option_a':'2 m/s east','option_b':'4 m/s east','option_c':'3 m/s east','option_d':'1.5 m/s east',
     'correct_answer':'B',
     'explanation':'p before = 0.2 x 5 = 1 kg m/s east. After collision: p after = 0.2 x (-1) + 0.3 x v = -0.2 + 0.3v. Conservation of momentum: 1 = -0.2 + 0.3v. 0.3v = 1.2. v = 4 m/s east.',
     'correction_tip':'Apply conservation of momentum. Assign positive direction and use signed velocities for bouncing objects. Check: total momentum before = total momentum after.'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':4,
     'question_text':'A car decelerates from 30 m/s to 10 m/s over a distance of 200 m. What is the deceleration?',
     'option_a':'2 m/s^2','option_b':'4 m/s^2','option_c':'1 m/s^2','option_d':'0.5 m/s^2',
     'correct_answer':'A',
     'explanation':'v^2 = u^2 + 2as: 100 = 900 + 2a(200). 400a = -800. a = -2 m/s^2. Deceleration = 2 m/s^2.',
     'correction_tip':'Use v^2 = u^2 + 2as. A negative value of a indicates deceleration.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':4,
     'question_text':'A 5000 kg lorry accelerates from 0 to 20 m/s in 8 seconds. The total resistive force is 500 N. What driving force must the engine produce?',
     'option_a':'12500 N','option_b':'13000 N','option_c':'12000 N','option_d':'500 N',
     'correct_answer':'B',
     'explanation':'Required acceleration = 20/8 = 2.5 m/s^2. Net force needed = ma = 5000 x 2.5 = 12500 N. Driving force = 12500 + 500 (overcomes resistance) = 13000 N.',
     'correction_tip':'Net force = driving force - resistance. Driving force = net force needed + resistive forces.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':4,
     'question_text':'A person pushes a 50 kg box at constant speed across a floor (mu = 0.3) with g = 10 N/kg. How much work do they do in pushing it 4 m?',
     'option_a':'600 J','option_b':'200 J','option_c':'2000 J','option_d':'150 J',
     'correct_answer':'A',
     'explanation':'Normal force = mg = 500 N. Friction = mu x N = 0.3 x 500 = 150 N. At constant speed, applied force = 150 N. W = Fs = 150 x 4 = 600 J.',
     'correction_tip':'At constant speed, applied force = friction force. W = Fs. Calculate friction from normal force and friction coefficient.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':4,
     'question_text':'A gun of mass 2 kg fires a 0.02 kg bullet at 300 m/s. What is the recoil velocity of the gun?',
     'option_a':'3 m/s','option_b':'6 m/s','option_c':'0.3 m/s','option_d':'30 m/s',
     'correct_answer':'A',
     'explanation':'Conservation of momentum: 0 = 0.02 x 300 + 2 x v_gun. 2 x v_gun = -6. v_gun = -3 m/s. Recoil speed = 3 m/s.',
     'correction_tip':'Initial momentum = 0 (both at rest). m1v1 + m2v2 = 0 after firing. The gun recoils in the opposite direction.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':4,
     'question_text':'An object is projected horizontally at 15 m/s from a cliff. It hits the ground after 4 s. How far from the base of the cliff does it land? (Ignore air resistance)',
     'option_a':'80 m','option_b':'60 m','option_c':'120 m','option_d':'30 m',
     'correct_answer':'B',
     'explanation':'Horizontal motion is independent of vertical. Horizontal distance = horizontal speed x time = 15 x 4 = 60 m.',
     'correction_tip':'Projectile motion: horizontal and vertical components are independent. Horizontal: no acceleration; vertical: a = g.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':4,
     'question_text':'A skydiver of mass 75 kg reaches terminal velocity. Air resistance is 750 N. What is terminal velocity condition and what is g at this location?',
     'option_a':'g = 10 N/kg; weight equals air resistance','option_b':'g = 8 N/kg; acceleration is zero','option_c':'g = 10 N/kg; air resistance exceeds weight','option_d':'g = 9.8 N/kg; weight exceeds air resistance',
     'correct_answer':'A',
     'explanation':'At terminal velocity, resultant force = 0, so weight = air resistance. Weight = 75 x 10 = 750 N = air resistance. g = 10 N/kg.',
     'correction_tip':'Terminal velocity occurs when weight = drag force, giving zero net force and constant velocity.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':4,
     'question_text':'A lever has its fulcrum 0.5 m from a 200 N load. How far from the fulcrum must a 50 N effort be applied on the other side to balance it?',
     'option_a':'0.125 m','option_b':'2 m','option_c':'4 m','option_d':'1 m',
     'correct_answer':'B',
     'explanation':'For balance: clockwise moment = anticlockwise moment. 200 x 0.5 = 50 x d. 100 = 50d. d = 2 m.',
     'correction_tip':'Moment = force x perpendicular distance. For equilibrium: sum of clockwise moments = sum of anticlockwise moments.'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':4,
     'question_text':'A train starts from rest and accelerates uniformly at 0.5 m/s^2 for 60 seconds, then travels at constant speed for 120 s, then decelerates uniformly to rest in 40 s. What is the total distance travelled?',
     'option_a':'4950 m','option_b':'5100 m','option_c':'4200 m','option_d':'3600 m',
     'correct_answer':'B',
     'explanation':'Phase 1: v = at = 0.5 x 60 = 30 m/s. d1 = 0.5 x 30 x 60 = 900 m. Phase 2: d2 = 30 x 120 = 3600 m. Phase 3: d3 = 0.5 x 30 x 40 = 600 m. Total = 900 + 3600 + 600 = 5100 m.',
     'correction_tip':'Break the journey into sections. Area under v-t graph for each section. Use triangle and rectangle areas.'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':4,
     'question_text':'A force-time graph for a collision shows a maximum force of 1200 N and the collision lasts 0.05 s. The shape is approximately triangular. What impulse does the object receive?',
     'option_a':'60 N s','option_b':'24000 N s','option_c':'30 N s','option_d':'12 N s',
     'correct_answer':'C',
     'explanation':'Impulse = area under force-time graph = 0.5 x base x height = 0.5 x 0.05 x 1200 = 30 N s.',
     'correction_tip':'Impulse = area under F-t graph. For a triangular shape, use area = 0.5 x base x height.'},

    {'subject':'Physics','topic':'Newton laws','topic_code':'P5','difficulty':4,
     'question_text':'Two masses, 3 kg and 5 kg, are connected by a light string over a frictionless pulley. What is the acceleration of the system? (g = 10 N/kg)',
     'option_a':'1.25 m/s^2','option_b':'2.5 m/s^2','option_c':'5 m/s^2','option_d':'10 m/s^2',
     'correct_answer':'B',
     'explanation':'Net force = (5 - 3) x 10 = 20 N. Total mass = 8 kg. a = F/m = 20/8 = 2.5 m/s^2.',
     'correction_tip':'In an Atwood machine, net force = difference in weights. Total mass = sum of both masses.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':4,
     'question_text':'A satellite of mass 500 kg orbits at a radius where the gravitational field strength is 9 N/kg. If it orbits at speed v, what centripetal acceleration does it experience?',
     'option_a':'9 m/s^2','option_b':'4500 N','option_c':'4 m/s^2','option_d':'18 m/s^2',
     'correct_answer':'A',
     'explanation':'Gravitational field strength = gravitational acceleration = 9 m/s^2. For a satellite, centripetal acceleration equals gravitational field strength at that orbit.',
     'correction_tip':'For a satellite, gravity provides centripetal force. g at that altitude = centripetal acceleration.'},

    {'subject':'Physics','topic':'Motion','topic_code':'P5','difficulty':4,
     'question_text':'Using kinematic equations, if a ball is thrown vertically upward at 20 m/s (g = 10 m/s^2), what is the maximum height reached?',
     'option_a':'40 m','option_b':'10 m','option_c':'20 m','option_d':'2 m',
     'correct_answer':'C',
     'explanation':'At maximum height, v = 0. v^2 = u^2 + 2as: 0 = 400 - 20s. s = 400/20 = 20 m.',
     'correction_tip':'At maximum height, v = 0. Use v^2 = u^2 + 2as with v = 0 to find s. a = -g (deceleration).'},

    {'subject':'Physics','topic':'Momentum','topic_code':'P5','difficulty':4,
     'question_text':'Why do airbags in cars reduce the risk of serious injury in a collision?',
     'option_a':'They increase the force experienced','option_b':'They reduce the speed of the car more quickly','option_c':'They increase the time over which momentum changes, reducing the force','option_d':'They increase the momentum of the occupant',
     'correct_answer':'C',
     'explanation':'F = delta p / delta t. Airbags increase the time (delta t) over which momentum changes, therefore reducing the force (F) experienced by the occupant.',
     'correction_tip':'Impulse = F x t = change in momentum. For a given impulse, increasing time reduces force.'},

    {'subject':'Physics','topic':'Forces','topic_code':'P5','difficulty':4,
     'question_text':'A 10 kg block is pushed up a smooth incline (no friction) at 30 degrees to the horizontal by a horizontal force F. The block moves at constant velocity. If g = 10 m/s^2, the component of weight down the slope is 50 N and the normal force gives a component 50N. What is F? (Hint: resolve horizontally)',
     'option_a':'57.7 N','option_b':'50 N','option_c':'100 N','option_d':'28.9 N',
     'correct_answer':'A',
     'explanation':'Resolving along slope: F cos(30) = W sin(30) = 50. F = 50/cos(30) = 50/0.866 = 57.7 N.',
     'correction_tip':'Resolve forces along and perpendicular to the slope. For constant velocity, net force along slope = 0.'},

    # =========================================================
    # P6 WAVES - D1 EASY (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What type of wave is a sound wave?',
     'option_a':'Transverse','option_b':'Longitudinal','option_c':'Electromagnetic','option_d':'Mechanical transverse',
     'correct_answer':'B',
     'explanation':'Sound waves are longitudinal waves where particles vibrate parallel to the direction of wave travel.',
     'correction_tip':'Longitudinal: vibration parallel to wave direction (e.g. sound). Transverse: vibration perpendicular (e.g. light, water waves).'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What is the frequency of a wave that has a period of 0.25 s?',
     'option_a':'4 Hz','option_b':'0.25 Hz','option_c':'2 Hz','option_d':'8 Hz',
     'correct_answer':'A',
     'explanation':'f = 1/T = 1/0.25 = 4 Hz.',
     'correction_tip':'Frequency and period are reciprocals: f = 1/T and T = 1/f.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':1,
     'question_text':'At what speed do electromagnetic waves travel in a vacuum?',
     'option_a':'3 x 10^6 m/s','option_b':'3 x 10^8 m/s','option_c':'3 x 10^10 m/s','option_d':'3 x 10^5 m/s',
     'correct_answer':'B',
     'explanation':'All electromagnetic waves travel at the speed of light in a vacuum: 3 x 10^8 m/s.',
     'correction_tip':'c = 3 x 10^8 m/s for all EM waves in vacuum. This is approximately 300,000 km/s.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What is the amplitude of a wave?',
     'option_a':'The distance between two peaks','option_b':'The maximum displacement from the equilibrium position','option_c':'The number of waves per second','option_d':'The time for one complete wave',
     'correct_answer':'B',
     'explanation':'Amplitude is the maximum displacement of particles from their equilibrium (rest) position.',
     'correction_tip':'Amplitude = maximum displacement from rest. Greater amplitude = greater energy carried by the wave.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':1,
     'question_text':'Which type of electromagnetic wave has the longest wavelength?',
     'option_a':'Gamma rays','option_b':'X-rays','option_c':'Radio waves','option_d':'Ultraviolet',
     'correct_answer':'C',
     'explanation':'Radio waves have the longest wavelengths in the electromagnetic spectrum, ranging from millimetres to kilometres.',
     'correction_tip':'EM spectrum order (longest to shortest wavelength): radio, microwave, infrared, visible, UV, X-ray, gamma.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':1,
     'question_text':'What is the law of reflection?',
     'option_a':'The angle of incidence equals the angle of refraction','option_b':'The angle of incidence equals the angle of reflection','option_c':'Light bends toward the normal when entering a denser medium','option_d':'Light cannot reflect off smooth surfaces',
     'correct_answer':'B',
     'explanation':'The law of reflection states that the angle of incidence equals the angle of reflection, both measured from the normal.',
     'correction_tip':'Both angles are measured from the NORMAL (perpendicular to the surface), not from the surface itself.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'Which of the following is a transverse wave?',
     'option_a':'Sound wave in air','option_b':'P-wave (seismic)','option_c':'Light wave','option_d':'Ultrasound wave',
     'correct_answer':'C',
     'explanation':'Light waves are transverse electromagnetic waves. Sound, P-waves, and ultrasound are longitudinal waves.',
     'correction_tip':'EM waves (including light) are transverse. Sound waves (including ultrasound) and P-waves are longitudinal.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':1,
     'question_text':'Which part of the electromagnetic spectrum is used in medical X-rays?',
     'option_a':'Ultraviolet','option_b':'Gamma rays','option_c':'Infrared','option_d':'X-rays',
     'correct_answer':'D',
     'explanation':'X-rays are used in medical imaging because they penetrate soft tissue but are absorbed by dense bones.',
     'correction_tip':'X-rays are used for medical imaging of bones. Gamma rays are used in cancer treatment and medical tracers.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What happens to a wave when it passes from one medium to another?',
     'option_a':'Reflection','option_b':'Diffraction','option_c':'Refraction','option_d':'Dispersion',
     'correct_answer':'C',
     'explanation':'When a wave passes from one medium to another, it changes speed, which can cause refraction (change of direction).',
     'correction_tip':'Refraction = change of direction due to change in speed when crossing a boundary between media.'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':1,
     'question_text':'What does a longitudinal wave consist of?',
     'option_a':'Compressions and rarefactions','option_b':'Crests and troughs','option_c':'Only compressions','option_d':'Electric and magnetic fields',
     'correct_answer':'A',
     'explanation':'Longitudinal waves consist of compressions (regions of high pressure) and rarefactions (regions of low pressure).',
     'correction_tip':'Compressions = particles pushed together. Rarefactions = particles spread apart. Sound travels as alternate compressions and rarefactions.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':1,
     'question_text':'Which type of electromagnetic radiation is used to cook food in microwave ovens?',
     'option_a':'Infrared','option_b':'Radio waves','option_c':'Microwaves','option_d':'X-rays',
     'correct_answer':'C',
     'explanation':'Microwaves cause water molecules to vibrate, heating food. They are used in microwave ovens.',
     'correction_tip':'Microwaves are absorbed by water and fat molecules. They can also be used for communications and satellite TV.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What is the wavelength of a wave?',
     'option_a':'The height of the wave','option_b':'The time for one complete oscillation','option_c':'The distance between two successive identical points on a wave','option_d':'The number of waves per second',
     'correct_answer':'C',
     'explanation':'Wavelength is the distance between two successive identical points (e.g. two crests or two troughs).',
     'correction_tip':'Wavelength (lambda) measured in metres. It is the length of one complete wave cycle.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':1,
     'question_text':'An image in a plane mirror appears to be the same distance behind the mirror as the object is in front. What type of image is this?',
     'option_a':'Real and inverted','option_b':'Virtual and upright','option_c':'Real and upright','option_d':'Virtual and inverted',
     'correct_answer':'B',
     'explanation':'A plane mirror forms a virtual, upright image that appears to be behind the mirror. It cannot be projected onto a screen.',
     'correction_tip':'Virtual images cannot be projected onto a screen. Plane mirror images are: same size, virtual, upright, laterally inverted.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':1,
     'question_text':'What is diffraction?',
     'option_a':'The bending of waves around obstacles or through gaps','option_b':'The bouncing of waves off surfaces','option_c':'The change of speed of waves at boundaries','option_d':'The combining of two waves',
     'correct_answer':'A',
     'explanation':'Diffraction is the spreading out of waves when they pass through a gap or around an obstacle.',
     'correction_tip':'Diffraction is greatest when the gap width is similar to or smaller than the wavelength of the wave.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':1,
     'question_text':'Which type of electromagnetic wave is emitted by hot objects and can be felt as heat?',
     'option_a':'Ultraviolet','option_b':'Visible light','option_c':'Infrared','option_d':'Microwaves',
     'correct_answer':'C',
     'explanation':'Infrared radiation is emitted by all objects with temperature above absolute zero and is detected as heat.',
     'correction_tip':'Infrared = heat radiation. Used in thermal imaging cameras, remote controls, and heating systems.'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':1,
     'question_text':'Can sound travel through a vacuum?',
     'option_a':'Yes, at 340 m/s','option_b':'No, because sound needs a medium to travel through','option_c':'Yes, but more slowly','option_d':'Yes, because it is an electromagnetic wave',
     'correct_answer':'B',
     'explanation':'Sound is a mechanical wave that requires a medium (solid, liquid, or gas) to propagate. It cannot travel through a vacuum.',
     'correction_tip':'Sound needs particles to vibrate. No particles in a vacuum means no sound. EM waves can travel through vacuum.'},

    # =========================================================
    # P6 WAVES - D2 MEDIUM (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'A wave has a frequency of 50 Hz and a wavelength of 0.6 m. What is its wave speed?',
     'option_a':'83.3 m/s','option_b':'0.012 m/s','option_c':'30 m/s','option_d':'50.6 m/s',
     'correct_answer':'C',
     'explanation':'v = f x lambda = 50 x 0.6 = 30 m/s.',
     'correction_tip':'Use v = f x lambda (wave equation). Ensure frequency is in Hz and wavelength in m to get m/s.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':2,
     'question_text':'When light travels from air into glass, it slows down. What happens to its direction?',
     'option_a':'It bends away from the normal','option_b':'It bends toward the normal','option_c':'It travels in the same direction','option_d':'It reflects completely',
     'correct_answer':'B',
     'explanation':'When light enters a denser medium (like glass), it slows down and bends toward the normal.',
     'correction_tip':'Entering denser medium: bends toward normal (angle of refraction < angle of incidence). Leaving denser medium: bends away from normal.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':2,
     'question_text':'Which type of electromagnetic radiation can cause sunburn and skin cancer with excessive exposure?',
     'option_a':'Infrared','option_b':'Visible light','option_c':'Ultraviolet','option_d':'Microwave',
     'correct_answer':'C',
     'explanation':'Ultraviolet radiation has enough energy to damage DNA in skin cells, causing sunburn and potentially skin cancer.',
     'correction_tip':'UV hazards: sunburn, skin cancer, eye damage. UV uses: sterilisation, detecting forged banknotes, sun tanning.'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':2,
     'question_text':'Ultrasound is used in medical imaging. Which property of ultrasound makes it useful for this?',
     'option_a':'It travels faster than light','option_b':'It reflects at boundaries between different tissues','option_c':'It is visible to the human eye','option_d':'It passes completely through all body tissues',
     'correct_answer':'B',
     'explanation':'Ultrasound reflects at boundaries between tissues of different densities. These reflections are used to create images of internal organs and babies in the womb.',
     'correction_tip':'Ultrasound imaging uses reflected pulses. Time delay of reflections gives distances to boundaries.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'What is the period of a wave with a frequency of 200 Hz?',
     'option_a':'200 s','option_b':'0.005 s','option_c':'0.05 s','option_d':'2000 s',
     'correct_answer':'B',
     'explanation':'T = 1/f = 1/200 = 0.005 s.',
     'correction_tip':'T = 1/f. Period is in seconds, frequency is in Hertz (Hz = 1/s).'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':2,
     'question_text':'What is total internal reflection?',
     'option_a':'When all light is absorbed at a boundary','option_b':'When light hitting an internal surface at an angle greater than the critical angle is completely reflected','option_c':'When light passes through a medium without any reflection','option_d':'When all colours of light are reflected equally',
     'correct_answer':'B',
     'explanation':'Total internal reflection occurs when light inside a denser medium hits the boundary at an angle greater than the critical angle, causing complete reflection back into the medium.',
     'correction_tip':'TIR conditions: light in denser medium, angle of incidence greater than critical angle. Used in optical fibres and prisms.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'Which type of seismic wave can only travel through solids?',
     'option_a':'P-waves','option_b':'S-waves','option_c':'Both P and S waves','option_d':'Neither P nor S waves',
     'correct_answer':'B',
     'explanation':'S-waves (Secondary or shear waves) are transverse seismic waves that can only travel through solids. P-waves can travel through solids and liquids.',
     'correction_tip':'S-waves are transverse (shear waves) and cannot travel through liquids. P-waves are longitudinal and can travel through both.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':2,
     'question_text':'Gamma rays are used to sterilise medical equipment. Why is this possible?',
     'option_a':'Gamma rays are cold and kill bacteria by freezing','option_b':'Gamma rays have very high frequency and energy, killing bacteria and viruses','option_c':'Gamma rays bounce off bacteria','option_d':'Gamma rays are absorbed by the plastic packaging',
     'correct_answer':'B',
     'explanation':'Gamma rays have very high frequency and energy, which can ionise atoms and molecules in bacteria and viruses, killing them.',
     'correction_tip':'Gamma rays are highly ionising and penetrating. They can sterilise without heating and can pass through packaging.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':2,
     'question_text':'A convex (converging) lens brings parallel rays of light to a focus. What is the point where they meet called?',
     'option_a':'The optical centre','option_b':'The focal point','option_c':'The principal axis','option_d':'The aperture',
     'correct_answer':'B',
     'explanation':'The focal point (or principal focus) is the point where parallel rays converge after passing through a convex lens.',
     'correction_tip':'Convex lens converges (brings together) light. Focal length is the distance from the lens to the focal point.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'An earthquake occurs 240 km from a seismic station. P-waves travel at 8 km/s. How long do the P-waves take to arrive?',
     'option_a':'30 s','option_b':'1920 s','option_c':'0.033 s','option_d':'248 s',
     'correct_answer':'A',
     'explanation':'time = distance / speed = 240 / 8 = 30 s.',
     'correction_tip':'Use time = distance / speed. Ensure units are consistent.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':2,
     'question_text':'Radio waves are used for communication. Which property makes them suitable for transmitting TV signals?',
     'option_a':'They can carry large amounts of information due to their high frequency','option_b':'They have long wavelengths that allow them to diffract around buildings','option_c':'They can heat the air and create the signal','option_d':'They travel slower than light so can be controlled',
     'correct_answer':'B',
     'explanation':'Long wavelength radio waves diffract around hills and buildings, allowing reception in areas not in line-of-sight of transmitters.',
     'correction_tip':'Diffraction is greater when wavelength is comparable to the size of the obstacle. Longer wavelengths diffract more around large obstacles.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'What happens to the wavelength of light when it enters glass from air, if its frequency remains constant?',
     'option_a':'Wavelength increases','option_b':'Wavelength stays the same','option_c':'Wavelength decreases','option_d':'Wavelength doubles',
     'correct_answer':'C',
     'explanation':'v = f x lambda. Frequency stays constant. Speed decreases in glass. Therefore wavelength decreases.',
     'correction_tip':'v = f x lambda. If f is constant and v decreases, lambda must decrease proportionally.'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':2,
     'question_text':'A sound wave has a frequency of 680 Hz and travels at 340 m/s. What is its wavelength?',
     'option_a':'2 m','option_b':'0.5 m','option_c':'231,200 m','option_d':'340 m',
     'correct_answer':'B',
     'explanation':'lambda = v/f = 340/680 = 0.5 m.',
     'correction_tip':'Rearrange v = f x lambda to lambda = v/f.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':2,
     'question_text':'What happens to diffraction when the wavelength is much smaller than the gap size?',
     'option_a':'Diffraction is greatest','option_b':'Diffraction is negligible','option_c':'Diffraction causes complete reflection','option_d':'Diffraction does not occur',
     'correct_answer':'B',
     'explanation':'Diffraction is greatest when the wavelength is similar to or larger than the gap. When the gap is much larger than the wavelength, diffraction is negligible.',
     'correction_tip':'Maximum diffraction: wavelength similar to gap width. Minimum diffraction: gap much larger than wavelength.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':2,
     'question_text':'What is the critical angle for total internal reflection related to?',
     'option_a':'The angle of incidence when the refracted ray is along the boundary (90 degrees)','option_b':'The angle of incidence when total reflection first occurs','option_c':'The angle between the incident and reflected ray','option_d':'The angle of the prism',
     'correct_answer':'A',
     'explanation':'The critical angle is the angle of incidence in the denser medium at which the refracted ray makes a 90-degree angle with the normal (travels along the boundary).',
     'correction_tip':'At critical angle, angle of refraction = 90 degrees. Above critical angle: TIR occurs.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':2,
     'question_text':'Infrared cameras are used by emergency services at night. Which property of infrared makes this possible?',
     'option_a':'Infrared can pass through walls','option_b':'All objects emit infrared based on their temperature','option_c':'Infrared is visible to the human eye at low light','option_d':'Infrared is reflected by warm objects',
     'correct_answer':'B',
     'explanation':'All objects above absolute zero emit infrared radiation. Warmer objects emit more infrared, allowing thermal cameras to detect temperature differences.',
     'correction_tip':'Infrared emission increases with temperature. Thermal cameras detect temperature differences, not reflected light.'},

    # =========================================================
    # P6 WAVES - D3 HARD (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'A radio wave has a wavelength of 1500 m. If the speed of EM waves is 3 x 10^8 m/s, what is the frequency?',
     'option_a':'200,000 Hz','option_b':'2 x 10^5 Hz','option_c':'Both A and B are correct','option_d':'2 x 10^11 Hz',
     'correct_answer':'C',
     'explanation':'f = v/lambda = (3 x 10^8) / 1500 = 2 x 10^5 Hz = 200,000 Hz. Both A and B are correct.',
     'correction_tip':'f = v/lambda. Use v = 3 x 10^8 m/s for EM waves. Express answer in Hz or standard form.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':3,
     'question_text':'Light travels from glass (refractive index 1.5) to air (refractive index 1). The critical angle C satisfies sin(C) = 1/n. What is the critical angle?',
     'option_a':'41.8 degrees','option_b':'48.2 degrees','option_c':'33.6 degrees','option_d':'56.4 degrees',
     'correct_answer':'A',
     'explanation':'sin(C) = 1/n = 1/1.5 = 0.667. C = arcsin(0.667) = approximately 41.8 degrees.',
     'correction_tip':'sin(critical angle) = n2/n1 = 1/n (when going from medium with refractive index n to air). n = 1.5 gives C = 41.8 degrees.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'An ultrasound pulse is sent into the body and reflects from a tissue boundary 0.12 m deep. If ultrasound travels at 1500 m/s in tissue, how long does it take for the echo to return?',
     'option_a':'1.6 x 10^-4 s','option_b':'8 x 10^-5 s','option_c':'0.08 s','option_d':'1.25 x 10^-4 s',
     'correct_answer':'A',
     'explanation':'Total distance = 2 x 0.12 = 0.24 m (to boundary and back). time = d/v = 0.24/1500 = 1.6 x 10^-4 s.',
     'correction_tip':'Remember to double the distance (pulse goes there AND back). time = 2d/v.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':3,
     'question_text':'A converging lens has a focal length of 10 cm. An object is placed 30 cm from the lens. Using 1/f = 1/v + 1/u, where u = -30 cm, what is the image distance v?',
     'option_a':'15 cm','option_b':'20 cm','option_c':'10 cm','option_d':'30 cm',
     'correct_answer':'A',
     'explanation':'1/f = 1/v - 1/u (using sign convention). 1/10 = 1/v + 1/30. 1/v = 1/10 - 1/30 = 3/30 - 1/30 = 2/30. v = 15 cm.',
     'correction_tip':'Use the lens equation 1/f = 1/v + 1/u carefully with sign conventions. Rearrange to find the unknown.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':3,
     'question_text':'X-rays have a frequency of approximately 3 x 10^18 Hz. What is their wavelength in a vacuum?',
     'option_a':'1 x 10^-10 m','option_b':'9 x 10^26 m','option_c':'1 x 10^10 m','option_d':'3 x 10^10 m',
     'correct_answer':'A',
     'explanation':'lambda = c/f = (3 x 10^8) / (3 x 10^18) = 1 x 10^-10 m = 0.1 nm.',
     'correction_tip':'lambda = v/f = c/f for EM waves. Divide 3x10^8 by the frequency.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'A student measures the time for 20 complete oscillations of a wave source as 0.4 s. What is the frequency of the waves produced?',
     'option_a':'50 Hz','option_b':'0.02 Hz','option_c':'20 Hz','option_d':'8 Hz',
     'correct_answer':'A',
     'explanation':'Period T = 0.4/20 = 0.02 s. Frequency f = 1/T = 1/0.02 = 50 Hz.',
     'correction_tip':'Period = total time / number of oscillations. Then f = 1/T.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':3,
     'question_text':'Optical fibres use total internal reflection to transmit data. If the critical angle of the fibre is 42 degrees, what happens to a ray hitting the fibre wall at 50 degrees to the normal?',
     'option_a':'It refracts out of the fibre','option_b':'It is totally internally reflected','option_c':'It is absorbed','option_d':'It diffracts along the fibre wall',
     'correct_answer':'B',
     'explanation':'Since 50 degrees > 42 degrees (critical angle), the ray undergoes total internal reflection and stays within the fibre.',
     'correction_tip':'TIR occurs when angle of incidence > critical angle. This keeps light inside the optical fibre.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'Why is the pitch of a sound wave related to its frequency?',
     'option_a':'Higher frequency sound waves have more energy, creating louder sounds','option_b':'Higher frequency means more vibrations per second, which the ear perceives as higher pitch','option_c':'Frequency determines the speed of sound','option_d':'Higher frequency waves travel further',
     'correct_answer':'B',
     'explanation':'Pitch is the perception of frequency by the human ear. More vibrations per second (higher frequency) are perceived as higher pitch.',
     'correction_tip':'Frequency = pitch. Amplitude = loudness. These are independent properties of sound waves.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':3,
     'question_text':'Gamma radiation from a radioactive source has a frequency of 5 x 10^20 Hz. How does its energy compare to visible light at 5 x 10^14 Hz?',
     'option_a':'Gamma has 10^6 times more energy','option_b':'Gamma has 1000 times more energy','option_c':'They have equal energy','option_d':'Visible light has more energy',
     'correct_answer':'A',
     'explanation':'Energy is proportional to frequency (E = hf). Ratio = 5 x 10^20 / 5 x 10^14 = 10^6. Gamma has one million times more energy.',
     'correction_tip':'E = hf. Higher frequency = higher energy. Compare by taking the ratio of frequencies.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'A wave travels from shallow water (speed 2 m/s) to deep water (speed 4 m/s). If the frequency is 1 Hz, what happens to the wavelength?',
     'option_a':'Wavelength halves from 2 m to 1 m','option_b':'Wavelength doubles from 2 m to 4 m','option_c':'Wavelength stays the same at 2 m','option_d':'Wavelength becomes zero',
     'correct_answer':'B',
     'explanation':'In shallow water: lambda = v/f = 2/1 = 2 m. In deep water: lambda = 4/1 = 4 m. Wavelength doubles.',
     'correction_tip':'When speed changes (refraction), frequency stays constant but wavelength changes proportionally (v = f x lambda).'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':3,
     'question_text':'Two ships use sonar. Ship A sends a pulse that returns after 0.06 s. The speed of sound in seawater is 1500 m/s. What is the depth of the ocean floor below the ship?',
     'option_a':'45 m','option_b':'90 m','option_c':'22.5 m','option_d':'0.00004 m',
     'correct_answer':'A',
     'explanation':'Total distance = v x t = 1500 x 0.06 = 90 m. Depth = 90/2 = 45 m (pulse travels down and back).',
     'correction_tip':'Sonar: total distance = speed x time. Depth = total distance / 2 (sound goes there and back).'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'Which observation provides evidence that light is a transverse wave?',
     'option_a':'Light can be diffracted','option_b':'Light can be refracted','option_c':'Light can be polarised','option_d':'Light travels in straight lines',
     'correct_answer':'C',
     'explanation':'Only transverse waves can be polarised. Polarisation restricts the vibration to one plane. Sound (longitudinal) cannot be polarised.',
     'correction_tip':'Polarisation is only possible for transverse waves. This is evidence that light is a transverse wave.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':3,
     'question_text':'A concave (diverging) lens always produces what type of image for a real object?',
     'option_a':'Real, inverted and magnified','option_b':'Virtual, upright and diminished','option_c':'Real, upright and same size','option_d':'Virtual, inverted and magnified',
     'correct_answer':'B',
     'explanation':'A concave (diverging) lens always produces a virtual, upright, and diminished image regardless of object position.',
     'correction_tip':'Concave (diverging) lens: always virtual, upright, smaller. Convex (converging) lens: image type depends on object distance.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':3,
     'question_text':'Mobile phone signals use microwaves. Why might people be concerned about their use near the body?',
     'option_a':'Microwaves are ionising and damage DNA','option_b':'Microwaves can cause localised heating of body tissue','option_c':'Microwaves cause immediate radiation burns','option_d':'Microwaves can be heard by the ear',
     'correct_answer':'B',
     'explanation':'Microwaves can cause heating of body tissue because they are absorbed by water molecules. This is a potential health concern though evidence is inconclusive at phone power levels.',
     'correction_tip':'Microwaves are non-ionising but can heat tissue. Ionising radiation (UV, X-ray, gamma) can damage DNA directly.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'What is the relationship between the frequency and wavelength of EM waves of different types, given that all travel at the same speed c?',
     'option_a':'Higher frequency EM waves have longer wavelengths','option_b':'Higher frequency EM waves have shorter wavelengths','option_c':'Frequency and wavelength are independent','option_d':'All EM waves have the same wavelength',
     'correct_answer':'B',
     'explanation':'c = f x lambda. Since c is constant, f and lambda are inversely proportional. Higher frequency = shorter wavelength.',
     'correction_tip':'f x lambda = c (constant). Inverse proportion: double the frequency, halve the wavelength.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':3,
     'question_text':'A wave source produces waves of frequency 5 Hz in water. The waves travel at 8 m/s. What is the wavelength, and if the speed doubles, what would the new wavelength be?',
     'option_a':'1.6 m then 3.2 m','option_b':'40 m then 80 m','option_c':'0.625 m then 1.25 m','option_d':'1.6 m then 0.8 m',
     'correct_answer':'A',
     'explanation':'lambda = v/f = 8/5 = 1.6 m. If speed doubles to 16 m/s: lambda = 16/5 = 3.2 m (frequency stays constant).',
     'correction_tip':'lambda = v/f. If speed changes but frequency stays constant, wavelength changes proportionally.'},

    # =========================================================
    # P6 WAVES - D4 EXAM CHALLENGE (16 questions)
    # =========================================================
    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A radar system uses EM waves with a frequency of 6 x 10^9 Hz to detect an aircraft. A pulse is sent and returns after 4 x 10^-4 s. How far away is the aircraft?',
     'option_a':'60,000 m','option_b':'120,000 m','option_c':'30,000 m','option_d':'240,000 m',
     'correct_answer':'A',
     'explanation':'Total distance = c x t = (3 x 10^8) x (4 x 10^-4) = 1.2 x 10^5 m. Distance to aircraft = 120,000/2 = 60,000 m.',
     'correction_tip':'Radar: distance = c x t / 2 (wave travels there and back). Frequency is not needed here.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':4,
     'question_text':'Light enters a glass block at an angle of incidence of 45 degrees in air. The refractive index of glass is 1.5. Using n1 sin(theta1) = n2 sin(theta2), what is the angle of refraction?',
     'option_a':'28.1 degrees','option_b':'56.4 degrees','option_c':'33.6 degrees','option_d':'45 degrees',
     'correct_answer':'A',
     'explanation':'1 x sin(45) = 1.5 x sin(theta2). sin(theta2) = 0.707/1.5 = 0.471. theta2 = arcsin(0.471) = 28.1 degrees.',
     'correction_tip':'Snell\'s Law: n1 sin(theta1) = n2 sin(theta2). Light enters denser medium: angle decreases.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':4,
     'question_text':'A gamma ray photon has energy E = hf where h = 6.63 x 10^-34 J s and f = 3 x 10^20 Hz. What is the energy of the photon?',
     'option_a':'1.99 x 10^-13 J','option_b':'4.52 x 10^53 J','option_c':'1.99 x 10^-13 eV','option_d':'2.21 x 10^-13 J',
     'correct_answer':'A',
     'explanation':'E = hf = 6.63 x 10^-34 x 3 x 10^20 = 1.989 x 10^-13 J, approximately 1.99 x 10^-13 J.',
     'correction_tip':'E = hf. Multiply h by f. Note that h = 6.63 x 10^-34 J s is given in the formula sheet.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A student investigates standing waves on a string. The fundamental frequency is 60 Hz with a string length of 0.5 m. What is the wave speed along the string?',
     'option_a':'120 m/s','option_b':'60 m/s','option_c':'30 m/s','option_d':'240 m/s',
     'correct_answer':'B',
     'explanation':'At fundamental frequency, the wavelength = 2 x string length = 2 x 0.5 = 1 m. v = f x lambda = 60 x 1 = 60 m/s.',
     'correction_tip':'Fundamental: half a wavelength fits in the string length. So lambda = 2L. Then use v = f x lambda.'},

    {'subject':'Physics','topic':'Sound','topic_code':'P6','difficulty':4,
     'question_text':'A doctor uses ultrasound at 2 MHz (2 x 10^6 Hz). The speed in soft tissue is 1540 m/s. An echo returns from a tumour after 1.3 x 10^-4 s. How deep is the tumour?',
     'option_a':'0.1001 m','option_b':'0.2002 m','option_c':'0.0501 m','option_d':'0.2 m',
     'correct_answer':'A',
     'explanation':'Total distance = v x t = 1540 x 1.3 x 10^-4 = 0.2002 m. Depth = 0.2002/2 = 0.1001 m (approximately 10 cm).',
     'correction_tip':'depth = (speed x time) / 2. Frequency is not needed for distance calculation.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':4,
     'question_text':'Light undergoes total internal reflection in an optical fibre. The core has refractive index 1.62. What is the critical angle? (sin C = 1/n)',
     'option_a':'38.2 degrees','option_b':'51.8 degrees','option_c':'38.2 radians','option_d':'45 degrees',
     'correct_answer':'A',
     'explanation':'sin C = 1/n = 1/1.62 = 0.617. C = arcsin(0.617) = 38.2 degrees.',
     'correction_tip':'sin C = 1/n (when going from the medium with refractive index n to air). Use inverse sine to find angle.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'Microwaves of frequency 1.5 x 10^10 Hz travel through air at 3 x 10^8 m/s. They are reflected off a metal plate creating a standing wave. What is the distance between adjacent nodes?',
     'option_a':'0.01 m','option_b':'0.02 m','option_c':'0.005 m','option_d':'0.04 m',
     'correct_answer':'A',
     'explanation':'lambda = v/f = 3 x 10^8 / 1.5 x 10^10 = 0.02 m. Distance between adjacent nodes = lambda/2 = 0.01 m.',
     'correction_tip':'In a standing wave, nodes are separated by half a wavelength. First find wavelength using v = f x lambda.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':4,
     'question_text':'In a hospital, an X-ray tube accelerates electrons through 80,000 V. The electrons hit a metal target and produce X-rays. The maximum frequency of X-rays produced depends on electron kinetic energy: eV = hf_max. If e = 1.6 x 10^-19 C, h = 6.63 x 10^-34 J s, V = 80,000 V, what is f_max?',
     'option_a':'1.93 x 10^19 Hz','option_b':'1.28 x 10^13 Hz','option_c':'8.3 x 10^23 Hz','option_d':'3 x 10^8 Hz',
     'correct_answer':'A',
     'explanation':'f_max = eV/h = (1.6 x 10^-19 x 80,000) / (6.63 x 10^-34) = (1.28 x 10^-14) / (6.63 x 10^-34) = 1.93 x 10^19 Hz.',
     'correction_tip':'eV = hf_max. Rearrange to f_max = eV/h. Calculate eV first, then divide by h.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A seismograph records P-waves arriving 80 s before S-waves from an earthquake. P-waves travel at 8 km/s and S-waves at 5 km/s. How far away is the earthquake epicentre?',
     'option_a':'1067 km','option_b':'800 km','option_c':'500 km','option_d':'1333 km',
     'correct_answer':'A',
     'explanation':'Let d be distance. Time for P: d/8. Time for S: d/5. Difference: d/5 - d/8 = 80. d(8-5)/(5x8) = 80. 3d/40 = 80. d = 80 x 40/3 = 1067 km.',
     'correction_tip':'Time difference = d/v_S - d/v_P. Rearrange to find d. This is how seismologists locate earthquakes.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':4,
     'question_text':'A glass prism with an apex angle of 60 degrees is used to disperse white light. The refractive index for red light is 1.51 and for violet light is 1.53. Why does the prism separate colours?',
     'option_a':'Each colour has the same speed in glass but different wavelengths in air','option_b':'Different colours travel at different speeds in glass, causing different angles of refraction','option_c':'Violet light is reflected and red light is transmitted','option_d':'The prism absorbs some colours more than others',
     'correct_answer':'B',
     'explanation':'Different colours (frequencies) of light have different speeds in glass, resulting in different refractive indices. This causes them to refract by different amounts, separating them.',
     'correction_tip':'Dispersion: different frequencies have different speeds in glass, so different refractive indices and different angles of refraction.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A student measures the wavelength of light using a diffraction grating with 500 lines/mm. The first-order maximum is observed at an angle of 18 degrees. Using d sin(theta) = n x lambda, what is the wavelength? (d = 2 x 10^-6 m)',
     'option_a':'618 nm','option_b':'309 nm','option_c':'6.18 x 10^-7 m','option_d':'Both A and C',
     'correct_answer':'D',
     'explanation':'lambda = d sin(theta) / n = (2 x 10^-6) x sin(18) / 1 = 2 x 10^-6 x 0.309 = 6.18 x 10^-7 m = 618 nm. Both A and C are correct.',
     'correction_tip':'d sin(theta) = n x lambda. For first order, n=1. d = 1/(lines per metre). 500 lines/mm = 5 x 10^5 lines/m, d = 2 x 10^-6 m.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':4,
     'question_text':'Why are short wave radio waves able to travel around the world while VHF radio waves require line-of-sight transmission?',
     'option_a':'Short waves are reflected by the ionosphere; VHF waves pass straight through it','option_b':'Short waves travel faster than VHF waves','option_c':'Short waves are absorbed by mountains; VHF waves pass through them','option_d':'VHF waves are reflected by the ionosphere; short waves pass through',
     'correct_answer':'A',
     'explanation':'Short wave radio is reflected back to Earth by the ionosphere, allowing it to travel around the curved Earth. VHF waves pass through the ionosphere and travel into space, requiring line-of-sight or satellite relay.',
     'correction_tip':'Short wave radio uses ionospheric reflection. VHF/UHF goes straight through the ionosphere and needs direct path or satellite.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A researcher studying earthquakes finds that S-waves do not reach certain areas on the opposite side of the Earth (the shadow zone). What does this tell us about the Earth\'s interior?',
     'option_a':'The Earth has a solid outer core that absorbs S-waves','option_b':'The Earth has a liquid outer core through which S-waves cannot travel','option_c':'The Earth has no inner core','option_d':'S-waves travel faster than P-waves in the core',
     'correct_answer':'B',
     'explanation':'S-waves (transverse) cannot travel through liquids. The S-wave shadow zone indicates that the outer core of the Earth is liquid.',
     'correction_tip':'S-waves cannot travel through liquids. The S-wave shadow zone is evidence for a liquid outer core.'},

    {'subject':'Physics','topic':'Light','topic_code':'P6','difficulty':4,
     'question_text':'An object is placed 15 cm from a converging lens of focal length 10 cm. Using the lens formula 1/v - 1/u = 1/f with u = -15 cm, what are the characteristics of the image?',
     'option_a':'Real, inverted, magnified at v = 30 cm','option_b':'Virtual, upright, magnified','option_c':'Real, inverted, diminished at v = 6 cm','option_d':'Real, upright, same size',
     'correct_answer':'A',
     'explanation':'1/f = 1/v - 1/u. 1/10 = 1/v - 1/(-15) = 1/v + 1/15. 1/v = 1/10 - 1/15 = 3/30 - 2/30 = 1/30. v = 30 cm. Positive v means real, inverted image. m = v/u = 30/15 = 2, so magnified.',
     'correction_tip':'Object between f and 2f produces magnified real image beyond 2f. Use lens formula and interpret sign of v.'},

    {'subject':'Physics','topic':'Waves','topic_code':'P6','difficulty':4,
     'question_text':'A scientist measures the speed of a water wave by timing it across a tank 1.2 m long. The wave crosses the tank in 0.4 s. If the wave frequency is 5 Hz, what is the wavelength?',
     'option_a':'0.6 m','option_b':'3 m','option_c':'1.2 m','option_d':'15 m',
     'correct_answer':'A',
     'explanation':'Wave speed = distance/time = 1.2/0.4 = 3 m/s. Wavelength = v/f = 3/5 = 0.6 m.',
     'correction_tip':'First calculate wave speed from distance and time. Then use lambda = v/f.'},

    {'subject':'Physics','topic':'Electromagnetic spectrum','topic_code':'P6','difficulty':4,
     'question_text':'In a CT scan, multiple X-ray images are taken from different angles. Why are CT scans potentially more harmful than a single chest X-ray?',
     'option_a':'CT scans use gamma rays, which are more ionising','option_b':'CT scans involve many X-ray exposures from multiple angles, resulting in a higher total radiation dose','option_c':'CT scan X-rays are higher frequency than normal X-rays','option_d':'CT scans inject radioactive tracers into the body',
     'correct_answer':'B',
     'explanation':'A CT scan requires many individual X-ray exposures from different angles to construct a 3D image, accumulating a much higher total radiation dose than a single X-ray image.',
     'correction_tip':'More exposures = higher total dose = greater risk of DNA damage. Risk must be weighed against diagnostic benefit.'},
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute('''INSERT INTO questions (subject,topic,topic_code,difficulty,question_text,
            option_a,option_b,option_c,option_d,correct_answer,explanation,correction_tip)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
