QUESTIONS = [
    # ─── B1 Cell Biology ── Easy D1 (2 questions) ───────────────────────────
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 1,
        'question_text': 'Which of the following structures is found in a prokaryotic cell but NOT in a eukaryotic cell?',
        'option_a': 'Mitochondria',
        'option_b': 'Plasmid',
        'option_c': 'Ribosome',
        'option_d': 'Cell membrane',
        'correct_answer': 'B',
        'explanation': 'Plasmids are small circular DNA molecules found in prokaryotic cells (such as bacteria). Eukaryotic cells do not contain plasmids. Ribosomes and cell membranes are found in both types of cell, and mitochondria are only found in eukaryotic cells.',
        'correction_tip': 'Prokaryotes lack a nucleus and membrane-bound organelles. Their unique features include plasmids, a cell wall made of peptidoglycan, and a single circular chromosome in the cytoplasm.',
    },
    {
        'subject': 'Biology',
        'topic': 'Microscopy',
        'topic_code': 'B1',
        'difficulty': 1,
        'question_text': 'A student uses a light microscope with an eyepiece lens of ×10 and an objective lens of ×40. What is the total magnification?',
        'option_a': '×50',
        'option_b': '×400',
        'option_c': '×4',
        'option_d': '×440',
        'correct_answer': 'B',
        'explanation': 'Total magnification = eyepiece lens magnification × objective lens magnification = 10 × 40 = 400.',
        'correction_tip': 'Always multiply the two lens magnifications together — do not add them.',
    },

    # ─── B1 Cell Biology ── Medium D2 (8 questions) ──────────────────────────
    {
        'subject': 'Biology',
        'topic': 'Microscopy',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'A cell is observed under a microscope and its image measures 30 mm. The magnification used is ×1000. What is the actual size of the cell in micrometres (μm)?',
        'option_a': '0.03 μm',
        'option_b': '3 μm',
        'option_c': '30 μm',
        'option_d': '300 μm',
        'correct_answer': 'C',
        'explanation': 'Actual size = image size ÷ magnification = 30 mm ÷ 1000 = 0.03 mm. Converting: 0.03 mm × 1000 = 30 μm.',
        'correction_tip': 'Use the formula: actual size = image size ÷ magnification. Remember 1 mm = 1000 μm when converting units.',
    },
    {
        'subject': 'Biology',
        'topic': 'Microscopy',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'A scale bar on an electron micrograph represents 2 μm and measures 20 mm on the image. A bacterium in the same image measures 8 mm. What is the actual length of the bacterium?',
        'option_a': '0.8 μm',
        'option_b': '1.6 μm',
        'option_c': '0.8 mm',
        'option_d': '8 μm',
        'correct_answer': 'A',
        'explanation': 'Scale: 20 mm on image = 2 μm real. So 1 mm on image = 0.1 μm real. Bacterium = 8 mm × 0.1 μm/mm = 0.8 μm.',
        'correction_tip': 'Find the scale factor first: real length per mm = scale bar real size ÷ scale bar image size. Then multiply by the object\'s image measurement.',
    },
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'Which of the following is a key difference between animal and plant cells?',
        'option_a': 'Plant cells have mitochondria; animal cells do not',
        'option_b': 'Animal cells have a cell wall; plant cells do not',
        'option_c': 'Plant cells have a permanent vacuole; animal cells do not',
        'option_d': 'Animal cells have chloroplasts; plant cells do not',
        'correct_answer': 'C',
        'explanation': 'Plant cells have a permanent vacuole filled with cell sap. Animal cells may have temporary vacuoles but not a permanent one. Both have mitochondria. Plant cells (not animal cells) have a cell wall and chloroplasts.',
        'correction_tip': 'Remember the three structures in plant cells that animal cells lack: cell wall (cellulose), chloroplasts, and permanent vacuole.',
    },
    {
        'subject': 'Biology',
        'topic': 'Diffusion',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'Which factor does NOT directly increase the rate of diffusion across a membrane?',
        'option_a': 'Increasing the concentration gradient',
        'option_b': 'Increasing the surface area of the membrane',
        'option_c': 'Increasing the thickness of the membrane',
        'option_d': 'Increasing the temperature',
        'correct_answer': 'C',
        'explanation': 'Increasing membrane thickness increases the distance molecules must travel, which decreases — not increases — the rate of diffusion. The other three factors all increase the rate of diffusion.',
        'correction_tip': 'Rate of diffusion is proportional to (surface area × concentration gradient) and inversely proportional to membrane thickness. Greater thickness = slower diffusion.',
    },
    {
        'subject': 'Biology',
        'topic': 'Osmosis',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'A plant cell is placed in a solution with a lower water potential than the cell\'s cytoplasm. What will happen to the cell?',
        'option_a': 'Water moves in by osmosis; the cell becomes turgid',
        'option_b': 'Water moves out by osmosis; the cell becomes flaccid',
        'option_c': 'Water moves out by active transport; the cell shrinks',
        'option_d': 'No net movement of water occurs',
        'correct_answer': 'B',
        'explanation': 'Water moves from a region of higher water potential (inside the cell) to a region of lower water potential (outside) by osmosis. This causes the cell to lose water and become flaccid. If further water is lost, the cell membrane pulls away from the cell wall — a process called plasmolysis.',
        'correction_tip': 'Osmosis always moves water from high water potential to low water potential. Pure water has the highest water potential (0); dissolved solutes lower water potential (make it more negative).',
    },
    {
        'subject': 'Biology',
        'topic': 'Active transport',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'Why does active transport require ATP, whereas diffusion does not?',
        'option_a': 'Active transport moves substances along a concentration gradient',
        'option_b': 'Active transport moves substances against a concentration gradient, requiring energy from respiration',
        'option_c': 'Diffusion moves large molecules that require energy to cross membranes',
        'option_d': 'Active transport only occurs in plant cells where ATP is produced',
        'correct_answer': 'B',
        'explanation': 'Active transport moves substances from a region of lower concentration to a region of higher concentration — against the concentration gradient. This requires energy (ATP) provided by cellular respiration. Diffusion is a passive process that moves substances down the concentration gradient without energy input.',
        'correction_tip': 'Key phrase: active transport moves substances AGAINST the concentration gradient. This is why mitochondria (for aerobic respiration to produce ATP) are important in cells that carry out a lot of active transport.',
    },
    {
        'subject': 'Biology',
        'topic': 'Mitosis',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'What is the correct sequence of stages in mitosis?',
        'option_a': 'Prophase → Metaphase → Anaphase → Telophase',
        'option_b': 'Metaphase → Prophase → Telophase → Anaphase',
        'option_c': 'Anaphase → Metaphase → Prophase → Telophase',
        'option_d': 'Telophase → Anaphase → Metaphase → Prophase',
        'correct_answer': 'A',
        'explanation': 'Mitosis proceeds in the order: Prophase (chromosomes condense, nuclear envelope breaks down) → Metaphase (chromosomes align at the cell equator) → Anaphase (chromatids pulled to opposite poles) → Telophase (nuclear envelopes reform, cell divides).',
        'correction_tip': 'Use the mnemonic PMAT: Prophase, Metaphase, Anaphase, Telophase.',
    },
    {
        'subject': 'Biology',
        'topic': 'Stem cells',
        'topic_code': 'B1',
        'difficulty': 2,
        'question_text': 'What is the main difference between embryonic stem cells and adult stem cells?',
        'option_a': 'Embryonic stem cells can only differentiate into blood cells',
        'option_b': 'Adult stem cells are pluripotent; embryonic stem cells are totipotent',
        'option_c': 'Embryonic stem cells are pluripotent and can differentiate into almost any cell type; adult stem cells are more limited',
        'option_d': 'There is no difference — both can differentiate into all cell types',
        'correct_answer': 'C',
        'explanation': 'Embryonic stem cells are pluripotent — they can differentiate into almost any cell type in the body. Adult stem cells are multipotent — they can only differentiate into a limited range of cell types related to the tissue they are found in (e.g., bone marrow stem cells mainly produce blood cells).',
        'correction_tip': 'Pluripotent = many types (embryonic). Multipotent = limited types (adult). The broader potential of embryonic stem cells is why they are more useful therapeutically — but also more controversial.',
    },

    # ─── B1 Cell Biology ── Hard D3 (7 questions) ────────────────────────────
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'A student measures a cell image as 54 mm. The actual cell is 18 μm long. What is the magnification, and which calculation shows the correct conversion step?',
        'option_a': '×3000; divide image size (54 mm) by actual size (18 μm) after converting 54 mm to 54 000 μm',
        'option_b': '×3000; divide actual size by image size',
        'option_c': '×3000; convert 18 μm to 0.018 mm, then 54 ÷ 0.018',
        'option_d': '×0.003; divide image size by actual size without converting units',
        'correct_answer': 'C',
        'explanation': 'Magnification = image size ÷ actual size, but units must match. Convert 18 μm to mm: 18 ÷ 1000 = 0.018 mm. Then magnification = 54 mm ÷ 0.018 mm = ×3000. Option A reaches the same answer but converts the wrong quantity (54 mm to μm).',
        'correction_tip': 'Always convert both measurements to the same unit before calculating magnification. Converting μm to mm: divide by 1000. Converting mm to μm: multiply by 1000.',
    },
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'Prokaryotic cells are typically 1–10 μm in size. Eukaryotic cells are typically 10–100 μm. Which statement correctly describes a structural difference and its functional significance?',
        'option_a': 'Prokaryotes have a nucleus, allowing faster gene expression',
        'option_b': 'Eukaryotes have membrane-bound organelles, allowing simultaneous compartmentalised reactions',
        'option_c': 'Prokaryotes have mitochondria but no cell wall',
        'option_d': 'Eukaryotes lack ribosomes, relying on the nucleus for protein synthesis',
        'correct_answer': 'B',
        'explanation': 'Eukaryotic cells have membrane-bound organelles (e.g. mitochondria, endoplasmic reticulum, Golgi apparatus). These create separate compartments where different biochemical reactions can occur simultaneously without interfering with each other, allowing more complex cell functions.',
        'correction_tip': 'Prokaryotes have NO membrane-bound organelles and NO true nucleus. Their DNA is a single circular chromosome in the cytoplasm. They DO have ribosomes (though smaller — 70S vs 80S in eukaryotes) and often have a cell wall.',
    },
    {
        'subject': 'Biology',
        'topic': 'Mitosis',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'During which stage of mitosis do the sister chromatids separate and move to opposite poles of the cell?',
        'option_a': 'Prophase',
        'option_b': 'Metaphase',
        'option_c': 'Anaphase',
        'option_d': 'Telophase',
        'correct_answer': 'C',
        'explanation': 'During Anaphase, the spindle fibres contract and pull the sister chromatids apart at their centromeres, moving them to opposite poles of the cell. This ensures each new daughter cell receives an identical set of chromosomes.',
        'correction_tip': 'Anaphase = Apart (chromatids move apart). Metaphase = Middle (chromosomes line up at the middle/equator). Prophase = chromosomes form (become visible). Telophase = Two nuclei form.',
    },
    {
        'subject': 'Biology',
        'topic': 'Mitosis',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'Meiosis produces four haploid cells, whereas mitosis produces two diploid cells. Which statement best explains why meiosis is essential for sexual reproduction?',
        'option_a': 'Meiosis produces cells with double the chromosome number, providing genetic variety',
        'option_b': 'Meiosis produces gametes with half the chromosome number, so that fertilisation restores the diploid number and introduces genetic variation',
        'option_c': 'Meiosis produces identical cells, ensuring offspring are exact copies of parents',
        'option_d': 'Meiosis prevents mutation by checking chromosomes before division',
        'correct_answer': 'B',
        'explanation': 'Meiosis halves the chromosome number (producing haploid cells), so when two gametes fuse at fertilisation the full diploid number is restored. Meiosis also introduces genetic variation through crossing over (exchange of genetic material between homologous chromosomes) and independent assortment.',
        'correction_tip': 'Mitosis: 1 cell → 2 genetically identical diploid cells (growth, repair). Meiosis: 1 cell → 4 genetically different haploid cells (gamete production). In humans: diploid = 46 chromosomes; haploid = 23.',
    },
    {
        'subject': 'Biology',
        'topic': 'Osmosis',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'A student places cylinders of potato in sucrose solutions of different concentrations and measures the change in mass. In which scenario would the potato cylinder gain the most mass?',
        'option_a': 'Placed in 1.0 mol/dm³ sucrose solution',
        'option_b': 'Placed in 0.5 mol/dm³ sucrose solution',
        'option_c': 'Placed in distilled water (0 mol/dm³ sucrose)',
        'option_d': 'Placed in 0.8 mol/dm³ sucrose solution',
        'correct_answer': 'C',
        'explanation': 'In distilled water, the water potential outside the cell is 0 (highest possible). The cell\'s cytoplasm has dissolved solutes so its water potential is lower (more negative). Water moves into the cell by osmosis down the water potential gradient, causing the potato to gain mass and the cells to become turgid.',
        'correction_tip': 'The greater the difference in water potential between outside and inside the cell, the more water moves by osmosis. Distilled water has the highest water potential (0), creating the largest gradient for water to move INTO plant cells.',
    },
    {
        'subject': 'Biology',
        'topic': 'Stem cells',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'A patient with type 1 diabetes cannot produce insulin. Scientists propose using embryonic stem cells to grow insulin-producing cells for transplant. Which statement identifies both a benefit AND an ethical concern of this approach?',
        'option_a': 'Benefit: eliminates need for insulin injections; Concern: embryonic stem cells may become cancerous and the embryo is destroyed in the process',
        'option_b': 'Benefit: the treatment is widely available; Concern: adult stem cells are more effective',
        'option_c': 'Benefit: no immune rejection possible; Concern: embryonic stem cells cannot differentiate',
        'option_d': 'Benefit: cells are genetically modified to produce more insulin; Concern: the patient may develop an allergic reaction',
        'correct_answer': 'A',
        'explanation': 'Using embryonic stem cells could replace the patient\'s damaged beta cells and eliminate the need for daily insulin injections. However, embryonic stem cells are harvested from human embryos, raising ethical concerns about destroying potential human life. Additionally, undifferentiated stem cells that are not fully controlled carry a risk of becoming cancerous (forming tumours).',
        'correction_tip': 'For any stem cell therapy question, consider: (1) therapeutic benefit, (2) risk of immune rejection, (3) risk of tumour formation, and (4) ethical issues specific to embryonic stem cells (embryo destruction).',
    },
    {
        'subject': 'Biology',
        'topic': 'Diffusion',
        'topic_code': 'B1',
        'difficulty': 3,
        'question_text': 'Alveoli in the lungs are adapted for efficient gas exchange. Which combination of adaptations maximises the rate of diffusion?',
        'option_a': 'Thick walls, small surface area, high blood flow',
        'option_b': 'Thin walls (one cell thick), large surface area, maintained concentration gradient by blood flow',
        'option_c': 'Thin walls, small surface area, maintained concentration gradient',
        'option_d': 'Thick walls, large surface area, slow blood flow',
        'correct_answer': 'B',
        'explanation': 'Rate of diffusion ∝ (surface area × concentration gradient) ÷ membrane thickness. Alveoli maximise diffusion by having: (1) thin walls — just one cell thick, minimising diffusion distance; (2) millions of alveoli — providing a large surface area; (3) rich capillary network with constant blood flow — maintaining the concentration gradient by continuously removing CO₂ and delivering O₂.',
        'correction_tip': 'Remember Fick\'s law: Rate ∝ (SA × concentration gradient) / thickness. For maximum diffusion, you want large SA, large gradient, and THIN membrane.',
    },

    # ─── B1 Cell Biology ── Exam Challenge D4 (9 questions) ──────────────────
    {
        'subject': 'Biology',
        'topic': 'Microscopy',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A transmission electron microscope (TEM) has a resolution of 0.1 nm. A light microscope has a maximum resolution of about 200 nm. An organelle is 50 nm in diameter. Which statement is correct?',
        'option_a': 'The organelle can be seen clearly with a light microscope but not a TEM',
        'option_b': 'The organelle can be resolved with a TEM but not with a light microscope',
        'option_c': 'Both microscopes can resolve the organelle equally well',
        'option_d': 'Neither microscope can resolve the organelle because it is too small',
        'correct_answer': 'B',
        'explanation': 'Resolution is the ability to distinguish two points as separate. A light microscope can resolve structures no smaller than ~200 nm. Since the organelle is 50 nm — well below 200 nm — it cannot be resolved by a light microscope. A TEM has a resolution of 0.1 nm, which is far smaller than 50 nm, so the TEM can resolve it clearly.',
        'correction_tip': 'Resolution ≠ magnification. A microscope can magnify a fuzzy image, but only high resolution makes detail visible. TEM uses electrons (shorter wavelength) → much higher resolution than light microscopes.',
    },
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A student compares a bacterial cell and a liver cell. The liver cell has many mitochondria, a large nucleus, rough endoplasmic reticulum, and Golgi apparatus. The bacterial cell has none of these. Which conclusion is best supported?',
        'option_a': 'Bacterial cells cannot carry out respiration',
        'option_b': 'The liver cell\'s greater compartmentalisation allows it to carry out more complex and specialised functions simultaneously',
        'option_c': 'Bacterial cells are unable to synthesise proteins',
        'option_d': 'The liver cell must divide more rapidly than the bacterial cell',
        'correct_answer': 'B',
        'explanation': 'The presence of membrane-bound organelles in the liver cell creates specialised compartments: mitochondria for aerobic respiration, rough ER for protein synthesis and folding, Golgi for processing and secretion. This compartmentalisation allows multiple complex biochemical processes simultaneously. Bacteria do carry out respiration and protein synthesis (using 70S ribosomes and the cell membrane), just without membrane-bound organelles.',
        'correction_tip': 'The key advantage of eukaryotic cell organisation is compartmentalisation. Different organelles maintain different internal environments (e.g., pH, enzyme concentrations) enabling specialised, simultaneous reactions.',
    },
    {
        'subject': 'Biology',
        'topic': 'Mitosis',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A scientist treats dividing cells with a drug that prevents spindle fibre formation. What would be the most likely consequence?',
        'option_a': 'DNA replication would stop',
        'option_b': 'Chromosomes would not separate; cells would have abnormal chromosome numbers',
        'option_c': 'The cell membrane would not divide',
        'option_d': 'The nuclear envelope would not break down',
        'correct_answer': 'B',
        'explanation': 'Spindle fibres are responsible for pulling chromatids to opposite poles during Anaphase. If spindle fibres cannot form, chromatids cannot separate. Both sets of chromosomes would remain in one cell, producing daughter cells with double the normal chromosome number (polyploidy), while the other daughter cell would have none — potentially triggering cell death or cancer.',
        'correction_tip': 'Spindle fibres are made of tubulin protein. They attach to centromeres during metaphase. Without them, Anaphase cannot occur correctly. Some cancer drugs (e.g., taxol, vinca alkaloids) work by disrupting spindle function.',
    },
    {
        'subject': 'Biology',
        'topic': 'Osmosis',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A student prepares potato cylinders and places them in sucrose solutions ranging from 0 to 1.0 mol/dm³. At 0.3 mol/dm³ the cylinders show no change in mass. What does this indicate, and what would happen to the cylinders in 0.8 mol/dm³?',
        'option_a': '0.3 mol/dm³ equals the cell\'s water potential; in 0.8 mol/dm³ the cells would gain water and become turgid',
        'option_b': '0.3 mol/dm³ equals the cell\'s water potential; in 0.8 mol/dm³ the cells would lose water and may become plasmolysed',
        'option_c': '0.3 mol/dm³ is too dilute for any osmosis to occur; in 0.8 mol/dm³ cells would gain water',
        'option_d': 'No change in mass means the membrane is impermeable at this concentration',
        'correct_answer': 'B',
        'explanation': 'No change in mass means the water potential of the solution equals the water potential of the cell contents — this is the isotonic point. At 0.8 mol/dm³ the external solution has a lower water potential than the cell, so water moves OUT by osmosis. The cell becomes flaccid and may become plasmolysed (cell membrane pulls away from cell wall) if the concentration is high enough.',
        'correction_tip': 'Isotonic = no net osmosis. Hypotonic (more dilute than cell) → water in → turgid. Hypertonic (more concentrated than cell) → water out → flaccid/plasmolysed. Plasmolysis is reversible if cells are returned to water.',
    },
    {
        'subject': 'Biology',
        'topic': 'Active transport',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'Root hair cells absorb mineral ions from the soil even when the ion concentration in the soil is lower than in the root hair cell. A student claims this must be diffusion. Which evidence would best disprove this?',
        'option_a': 'The ions are electrically charged',
        'option_b': 'Mineral uptake decreases significantly when the plant is treated with a respiratory inhibitor that reduces ATP production',
        'option_c': 'The root hair cell has a large surface area',
        'option_d': 'The soil water contains dissolved oxygen',
        'correct_answer': 'B',
        'explanation': 'If ion uptake decreased when ATP production was inhibited, this proves the process requires energy — which is a defining feature of active transport, not diffusion. Diffusion is passive and requires no ATP. The fact that ions move against the concentration gradient (from low to high concentration) also indicates active transport.',
        'correction_tip': 'Evidence for active transport: movement against concentration gradient + requires ATP + reduced by metabolic poisons/lack of oxygen. This is the classic exam test — always link ATP/respiration to active transport.',
    },
    {
        'subject': 'Biology',
        'topic': 'Stem cells',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'Scientists can now create induced pluripotent stem cells (iPSCs) by reprogramming adult body cells. How does this address the main ethical concern about embryonic stem cells, and what limitation remains?',
        'option_a': 'iPSCs avoid destroying embryos since they come from adult cells; limitation is that iPSCs are only unipotent',
        'option_b': 'iPSCs avoid destroying embryos since they come from the patient\'s own cells; limitation is that reprogramming may introduce mutations, and immune rejection risk remains with donor cells',
        'option_c': 'iPSCs are derived from embryos so the ethical concern remains; limitation is that they cannot differentiate',
        'option_d': 'iPSCs avoid ethical concerns entirely; there are no remaining limitations',
        'correct_answer': 'B',
        'explanation': 'iPSCs are created by reprogramming adult somatic cells (e.g., skin cells) back to a pluripotent state using transcription factors. No embryo is destroyed, removing the main ethical objection. However, limitations include: the reprogramming process can introduce mutations (cancer risk), the technique is expensive and complex, and using cells from a different donor still carries immune rejection risk.',
        'correction_tip': 'iPSCs = patient\'s own cells → reduced rejection risk + no embryo destroyed. BUT: mutation risk from reprogramming. GCSE questions may not use "iPSC" but may describe the concept as "reprogrammed adult stem cells".',
    },
    {
        'subject': 'Biology',
        'topic': 'Diffusion',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'Two cells, A and B, are both absorbing glucose by diffusion. Cell A has a surface area of 200 μm² and a membrane thickness of 8 nm. Cell B has a surface area of 400 μm² and a membrane thickness of 4 nm. The concentration gradient is the same for both. By how many times is Cell B\'s rate of diffusion greater than Cell A\'s?',
        'option_a': '2×',
        'option_b': '4×',
        'option_c': '8×',
        'option_d': '16×',
        'correct_answer': 'B',
        'explanation': 'Using Fick\'s law: Rate ∝ (SA × concentration gradient) / thickness. Cell A: rate ∝ 200/8 = 25. Cell B: rate ∝ 400/4 = 100. Ratio = 100/25 = 4. Cell B\'s diffusion rate is 4× greater.',
        'correction_tip': 'Fick\'s law: Rate ∝ (SA × conc. gradient) / thickness. When concentration gradient is the same, just compare SA/thickness. Cell B has double the SA AND half the thickness — both factors double the rate: 2 × 2 = 4×.',
    },
    {
        'subject': 'Biology',
        'topic': 'Mitosis',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A scientist examines a slide of onion root tip cells. She counts 200 cells; 20 are in mitosis. The full cell cycle takes 24 hours. How long, in hours, do cells spend in mitosis?',
        'option_a': '0.24 hours',
        'option_b': '2.4 hours',
        'option_c': '4.8 hours',
        'option_d': '20 hours',
        'correct_answer': 'B',
        'explanation': 'The proportion of cells in mitosis = 20/200 = 0.10 (10%). This proportion reflects the fraction of the cell cycle spent in mitosis. Time in mitosis = 0.10 × 24 hours = 2.4 hours.',
        'correction_tip': 'Time in a stage = (cells in that stage / total cells) × total cycle time. This works because cells are dividing continuously and the proportion seen in each stage reflects the time spent there.',
    },
    {
        'subject': 'Biology',
        'topic': 'Cell biology',
        'topic_code': 'B1',
        'difficulty': 4,
        'question_text': 'A student claims: "All cells in a multicellular organism contain the same DNA but look and function differently because they express different genes." Evaluate this statement with reference to cell differentiation and stem cells.',
        'option_a': 'The statement is false — different cell types have different amounts of DNA',
        'option_b': 'The statement is correct — differentiation involves permanent DNA deletion for unused genes',
        'option_c': 'The statement is correct — all cells have the same genome but selective gene expression during differentiation switches certain genes on or off, producing specialised proteins and cell structures',
        'option_d': 'The statement is partly wrong — stem cells have more DNA than differentiated cells',
        'correct_answer': 'C',
        'explanation': 'All somatic cells in an organism (with a few exceptions) contain the full genome. Differentiation occurs when specific genes are switched on (transcribed) or off (silenced) in response to signals during development. This produces different proteins (enzymes, structural proteins, receptors) that give each cell type its characteristic structure and function. Stem cells can redifferentiate because they retain the potential to express genes that were previously silent.',
        'correction_tip': 'Key principle: same DNA in all cells (except gametes/red blood cells) + selective gene expression = differentiation. This is why stem cell therapy works — stem cells still have all the genes needed to become any cell type.',
    },

    # ─── B2 Organisation ── Easy D1 (3 questions) ─────────────────────────────
    {
        'subject': 'Biology',
        'topic': 'Enzymes',
        'topic_code': 'B2',
        'difficulty': 1,
        'question_text': 'What is meant by the "active site" of an enzyme?',
        'option_a': 'The part of the enzyme that produces energy during reactions',
        'option_b': 'The specific region on the enzyme where the substrate binds',
        'option_c': 'The outer surface of the enzyme that repels other molecules',
        'option_d': 'The part of the enzyme that is destroyed during the reaction',
        'correct_answer': 'B',
        'explanation': 'The active site is a specific region on the enzyme molecule with a shape complementary to the substrate. The substrate binds to the active site forming an enzyme-substrate complex, which lowers the activation energy of the reaction.',
        'correction_tip': 'The active site has a specific, complementary shape to the substrate — like a lock and key. If the active site shape changes (e.g., due to heat or pH), the enzyme is denatured and no longer works.',
    },
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 1,
        'question_text': 'Which blood vessel carries oxygenated blood away from the heart to the body?',
        'option_a': 'Pulmonary vein',
        'option_b': 'Vena cava',
        'option_c': 'Aorta',
        'option_d': 'Pulmonary artery',
        'correct_answer': 'C',
        'explanation': 'The aorta is the largest artery in the body. It carries oxygenated blood from the left ventricle to the rest of the body (systemic circulation). The pulmonary artery carries deoxygenated blood to the lungs; the pulmonary vein returns oxygenated blood from the lungs to the heart; the vena cava returns deoxygenated blood from the body to the heart.',
        'correction_tip': 'Remember: arteries carry blood AWAY from the heart. The aorta = left ventricle → body (oxygenated). Pulmonary artery = right ventricle → lungs (deoxygenated — the only artery carrying deoxygenated blood).',
    },
    {
        'subject': 'Biology',
        'topic': 'Digestion',
        'topic_code': 'B2',
        'difficulty': 1,
        'question_text': 'Where in the digestive system is bile produced and where is it stored before being released?',
        'option_a': 'Produced in the stomach; stored in the pancreas',
        'option_b': 'Produced in the liver; stored in the gall bladder',
        'option_c': 'Produced in the gall bladder; stored in the liver',
        'option_d': 'Produced and stored in the small intestine',
        'correct_answer': 'B',
        'explanation': 'Bile is produced by the liver and stored in the gall bladder. When food (particularly fatty food) enters the small intestine (duodenum), the gall bladder contracts and releases bile through the bile duct into the duodenum.',
        'correction_tip': 'Liver = produces bile. Gall bladder = stores bile. Bile is NOT an enzyme — it emulsifies fats (breaks large fat droplets into smaller ones to increase surface area for lipase to act on) and neutralises stomach acid.',
    },

    # ─── B2 Organisation ── Hard D3 (7 questions) ─────────────────────────────
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'A patient has a resting heart rate of 70 beats per minute and a stroke volume of 75 mL. What is their cardiac output, and what would happen to cardiac output during vigorous exercise?',
        'option_a': '5250 mL/min at rest; decreases during exercise as the heart needs to conserve energy',
        'option_b': '5250 mL/min at rest; increases during exercise due to increased heart rate and stroke volume',
        'option_c': '145 mL/min at rest; doubles during exercise',
        'option_d': '5.25 mL/min at rest; increases during exercise',
        'correct_answer': 'B',
        'explanation': 'Cardiac output = heart rate × stroke volume = 70 × 75 = 5250 mL/min = 5.25 L/min. During vigorous exercise, cardiac output increases substantially (can reach 20–25 L/min in trained athletes) because both heart rate and stroke volume increase, delivering more oxygen and glucose to respiring muscles and removing CO₂ faster.',
        'correction_tip': 'Cardiac output (CO) = heart rate (HR) × stroke volume (SV). Units: if HR is beats/min and SV is mL/beat, then CO is mL/min. Divide by 1000 to get L/min. Both HR and SV increase during exercise.',
    },
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'Compare the advantages and disadvantages of using a stent versus a statin to treat coronary heart disease.',
        'option_a': 'Stents dissolve plaques; statins widen arteries — both work immediately',
        'option_b': 'Stents physically hold arteries open giving immediate effect but carry surgical risk; statins lower cholesterol long-term but require daily medication and may have side effects',
        'option_c': 'Statins physically hold arteries open; stents are chemical drugs taken daily',
        'option_d': 'Both stents and statins are equally effective and carry the same risks',
        'correct_answer': 'B',
        'explanation': 'Stents are wire mesh tubes inserted into coronary arteries to keep them open, providing an immediate solution to reduced blood flow. Risks include infection, blood clots, and re-narrowing. Statins are drugs that reduce LDL cholesterol production in the liver, slowing the progression of atherosclerosis over time. Side effects can include muscle pain (myopathy) and liver damage with long-term use. Statins require daily medication for life.',
        'correction_tip': 'For exam questions comparing treatments, always give: mechanism, advantages (including speed of effect), disadvantages (including risks/side effects), and suitability for different patients. Lifestyle changes (diet, exercise, stopping smoking) should also be mentioned as a first-line approach.',
    },
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'A patient requires a heart valve replacement. A surgeon can use either a mechanical valve or a biological (tissue) valve. Which statement correctly compares these options?',
        'option_a': 'Mechanical valves never require anticoagulants and last only 10 years',
        'option_b': 'Biological valves last longer than mechanical valves and require no medication',
        'option_c': 'Mechanical valves are very durable but require lifelong anticoagulant medication; biological valves do not require anticoagulants but may need replacing after 10–20 years',
        'option_d': 'Biological valves are made from plastic and do not degrade; mechanical valves are made from animal tissue',
        'correct_answer': 'C',
        'explanation': 'Mechanical valves are made from durable materials (e.g. titanium) and can last a lifetime, but their surface promotes blood clot formation, requiring lifelong anticoagulant drugs (e.g. warfarin). Biological valves (from pig or human donor tissue) are more compatible with blood and do not require anticoagulants, but they degrade over time and typically need replacing after 10–20 years.',
        'correction_tip': 'Mechanical valve: durable, lasts longer, needs anticoagulants. Biological valve: no anticoagulants, more natural, but wears out and may need replacement. Younger patients often get mechanical valves to avoid repeated surgery.',
    },
    {
        'subject': 'Biology',
        'topic': 'Organisation',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'Why does the human circulatory system being a double circulation (two separate loops) provide an advantage over a single circulatory system like that of fish?',
        'option_a': 'Double circulation means blood travels through the heart twice in one circuit, reducing flow rate',
        'option_b': 'Double circulation allows oxygenated blood to be pumped to the body at high pressure separately from deoxygenated blood sent to the lungs, maintaining efficient oxygen delivery',
        'option_c': 'Single circulation is more efficient because blood travels a shorter distance',
        'option_d': 'Double circulation prevents oxygenated and deoxygenated blood from mixing by removing the need for haemoglobin',
        'correct_answer': 'B',
        'explanation': 'In a double circulatory system, blood passes through the heart twice per circuit. The right side pumps deoxygenated blood to the lungs (pulmonary circuit); the left side pumps oxygenated blood to the body (systemic circuit) at high pressure. This maintains higher blood pressure to the body (delivering oxygen and nutrients faster), keeps oxygenated and deoxygenated blood separate, and allows different pressures in the two circuits.',
        'correction_tip': 'Double circulation: 2 pumps (right = lungs, left = body). Fish have single circulation: blood passes through the heart once per circuit, losing pressure as it passes through capillaries in gills, arriving at body tissues at low pressure.',
    },
    {
        'subject': 'Biology',
        'topic': 'Enzymes',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'Describe the induced fit model of enzyme action and explain how it differs from the lock and key model.',
        'option_a': 'Both models are identical — the active site is rigid in both',
        'option_b': 'Induced fit: the active site is flexible and moulds around the substrate; lock and key: the active site is rigid and pre-shaped to exactly fit the substrate',
        'option_c': 'Lock and key: active site changes shape; induced fit: active site is rigid',
        'option_d': 'Induced fit requires more energy; lock and key is only for intracellular enzymes',
        'correct_answer': 'B',
        'explanation': 'In the lock and key model, the enzyme\'s active site has a fixed, rigid shape exactly complementary to the substrate. In the induced fit model (more accurate), the active site is flexible — it changes shape slightly as the substrate binds, moulding around it to form a tighter enzyme-substrate complex. This better explains why some molecules that are similar in shape to the substrate (competitive inhibitors) can partially fit but not activate the enzyme.',
        'correction_tip': 'Lock and key = rigid active site (complementary shape). Induced fit = flexible active site that adjusts on binding. GCSE usually accepts either model, but the induced fit model is considered more scientifically accurate.',
    },
    {
        'subject': 'Biology',
        'topic': 'Transpiration',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'A plant is placed in a potometer. The rate of water uptake increases when the air flow (wind) around the plant increases. Explain, at the particle level, why increased air movement increases the rate of transpiration.',
        'option_a': 'Wind physically pushes water up the stem through increased pressure',
        'option_b': 'Wind removes water vapour from around the stomata, maintaining a steep concentration gradient for water to diffuse out of the leaf',
        'option_c': 'Wind cools the leaf, causing stomata to open wider and allowing faster water movement',
        'option_d': 'Wind increases photosynthesis, producing more water as a by-product',
        'correct_answer': 'B',
        'explanation': 'Water evaporates from spongy mesophyll cells inside the leaf and diffuses out through open stomata. Normally, water vapour builds up just outside the stomata, reducing the concentration gradient. Wind removes this accumulated water vapour, keeping the concentration of water molecules outside the leaf low. This maintains a steep concentration gradient between the humid air spaces inside the leaf and the drier air outside, so water diffuses out faster.',
        'correction_tip': 'Transpiration rate increases with: higher temperature (more kinetic energy → faster evaporation), lower humidity (maintains gradient), increased light (stomata open wider), and increased wind speed (removes water vapour to maintain gradient).',
    },
    {
        'subject': 'Biology',
        'topic': 'Gas exchange',
        'topic_code': 'B2',
        'difficulty': 3,
        'question_text': 'Compare the gas exchange surfaces of alveoli in the lungs and villi in the small intestine. Which statement correctly identifies a structural similarity and a functional difference?',
        'option_a': 'Both are folded to increase surface area; alveoli exchange gases while villi absorb digested food molecules',
        'option_b': 'Both absorb oxygen; alveoli also absorb glucose while villi only exchange gases',
        'option_c': 'Both are found in the stomach; both exchange oxygen and carbon dioxide',
        'option_d': 'Villi are thicker than alveoli to allow selective absorption; both have reduced blood supply',
        'correct_answer': 'A',
        'explanation': 'Both alveoli and villi are folded/highly convoluted structures that increase surface area (alveoli within the lungs; villi lining the small intestine). Both have a single layer of epithelial cells (thin walls) and a rich capillary network. However, they serve different functions: alveoli exchange O₂ and CO₂ between air and blood by diffusion; villi absorb digested food molecules (glucose, amino acids, fatty acids) from the intestinal lumen into the blood and lymph.',
        'correction_tip': 'Shared adaptations of gas exchange/absorption surfaces: large SA (folding), thin walls (short diffusion distance), rich blood supply (maintains gradient). The function differs: lungs = gas exchange; villi = nutrient absorption.',
    },

    # ─── B2 Organisation ── Exam Challenge D4 (10 questions) ─────────────────
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'A 45-year-old patient is diagnosed with atherosclerosis in the coronary arteries. Explain the sequence of events from cholesterol deposition to a heart attack (myocardial infarction), and suggest why LDL cholesterol is specifically implicated.',
        'option_a': 'HDL cholesterol builds up in arteries; this triggers blood clotting which forms a plaque; the plaque blocks veins causing a heart attack',
        'option_b': 'Excess LDL cholesterol is deposited beneath the inner lining of coronary arteries forming plaques; plaques narrow the lumen and reduce blood flow; if a plaque ruptures a blood clot (thrombus) can completely block the artery, cutting off oxygen to heart muscle, causing myocardial infarction',
        'option_c': 'Plaques form in the chambers of the heart; they reduce pumping efficiency; eventually the heart stops beating',
        'option_d': 'LDL cholesterol destroys red blood cells, reducing oxygen delivery; this weakens the heart muscle over time',
        'correct_answer': 'B',
        'explanation': 'LDL (low-density lipoprotein) carries cholesterol to peripheral tissues and is associated with plaque formation. When LDL levels are high, cholesterol deposits under the endothelium (inner arterial lining), forming fatty streaks that develop into plaques (atheroma). Plaques narrow the coronary artery lumen, reducing blood flow and oxygen to heart muscle. If the fibrous cap of a plaque ruptures, a blood clot (thrombus) forms. If the clot completely blocks the artery, the heart muscle is starved of oxygen and cells die — a myocardial infarction. HDL carries cholesterol back to the liver for removal, so it is protective.',
        'correction_tip': 'Atherosclerosis pathway: high LDL → plaque formation → narrowed artery → reduced O₂ → chest pain (angina). Rupture → thrombus → complete block → heart attack. LDL = bad cholesterol (deposits). HDL = good cholesterol (removes).',
    },
    {
        'subject': 'Biology',
        'topic': 'Heart',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'An artificial heart is implanted in a patient awaiting a donor heart transplant. Evaluate the advantages and disadvantages of an artificial heart compared to a donor transplant.',
        'option_a': 'Artificial heart: no surgery needed; donor heart: requires surgery and immunosuppressants',
        'option_b': 'Artificial heart: avoids immune rejection and keeps patient alive while waiting; disadvantages include mechanical failure risk, need for external power source, and risk of blood clots. Donor transplant: natural heart function once healed, but requires immunosuppressant drugs for life and is limited by donor availability',
        'option_c': 'Artificial heart is always superior; donor transplants are no longer used in medicine',
        'option_d': 'Donor transplant: no rejection risk; artificial heart: rejection of foreign materials is the main concern',
        'correct_answer': 'B',
        'explanation': 'Artificial hearts are used as a bridge to transplant or in patients unsuitable for transplant. Advantages: no immune rejection (made from synthetic materials), keeps patient alive, available immediately. Disadvantages: mechanical parts can fail, require anticoagulants (blood clot risk), often need external power (limits patient mobility), not a permanent solution. Donor heart transplant: restores natural heart function if successful. Disadvantages: shortage of donors (waiting list), requires matching, lifelong immunosuppressants (increase infection risk), possibility of rejection.',
        'correction_tip': 'Artificial heart: available but limited/mechanical. Donor heart: natural but scarce + rejection risk. GCSE evaluation questions expect balanced answers — give at least two points for each side.',
    },
    {
        'subject': 'Biology',
        'topic': 'Organisation',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'Blood vessels: which combination correctly matches the structural feature to the blood vessel type and explains its functional significance?',
        'option_a': 'Veins have thick muscular walls to withstand high pressure; arteries have valves to prevent backflow',
        'option_b': 'Arteries have thick muscular, elastic walls to withstand and smooth out high pressure pulsatile blood flow; veins have thin walls and valves to prevent backflow of low-pressure blood; capillaries have walls one cell thick to allow rapid exchange of substances by diffusion',
        'option_c': 'Capillaries have the largest lumen; veins have the thickest walls; arteries have valves',
        'option_d': 'All three vessel types have the same wall thickness; differences are only in their diameter',
        'correct_answer': 'B',
        'explanation': 'Arteries carry blood at high pressure from the heart — their thick muscular and elastic walls can withstand this pressure and the elasticity smooths out the pulse. Veins carry blood at low pressure back to the heart — thin walls are sufficient, and semilunar valves prevent backflow. Capillaries have walls that are just one endothelial cell thick (≈1 μm), minimising the diffusion distance for O₂, CO₂, glucose, and waste products exchanged between blood and tissues.',
        'correction_tip': 'Artery: thick muscular elastic wall, small lumen, no valves, high pressure. Vein: thin wall, large lumen, valves, low pressure. Capillary: one cell thick wall, smallest diameter, exchange surface. Valves are found in VEINS (not arteries) and in the heart.',
    },
    {
        'subject': 'Biology',
        'topic': 'Enzymes',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'A student investigates the effect of pH on amylase activity. They find that amylase works optimally at pH 7 but is inactive at pH 2. Explain why the enzyme is inactive at pH 2 at the molecular level, and suggest what happens when the enzyme is returned to pH 7.',
        'option_a': 'At pH 2 the substrate changes shape so it no longer fits the active site; returning to pH 7 restores the substrate shape',
        'option_b': 'At pH 2 the high concentration of H⁺ ions disrupts the hydrogen bonds and ionic interactions holding the enzyme\'s tertiary structure, altering the active site shape so substrate cannot bind. The denaturation caused by extreme pH is often irreversible, so returning to pH 7 may not restore activity',
        'option_c': 'pH 2 is too acidic for the substrate to dissolve; returning to pH 7 allows the substrate to dissolve and react',
        'option_d': 'At pH 2 temperature increases, denaturing the enzyme; pH 7 has a lower temperature restoring function',
        'correct_answer': 'B',
        'explanation': 'An enzyme\'s active site shape is maintained by weak intermolecular forces (hydrogen bonds, ionic bonds, van der Waals forces) that hold its tertiary structure. At pH 2, excess H⁺ ions disrupt ionic bonds and hydrogen bonds, causing the protein to unfold and the active site to change shape. The substrate can no longer bind — the enzyme is denatured. Unlike temperature denaturation (which is always irreversible), some pH denaturation may be reversible at mild pH changes, but extremes like pH 2 for amylase typically cause permanent denaturation.',
        'correction_tip': 'Denaturation = change in tertiary structure → change in active site shape → substrate cannot bind → no enzyme-substrate complex → no catalysis. Caused by high temperature OR extreme pH. At GCSE, denaturation is permanent.',
    },
    {
        'subject': 'Biology',
        'topic': 'Digestion',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'Explain the two roles of bile in digestion, and why emulsification (not chemical digestion) is the correct term for what bile does to fats.',
        'option_a': 'Bile digests fats by breaking ester bonds; it also neutralises alkalis from the pancreas',
        'option_b': 'Bile emulsifies fats by breaking large fat droplets into smaller droplets (increasing surface area for lipase) and neutralises stomach acid (HCl) to provide the alkaline conditions needed by intestinal enzymes',
        'option_c': 'Bile is a protease enzyme that digests fat; it also provides the acid conditions needed by intestinal enzymes',
        'option_d': 'Bile absorbs water from fats and raises the pH of the stomach',
        'correct_answer': 'B',
        'explanation': 'Role 1 (emulsification): Bile salts have hydrophilic and hydrophobic ends. They surround large fat droplets and break them into many smaller droplets, dramatically increasing the total surface area exposed to lipase enzymes, speeding up fat digestion. This is PHYSICAL, not chemical — no bonds in fat molecules are broken. Role 2 (neutralisation): Stomach acid (HCl, pH ≈2) makes chyme very acidic. Bile (alkaline, made in liver) raises the pH in the duodenum to about 7–8, providing optimal conditions for pancreatic enzymes (lipase, amylase, protease) which work best at neutral/alkaline pH.',
        'correction_tip': 'Emulsification = physical breakdown of large fat droplets into small ones (increases SA). Chemical digestion = breaking chemical bonds (hydrolysis). Bile does NOT break chemical bonds in fats — lipase does that.',
    },
    {
        'subject': 'Biology',
        'topic': 'Gas exchange',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'Using Fick\'s law, explain how the gas exchange surface of human lungs is adapted for maximum efficiency, and compare it with the gas exchange surface of a fish gill.',
        'option_a': 'Lungs: thick membrane, small surface area; gills: thin membrane, small surface area — both equally efficient',
        'option_b': 'Both lungs and gills apply Fick\'s law: large SA (alveoli/gill lamellae), thin membrane (1–2 cells), maintained gradient (ventilation in lungs; counter-current flow in gills). Counter-current exchange in gills maintains a diffusion gradient along the entire gill surface, making them more efficient than lungs where diffusion gradients vary',
        'option_c': 'Fick\'s law only applies to lungs; gills use active transport for gas exchange',
        'option_d': 'Gills have a thick wall compared to lungs, compensating by having a larger surface area',
        'correct_answer': 'B',
        'explanation': 'Fick\'s law: Rate ∝ (SA × conc. gradient) / thickness. Human lungs: ~70 m² surface area from ~300–500 million alveoli; walls 1–2 cells thick (≈0.1 μm); constant ventilation (breathing) and perfusion (blood flow) maintain the O₂/CO₂ gradient. Fish gills: gill lamellae provide large SA; thin epithelium; a counter-current exchange system (water flows over gills opposite to blood flow direction) maintains a concentration gradient along the entire gill surface, achieving up to 80% O₂ extraction from water vs ~25% in human lungs.',
        'correction_tip': 'Fick\'s law: maximise SA and concentration gradient; minimise membrane thickness. Counter-current exchange in fish gills is more efficient than the concurrent system. In concurrent systems, equilibrium is reached halfway and no further diffusion occurs.',
    },
    {
        'subject': 'Biology',
        'topic': 'Transpiration',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'A student measures transpiration rate in a plant under four conditions: (1) bright light, 20°C, low humidity; (2) dim light, 20°C, low humidity; (3) bright light, 30°C, low humidity; (4) bright light, 20°C, high humidity. Rank these conditions from highest to lowest transpiration rate and explain the key factor that most increases transpiration.',
        'option_a': 'Ranking: 2 > 1 > 3 > 4; key factor: light closes stomata',
        'option_b': 'Ranking: 3 > 1 > 2 > 4; key factor: temperature most increases transpiration because it increases the kinetic energy of water molecules and widens stomatal aperture',
        'option_c': 'Ranking: 1 > 3 > 4 > 2; key factor: high humidity increases transpiration rate',
        'option_d': 'Ranking: 4 > 1 > 3 > 2; key factor: high humidity closes stomata',
        'correct_answer': 'B',
        'explanation': 'Condition 3 (bright light + 30°C + low humidity) has the highest transpiration: high temperature increases the kinetic energy of water molecules, increasing evaporation rate inside the leaf and widening stomata; bright light keeps stomata open; low humidity maintains the steep concentration gradient for water vapour to diffuse out. Condition 1 (bright light, 20°C, low humidity) is next. Condition 2 (dim light) is lower because stomata are more closed. Condition 4 (high humidity) has the lowest rate because the concentration gradient between the leaf interior and the surrounding air is smallest, reducing the rate of diffusion out.',
        'correction_tip': 'Key factors increasing transpiration rate: higher temperature > lower humidity > brighter light > increased wind speed. High humidity REDUCES transpiration because it reduces the concentration gradient for water vapour diffusion.',
    },
    {
        'subject': 'Biology',
        'topic': 'Enzymes',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'At 37°C amylase breaks down starch in 5 minutes. At 60°C the reaction completes in 2 minutes initially, but the enzyme stops working permanently after 10 minutes at this temperature. At 10°C the reaction takes 40 minutes. Explain these results with reference to enzyme structure and activation energy.',
        'option_a': 'At 60°C the enzyme speeds up then slows down because it runs out of substrate',
        'option_b': 'At 60°C the initial rate is higher because molecules have more kinetic energy (more frequent successful collisions, lower activation energy needed), but the enzyme denatures as heat permanently disrupts bonds in the tertiary structure, altering the active site. At 10°C the lower kinetic energy of molecules means fewer collisions per unit time, reducing the rate even though the enzyme retains its structure.',
        'option_c': 'At 10°C the enzyme is denatured by cold temperatures, so the reaction slows but is reversible',
        'option_d': 'All three temperatures produce identical results; only pH affects enzyme activity',
        'correct_answer': 'B',
        'explanation': 'Rate of reaction depends on frequency of successful enzyme-substrate collisions. At higher temperatures, molecules have more kinetic energy → faster movement → more frequent collisions → higher rate. However, above the optimum (~37°C for amylase) excessive thermal energy breaks hydrogen bonds and other weak interactions maintaining the enzyme\'s tertiary structure. The active site changes shape irreversibly (denaturation), so no more substrate can bind. At 10°C, molecules have less kinetic energy → fewer collisions per unit time → slower reaction, but the enzyme structure is intact and activity resumes if temperature rises.',
        'correction_tip': 'Temperature effects: below optimum = slower rate (less KE). Above optimum = faster rate then denaturation. Denaturation = permanent structural change. Low temperature = no denaturation, just slower (reversible). Always distinguish between "less active" (reversible) and "denatured" (irreversible).',
    },
    {
        'subject': 'Biology',
        'topic': 'Blood',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'A patient has a genetic condition causing their red blood cells to be sickle-shaped rather than biconcave disc-shaped. Explain two ways in which this affects the function of the red blood cells, with reference to cell structure and gas exchange.',
        'option_a': 'Sickle cells carry more haemoglobin due to their irregular shape; they also pass through capillaries more easily',
        'option_b': 'Sickle cells have reduced surface area to volume ratio compared to biconcave disc cells, reducing the rate of oxygen diffusion; they are also rigid and can block small capillaries, reducing blood flow and oxygen delivery to tissues',
        'option_c': 'Sickle cells only affect CO₂ transport; oxygen transport is unaffected',
        'option_d': 'Sickle cells increase the viscosity of blood, improving delivery to all organs',
        'correct_answer': 'B',
        'explanation': 'Normal red blood cells are biconcave discs — this shape maximises surface area to volume ratio (SA:V) for oxygen diffusion and allows them to flex to pass through narrow capillaries. Sickle cells: (1) have a reduced SA:V ratio due to their elongated crescent shape, reducing diffusion rate of O₂ in and CO₂ out; (2) are rigid due to abnormal haemoglobin (HbS) polymerising under low oxygen conditions — they cannot deform to squeeze through capillaries, causing blockages, reduced blood flow, and tissue hypoxia (oxygen starvation).',
        'correction_tip': 'Biconcave disc shape = large SA:V + flexible. Sickle shape = smaller SA:V + rigid. SA:V ratio is critical for diffusion efficiency. Smaller SA:V → slower diffusion of gases across the cell membrane.',
    },
    {
        'subject': 'Biology',
        'topic': 'Organisation',
        'topic_code': 'B2',
        'difficulty': 4,
        'question_text': 'A researcher studying the hierarchy of biological organisation states: "A tissue is simply a collection of cells." Evaluate this statement and explain why the concept of emergent properties is important in biological organisation.',
        'option_a': 'The statement is fully correct; cells in a tissue have the same properties as individual cells',
        'option_b': 'The statement is an oversimplification — a tissue is a group of similar cells working together to perform a specific function. At each level of organisation (cell → tissue → organ → organ system → organism), emergent properties arise that are not present at lower levels, making the whole more functional than the sum of its parts',
        'option_c': 'Tissues are only found in animals; in plants, cells are directly organised into organs',
        'option_d': 'Emergent properties are irrelevant to biology; all properties can be explained at the cellular level',
        'correct_answer': 'B',
        'explanation': 'A tissue is not merely a collection of cells — it is a group of similar cells with a common origin that work together to carry out a specific function (e.g., muscle tissue contracts; epithelial tissue lines surfaces). At each level of biological organisation, new properties emerge that cannot be attributed to individual components: individual cardiac muscle cells can contract rhythmically, but only when organised into heart tissue and the whole organ does effective blood pumping emerge. This principle of emergent properties explains why biology must be studied at multiple levels of organisation.',
        'correction_tip': 'Levels of organisation: cell → tissue → organ → organ system → organism. Emergent properties = new functions that arise at higher levels. A single neuron cannot think; a network of neurons can. A single muscle fibre cannot pump blood; a heart can.',
    },
]

import sqlite3, os

def main():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'quiz.db')
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    added = 0
    for q in QUESTIONS:
        c.execute(
            '''INSERT INTO questions (subject, topic, topic_code, difficulty, question_text,
               option_a, option_b, option_c, option_d, correct_answer, explanation, correction_tip)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?)''',
            (q['subject'],q['topic'],q['topic_code'],q['difficulty'],q['question_text'],
             q['option_a'],q['option_b'],q['option_c'],q['option_d'],
             q['correct_answer'],q['explanation'],q['correction_tip']))
        added += 1
    conn.commit(); conn.close()
    print(f'Added {added} questions.')

if __name__ == '__main__': main()
