"""
Run once to add the Heart, Digestion, Blood, Transpiration & Leaf Structure question set.
Usage: python3 add_questions2.py
"""
import database as db

QUESTIONS = [
    # ─────────────────────────────────────────────────────
    # BIOLOGY – Easy
    # ─────────────────────────────────────────────────────
    ('Biology', 'Heart', 1,
     'What is the function of valves in the heart?',
     'To pump blood around the body',
     'To prevent the backflow of blood',
     'To carry oxygen to the muscles',
     'To filter waste products from the blood',
     'B',
     'Pumping blood is done by the ventricles. Carrying oxygen is the role of red blood cells. Filtering waste is done by the kidneys.',
     'Valves open to let blood through and then snap shut to stop blood flowing backwards, ensuring a one-way flow through the heart.'),

    ('Biology', 'Heart', 1,
     'What is coronary heart disease (CHD)?',
     'A disease caused by a virus attacking the heart muscle',
     'A condition where the heart beats too slowly',
     'When coronary arteries become narrowed by a build-up of fatty material, restricting blood flow to the heart',
     'A genetic condition where the heart has the wrong number of chambers',
     'C',
     'CHD is not caused by a virus or genetics — it is caused by fatty deposits (plaques) in the coronary arteries.',
     'Coronary arteries supply the heart muscle with oxygenated blood. If they narrow due to fatty plaques (atherosclerosis), the heart receives less oxygen, increasing the risk of a heart attack.'),

    ('Biology', 'Heart', 1,
     'What do statins do?',
     'They widen narrowed arteries using a small balloon',
     'They replace faulty heart valves',
     'They act as an artificial pacemaker',
     'They reduce the level of LDL (bad) cholesterol in the blood',
     'D',
     'Widening arteries describes a stent. Replacing valves is valve surgery. An artificial pacemaker is a separate device.',
     'Statins are tablets taken daily that lower LDL (bad) cholesterol and raise HDL (good) cholesterol, reducing the build-up of fatty plaques in arteries.'),

    ('Biology', 'Organisation', 1,
     'What is the definition of a tissue?',
     'A single cell with a specialised function',
     'A group of similar cells working together to perform a specific function',
     'A group of different organs working together',
     'The smallest unit of life',
     'B',
     'A single specialised cell is just a cell, not a tissue. A group of organs is an organ system. The smallest unit of life is a cell.',
     'Tissue = group of similar cells. Examples: muscle tissue (muscle cells), nervous tissue (neurones), epithelial tissue (lining cells).'),

    ('Biology', 'Organisation', 1,
     'What is the definition of an organ?',
     'A group of similar cells working together',
     'The smallest unit of life',
     'A group of different tissues working together to perform a specific function',
     'A group of organs working together',
     'C',
     'A group of similar cells is a tissue. The smallest unit of life is a cell. A group of organs is an organ system.',
     'Organ = group of different tissues working together. Example: the stomach contains muscle tissue, epithelial tissue, and glandular tissue all working together to digest food.'),

    ('Biology', 'Digestion', 1,
     'What does amylase break down, and what does it produce?',
     'Proteins into amino acids',
     'Lipids into fatty acids and glycerol',
     'Carbohydrates (starch) into simple sugars',
     'Nucleic acids into nucleotides',
     'C',
     'Proteins → amino acids is done by protease. Lipids → fatty acids and glycerol is done by lipase.',
     'Amylase is a carbohydrase. It breaks the bonds in starch molecules to produce maltose and then glucose — simple sugars that can be absorbed into the bloodstream.'),

    ('Biology', 'Digestion', 1,
     'What does protease do in the digestive system?',
     'Breaks down carbohydrates into simple sugars',
     'Breaks down proteins into amino acids',
     'Emulsifies fats into smaller droplets',
     'Breaks down lipids into fatty acids and glycerol',
     'B',
     'Carbohydrates → sugars is amylase. Emulsifying fats is bile. Lipids → fatty acids and glycerol is lipase.',
     'Protease enzymes break the peptide bonds between amino acids in protein chains. The resulting amino acids can then be absorbed through the intestinal wall into the bloodstream.'),

    ('Biology', 'Digestion', 1,
     'What does lipase do in the digestive system?',
     'Breaks proteins into amino acids',
     'Breaks starch into glucose',
     'Neutralises stomach acid in the small intestine',
     'Breaks down lipids (fats) into three fatty acids and glycerol',
     'D',
     'Proteins → amino acids is protease. Starch → glucose is amylase. Neutralising acid is done by bile.',
     'Lipase breaks the ester bonds in triglyceride (fat) molecules to produce 3 fatty acids and 1 glycerol molecule. These smaller products can then be absorbed across the intestinal wall.'),

    ('Biology', 'Blood', 1,
     'What is the main function of red blood cells?',
     'To engulf and destroy pathogens',
     'To help blood clot at a wound',
     'To transport oxygen and carbon dioxide around the body',
     'To carry hormones and nutrients in solution',
     'C',
     'Engulfing pathogens is done by white blood cells. Clotting is done by platelets. Carrying hormones and nutrients in solution is the role of plasma.',
     'Red blood cells contain haemoglobin, which binds to oxygen in the lungs and releases it at body tissues. They also carry some CO₂ back to the lungs.'),

    ('Biology', 'Blood', 1,
     'What is the function of platelets?',
     'To carry oxygen to the muscles',
     'To produce antibodies against pathogens',
     'To transport hormones around the body',
     'Small fragments of cells that help blood to clot at a wound, preventing blood loss and entry of pathogens',
     'D',
     'Carrying oxygen is red blood cells. Producing antibodies is white blood cells. Transporting hormones is plasma.',
     'Platelets are tiny cell fragments with no nucleus. When a blood vessel is damaged, platelets clump together and trigger a clotting cascade that forms a scab, sealing the wound.'),

    ('Biology', 'Transpiration', 1,
     'What is transpiration?',
     'The movement of sugar molecules up and down the phloem',
     'The movement of water and minerals up the xylem',
     'The evaporation of water vapour from the surface of a plant',
     'The absorption of water by root hair cells',
     'C',
     'Sugar movement in phloem is translocation. Water and minerals moving up xylem is the transpiration stream. Water absorption is osmosis in root hair cells.',
     'Transpiration: water evaporates from the leaf surface (mainly through stomata). This loss of water pulls more water up through the xylem from the roots — creating the transpiration stream.'),

    ('Biology', 'Transpiration', 1,
     'What is translocation?',
     'The evaporation of water from the leaf surface',
     'The movement of water and minerals up the xylem from roots to leaves',
     'The movement of sugar molecules up and down the phloem to where they are needed',
     'The absorption of mineral ions by root hair cells',
     'C',
     'Water evaporation is transpiration. Water and minerals moving up xylem is the transpiration stream. Mineral ion absorption uses active transport.',
     'Translocation moves sucrose (sugar) made by photosynthesis from the leaves (source) through the phloem to where it is needed — growing regions, storage organs, or anywhere requiring energy.'),

    ('Biology', 'Leaf structure', 1,
     'What is the function of stomata in a leaf?',
     'To absorb light energy for photosynthesis',
     'To provide structural support for the leaf',
     'Small pores that allow gases (CO₂ and O₂) to enter and exit the leaf',
     'To waterproof the outer surface of the leaf',
     'C',
     'Light absorption is done by chloroplasts. Structural support is from the cell wall. Waterproofing is done by the waxy cuticle.',
     'Stomata are tiny pores, mainly on the underside of leaves. CO₂ enters for photosynthesis and O₂ exits; water vapour also exits during transpiration. Guard cells control whether they are open or closed.'),

    ('Biology', 'Heart', 1,
     'Where does deoxygenated blood enter the heart?',
     'Left ventricle via the aorta',
     'Left atrium via the pulmonary vein',
     'Right atrium via the vena cava',
     'Right ventricle via the pulmonary artery',
     'C',
     'Oxygenated blood returns from the lungs to the LEFT atrium via the pulmonary vein. The aorta carries blood OUT of the heart. The pulmonary artery carries blood FROM the heart TO the lungs.',
     'Deoxygenated blood from the body travels through the vena cava into the RIGHT atrium. It then moves to the right ventricle, which pumps it to the lungs via the pulmonary artery.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Medium
    # ─────────────────────────────────────────────────────
    ('Biology', 'Heart', 2,
     'Where are pacemaker cells located, and what do they do?',
     'In the left ventricle; they pump oxygenated blood to the body',
     'In the right atrium; they produce electrical impulses that spread to heart muscles causing them to contract at a regular rate',
     'In the aorta; they monitor blood pressure and adjust heart rate',
     'In the pulmonary vein; they control the flow of oxygenated blood into the heart',
     'B',
     'Pacemaker cells are in the RIGHT ATRIUM, not the ventricle, aorta, or pulmonary vein.',
     'The sinoatrial node (SAN) — the natural pacemaker — is in the right atrium. It generates regular electrical impulses that cause the heart to contract rhythmically. If it malfunctions, an artificial pacemaker is implanted.'),

    ('Biology', 'Digestion', 2,
     'Where is bile made and stored, and what is its function?',
     'Made in the stomach and stored in the pancreas; it kills bacteria in food',
     'Made in the kidneys and stored in the bladder; it neutralises stomach acid',
     'Made in the liver and stored in the gall bladder; it emulsifies fats and neutralises stomach acid',
     'Made in the small intestine and stored in the liver; it breaks down proteins',
     'C',
     'Bile is made in the LIVER and stored in the GALL BLADDER (not the stomach, kidneys, or small intestine).',
     'Bile: (1) emulsifies fats — breaks large fat droplets into smaller ones, increasing surface area for lipase; (2) neutralises stomach acid — provides alkaline conditions in the small intestine, which is the optimum pH for lipase.'),

    ('Biology', 'Blood', 2,
     'What is the function of white blood cells (WBCs)?',
     'To transport oxygen and carbon dioxide around the body',
     'To carry nutrients, hormones, and waste products in solution',
     'To engulf and destroy pathogens, and produce antibodies to fight infection',
     'To help blood clot at a wound site to prevent excessive bleeding',
     'C',
     'Transporting oxygen is red blood cells. Carrying nutrients in solution is plasma. Clotting is platelets.',
     'WBCs are part of the immune system. Phagocytes engulf (eat) pathogens. Lymphocytes produce specific antibodies that target and neutralise pathogens.'),

    ('Biology', 'Blood', 2,
     'What does plasma transport around the body?',
     'Only oxygen and carbon dioxide',
     'Nutrients, CO₂, urea, hormones, proteins, antibodies, and antitoxins dissolved in liquid',
     'Only red blood cells and platelets',
     'Only waste products such as urea',
     'B',
     'Plasma carries MANY different substances. Oxygen is mainly carried by red blood cells (not dissolved in plasma in significant amounts).',
     'Plasma is the yellow liquid component of blood. It transports: digested food (glucose, amino acids), CO₂ from tissues to lungs, urea from liver to kidneys, hormones, antibodies, and heat energy.'),

    ('Biology', 'Transpiration', 2,
     'What happens to the rate of transpiration when humidity increases?',
     'Transpiration rate increases because more water vapour is available',
     'Transpiration rate stays the same — humidity has no effect',
     'Transpiration rate decreases because the concentration gradient between the leaf and air is reduced',
     'Transpiration rate doubles because stomata open wider in humid conditions',
     'C',
     'High humidity means the air already contains lots of water vapour — this REDUCES the concentration gradient, so less water evaporates from the leaf.',
     'Transpiration depends on the concentration gradient of water vapour between leaf and air. High humidity = smaller gradient = less evaporation = lower transpiration rate.'),

    ('Biology', 'Transpiration', 2,
     'What happens to the rate of transpiration when temperature increases?',
     'Transpiration rate decreases because stomata close in warm conditions',
     'Transpiration rate increases because water molecules have more kinetic energy and are more likely to evaporate',
     'Transpiration rate stays the same regardless of temperature',
     'Transpiration rate increases because chloroplasts produce more water at higher temperatures',
     'B',
     'Stomata do not close in warm conditions under normal circumstances. Chloroplasts do not produce water.',
     'Higher temperature gives water molecules more kinetic energy, increasing the rate of evaporation from leaf cells. More water diffuses out through stomata → higher transpiration rate.'),

    ('Biology', 'Transpiration', 2,
     'What happens to transpiration rate when light intensity increases?',
     'Transpiration rate decreases because photosynthesis uses up water',
     'Transpiration rate stays the same — stomata are always open',
     'Transpiration rate increases because more stomata open to allow CO₂ in for increased photosynthesis, allowing more water to escape',
     'Transpiration rate decreases because guard cells lose water in bright light',
     'C',
     'More light = more photosynthesis = stomata OPEN more. More open stomata = more water vapour escaping.',
     'In bright light, guard cells become turgid and open the stomata to let in CO₂ for photosynthesis. More open stomata means more water vapour evaporates → higher transpiration rate.'),

    ('Biology', 'Transpiration', 2,
     'What happens to transpiration rate when air flow (wind speed) increases?',
     'Transpiration rate decreases because wind cools the leaf surface',
     'Transpiration rate stays the same — wind only affects the roots',
     'Transpiration rate increases because moving air removes water vapour from around the stomata, maintaining a steep concentration gradient',
     'Transpiration rate decreases because stomata close in windy conditions',
     'C',
     'Wind does not cause stomata to close. Wind moves water vapour AWAY from the leaf, steepening the gradient and increasing transpiration.',
     'In still air, water vapour builds up around stomata, reducing the concentration gradient. Wind sweeps this vapour away, keeping the gradient steep so water continues to diffuse out rapidly.'),

    ('Biology', 'Leaf structure', 2,
     'What is the function of the waxy cuticle on a leaf?',
     'To absorb sunlight for photosynthesis',
     'To allow gas exchange between leaf and air',
     'A waterproof outer layer that reduces water loss from the leaf surface by evaporation',
     'To control the opening and closing of stomata',
     'C',
     'Light absorption is done by chlorophyll. Gas exchange is through stomata. Stomata opening/closing is controlled by guard cells.',
     'The waxy cuticle is a transparent, waterproof layer on the upper epidermis. It prevents water loss by evaporation from the leaf surface, which would otherwise significantly reduce water content.'),

    ('Biology', 'Leaf structure', 2,
     'What is the function of the palisade mesophyll layer?',
     'To allow gases to diffuse efficiently through the leaf',
     'To contain lots of chlorophyll and be tightly packed to maximise light absorption for photosynthesis',
     'To waterproof the outer surface of the leaf',
     'To control the opening and closing of stomata',
     'B',
     'Gas diffusion is the role of spongy mesophyll with its air spaces. Waterproofing is the waxy cuticle. Stomata control is by guard cells.',
     'Palisade mesophyll cells are tall, tightly packed, and full of chloroplasts. They are positioned at the top of the leaf to capture maximum light energy for photosynthesis.'),

    ('Biology', 'Leaf structure', 2,
     'What is the function of the spongy mesophyll layer?',
     'To absorb light energy directly from the sun',
     'To waterproof the leaf and prevent water loss',
     'Large air spaces between loosely arranged cells allow gases (CO₂, O₂, water vapour) to diffuse efficiently through the leaf',
     'To produce the waxy cuticle layer',
     'C',
     'Light absorption is mainly in the palisade layer above. Waterproofing is the waxy cuticle. The spongy mesophyll is specifically adapted for gas diffusion.',
     'Spongy mesophyll cells are irregularly shaped with large air spaces between them. These spaces create a large internal surface area for gases to dissolve and diffuse, connecting stomata to photosynthesising cells.'),

    ('Biology', 'Leaf structure', 2,
     'What is the role of guard cells in a leaf?',
     'To absorb light for photosynthesis',
     'To control the opening and closing of stomata, regulating gas exchange and water loss',
     'To produce waxy substances to waterproof the leaf',
     'To carry water up from the roots to the leaves',
     'B',
     'Light absorption is by palisade cells. Waterproofing is the waxy cuticle. Water transport is by xylem.',
     'Guard cells surround each stoma. When turgid (full of water) they bow outward, opening the stoma. When flaccid (water lost) they close. This balances gas exchange for photosynthesis with minimising water loss.'),

    ('Biology', 'Heart', 2,
     'What is the double circulatory system?',
     'A system where the heart pumps blood twice before it reaches the body',
     'One circuit where the heart pumps deoxygenated blood to the lungs, and a separate circuit where it pumps oxygenated blood to the rest of the body',
     'A system where two hearts work together to pump blood',
     'A system where arteries and veins form two separate but identical loops',
     'B',
     'The heart does not pump blood twice in one cycle. There is only one heart. The two circuits serve different purposes (lungs vs. body).',
     'Circuit 1 (pulmonary): right side of heart → lungs (to oxygenate blood) → back to heart. Circuit 2 (systemic): left side of heart → body (to deliver oxygen) → back to heart. Two separate circuits keep oxygenated and deoxygenated blood apart.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Hard
    # ─────────────────────────────────────────────────────
    ('Biology', 'Heart', 3,
     'Describe the full pathway of blood through the heart, from entering as deoxygenated blood to leaving as oxygenated blood.',
     'Deoxygenated blood enters the left atrium → left ventricle → pulmonary vein → lungs → right atrium → aorta',
     'Deoxygenated blood enters the right atrium via the vena cava → right ventricle → pulmonary artery → lungs; oxygenated blood returns via pulmonary vein → left atrium → left ventricle → aorta → body',
     'Deoxygenated blood enters both atria simultaneously → both ventricles → aorta and pulmonary artery at the same time',
     'Deoxygenated blood enters the right ventricle → right atrium → pulmonary vein → lungs → left atrium → aorta',
     'B',
     'Blood always enters the ATRIA first, not the ventricles. The pulmonary VEIN carries oxygenated blood back from the lungs. The pulmonary ARTERY carries deoxygenated blood TO the lungs.',
     'Right atrium (deoxygenated blood in via vena cava) → right ventricle → pulmonary artery → lungs (oxygenated) → pulmonary vein → left atrium → left ventricle → aorta → body.'),

    ('Biology', 'Heart', 3,
     'Why are the walls of the ventricles thicker than the walls of the atria?',
     'Because the ventricles receive blood from the lungs which is under higher pressure',
     'Because the ventricles need to push blood a greater distance — the right ventricle to the lungs and the left ventricle all the way around the body',
     'Because the ventricles contain more valves and need extra muscle to operate them',
     'Because the ventricles are smaller so need thicker walls to compensate',
     'B',
     'The atria receive incoming blood — they only push blood a short distance to the ventricles below, needing less muscle.',
     'The ventricles must pump blood out of the heart — the right to the lungs, and the left to the whole body. Greater distance = greater pressure needed = thicker, more muscular walls. The left ventricle is thicker than the right because it pumps blood further.'),

    ('Biology', 'Heart', 3,
     'Explain how a heart attack occurs.',
     'The heart beats too fast for too long, causing the muscle to tire and stop',
     'A blood clot in a vein in the leg breaks off and travels to the brain',
     'If fatty plaques in the coronary arteries build up enough to block the artery, the heart muscle is starved of oxygen and begins to die',
     'The pacemaker cells stop producing electrical impulses, causing the heart to stop',
     'C',
     'Heart rate alone does not cause a heart attack. A blood clot to the brain causes a stroke, not a heart attack. Pacemaker failure causes arrhythmia, not a heart attack.',
     'Coronary arteries supply the heart muscle with oxygenated blood. Fatty plaques gradually narrow them. If a plaque ruptures, a clot can form and block the artery completely, cutting off oxygen to part of the heart muscle — causing it to die (myocardial infarction).'),

    ('Biology', 'Heart', 3,
     'What happens if a heart valve does not work correctly?',
     'The heart beats faster to compensate for reduced oxygen',
     'Blood cannot circulate properly as it flows backwards or leaks in the wrong direction through the faulty valve',
     'The pacemaker cells produce weaker electrical signals',
     'The coronary arteries become blocked with fatty deposits',
     'B',
     'Heart rate changes are caused by pacemaker issues. Coronary artery blockage is CHD. Valve problems specifically prevent one-directional blood flow.',
     'Valves ensure one-way flow. A faulty valve may not open fully (stenosis — restricting flow) or not close fully (regurgitation — allowing backflow), reducing the efficiency of the heart and potentially causing heart failure.'),

    ('Biology', 'Enzymes', 3,
     'What happens to enzyme activity when temperature is too high?',
     'The enzyme speeds up indefinitely because more energy is available',
     'The enzyme becomes more specific to its substrate at high temperatures',
     'High temperatures break the bonds holding the enzyme\'s shape, changing the active site permanently — the enzyme is denatured and the substrate can no longer fit',
     'The enzyme slows down temporarily but recovers when temperature drops',
     'C',
     'Enzymes do not speed up indefinitely — above the optimum, activity falls. Denaturation is IRREVERSIBLE — the enzyme does not recover.',
     'Enzymes are proteins held in shape by weak hydrogen bonds. High temperature provides enough energy to break these bonds, changing the active site shape permanently (denaturation). The substrate no longer fits → no reaction.'),

    ('Biology', 'Enzymes', 3,
     'What happens to enzyme activity when temperature is too low?',
     'The enzyme is immediately denatured and stops working permanently',
     'The enzyme activity increases because cold preserves the enzyme',
     'The rate of reaction decreases because molecules move more slowly, reducing the frequency of successful collisions between enzyme and substrate',
     'The active site changes shape permanently so the substrate cannot bind',
     'C',
     'Denaturation does not occur at low temperatures — it happens at HIGH temperatures. Cold slows enzymes but does not permanently damage them.',
     'Low temperature reduces kinetic energy of molecules. Fewer enzyme-substrate collisions occur per second, so the rate of reaction decreases. The enzyme is NOT denatured — warm it up and activity returns.'),

    ('Biology', 'Enzymes', 3,
     'How does a change in pH affect enzyme activity?',
     'pH has no effect on enzymes because they are proteins not affected by acidity',
     'High pH always speeds up enzymes because alkaline conditions provide more energy',
     'Changing pH alters the charges on amino acids in the enzyme, disrupting the bonds that maintain the active site shape — the enzyme denatures and the substrate cannot bind',
     'Low pH speeds up enzymes because acid provides hydrogen ions for the reaction',
     'C',
     'pH directly affects the charge on amino acids and the bonds holding the enzyme\'s shape. Extreme pH — high or low — causes denaturation. pH does not provide energy.',
     'Each enzyme has an optimum pH. At other pH values, H⁺ or OH⁻ ions disrupt ionic and hydrogen bonds in the enzyme\'s 3D structure, changing the active site shape so the substrate no longer fits.'),

    ('Biology', 'Heart', 3,
     'How do stents treat coronary heart disease?',
     'They dissolve fatty plaques by releasing drugs directly into the artery wall',
     'A small metal mesh is inserted into a narrowed artery; a balloon inflates to expand the stent, holding the artery open and restoring blood flow',
     'They replace the blocked artery with a vein taken from the patient\'s leg',
     'They reduce cholesterol production in the liver, preventing further plaque build-up',
     'B',
     'Dissolving plaques with drugs is not how stents work. Replacing an artery with a vein is bypass surgery. Reducing cholesterol is what statins do.',
     'A stent is a metal mesh tube inserted via a catheter. When the balloon at its tip inflates at the narrow section, the stent expands and stays in place, keeping the artery permanently open and restoring normal blood flow.'),

    ('Biology', 'Digestion', 3,
     'Explain how amylase breaks down starch using the lock and key theory.',
     'Amylase randomly collides with starch and breaks it apart by releasing heat energy',
     'Starch fits into the active site of amylase (complementary shapes form an enzyme-substrate complex); bonds in the starch molecule are broken, producing simple sugars that can be absorbed into the bloodstream',
     'Amylase breaks starch by changing the pH of the digestive fluid around it',
     'Starch and amylase have the same shape so they repel each other, causing starch to break apart',
     'B',
     'Amylase is highly specific — it does not break starch randomly or through heat. The active site and substrate must be complementary, not the same shape.',
     'Lock and key: starch (substrate = key) fits the specific active site of amylase (lock). An enzyme-substrate complex forms. Bonds in starch break, releasing maltose/glucose. The enzyme is unchanged and can be reused.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Exam Challenge
    # ─────────────────────────────────────────────────────
    ('Biology', 'Heart', 4,
     'Evaluate the advantages and disadvantages of using statins compared to stents to treat cardiovascular disease.',
     'Statins and stents are identical in their mechanism and risks',
     'Stents work immediately to open blocked arteries and last a long time, but carry surgical risks (infection, blood clot). Statins reduce cholesterol over time and are non-invasive, but must be taken daily and may cause side effects such as muscle damage or liver problems',
     'Statins are always the better treatment because they have no side effects',
     'Stents are always the better treatment because they provide a permanent cure',
     'B',
     'Neither treatment is universally superior — the choice depends on severity of blockage, patient health, and risk factors.',
     'Stents: quick effect, long-lasting, but surgical risk of infection, thrombosis, and complications. Statins: no surgery needed, reduce LDL and raise HDL, but require daily use and can cause muscle pain, abdominal problems, or liver damage in some patients.'),

    ('Biology', 'Heart', 4,
     'A patient needs a new heart valve. Evaluate the choice between a mechanical valve and a biological (donor) valve.',
     'Mechanical valves are always preferable because they last longer and require no drugs',
     'Biological valves are always preferable because they require no surgery',
     'Mechanical valves are available quickly and do not cause rejection, but may cause blood clots requiring blood-thinning drugs. Biological valves can last a lifetime without drugs, but require a tissue-matched donor and carry a risk of rejection',
     'Both types of valve carry identical risks and benefits',
     'C',
     'Mechanical valves DO require blood-thinning drugs. Biological valves still require surgery — the difference is whether ongoing drug therapy is needed.',
     'Mechanical: readily available, no anti-rejection drugs, but risk of clotting → needs lifelong anticoagulants. Biological (from donor): can last longer without drugs, but need for anti-rejection medication, tissue matching, and donor wait time.'),

    ('Biology', 'Heart', 4,
     'Evaluate the use of an artificial heart as a treatment, compared to a heart transplant.',
     'An artificial heart is a permanent cure that is always better than a transplant',
     'An artificial heart is a temporary measure to keep the patient alive whilst awaiting a donor; it is less likely to be rejected (made of metal/plastic) but requires blood-thinning drugs. A transplant is a long-term fix but risks rejection and depends on donor availability',
     'A heart transplant carries no risks and should always be preferred over an artificial heart',
     'Artificial hearts are not used in medicine because they always cause infections',
     'B',
     'Artificial hearts are a TEMPORARY measure, not a permanent cure. Transplants do carry significant risks of rejection and infection.',
     'Artificial heart: less risk of rejection (non-biological), buys time for donor matching, but risk of blood clots/infection and requires anticoagulant drugs. Transplant: long-term or permanent solution, but risk of rejection, limited donor supply, and need for immunosuppressant drugs.'),

    ('Biology', 'Ecology', 4,
     'Explain why a fish may die in water with a very low concentration of dissolved oxygen.',
     'Low oxygen means the fish cannot swim fast enough to find food',
     'Low oxygen concentration in water reduces the concentration gradient across the gills, so less oxygen diffuses into the blood; the fish must rely on anaerobic respiration which produces toxic lactic acid and releases less energy',
     'Low oxygen causes the fish\'s gills to close, preventing all gas exchange',
     'Low oxygen increases the concentration of CO₂ in the water, which poisons the fish directly',
     'B',
     'Fish gills do not "close" in low oxygen. It is not CO₂ that directly poisons the fish — it is lactic acid from anaerobic respiration.',
     'Gills exchange gases by diffusion. Low dissolved O₂ → smaller concentration gradient → less O₂ diffuses into blood → insufficient aerobic respiration → anaerobic respiration → lactic acid builds up → cell damage and death.'),

    ('Biology', 'Digestion', 4,
     'Explain the full role of bile in digestion, including why both of its functions are important for efficient fat digestion.',
     'Bile breaks down proteins into amino acids and provides an acidic environment for pepsin',
     'Bile emulsifies fats into tiny droplets (increasing surface area for lipase) and neutralises stomach acid (providing alkaline conditions for lipase to work at its optimum pH)',
     'Bile directly digests fat molecules by breaking their chemical bonds',
     'Bile absorbs fat molecules directly through the intestine wall',
     'B',
     'Bile does not break down proteins — that is protease. Bile does not directly break chemical bonds in fat — that is lipase. Bile creates ALKALINE (not acidic) conditions.',
     'Bile emulsification: large fat globules → tiny droplets → greater surface area → lipase works faster. Bile neutralisation: stomach acid (pH 2) is neutralised to pH 7–8 in the small intestine — the optimum pH for lipase activity.'),

    ('Biology', 'Enzymes', 4,
     'A student investigates the effect of pH on the rate of amylase breaking down starch, using iodine in a spotting tile. Describe the method and explain how results would be interpreted.',
     'Mix amylase and starch at different temperatures; record colour change of Benedict\'s solution every 10 seconds',
     'Mix amylase with starch at the same temperature but in different pH buffers; add samples to iodine on a spotting tile every 15 seconds; the pH at which iodine turns yellow/brown fastest is the optimum pH for amylase',
     'Add different concentrations of amylase to starch; measure how quickly the solution clears',
     'Add amylase to glucose solutions at different pH values; measure CO₂ produced',
     'B',
     'The independent variable is pH, not temperature or concentration. Benedict\'s solution tests for glucose, not starch breakdown. Iodine is used here, not CO₂ measurement.',
     'Method: different pH buffers + amylase in test tubes; add starch; sample into iodine every 15 s. Iodine = blue-black with starch present; yellow-brown when starch fully broken down. Fastest colour change = optimum pH for amylase (around pH 7).'),

    ('Biology', 'Heart', 4,
     'Pros and cons of a heart transplant as a treatment for heart failure.',
     'A transplant is risk-free and always successful, making it the best treatment option',
     'A transplant is a long-term fix that can save a patient\'s life, but carries risks of immune rejection, infection, and is limited by the availability of compatible donors',
     'A transplant is only a temporary measure lasting a few years at most',
     'Transplants carry no risk of rejection because the immune system accepts all donated hearts',
     'B',
     'Transplants are NOT risk-free. They are intended as a long-term solution but rejection is a real risk. The immune system CAN reject donor organs.',
     'Advantages: long-term/potentially permanent fix, saves lives, restores full heart function. Disadvantages: risk of rejection (immune system attacks donor heart), risk of infection, limited donor supply, need for lifelong immunosuppressant drugs.'),
]


def add():
    db.init_db()
    conn = db.get_db()
    conn.executemany(
        '''INSERT INTO questions
           (subject, topic, difficulty, question_text,
            option_a, option_b, option_c, option_d,
            correct_answer, explanation, correction_tip)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)''',
        QUESTIONS
    )
    conn.commit()
    conn.close()
    print(f'Added {len(QUESTIONS)} new questions.')


if __name__ == '__main__':
    add()
