import database as db

QUESTIONS = [
    # ─────────────────────────────────────────────────────
    # BIOLOGY – Easy (1)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Cells', 1,
     'What is the function of the nucleus in a cell?',
     'To produce energy', 'To control cell activities',
     'To store water', 'To digest waste',
     'B',
     'The nucleus does not produce energy — that is the job of the mitochondria.',
     'Remember: the nucleus contains DNA and acts as the control centre of the cell.'),

    ('Biology', 'Cells', 1,
     'Which organelle is responsible for producing energy in a cell?',
     'Ribosome', 'Vacuole', 'Mitochondria', 'Chloroplast',
     'C',
     'Ribosomes make proteins; vacuoles store substances; chloroplasts are for photosynthesis.',
     'Mitochondria are the site of aerobic respiration, which releases energy for the cell.'),

    ('Biology', 'Photosynthesis', 1,
     'What gas do plants release as a product of photosynthesis?',
     'Carbon dioxide', 'Nitrogen', 'Hydrogen', 'Oxygen',
     'D',
     'Plants take in carbon dioxide and release oxygen — not the other way round.',
     'The equation is: carbon dioxide + water → glucose + oxygen (using light energy).'),

    ('Biology', 'Photosynthesis', 1,
     'Where does photosynthesis mainly take place in a plant cell?',
     'Mitochondria', 'Nucleus', 'Cell wall', 'Chloroplast',
     'D',
     'Mitochondria are for respiration; the nucleus stores DNA; the cell wall provides support.',
     'Chloroplasts contain chlorophyll, which absorbs light energy for photosynthesis.'),

    ('Biology', 'Blood', 1,
     'What is the main function of red blood cells?',
     'To fight infection', 'To produce hormones',
     'To carry oxygen around the body', 'To digest food',
     'C',
     'Fighting infection is mainly done by white blood cells.',
     'Red blood cells contain haemoglobin, which binds to oxygen and transports it around the body.'),

    ('Biology', 'Cells', 1,
     'Which of the following is found in a plant cell but NOT in an animal cell?',
     'Nucleus', 'Cell membrane', 'Mitochondria', 'Cell wall',
     'D',
     'Nuclei, cell membranes, and mitochondria are present in both plant and animal cells.',
     'Plant cells have a cell wall (made of cellulose), a vacuole, and chloroplasts — animal cells do not.'),

    ('Biology', 'Genetics', 1,
     'What is DNA?',
     'A type of protein', 'A molecule that carries genetic information',
     'A form of sugar', 'An enzyme',
     'B',
     'DNA is not a protein or sugar; it is a nucleic acid that stores genetic instructions.',
     'DNA (deoxyribonucleic acid) is a double-helix molecule that carries the instructions for building and running living organisms.'),

    ('Biology', 'Cells', 1,
     'What process allows substances to move from a high concentration to a low concentration without using energy?',
     'Active transport', 'Osmosis', 'Diffusion', 'Endocytosis',
     'C',
     'Active transport requires energy; osmosis specifically refers to the movement of water.',
     'Diffusion is the net movement of particles from a region of high concentration to low concentration — it is a passive process.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Medium (2)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Photosynthesis', 2,
     'Which factor would most directly limit the rate of photosynthesis on a cold, bright day?',
     'Light intensity', 'Carbon dioxide concentration', 'Temperature', 'Oxygen levels',
     'C',
     'On a bright day light is not limiting. Oxygen is a product, not a reactant.',
     'Low temperature slows enzyme activity, reducing the rate of photosynthesis even when light is plentiful.'),

    ('Biology', 'Cells', 2,
     'A student places a plant cell in a very concentrated salt solution. What happens?',
     'The cell swells and bursts', 'The cell becomes turgid',
     'The cell becomes plasmolysed', 'Nothing happens',
     'C',
     'Swelling and turgidity occur in dilute solutions; plant cells do not burst because of their cell wall.',
     'In a concentrated solution water leaves the cell by osmosis, the vacuole shrinks, and the membrane pulls away from the cell wall — this is plasmolysis.'),

    ('Biology', 'Genetics', 2,
     'What is the difference between mitosis and meiosis?',
     'Mitosis produces 4 cells; meiosis produces 2', 'Mitosis halves the chromosome number; meiosis doubles it',
     'Meiosis halves the chromosome number; mitosis keeps it the same', 'They are the same process',
     'C',
     'Mitosis produces two genetically identical cells with the same number of chromosomes as the parent.',
     'Meiosis produces four genetically different cells each with half the chromosome number — these become gametes.'),

    ('Biology', 'Digestion', 2,
     'Which enzyme breaks down proteins in the digestive system?',
     'Amylase', 'Lipase', 'Protease', 'Catalase',
     'C',
     'Amylase breaks down starch; lipase breaks down fats; catalase breaks down hydrogen peroxide.',
     'Proteases are enzymes that break down proteins into amino acids in the stomach and small intestine.'),

    ('Biology', 'Respiration', 2,
     'What are the products of aerobic respiration?',
     'Glucose and oxygen', 'Lactic acid and carbon dioxide',
     'Carbon dioxide and water', 'Ethanol and carbon dioxide',
     'C',
     'Lactic acid is a product of anaerobic respiration in animals; ethanol is from anaerobic respiration in yeast.',
     'Aerobic respiration: glucose + oxygen → carbon dioxide + water (+ energy released as ATP).'),

    ('Biology', 'Ecology', 2,
     'In a food chain, what do arrows represent?',
     'The direction energy travels from predator to prey',
     'The direction energy travels from prey to predator',
     'Which organism is larger',
     'How organisms compete for resources',
     'B',
     'Arrows point from prey TO predator, showing the direction that energy and matter flow.',
     'Each arrow in a food chain points from the organism being eaten to the organism eating it, showing energy transfer.'),

    ('Biology', 'Genetics', 2,
     'A parent has the genotype Bb. What is the probability that an offspring from two Bb parents will be homozygous dominant (BB)?',
     '25%', '50%', '75%', '100%',
     'A',
     'A Punnett square for Bb × Bb gives BB : Bb : bb = 1 : 2 : 1, so BB is 1 in 4 = 25%.',
     'Use a Punnett square: BB (25%), Bb (50%), bb (25%). Only 1 out of 4 outcomes is BB.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Hard (3)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Photosynthesis', 3,
     'A student increases light intensity but the rate of photosynthesis stops rising. Which explanation is correct?',
     'The plant has run out of chlorophyll',
     'Another factor such as CO2 concentration or temperature has become limiting',
     'Light intensity has no effect above a certain level',
     'The plant is respiring faster than it is photosynthesising',
     'B',
     'Chlorophyll is not used up. Light intensity does matter, but other factors can cap the rate.',
     'When one factor is in short supply it becomes the limiting factor. Increasing light further cannot help if CO2 or temperature is now the bottleneck.'),

    ('Biology', 'Respiration', 3,
     'During vigorous exercise the body switches to anaerobic respiration. What is the consequence of this in human muscle cells?',
     'ATP production increases significantly',
     'Glucose is converted to ethanol and carbon dioxide',
     'Lactic acid builds up in the muscles causing fatigue',
     'Oxygen consumption doubles',
     'C',
     'Ethanol production occurs in yeast, not human muscle cells. Anaerobic respiration produces less ATP, not more.',
     'In humans, anaerobic respiration converts glucose to lactic acid. Lactic acid accumulates in muscles, leading to fatigue and cramp.'),

    ('Biology', 'Genetics', 3,
     'A mutation occurs in a gamete. What is the most significant consequence?',
     'Only the organism itself is affected',
     'The mutation may be inherited by offspring',
     'The mutation cannot be passed on',
     'The organism immediately develops cancer',
     'B',
     'Somatic (body cell) mutations affect only that organism. Gamete mutations can be passed to the next generation.',
     'Because gametes fuse during fertilisation, any mutation in a gamete can be incorporated into every cell of the offspring.'),

    ('Biology', 'Homeostasis', 3,
     'How does the body reduce blood glucose levels after a meal?',
     'The pancreas releases glucagon, which converts glucose to glycogen',
     'The liver releases stored glycogen into the blood',
     'The pancreas releases insulin, which stimulates cells to take up glucose and the liver to store it as glycogen',
     'The kidneys filter excess glucose into the urine',
     'C',
     'Glucagon raises blood glucose. The liver releasing glycogen would also raise blood glucose.',
     'After a meal, insulin is released by the pancreas. It allows body cells to absorb glucose and signals the liver to convert glucose to glycogen for storage.'),

    ('Biology', 'Ecology', 3,
     'A student removes all foxes from an ecosystem. Which long-term change is most likely?',
     'The rabbit population increases indefinitely',
     'The rabbit population rises, then falls as food becomes scarce',
     'The plant population increases',
     'The fox population recovers immediately',
     'B',
     'Without a top predator, rabbits will not grow indefinitely — they will exhaust their food supply.',
     'With fewer predators the prey population initially booms, but overgrazing depletes vegetation, causing the prey population to crash due to starvation.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Exam Challenge (4)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Photosynthesis', 4,
     'In an investigation a student varies CO2 concentration and measures the rate of photosynthesis at two light intensities. At low light, increasing CO2 has no effect. At high light, increasing CO2 raises the rate. What conclusion best explains both results?',
     'CO2 is always the limiting factor regardless of light',
     'At low light, light is the limiting factor; at high light, CO2 is the limiting factor',
     'High light intensity destroys chlorophyll, so CO2 cannot be used',
     'CO2 only affects photosynthesis at high temperatures',
     'B',
     'If CO2 had no effect at low light it cannot be the limiting factor there. High light intensity does not destroy chlorophyll.',
     'When light is scarce it limits the reaction, so adding CO2 makes no difference. When light is plentiful, CO2 becomes the bottleneck — adding more CO2 then raises the rate.'),

    ('Biology', 'Genetics', 4,
     'Cystic fibrosis is caused by a recessive allele (f). Two carriers (Ff × Ff) have children. What is the probability their child will have cystic fibrosis AND be female, assuming equal sex probability?',
     '25%', '12.5%', '50%', '6.25%',
     'B',
     'The probability of cystic fibrosis (ff) is 25%. The probability of being female is 50%. These are independent events.',
     '25% (ff) × 50% (female) = 12.5%. You must multiply the independent probabilities together.'),

    ('Biology', 'Homeostasis', 4,
     'A patient has type 1 diabetes. Their blood glucose rises sharply after a meal and stays high. Evaluate which treatment is most appropriate and why.',
     'Diet alone can fully control blood glucose because insulin is not needed',
     'Glucagon injections will lower blood glucose after meals',
     'Insulin injections are required because the pancreas cannot produce insulin',
     'Exercise alone can restore normal blood glucose permanently',
     'C',
     'In type 1 diabetes the immune system destroys insulin-producing beta cells. Diet helps but cannot replace insulin. Glucagon raises blood glucose.',
     'Type 1 diabetics cannot produce insulin. Without it, cells cannot absorb glucose. Insulin injections (or a pump) are essential to regulate blood glucose after meals.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Easy (1)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Atoms', 1,
     'What is the charge of a proton?',
     'Negative', 'Neutral', 'Positive', 'Variable',
     'C',
     'Electrons are negative; neutrons are neutral; protons are positive.',
     'Protons have a charge of +1 and are found in the nucleus of an atom.'),

    ('Chemistry', 'Atoms', 1,
     'Where are electrons found in an atom?',
     'In the nucleus', 'In shells around the nucleus',
     'Randomly throughout the atom', 'Only on the surface',
     'B',
     'Protons and neutrons are in the nucleus; electrons orbit the nucleus in shells (energy levels).',
     'Electrons occupy energy levels (shells) around the nucleus. The first shell holds up to 2 electrons; the second and third shells hold up to 8.'),

    ('Chemistry', 'Periodic Table', 1,
     'Elements in the same GROUP of the periodic table have the same number of…',
     'Neutrons', 'Protons', 'Electrons in the outer shell', 'Electron shells',
     'C',
     'Periods share the same number of electron shells; groups share the same number of outer-shell electrons.',
     'Elements in the same group have the same number of outer-shell (valence) electrons, giving them similar chemical properties.'),

    ('Chemistry', 'Bonding', 1,
     'What type of bonding occurs between a metal and a non-metal?',
     'Covalent', 'Metallic', 'Ionic', 'Hydrogen',
     'C',
     'Covalent bonding is between non-metals; metallic bonding occurs in metals only.',
     'Ionic bonding involves the transfer of electrons from a metal to a non-metal, forming oppositely charged ions that attract each other.'),

    ('Chemistry', 'Reactions', 1,
     'What is the name of the process where a substance burns in oxygen to release energy?',
     'Electrolysis', 'Reduction', 'Combustion', 'Neutralisation',
     'C',
     'Electrolysis uses electricity; reduction involves gaining electrons; neutralisation is acid + base.',
     'Combustion is the reaction of a fuel with oxygen to release heat and light energy, producing carbon dioxide and water (complete combustion).'),

    ('Chemistry', 'Atoms', 1,
     'What does the atomic number of an element tell you?',
     'The number of neutrons in the nucleus',
     'The total mass of the atom',
     'The number of protons in the nucleus',
     'The number of electron shells',
     'C',
     'The mass number is the total of protons + neutrons. The atomic number is protons only.',
     'The atomic number is unique to each element and equals the number of protons (and electrons in a neutral atom).'),

    ('Chemistry', 'Periodic Table', 1,
     'Which group of the periodic table contains the noble gases?',
     'Group 1', 'Group 7', 'Group 0 (Group 18)', 'Group 2',
     'C',
     'Group 1 is the alkali metals; Group 7 is the halogens; Group 2 is the alkaline earth metals.',
     'Noble gases are in Group 0 (sometimes called Group 18). They have full outer electron shells and are very unreactive.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Medium (2)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Bonding', 2,
     'Why do ionic compounds have high melting points?',
     'They are made of small molecules',
     'They contain strong covalent bonds',
     'They have a giant lattice structure with strong electrostatic forces between ions',
     'Electrons can move freely',
     'C',
     'Small molecules have low melting points. Covalent bonds are in covalent compounds. Free electrons are a property of metals.',
     'Ionic compounds form giant lattice structures held together by strong electrostatic attraction between oppositely charged ions. Breaking this structure requires a large amount of energy.'),

    ('Chemistry', 'Reactions', 2,
     'In a neutralisation reaction between hydrochloric acid (HCl) and sodium hydroxide (NaOH), what are the products?',
     'Hydrogen gas and sodium chloride',
     'Sodium chloride and water',
     'Carbon dioxide and water',
     'Sodium oxide and hydrogen chloride',
     'B',
     'Hydrogen gas is not produced in neutralisation. CO2 is produced when an acid reacts with a carbonate.',
     'Acid + alkali → salt + water. HCl + NaOH → NaCl + H₂O. The salt formed is sodium chloride (common salt).'),

    ('Chemistry', 'Periodic Table', 2,
     'As you go down Group 1 (alkali metals), how does their reactivity change?',
     'It decreases', 'It stays the same', 'It increases', 'It becomes unpredictable',
     'C',
     'Group 1 reactivity increases down the group because the outer electron is further from the nucleus and more easily lost.',
     'Down Group 1, there are more electron shells so the outer electron experiences greater shielding and is further from the nucleus — it is lost more easily, increasing reactivity.'),

    ('Chemistry', 'Reactions', 2,
     'What does a catalyst do in a chemical reaction?',
     'It increases the amount of product formed',
     'It is used up during the reaction',
     'It provides an alternative reaction pathway with lower activation energy',
     'It changes the products of the reaction',
     'C',
     'A catalyst does not change the amount of product, is not consumed, and does not alter what products are made.',
     'A catalyst speeds up a reaction by providing a lower activation energy pathway. It is not consumed in the reaction and can be reused.'),

    ('Chemistry', 'Electrolysis', 2,
     'During electrolysis of copper sulfate solution, what is produced at the cathode?',
     'Oxygen gas', 'Sulfate ions', 'Copper metal', 'Hydrogen gas',
     'C',
     'Oxygen is produced at the anode. Sulfate ions are not discharged. Hydrogen is produced at the cathode with dilute sulfuric acid only if copper is absent.',
     'The cathode is the negative electrode. Positive copper ions (Cu²⁺) are attracted to it, gain electrons, and are deposited as copper metal.'),

    ('Chemistry', 'Bonding', 2,
     'Why does carbon dioxide (CO₂) have a low boiling point despite having strong covalent bonds?',
     'Because the covalent bonds are weak',
     'Because there are only weak intermolecular forces between CO₂ molecules',
     'Because CO₂ is an ionic compound',
     'Because CO₂ has a giant covalent structure',
     'B',
     'CO₂ has strong C=O covalent bonds, but these are intramolecular (within the molecule), not between molecules.',
     'Simple molecular substances have strong covalent bonds within molecules but only weak van der Waals forces between molecules. Little energy is needed to overcome these, giving a low boiling point.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Hard (3)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Reactions', 3,
     'Magnesium reacts with dilute hydrochloric acid. Which change would most increase the rate of reaction?',
     'Using larger pieces of magnesium',
     'Decreasing the acid concentration',
     'Increasing the temperature',
     'Using a less reactive metal',
     'C',
     'Larger pieces reduce surface area. Decreasing concentration and using a less reactive metal would slow the reaction.',
     'Increasing temperature increases the kinetic energy of particles, leading to more frequent and energetic collisions that exceed the activation energy.'),

    ('Chemistry', 'Equilibrium', 3,
     'In a reversible reaction at equilibrium, what happens when the temperature is increased?',
     'The equilibrium shifts to favour the exothermic direction',
     'The equilibrium shifts to favour the endothermic direction',
     'The reaction stops',
     'The equilibrium position does not change',
     'B',
     'Increasing temperature shifts the equilibrium to counteract the change — it favours the direction that absorbs heat (endothermic).',
     "By Le Chatelier's principle, increasing temperature causes the equilibrium to shift in the endothermic direction to absorb the extra energy."),

    ('Chemistry', 'Bonding', 3,
     'Diamond has a very high melting point. What structural feature explains this?',
     'It is a simple molecular structure with strong intermolecular forces',
     'It is a giant ionic lattice',
     'It is a giant covalent structure where every carbon atom forms four strong covalent bonds',
     'It contains delocalised electrons',
     'C',
     'Diamond is not ionic and not a simple molecule. Delocalised electrons are a feature of graphite and metals, not diamond.',
     'In diamond each carbon atom forms four covalent bonds in a giant 3D lattice. Melting requires breaking many strong covalent bonds, needing enormous amounts of energy.'),

    ('Chemistry', 'Moles', 3,
     'What mass of sodium hydroxide (NaOH) is needed to make 250 cm³ of a 2 mol/dm³ solution? (Mr of NaOH = 40)',
     '10 g', '20 g', '40 g', '80 g',
     'B',
     'Moles = concentration × volume (in dm³). 250 cm³ = 0.25 dm³. Moles = 2 × 0.25 = 0.5. Mass = 0.5 × 40 = 20 g.',
     'Step 1: Convert volume to dm³: 250/1000 = 0.25 dm³. Step 2: moles = 2 × 0.25 = 0.5 mol. Step 3: mass = 0.5 × 40 = 20 g.'),

    ('Chemistry', 'Reactions', 3,
     'In the Haber process, iron is used as a catalyst. What effect does this have on the equilibrium yield of ammonia?',
     'It increases the equilibrium yield',
     'It decreases the equilibrium yield',
     'It has no effect on the equilibrium yield but speeds up how quickly equilibrium is reached',
     'It shifts the equilibrium to the right permanently',
     'C',
     'Catalysts do not change the position of equilibrium — they speed up both the forward and reverse reactions equally.',
     'A catalyst lowers activation energy for both the forward and reverse reactions, so equilibrium is reached faster. The actual proportion of ammonia at equilibrium is unchanged.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Exam Challenge (4)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Reactions', 4,
     'A student investigates the effect of surface area on the rate of reaction between marble chips and dilute HCl. She uses equal masses of large and powdered chips. Which result would she expect, and why?',
     'Same rate; mass is the same so the same amount reacts',
     'Slower rate with powder; smaller particles have less surface area',
     'Faster rate with powder; more surface area means more collisions per second',
     'Faster rate with large chips; larger particles react more vigorously',
     'C',
     'Equal mass does not mean equal surface area. Smaller particles expose more surface area, not less. Large chips have less surface area per unit mass.',
     'Powdering the marble greatly increases the surface area, exposing more particles to acid. More frequent successful collisions per second means a faster rate of reaction.'),

    ('Chemistry', 'Electrolysis', 4,
     'In the electrolysis of brine (sodium chloride solution), what is produced at the anode and why?',
     'Hydrogen, because H⁺ ions are attracted to the positive electrode',
     'Chlorine, because Cl⁻ ions are discharged at the positive electrode despite hydroxide ions also being present',
     'Oxygen, because water is oxidised at the anode',
     'Sodium, because Na⁺ ions are reduced at the anode',
     'B',
     'Hydrogen is produced at the cathode, not anode. Sodium is not produced in solution — it would react with water. Oxygen is produced with dilute solutions, but concentrated brine preferentially discharges Cl⁻.',
     'At the anode (positive), negative ions are discharged. In concentrated brine Cl⁻ ions are preferentially discharged over OH⁻ ions, producing chlorine gas (Cl₂).'),

    ('Chemistry', 'Bonding', 4,
     'Graphite conducts electricity but diamond does not, even though both are made of carbon. Explain why.',
     'Graphite has ionic bonds; diamond has covalent bonds',
     'In graphite each carbon forms only three covalent bonds, leaving one delocalised electron per atom that can carry charge; in diamond all four electrons are in covalent bonds',
     'Diamond is denser so electrons cannot move',
     'Graphite is a metal; diamond is a non-metal',
     'B',
     'Both graphite and diamond are non-metals with covalent bonds. Density does not determine conductivity. The key difference is the number of bonds and whether electrons are delocalised.',
     'Graphite has layered hexagonal rings; each carbon bonds to three others, leaving one electron per atom delocalised between layers. These free electrons carry electrical charge. Diamond has no free electrons.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Easy (1)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Forces', 1,
     'What is the unit of force?',
     'Joule', 'Watt', 'Newton', 'Pascal',
     'C',
     'Joules measure energy; Watts measure power; Pascals measure pressure.',
     'Force is measured in Newtons (N), named after Isaac Newton. 1 N is the force needed to accelerate 1 kg by 1 m/s².'),

    ('Physics', 'Energy', 1,
     'What type of energy does a moving object have?',
     'Potential energy', 'Thermal energy', 'Kinetic energy', 'Chemical energy',
     'C',
     'Potential energy is stored energy (e.g., height); thermal energy relates to temperature; chemical energy is stored in bonds.',
     'Kinetic energy (KE) is the energy an object has due to its motion. KE = ½mv².'),

    ('Physics', 'Electricity', 1,
     'What is the unit of electrical resistance?',
     'Volt', 'Ampere', 'Watt', 'Ohm',
     'D',
     'Volts measure voltage; Amperes measure current; Watts measure power.',
     'Resistance is measured in Ohms (Ω). Ohm\'s law states: V = I × R.'),

    ('Physics', 'Waves', 1,
     'What type of wave is a sound wave?',
     'Transverse', 'Electromagnetic', 'Longitudinal', 'Seismic',
     'C',
     'Transverse waves (e.g., light) vibrate perpendicular to the direction of travel. Electromagnetic waves can travel through a vacuum; sound cannot.',
     'Sound waves are longitudinal — the particles vibrate parallel to (along) the direction of wave travel, creating compressions and rarefactions.'),

    ('Physics', 'Forces', 1,
     'According to Newton\'s first law, what happens to an object with no resultant force acting on it?',
     'It accelerates', 'It decelerates', 'It remains at rest or continues at constant velocity', 'It falls',
     'C',
     'A resultant force is needed to cause acceleration or deceleration.',
     'Newton\'s first law: an object stays at rest or moves at constant velocity unless acted on by a resultant (unbalanced) force.'),

    ('Physics', 'Energy', 1,
     'Which of the following is a renewable energy source?',
     'Coal', 'Natural gas', 'Nuclear', 'Wind',
     'D',
     'Coal, natural gas, and nuclear all use finite resources (coal and gas are fossil fuels; nuclear uses uranium).',
     'Wind energy is renewable because it is continuously replenished by natural processes and will not run out.'),

    ('Physics', 'Electricity', 1,
     'In a series circuit, what happens to the current at different points?',
     'It is different at each component', 'It is the same throughout', 'It doubles at each component', 'It is zero',
     'B',
     'Current varies at different points only in a parallel circuit.',
     'In a series circuit there is only one path for current to flow, so the current is the same at every point in the circuit.'),

    ('Physics', 'Waves', 1,
     'What is the relationship between wave speed, frequency, and wavelength?',
     'Speed = frequency ÷ wavelength',
     'Speed = frequency × wavelength',
     'Speed = wavelength ÷ frequency',
     'Frequency = speed × wavelength',
     'B',
     'The wave equation is v = f × λ (speed = frequency × wavelength).',
     'Wave speed (v) = frequency (f) × wavelength (λ). If frequency doubles and speed stays constant, wavelength halves.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Medium (2)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Forces', 2,
     'A car of mass 1,000 kg accelerates at 3 m/s². What is the resultant force on the car?',
     '333 N', '1,003 N', '3,000 N', '300 N',
     'C',
     'F = ma. F = 1000 × 3 = 3000 N. Dividing gives the wrong formula.',
     'Newton\'s second law: F = ma. F = 1000 kg × 3 m/s² = 3000 N.'),

    ('Physics', 'Energy', 2,
     'A 2 kg ball is lifted 5 m above the ground. What is its gravitational potential energy? (g = 10 N/kg)',
     '10 J', '50 J', '100 J', '25 J',
     'C',
     'GPE = mgh = 2 × 10 × 5 = 100 J. Multiplying only two values gives the wrong answer.',
     'Gravitational potential energy: GPE = m × g × h = 2 × 10 × 5 = 100 J.'),

    ('Physics', 'Electricity', 2,
     'A resistor has a voltage of 12 V across it and a current of 3 A through it. What is its resistance?',
     '36 Ω', '4 Ω', '9 Ω', '15 Ω',
     'B',
     'R = V/I = 12/3 = 4 Ω. V × I = power, not resistance.',
     "Ohm's law: R = V ÷ I = 12 ÷ 3 = 4 Ω."),

    ('Physics', 'Waves', 2,
     'A wave has a frequency of 500 Hz and a wavelength of 0.68 m. What is its speed?',
     '735 m/s', '340 m/s', '0.00136 m/s', '1000 m/s',
     'B',
     'v = f × λ = 500 × 0.68 = 340 m/s. This is the speed of sound in air.',
     'v = f × λ = 500 Hz × 0.68 m = 340 m/s. This is approximately the speed of sound in air at room temperature.'),

    ('Physics', 'Forces', 2,
     'A skydiver reaches terminal velocity. What does this mean about the forces acting on them?',
     'Gravity is greater than air resistance',
     'Air resistance is greater than gravity',
     'Gravity equals air resistance so the resultant force is zero',
     'There are no forces acting on them',
     'C',
     'At terminal velocity the skydiver is still falling — they are not weightless. Forces are balanced, not absent.',
     'Terminal velocity occurs when air resistance equals the weight (gravitational force). The resultant force is zero, so there is no acceleration — the skydiver falls at a constant speed.'),

    ('Physics', 'Thermal', 2,
     'Which method of heat transfer requires a medium (cannot occur through a vacuum)?',
     'Radiation', 'Conduction', 'Convection', 'Both conduction and convection',
     'D',
     'Radiation can travel through a vacuum (e.g., the Sun warming the Earth). Conduction and convection both need particles.',
     'Conduction requires particle-to-particle vibration transfer; convection requires fluid particles to circulate. Neither can occur in a vacuum. Radiation (infrared) can travel through empty space.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Hard (3)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Forces', 3,
     'A 500 g ball is dropped from rest and falls 20 m (g = 10 m/s²). Assuming no air resistance, what is its speed just before hitting the ground?',
     '10 m/s', '20 m/s', '100 m/s', '200 m/s',
     'B',
     'Use v² = u² + 2as. v² = 0 + 2 × 10 × 20 = 400, so v = 20 m/s. The mass is not needed here.',
     'v² = u² + 2as → v² = 0 + 2 × 10 × 20 = 400 → v = √400 = 20 m/s. You can also use energy: KE = GPE → ½mv² = mgh → v = √(2gh) = √400 = 20 m/s.'),

    ('Physics', 'Electricity', 3,
     'A 60 W lamp is used for 2 minutes. What is the energy transferred in joules?',
     '120 J', '43,200 J', '7,200 J', '30 J',
     'C',
     'E = P × t, where t must be in seconds. 2 minutes = 120 s. E = 60 × 120 = 7,200 J. Not 2 hours.',
     'E = P × t = 60 W × 120 s = 7,200 J. Always convert time to seconds (1 minute = 60 s).'),

    ('Physics', 'Nuclear', 3,
     'What happens to the atomic number and mass number of a nucleus when it emits a beta particle?',
     'Atomic number increases by 1; mass number is unchanged',
     'Atomic number decreases by 2; mass number decreases by 4',
     'Atomic number is unchanged; mass number decreases by 1',
     'Atomic number decreases by 1; mass number is unchanged',
     'A',
     'Alpha emission: atomic number –2, mass number –4. In beta decay a neutron becomes a proton, so atomic number rises by 1 but mass number stays the same.',
     'Beta decay: a neutron in the nucleus converts to a proton and an electron. The electron is emitted as the beta particle. Atomic number +1, mass number unchanged.'),

    ('Physics', 'Waves', 3,
     'A student measures the refractive index of glass as 1.5. What does this mean?',
     'Light travels 1.5 times faster in glass than in air',
     'Light bends 1.5 degrees when entering glass',
     'Light travels 1.5 times slower in glass than in air',
     'The glass absorbs 1.5% of the light',
     'C',
     'A refractive index greater than 1 means light slows down, not speeds up. Refractive index is not measured in degrees.',
     'Refractive index n = speed of light in vacuum / speed of light in medium. n = 1.5 means light travels at 1/1.5 ≈ 0.67 times its vacuum speed in the glass.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Exam Challenge (4)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Forces', 4,
     'A car travelling at 20 m/s brakes and stops in 50 m. Calculate the deceleration and the braking force if the car has a mass of 1200 kg.',
     'a = 4 m/s², F = 4800 N',
     'a = 8 m/s², F = 9600 N',
     'a = 2 m/s², F = 2400 N',
     'a = 0.4 m/s², F = 480 N',
     'A',
     'Use v² = u² + 2as: 0 = 400 + 100a → a = –4 m/s². F = ma = 1200 × 4 = 4800 N.',
     'v² = u² + 2as → 0 = 20² + 2×a×50 → a = –400/100 = –4 m/s² (deceleration = 4 m/s²). F = ma = 1200 × 4 = 4800 N.'),

    ('Physics', 'Energy', 4,
     'A pumped-storage power station is 80% efficient. It uses 500,000 J of electrical energy to pump water uphill. How much gravitational potential energy is stored?',
     '625,000 J', '400,000 J', '100,000 J', '500,000 J',
     'B',
     'Efficiency = useful output / total input. Useful GPE = 0.80 × 500,000 = 400,000 J.',
     'Efficiency = useful energy output / total energy input. 80% = 0.80. GPE stored = 0.80 × 500,000 = 400,000 J.'),

    ('Physics', 'Nuclear', 4,
     'Evaluate nuclear power as a low-carbon energy source. Which statement is most balanced and scientifically accurate?',
     'Nuclear power emits no greenhouse gases and has no risks, making it ideal',
     'Nuclear power produces no direct CO₂ during operation but generates radioactive waste that must be stored safely for thousands of years',
     'Nuclear power is as polluting as coal because it releases CO₂',
     'Nuclear power is renewable because uranium is widely available',
     'B',
     'Nuclear does not emit CO₂ during operation, but radioactive waste is a real and significant concern. Uranium is a finite resource so nuclear is not renewable.',
     'Nuclear fission releases large amounts of energy with minimal CO₂ emissions during operation. However, it produces long-lived radioactive waste requiring secure long-term storage, and there are risks of accidents. Uranium is finite so it is not classed as renewable.'),
]


EXTRA_QUESTIONS = [
    # ─────────────────────────────────────────────────────
    # BIOLOGY – Easy (2 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Infection', 1,
     'What type of pathogen causes influenza (flu)?',
     'Fungus', 'Bacterium', 'Protozoan', 'Virus',
     'D',
     'Influenza is not caused by a fungus, bacterium, or protozoan.',
     'Influenza is caused by a virus — a non-living pathogen that reproduces only inside host cells. Other examples of viral diseases include COVID-19 and HIV.'),

    ('Biology', 'Hormones', 1,
     'Which organ produces the hormone insulin?',
     'Liver', 'Kidney', 'Stomach', 'Pancreas',
     'D',
     'The liver stores glycogen; the kidneys filter blood; the stomach produces digestive enzymes.',
     'The pancreas produces insulin (and glucagon). Insulin is released when blood glucose rises and stimulates cells to absorb glucose.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Medium (3 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Food tests', 2,
     'A student adds Biuret reagent to a food sample and the solution turns purple. What substance is present?',
     'Starch', 'Reducing sugar', 'Lipid', 'Protein',
     'D',
     'Iodine tests for starch (blue-black result); Benedict\'s tests for reducing sugars (brick-red); Sudan III tests for lipids (red layer).',
     'Biuret reagent turns purple/lilac in the presence of protein. A blue result means no protein was detected.'),

    ('Biology', 'Nervous system', 2,
     'In a reflex action, which type of neuron carries the impulse from the receptor to the spinal cord?',
     'Motor neuron', 'Relay neuron', 'Sensory neuron', 'Effector',
     'C',
     'Motor neurons carry impulses FROM the CNS to effectors; relay neurons connect neurons within the CNS; effectors are muscles or glands, not neurons.',
     'Reflex arc order: receptor → sensory neuron → relay neuron (in spinal cord) → motor neuron → effector.'),

    ('Biology', 'Plant hormones', 2,
     'Which plant hormone causes shoots to bend towards a light source?',
     'Glucagon', 'Gibberellin', 'Auxin', 'Adrenaline',
     'C',
     'Glucagon and adrenaline are animal hormones. Gibberellins affect germination and stem elongation, not directional bending towards light.',
     'Auxin causes cell elongation. In phototropism it accumulates on the shaded side, making those cells elongate more and bending the shoot towards the light.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Hard (5 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Enzymes', 3,
     'An enzyme is heated to 80 °C. What happens and why?',
     'The enzyme is denatured — the active site permanently changes shape so the substrate can no longer fit',
     'The enzyme speeds up indefinitely due to increased kinetic energy',
     'The enzyme becomes more specific to its substrate',
     'The enzyme is unaffected because proteins are heat-stable',
     'A',
     'Above the optimum temperature, hydrogen bonds maintaining the enzyme\'s 3D shape break permanently.',
     'Denaturation is irreversible. The active site loses its specific shape, so the substrate cannot bind and no products are formed.'),

    ('Biology', 'Nervous system', 3,
     'What is the correct sequence of structures in a reflex arc?',
     'Receptor → motor neuron → relay neuron → sensory neuron → effector',
     'Receptor → sensory neuron → relay neuron → motor neuron → effector',
     'Effector → sensory neuron → brain → motor neuron → receptor',
     'Brain → relay neuron → sensory neuron → motor neuron → receptor',
     'B',
     'The signal always travels from receptor through the sensory neuron first, never the motor neuron first.',
     'Receptor detects stimulus → sensory neuron carries signal to spinal cord → relay neuron connects → motor neuron carries signal → effector (muscle or gland) responds.'),

    ('Biology', 'Homeostasis', 3,
     'ADH is released when blood water level is too low. What is its effect on the kidneys?',
     'The kidney tubules become more permeable to water, reabsorbing more water and producing small amounts of concentrated urine',
     'The kidneys produce more dilute urine to re-dilute the blood',
     'The kidneys filter more blood per minute',
     'ADH has no effect on the kidneys',
     'A',
     'When blood water is low the body needs to retain water — producing more urine would worsen the problem.',
     'ADH (from the pituitary gland) makes collecting ducts more permeable to water. More water is reabsorbed into the blood, producing less but more concentrated urine.'),

    ('Biology', 'Ecology', 3,
     'Why does a pyramid of biomass narrow at higher trophic levels?',
     'Predators are always smaller in body size than prey',
     'Organisms at higher levels reproduce more slowly',
     'Energy is lost as heat and in waste at each trophic level, so less biomass can be supported',
     'Higher trophic levels receive more energy directly from the Sun',
     'C',
     'Body size and reproduction rate do not explain the narrowing. Only producers receive energy directly from the Sun.',
     'Only about 10% of energy is transferred from one trophic level to the next. The rest is lost through respiration (heat) and excretion. Less energy means less biomass can be sustained.'),

    ('Biology', 'Variation', 3,
     'Identical twins are raised in different environments and develop different heights. What does this demonstrate?',
     'Genes are the only factor determining height',
     'Both genes and environmental factors influence phenotype',
     'The environment has no effect on genetically determined traits',
     'Identical twins must always have different heights',
     'B',
     'If genes were the only factor, identical twins (who share 100% of their DNA) would always be the same height.',
     'Identical twins share the same genotype. Any phenotypic difference (such as height) must result from environmental factors like diet, exercise, and illness. Phenotype = genes + environment.'),

    # ─────────────────────────────────────────────────────
    # BIOLOGY – Exam Challenge (7 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Biology', 'Genetics', 4,
     'Two heterozygous tall pea plants (Tt × Tt) are crossed. Using a Punnett square, what is the expected ratio of tall to short offspring? (T is dominant)',
     '1 tall : 1 short',
     'All tall',
     '3 tall : 1 short',
     '1 tall : 3 short',
     'C',
     'Tt × Tt gives TT (25%), Tt (50%), tt (25%). TT and Tt are both tall (T is dominant) so 75% are tall.',
     'Punnett square: TT (25%), Tt (50%), tt (25%). Any plant with at least one T allele is tall → 3 tall : 1 short.'),

    ('Biology', 'Enzymes', 4,
     'A student investigates pH and enzyme activity. The enzyme works fastest at pH 7 and stops working at pH 2 and pH 11. What is the full explanation?',
     'pH changes the concentration of substrate, not the enzyme itself',
     'At pH 7 the active site is the optimal shape; at extreme pH values ionic bonds are disrupted, denaturing the enzyme and changing the active site shape so the substrate cannot bind',
     'At pH 2 there is not enough substrate to keep the reaction going',
     'At extreme pH values the enzyme becomes faster but produces the wrong products',
     'B',
     'pH affects enzyme structure directly, not substrate concentration. Extreme pH causes denaturation, not faster reactions.',
     'Each enzyme has an optimum pH. At extreme pH values, H⁺ or OH⁻ ions disrupt ionic bonds and hydrogen bonds in the enzyme\'s tertiary structure. The active site changes shape (denaturation) — the substrate no longer fits.'),

    ('Biology', 'Infection', 4,
     'Explain how the immune system responds to a new pathogen, and why a second infection is defeated more quickly.',
     'The body produces antibodies immediately because it already has memory cells from birth',
     'B-lymphocytes produce specific antibodies on first infection (slow); memory cells remain. On second infection, memory cells rapidly produce large quantities of antibodies before symptoms develop',
     'Phagocytes engulf all pathogens on first infection and no immunological memory is formed',
     'Antibodies are non-specific and attack all pathogens equally on first and second infection',
     'B',
     'Memory cells are formed AFTER first exposure — they cannot exist before the first infection.',
     'Primary response: B-lymphocytes are activated slowly, producing antibodies; memory cells form. Secondary response: memory cells rapidly clone and produce high antibody levels, clearing the pathogen before illness develops. This is the basis of vaccination.'),

    ('Biology', 'Ecology', 4,
     'Wolves are reintroduced to a national park. Which chain of effects is most scientifically likely?',
     'Wolf numbers decline immediately because there is no prey',
     'Deer numbers increase because wolves compete with other predators only',
     'Deer population falls; vegetation recovers; river bank erosion decreases as plant roots stabilise soil',
     'All herbivore species decline because wolves compete with them for food',
     'C',
     'Wolves prey on deer, not other predators. Wolves do not eat plants, so herbivory competition is incorrect.',
     'This is a trophic cascade: wolves reduce deer overgrazing → vegetation recovers → plant roots stabilise river banks. This was observed when wolves were reintroduced to Yellowstone National Park.'),

    ('Biology', 'Homeostasis', 4,
     'A marathon runner\'s blood glucose falls well below normal. Which hormonal response occurs and what is its effect?',
     'Insulin is released, stimulating cells to absorb more glucose from the blood',
     'Glucagon is released by the pancreas, stimulating the liver to convert glycogen to glucose',
     'Adrenaline causes the kidneys to filter glucose back into the blood',
     'ADH is released, increasing blood glucose by reabsorbing it in the kidney tubules',
     'B',
     'Insulin lowers blood glucose — releasing it when glucose is already low would be dangerous. ADH controls water balance. Kidneys do not produce glucose.',
     'When blood glucose falls, the pancreas releases glucagon. Glucagon signals the liver to break down glycogen stores into glucose (glycogenolysis) and release it into the blood.'),

    ('Biology', 'Evolution', 4,
     'Antibiotic resistance in bacteria is increasing. Which explanation is most scientifically accurate?',
     'Bacteria deliberately mutate their DNA when they detect antibiotics',
     'Overuse of antibiotics causes all bacteria to simultaneously change their DNA',
     'Random mutations naturally arise; bacteria with resistance survive antibiotic treatment and reproduce, passing on resistance — this is natural selection',
     'Resistance is caused solely by patients not completing their antibiotic course',
     'C',
     'Bacteria cannot deliberately mutate. All bacteria do not change simultaneously. Not completing a course is a contributing factor but not the full explanation.',
     'Random mutations occur constantly. When antibiotics are applied, non-resistant bacteria die but resistant bacteria survive and reproduce, passing on resistance genes. The resistant allele spreads through the population by natural selection.'),

    ('Biology', 'Cell biology', 4,
     'Mineral ion concentration is often higher inside root cells than in the surrounding soil. Why is active transport needed rather than diffusion?',
     'Diffusion always moves substances in the wrong direction for all substances',
     'Mineral ions are too large to pass through the cell membrane by diffusion',
     'Active transport moves ions against their concentration gradient using ATP energy; diffusion would move ions in the wrong direction (out of the cell)',
     'Root hair cells lack membranes so diffusion cannot occur at all',
     'C',
     'Diffusion moves substances down a concentration gradient — if ions are more concentrated inside the cell, diffusion would move them OUT. Ions are not too large for membranes; water and small ions diffuse readily.',
     'Active transport uses ATP (from respiration) to carry mineral ions against their concentration gradient — from low concentration in soil to higher concentration inside the root cell. Diffusion cannot achieve this.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Easy (3 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Separation', 1,
     'Which technique is used to separate a mixture of different coloured inks?',
     'Filtration', 'Distillation', 'Chromatography', 'Crystallisation',
     'C',
     'Filtration separates insoluble solids from liquids; distillation separates liquids with different boiling points; crystallisation separates a dissolved solid from solution.',
     'Chromatography separates dissolved substances based on how far they travel up paper with a solvent. Different dyes travel different distances.'),

    ('Chemistry', 'Reactions', 1,
     'What type of reaction produces a salt and water?',
     'Combustion', 'Neutralisation', 'Electrolysis', 'Oxidation',
     'B',
     'Combustion produces CO₂ and H₂O (from burning a fuel, not a base). Electrolysis separates compounds. Oxidation involves gaining oxygen or losing electrons.',
     'Neutralisation: acid + base → salt + water. The specific salt depends on which acid and base are used.'),

    ('Chemistry', 'Atoms', 1,
     'An atom has 6 protons and 6 neutrons. What is its mass number?',
     '6', '12', '18', '3',
     'B',
     'Mass number = protons + neutrons = 6 + 6 = 12. The mass number is NOT just the number of protons (that is the atomic number).',
     'Mass number = protons + neutrons. For carbon-12: 6 + 6 = 12. The number of electrons does not contribute to mass number.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Medium (4 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Equations', 2,
     'In the equation 2H₂ + O₂ → 2H₂O, what does the coefficient "2" in front of H₂O tell you?',
     'There are 2 oxygen atoms in each water molecule',
     'The reaction is exothermic',
     'There are 2 moles of water produced for every mole of oxygen that reacts',
     'Water is a liquid product',
     'C',
     'The coefficient gives the number of moles, not the number of atoms in one molecule. The reaction being exothermic is a separate fact.',
     'Coefficients in balanced equations represent the number of moles (or molecules). 2H₂O means 2 moles of water are produced.'),

    ('Chemistry', 'Energy changes', 2,
     'In an exothermic reaction, how does the energy of the products compare to the energy of the reactants?',
     'Products have more energy; energy is absorbed from the surroundings',
     'Products and reactants have exactly equal energy',
     'Products have less energy than reactants — energy is released to the surroundings',
     'The temperature of the mixture always decreases',
     'C',
     'If energy is released to the surroundings, the products must end up at a lower energy level. Temperature increases (not decreases) in exothermic reactions.',
     'Exothermic reactions release energy to the surroundings (temperature rises). Energy is conserved: reactants have more energy → products + released energy. Bond breaking absorbs energy; bond making releases energy.'),

    ('Chemistry', 'Organic chemistry', 2,
     'What is the general formula for alkanes?',
     'CₙH₂ₙ', 'CₙH₂ₙ₊₂', 'CₙH₂ₙ₋₂', 'CₙHₙ',
     'B',
     'CₙH₂ₙ is for alkenes (one C=C double bond). CₙH₂ₙ₋₂ contains two degrees of unsaturation (e.g. alkynes).',
     'Alkanes: CₙH₂ₙ₊₂. Examples — methane CH₄ (n=1), ethane C₂H₆ (n=2), propane C₃H₈ (n=3). They are saturated (no double bonds).'),

    ('Chemistry', 'Periodic table', 2,
     'Why are noble gases (Group 0) so unreactive?',
     'They are too large to react with other atoms',
     'They have a full outer electron shell, giving a very stable electronic configuration',
     'They are all gases at room temperature',
     'They have very low density',
     'B',
     'Atomic size and density are not the reason for low reactivity. Being a gas is a result of weak intermolecular forces, not the cause of chemical stability.',
     'Noble gases have a full outer electron shell (2 for helium, 8 for the rest). This complete arrangement is very stable — they have no tendency to gain, lose, or share electrons in chemical reactions.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Hard (5 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Moles', 3,
     'In an experiment, 4.8 g of magnesium oxide is produced. The theoretical yield was 8.0 g. What is the percentage yield?',
     '40%', '60%', '80%', '166%',
     'B',
     'Percentage yield = (actual ÷ theoretical) × 100 = (4.8 ÷ 8.0) × 100 = 60%. 40% would mean only 3.2 g was produced.',
     'Percentage yield = (actual yield ÷ theoretical yield) × 100 = (4.8 ÷ 8.0) × 100 = 60%. Yields are less than 100% due to incomplete reactions or losses during purification.'),

    ('Chemistry', 'Organic chemistry', 3,
     'What functional group is present in all alcohols?',
     '-COOH (carboxyl)', '-OH (hydroxyl)', '-NH₂ (amine)', '-CHO (aldehyde)',
     'B',
     '-COOH is the carboxylic acid group; -NH₂ is the amine group; -CHO is the aldehyde group.',
     'Alcohols always contain the hydroxyl group (-OH). Examples: methanol (CH₃OH), ethanol (C₂H₅OH), propan-1-ol (C₃H₇OH).'),

    ('Chemistry', 'Reactivity series', 3,
     'Zinc powder is added to copper sulfate solution. What type of reaction occurs and what would you observe?',
     'Endothermic precipitation — the solution turns blue and a white solid forms',
     'Displacement reaction — the blue solution fades and a brown solid (copper) forms on the zinc',
     'Neutralisation — gas bubbles are produced and the solution turns red',
     'Oxidation only — the zinc dissolves with no visible colour change',
     'B',
     'The blue colour fades because Cu²⁺ ions are removed from solution. Zinc is more reactive than copper so it displaces it.',
     'Zn + CuSO₄ → ZnSO₄ + Cu. Zinc displaces copper because it is higher in the reactivity series. The blue colour (Cu²⁺) fades and brown copper metal is deposited.'),

    ('Chemistry', 'Atmosphere', 3,
     'Since the Industrial Revolution, atmospheric CO₂ levels have risen significantly. Which human activities are most responsible?',
     'Increased nuclear power generation and deforestation',
     'Burning fossil fuels and deforestation',
     'Volcanic activity and ocean evaporation',
     'Use of CFCs and nitrogen fertilisers only',
     'B',
     'Nuclear power generates very little CO₂. Volcanic activity and ocean evaporation are natural, not human, sources. CFCs damage the ozone layer rather than increasing CO₂.',
     'Burning fossil fuels releases CO₂ stored for millions of years. Deforestation removes trees that absorb CO₂ through photosynthesis. Both significantly raise atmospheric CO₂ and contribute to climate change.'),

    ('Chemistry', 'Bonding', 3,
     'Sodium chloride does not conduct electricity as a solid, but does when molten or dissolved in water. Why?',
     'Solid NaCl has covalent bonds that break on heating',
     'When solid, ions are fixed in the lattice and cannot move; when molten or dissolved, ions are free to move and carry electrical charge',
     'NaCl gains electrons when dissolved in water, creating conducting species',
     'Water reacts with NaCl to form a new conducting compound',
     'B',
     'NaCl has ionic bonds, not covalent bonds. Dissolving in water does not create new compounds — it dissociates the existing ions.',
     'Electrical conductivity requires free-moving charged particles. In solid NaCl, ions are locked in the lattice. Melting or dissolving breaks the lattice structure and frees ions to move towards electrodes.'),

    # ─────────────────────────────────────────────────────
    # CHEMISTRY – Exam Challenge (7 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Chemistry', 'Rates', 4,
     'A student doubles the concentration of sodium thiosulfate in a reaction with HCl and the time for the mixture to turn cloudy halves. What conclusion can be drawn?',
     'Doubling concentration has no measurable effect on rate',
     'Halving the time means the rate has halved',
     'Doubling concentration doubles the rate — more particles in the same volume means more frequent collisions',
     'The reaction is endothermic when concentration increases',
     'C',
     'If time halves, rate doubles (rate ∝ 1/time). Halving time means the rate has DOUBLED, not halved.',
     'Rate = 1/time. If time halves, rate doubles. Higher concentration means more particles per unit volume, so collisions are more frequent and the rate of successful collisions increases.'),

    ('Chemistry', 'Electrolysis', 4,
     'In industrial aluminium extraction, aluminium oxide is dissolved in molten cryolite rather than just melted. Why?',
     'Cryolite reacts with aluminium oxide to produce pure aluminium directly',
     'Al₂O₃ has a very high melting point (~2050 °C); dissolving it in cryolite lowers the operating temperature to ~950 °C, saving significant energy costs',
     'Cryolite provides additional aluminium ions for a greater yield',
     'Molten cryolite acts as the anode in the electrolysis cell',
     'B',
     'Cryolite does not react with Al₂O₃ or provide Al ions. The electrodes (anodes) are carbon, not cryolite.',
     'Melting Al₂O₃ alone would require over 2000 °C — extremely expensive. Dissolving in cryolite brings the temperature down to ~950 °C while maintaining free-moving ions needed for electrolysis.'),

    ('Chemistry', 'Organic chemistry', 4,
     'Ethene undergoes addition polymerisation to form poly(ethene). How does the structure of poly(ethene) differ from ethene?',
     'A small cyclic molecule with a remaining C=C double bond is formed',
     'Carbon dioxide and water are produced as the only products',
     'A long-chain polymer forms as the C=C double bonds open up and monomers link together; no other products are formed',
     'An ester is formed when ethene reacts with an alcohol',
     'C',
     'Addition polymerisation opens double bonds and joins monomers — it does not produce CO₂, water, or esters (those come from other reactions).',
     'In addition polymerisation, the C=C double bond in each ethene monomer opens. Monomers join in a long chain: …-CH₂-CH₂-CH₂-CH₂-… forming poly(ethene). No other products are formed.'),

    ('Chemistry', 'Quantitative chemistry', 4,
     '24 g of magnesium reacts completely with excess hydrochloric acid: Mg + 2HCl → MgCl₂ + H₂. What volume of hydrogen is produced at RTP? (Aᵣ Mg = 24; molar volume at RTP = 24 dm³)',
     '12 dm³', '24 dm³', '48 dm³', '6 dm³',
     'B',
     'Moles of Mg = 24 ÷ 24 = 1 mol. Mole ratio Mg : H₂ = 1 : 1, so moles H₂ = 1. Volume = 1 × 24 = 24 dm³.',
     'Step 1: moles Mg = mass ÷ Mᵣ = 24 ÷ 24 = 1 mol. Step 2: ratio Mg:H₂ = 1:1 → moles H₂ = 1. Step 3: volume = 1 × 24 dm³ = 24 dm³.'),

    ('Chemistry', 'Haber process', 4,
     'The Haber process uses 450 °C even though a lower temperature gives a higher yield of ammonia. Explain this compromise.',
     'Higher temperatures produce more ammonia, so 450 °C maximises yield',
     'At lower temperatures the reaction is too slow to be economically viable; 450 °C gives an acceptable yield at a practical rate — a deliberate compromise between rate and yield',
     'The iron catalyst only functions above 450 °C',
     '450 °C is the exact boiling point of ammonia',
     'B',
     'The Haber process is exothermic — lower temperature favours higher yield but slows the rate. 450 °C is not the only temperature the catalyst works at.',
     'Le Chatelier: forward reaction is exothermic, so low temperature shifts equilibrium right (more NH₃), but rate becomes unacceptably slow. 450 °C is a compromise: reasonable rate + acceptable yield. The iron catalyst also helps boost rate.'),

    ('Chemistry', 'Titration', 4,
     '25 cm³ of NaOH is titrated with 0.1 mol/dm³ HCl. The end point is reached after 20 cm³ of HCl. What is the concentration of the NaOH?',
     '0.08 mol/dm³', '0.125 mol/dm³', '0.1 mol/dm³', '0.2 mol/dm³',
     'A',
     'n(HCl) = 0.1 × 0.020 = 0.002 mol. NaOH + HCl → 1:1 ratio, so n(NaOH) = 0.002 mol. c(NaOH) = 0.002 ÷ 0.025 = 0.08 mol/dm³.',
     'Step 1: n(HCl) = c × v = 0.1 × 0.020 = 0.002 mol. Step 2: 1:1 ratio → n(NaOH) = 0.002 mol. Step 3: c(NaOH) = 0.002 ÷ 0.025 = 0.08 mol/dm³. Always convert cm³ to dm³ (÷ 1000).'),

    ('Chemistry', 'Metallic bonding', 4,
     'Explain why metals have high melting points and conduct electricity.',
     'Metal atoms share electrons in directional covalent bonds which are very strong',
     'Metal ions are held in a lattice by strong electrostatic attraction to a sea of delocalised electrons; these same electrons carry electrical charge when a voltage is applied',
     'Metals have ionic bonds between atoms that require enormous energy to break',
     'Large atoms packed tightly together prevent movement and carry charge',
     'B',
     'Metals have metallic bonding, not covalent or ionic. Atomic size does not explain electrical conductivity.',
     'Metallic bonding: positive metal ions in a regular lattice surrounded by a sea of delocalised electrons. Strong electrostatic forces → high melting point. Free-moving delocalised electrons carry charge → electrical conductivity.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Easy (2 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Electricity', 1,
     'What is the unit of electrical power?',
     'Volt', 'Ampere', 'Joule', 'Watt',
     'D',
     'Volts measure potential difference; Amperes measure current; Joules measure energy (not the rate of energy transfer).',
     'Power is measured in Watts (W). 1 W = 1 J/s. P = I × V or P = I²R.'),

    ('Physics', 'Radiation', 1,
     'Which type of nuclear radiation is stopped by a sheet of paper?',
     'Beta', 'Gamma', 'Alpha', 'X-ray',
     'C',
     'Beta radiation requires a few millimetres of aluminium to stop it; gamma radiation requires thick lead or concrete; X-rays penetrate paper easily.',
     'Alpha particles are the most massive and least penetrating type of nuclear radiation. They are stopped by a few centimetres of air or a sheet of paper.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Medium (4 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Waves', 2,
     'A wave passes from air into glass and slows down. What happens to its frequency?',
     'Frequency increases proportionally', 'Frequency decreases', 'Frequency stays the same', 'Frequency becomes zero',
     'C',
     'When a wave enters a new medium, speed and wavelength change together (v = fλ). Frequency is set by the source and cannot change.',
     'Frequency is determined by the source and remains constant when a wave changes medium. Speed decreases → wavelength decreases proportionally, keeping f = v/λ constant.'),

    ('Physics', 'Electricity', 2,
     'Two resistors of 4 Ω and 6 Ω are connected in series. What is the total resistance?',
     '2.4 Ω', '5 Ω', '10 Ω', '24 Ω',
     'C',
     'In series, resistances add directly: 4 + 6 = 10 Ω. 2.4 Ω is the result for a parallel combination. 24 Ω = 4 × 6, which is not the series formula.',
     'Series total resistance: Rₜ = R₁ + R₂ = 4 + 6 = 10 Ω. In series there is only one path, so current passes through both resistors fully.'),

    ('Physics', 'Energy', 2,
     'A machine has an efficiency of 40% and receives 500 J of input energy. How much useful energy does it transfer?',
     '460 J', '300 J', '125 J', '200 J',
     'D',
     'Useful energy = efficiency × input energy = 0.40 × 500 = 200 J. 460 J would mean 92% efficiency. 300 J would be 60% efficiency.',
     'Useful energy output = efficiency × total energy input = 0.40 × 500 = 200 J. The remaining 300 J is wasted, usually as heat.'),

    ('Physics', 'Particle model', 2,
     'A solid block has a mass of 500 g and a volume of 25 cm³. What is its density?',
     '0.05 g/cm³', '12,500 g/cm³', '20 g/cm³', '475 g/cm³',
     'C',
     'Density = mass ÷ volume = 500 ÷ 25 = 20 g/cm³. Multiplying mass by volume gives the wrong answer. Subtracting gives the wrong answer.',
     'Density = mass ÷ volume = 500 ÷ 25 = 20 g/cm³. Check units: if mass is in g and volume in cm³, density is in g/cm³.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Hard (6 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Nuclear', 3,
     'A radioactive isotope has a half-life of 20 years. After 60 years, what fraction of the original sample remains?',
     '1/2', '1/4', '1/8', '1/6',
     'C',
     '60 ÷ 20 = 3 half-lives. After 1: ½; after 2: ¼; after 3: ⅛. Dividing 1/6 does not follow the halving rule.',
     '60 years ÷ 20 years per half-life = 3 half-lives. ½ → ¼ → ⅛. After 3 half-lives, 1/8 of the original activity and mass remain.'),

    ('Physics', 'Electromagnetism', 3,
     'A transformer has 200 turns on the primary coil and 1000 turns on the secondary coil. The input voltage is 12 V. What is the output voltage?',
     '2.4 V', '60 V', '120 V', '240 V',
     'B',
     'Vₛ/Vₚ = Nₛ/Nₚ → Vₛ = 12 × (1000/200) = 12 × 5 = 60 V. 120 V and 240 V are common mains voltages but are not the result of this calculation.',
     'Transformer equation: Vₛ/Vₚ = Nₛ/Nₚ. Vₛ = 12 × (1000/200) = 60 V. More turns on the secondary than primary → step-up transformer (voltage increases).'),

    ('Physics', 'Forces', 3,
     'A car of mass 1200 kg is travelling at 30 m/s. What is its kinetic energy?',
     '36,000 J', '18,000 J', '540,000 J', '1,080,000 J',
     'C',
     'KE = ½mv² = ½ × 1200 × 30² = ½ × 1200 × 900 = 540,000 J. Using v = 30 without squaring it gives the wrong answer.',
     'KE = ½ × m × v² = ½ × 1200 × 900 = 540,000 J. Always square the velocity first, then multiply by ½ × mass.'),

    ('Physics', 'Electricity', 3,
     'A 230 V appliance draws a current of 4 A during normal operation. Which fuse is most appropriate: 3 A, 5 A, or 13 A?',
     '3 A fuse', '5 A fuse', '13 A fuse', 'No fuse is needed',
     'B',
     'A 3 A fuse would blow immediately because the operating current (4 A) already exceeds it. A 13 A fuse would not blow quickly enough in a fault, giving poor protection.',
     'Choose the fuse rated just above the normal operating current. Here current = 4 A, so a 5 A fuse is correct. It allows normal operation but blows if current rises dangerously (e.g. a fault).'),

    ('Physics', 'Waves', 3,
     'An ambulance siren sounds higher-pitched as it approaches and lower-pitched as it moves away. What is this effect called and why does it occur?',
     'Reflection — sound bounces off buildings changing the pitch',
     'Refraction — sound bends as it travels through different air temperatures',
     'The Doppler effect — approaching compresses sound waves (higher frequency); moving away stretches them (lower frequency)',
     'Resonance — the siren vibrates faster when moving towards the listener',
     'C',
     'The siren does not change its own frequency. Reflection and refraction do not explain the direction-dependent pitch change.',
     'Doppler effect: when a source moves towards you, the emitted waves are compressed (shorter wavelength, higher frequency). When it moves away, waves are stretched (longer wavelength, lower frequency). The siren\'s actual frequency is constant.'),

    ('Physics', 'Space', 3,
     'Light from distant galaxies is red-shifted. What does this tell us about the universe?',
     'Distant galaxies are much cooler than nearby ones',
     'The universe is expanding — galaxies are moving away from us, and more distant ones move faster',
     'Light slows down over very large distances',
     'Distant galaxies are rotating extremely quickly',
     'B',
     'Temperature affects the colour of a star but does not cause red-shift in spectral lines. Light speed is constant. Rotation produces a mix of red-shift and blue-shift, not uniform red-shift.',
     'Red-shift (longer wavelength) occurs when a source moves away from the observer (Doppler effect). All distant galaxies show red-shift, and more distant galaxies show greater red-shift — strong evidence that the universe is expanding uniformly.'),

    # ─────────────────────────────────────────────────────
    # PHYSICS – Exam Challenge (7 more → 10 total)
    # ─────────────────────────────────────────────────────
    ('Physics', 'Nuclear', 4,
     'Evaluate nuclear fusion as a future energy source compared to nuclear fission currently used in power stations.',
     'Fusion is already the main source of nuclear power and is completely safe',
     'Fusion produces more long-lived radioactive waste than fission and is harder to control',
     'Fusion fuels (hydrogen isotopes) are more abundant than uranium, and fusion produces far less long-lived radioactive waste than fission — but controlled fusion at commercial scale has not yet been achieved',
     'Fusion and fission are the same process and carry identical risks',
     'C',
     'Fusion is not yet used commercially. Fusion produces less long-lived waste than fission, not more.',
     'Fusion advantages: abundant fuel (deuterium from seawater), much less long-lived radioactive waste, no CO₂. Disadvantage: extremely high temperatures (~100 million °C) needed to overcome repulsion between nuclei — no material can contain this, so magnetic confinement is used experimentally but commercial reactors do not yet exist.'),

    ('Physics', 'Forces', 4,
     'A 2 kg ball moving at 6 m/s collides with a stationary 4 kg ball. They stick together. What is their combined velocity after the collision?',
     '6 m/s', '3 m/s', '2 m/s', '4 m/s',
     'C',
     'Conservation of momentum: p_before = 2 × 6 = 12 kg m/s. p_after = (2 + 4) × v = 6v. So v = 12 ÷ 6 = 2 m/s.',
     'Total momentum is conserved in a collision. p = mv: before = 2 × 6 = 12 kg m/s; after = 6 × v. Therefore v = 12 ÷ 6 = 2 m/s.'),

    ('Physics', 'Thermal physics', 4,
     'A 2 kg aluminium block (specific heat capacity = 900 J/kg°C) is heated from 20 °C to 70 °C. How much energy is required?',
     '45,000 J', '90,000 J', '126,000 J', '180,000 J',
     'B',
     'E = mcΔT = 2 × 900 × (70 − 20) = 2 × 900 × 50 = 90,000 J.',
     'E = m × c × ΔT = 2 × 900 × 50 = 90,000 J. Always calculate the temperature change (ΔT) first: 70 − 20 = 50 °C.'),

    ('Physics', 'Space', 4,
     'A satellite orbits Earth at constant speed in a circular orbit. Although its speed is constant it is accelerating. Explain why, and identify the force causing this.',
     'The satellite is not accelerating because its speed is constant',
     'Gravity provides a centripetal force directed towards Earth\'s centre; the direction of velocity constantly changes, so the satellite accelerates even though its speed is unchanged',
     'Rocket engines on the satellite provide the centripetal force',
     'Air resistance keeps the satellite in orbit',
     'B',
     'Acceleration can be a change in direction, not just speed. There are no rocket engines running in a stable orbit. Air resistance would slow the satellite, not keep it in orbit.',
     'Velocity is a vector — it includes direction. In circular motion the direction changes continuously, so there is constant acceleration towards the centre. For an orbiting satellite, gravity provides this centripetal force.'),

    ('Physics', 'Electricity', 4,
     'Explain why electrical energy is transmitted at high voltage across the National Grid.',
     'High voltage makes electricity travel faster through the cables',
     'Increasing voltage decreases current (P = IV); lower current reduces energy wasted as heat in cables (P = I²R), making transmission much more efficient',
     'High voltage is safer for engineers working near overhead power lines',
     'Power stations generate electricity at high voltage and it cannot be changed',
     'B',
     'Electricity does not travel faster at high voltage. High voltage cables are extremely dangerous. Transformers allow voltage to be stepped up or down as needed.',
     'P = IV: for the same power, higher voltage means lower current. Energy lost in cables = I²R: lower current dramatically reduces cable losses. Step-up transformers increase voltage before transmission; step-down transformers reduce it for safe use in homes.'),

    ('Physics', 'Thermal physics', 4,
     'A student compares how quickly two identical cans of hot water cool: one painted matt black, one polished silver. Which cools faster and why?',
     'The silver can cools faster because shiny surfaces reflect heat outward',
     'They cool at the same rate because they are identical in shape and size',
     'The matt black can cools faster because dark, matt surfaces emit infrared radiation more effectively than shiny surfaces',
     'The silver can cools faster because metal is a better thermal conductor',
     'C',
     'Shiny surfaces REFLECT radiation coming in and emit less radiation going out — they are poor emitters. The cans are identical so shape/size is not the differentiator.',
     'Dark, matt surfaces are good absorbers AND good emitters of infrared radiation. Shiny, light-coloured surfaces are poor emitters. The matt black can loses energy by radiation more quickly, so it cools faster.'),

    ('Physics', 'Electricity', 4,
     'A cable has a resistance of 0.5 Ω. It carries a current of 100 A. How much power is wasted as heat? If current is reduced to 1 A, what is the new wasted power, and by what factor has it changed?',
     '50 W at 100 A; 0.005 W at 1 A — 10,000 times less',
     '5,000 W at 100 A; 0.5 W at 1 A — 10,000 times less',
     '5,000 W at 100 A; 5 W at 1 A — 1,000 times less',
     '500 W at 100 A; 5 W at 1 A — 100 times less',
     'B',
     'P = I²R. At 100 A: P = 100² × 0.5 = 10,000 × 0.5 = 5,000 W. At 1 A: P = 1² × 0.5 = 0.5 W. Ratio = 5000/0.5 = 10,000.',
     'P = I²R. At 100 A: P = 10,000 × 0.5 = 5,000 W. At 1 A: P = 1 × 0.5 = 0.5 W. Factor = 5000 ÷ 0.5 = 10,000. This is why the National Grid uses very high voltages (and very low currents) for long-distance transmission.'),
]


ALL_QUESTIONS = QUESTIONS + EXTRA_QUESTIONS


def seed():
    conn = db.get_db()
    conn.executemany(
        '''INSERT INTO questions
           (subject, topic, difficulty, question_text,
            option_a, option_b, option_c, option_d,
            correct_answer, explanation, correction_tip)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)''',
        ALL_QUESTIONS
    )
    conn.commit()
    conn.close()
    print(f'Seeded {len(ALL_QUESTIONS)} questions.')
